### ISSUE TITLE
How to use custom raster tiles source with Mapbox?

### ISSUE THREAD

**Issue by Gelembjuk** [mapbox/mapbox-maps-ios#1000]
Hello,
Is it possible to use 3-rd party map tiles with mapbox on iOS?
For example, can i point mapbox to https://{a|b|c}.tile.opentopomap.org/{z}/{x}/{y}.png so OpenTopMaps are displayed?

There is the trick to use some offline maps with Mapbox , where local webserver is started and tiles are stored in SQLite DB.
But that tutorial is created for older version of Mapbox. 
https://gist.github.com/namannik/3b7c8b69c2d0768d0c2b48d2ed5ff71c
I am not sure it can work with modern version

**Comment by ZiZasaurus** [comment]
@gelembjuk, you can use third party map tiles with Mapbox SDK v10, please take a look at our example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/RasterTileSourceExample.swift).

To use third party raster tiles offline, you would need to use the OfflineRegionManager. An example can be seen [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/OfflineRegionManagerExample.swift).
