### ISSUE TITLE
Add missing methods for legacy offline data download API

### ISSUE THREAD

**Issue by tomascern** [mapbox/mapbox-maps-ios#1005]
Hello, we need to download our own self-hosted tiles for offline usage.  According to this comment: https://github.com/mapbox/mapbox-maps-ios/issues/986#issuecomment-1005800597 we should continue use legacy APIs (OfflineRegionManager) for now. In this case, we need to add some missing methods - setting metadata of the offline region (right now there is only method for getting metadata) and method for deleting a region from the database.

**Comment by bmt2018** [comment]
Agreed.  I was just looking into how to set the metadata for a specific offline region using the legacy OfflineRegionManager and I don't see a way to do it.

**Comment by ZiZasaurus** [comment]
@tomascern we are working on exposing the ability to delete offline regions. Setting the metadata is not a supported feature at the moment, however, we will consider your request for adding this functionality in a future version of v10.

**Comment by rickycpadilla** [comment]
> @tomascern we are working on exposing the ability to delete offline regions. Setting the metadata is not a supported feature at the moment, however, we will consider your request for adding this functionality in a future version of v10.

@ZiZasaurus  Any update on deleting offline regions?
