### ISSUE TITLE
Move the camera to bounds without setting the bound

### ISSUE THREAD

**Issue by AlexaderDNT** [mapbox/mapbox-maps-ios#1022]
## New Feature

I wanna move to a area with points and zoom all out so you can se all the points.

**Comment by AlexaderDNT** [comment]
I want this https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/

**Comment by ZiZasaurus** [comment]
@alexaderDNT, please take a look at our RestrictCoordinateBounds example [here](https://github.com/mapbox/mapbox-maps-ios/blob/167cc03f433655fa7f993be6083fbf6c114580b1/Apps/Examples/Examples/All%20Examples/RestrictCoordinateBoundsExample.swift).

**Comment by AlexaderDNT** [comment]
thanks @ZiZasaurus
