### ISSUE TITLE
PointAnnotation Coordinate Update 

### ISSUE THREAD

**Issue by iosamar** [mapbox/mapbox-maps-ios#1027]
## Environment

- Xcode version: - 13.1
- iOS version: - 13 and above
- Maps SDK Version: - 10.2.0

Hi Team,

I have an array of coordinates from which i want to update PointAnnotation on map with animation like OLA and Uber does.
but i checked MapView, PointAnnotation and  PointAnnotationManager classes and i didn't found any method to do so. 
Although there is property in MapView class CameraAnimationsManager from which i am able to animate camera position but there is no option for Annotation.

Code Snippet to animate camera to desired location

let loc = CLLocationCoordinate2D(latitude: (location?.coordinate.latitude)!, longitude: (location?.coordinate.longitude)! )
let newCamera = CameraOptions(center: loc, zoom: 18.0,  bearing: 180.0, pitch: 15.0)
self.mapView.camera.ease(to: newCamera, duration: 2.0)

but there is no method to update Annotation on Map.

import UIKit
import MapboxMaps
import CoreLocation

class ViewController: UIViewController {

    internal var mapView: MapView!

    private var locationManager:CLLocationManager? = CLLocationManager()
    var pointAnnotationManager: PointAnnotationManager!
    var customPointAnnotation: PointAnnotation!

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        let myResourceOptions = ResourceOptions(accessToken: "sk.eyJ1IjoiYW1hcmlvcyIsImEiOiJja3lpZTZucmcyYnFnMnZwYjVtcDhrZ245In0.G2sfqesoHv_cfc7HyUdddw")
        let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
        mapView = MapView(frame: view.bounds, mapInitOptions: myMapInitOptions)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        self.view.addSubview(mapView)
        
        pointAnnotationManager = mapView.annotations.makePointAnnotationManager()
        let centerCoordinate = mapView.cameraState.center
        customPointAnnotation = PointAnnotation(coordinate: centerCoordinate)
        customPointAnnotation.image = .init(image: UIImage(named: "car")!, name: "car")
        pointAnnotationManager.annotations = [customPointAnnotation]
      
    

        self.locationManager = CLLocationManager()
        self.locationManager?.delegate = self
        self.locationManager?.startUpdatingLocation()

    }

}
extension ViewController: CLLocationManagerDelegate {

    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        let location = locations.last
        let loc = CLLocationCoordinate2D(latitude: (location?.coordinate.latitude)!, longitude: (location?.coordinate.longitude)! )
        let bearing = calculateBearing(from: customPointAnnotation.point.coordinates, to: loc)
        let newCamera = CameraOptions(center: loc, zoom: 18.0, bearing: 180.0, pitch: 15.0)
        self.customPointAnnotation.point = Point(loc)
        self.customPointAnnotation.iconRotate = bearing
        self.pointAnnotationManager.annotations = [self.customPointAnnotation]
        self.mapView.camera.ease(to: newCamera, duration: 2.0)
    }
    
    func calculateBearing(from: CLLocationCoordinate2D, to: CLLocationCoordinate2D) -> Double {
        let x1 = from.longitude * (Double.pi / 180.0)
        let y1 = from.latitude  * (Double.pi / 180.0)
        let x2 = to.longitude   * (Double.pi / 180.0)
        let y2 = to.latitude    * (Double.pi / 180.0)

        let dx = x2 - x1
        let sita = atan2(sin(dx) * cos(y2), cos(y1) * sin(y2) - sin(y1) * cos(y2) * cos(dx))

        return sita * (180.0 / Double.pi)
    }
}

So from this code the Annotation is updated but not with smooth animation liking moving car or bilke.
So will you please help to found out right way to update PointAnnotation on MapView.
your support will be be Appreciated.
Thanks in advance.

**Comment by ZiZasaurus** [comment]
@iosamar, is there a reason why you're not using a custom [locationIndicatorLayer](https://docs.mapbox.com/ios/maps/api/10.2.0/Structs/LocationIndicatorLayer.html) instead of a point annotation?

**Comment by iosamar** [comment]
@ZiZasaurus  Thanks for the reply.
can you provide me a link or some sample that how we can use locationIndicatorLayer instead of Point annotation so that we can update its coordinate.

**Comment by Tapestes** [comment]
Same situation as @iosamar: multiple locations coming from a database.  The ability to update the annotation point would be fantastic.  Especially because the method we're using currently - removing the annotation from the manager and adding a new one with the updated position - results in the annotation text flashing off/on once if the distance moved on screen is farther than a few pixels.

**Comment by ZiZasaurus** [comment]
If you would like to animate point annotations, one suggestion would be to try updating the location of your point annotations at every frame using their own CADisplayLink, however, this may not be the most performant option.

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you have additional questions.

**Comment by tlextrait** [comment]
Sounds like there's still no way to display multiple moving objects using MapBox right?
