### ISSUE TITLE
iOS on dark appearance, UIWindow on light appearance, MapView is taking in cosideration iOS appearance instead of traitCollection when loading image asset

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-maps-ios#1030]
## Environment

- Xcode version: 13.2.1 (13C100)
- iOS version: 15.2
- Devices affected: Simulator & real devices
- Maps SDK Version: 
    - MapboxCommon (21.0.1)
  - MapboxCoreMaps (10.2.0):
    - MapboxCommon (~> 21.0)
  - MapboxCoreNavigation (2.2.0-rc.1):
    - MapboxDirections-pre (~> 2.2.0-rc.1)
    - MapboxMobileEvents (~> 1.0)
    - MapboxNavigationNative (~> 83.0)
  - MapboxDirections-pre (2.2.0-rc.1):
    - Polyline (~> 5.0)
    - Turf (~> 2.0)
  - MapboxMaps (10.2.0):
    - MapboxCommon (= 21.0.1)
    - MapboxCoreMaps (= 10.2.0)
    - MapboxMobileEvents (= 1.0.6)
    - Turf (~> 2.0)
  - MapboxMobileEvents (1.0.6)
  - MapboxNavigation (2.2.0-rc.1):
    - MapboxCoreNavigation (= 2.2.0-rc.1)
    - MapboxMaps (= 10.2.0)
    - MapboxMobileEvents (~> 1.0)
    - MapboxSpeech (~> 2.0)
    - Solar-dev (~> 3.0)
  - MapboxNavigationNative (83.0.0):
    - MapboxCommon (~> 21.0)
  - MapboxSpeech (2.0.0)

## Observed behavior and steps to reproduce
1) Set your device appearance mode on dark
2) Set UIWindow appearance on light (override system appearance capability in the app)
3) Create a new image asset 
4) Set an image for  light mode (any) and one for dark mode
5) Add image annotation on the map

## Expected behavior
Considering that my UIWindow appearance is light, I should see the asset that corresponds to light mode.

Issue:
Right now, the map is displaing the image for dark mode.

If you go  Settings app and set the device on light mode, on the MapView you can see the image that is set for light mode.

**Comment by ZiZasaurus** [comment]
@nastasiupta can you please let us know how you're creating your UIImages?

**Comment by nastasiupta** [comment]
@ZiZasaurus `annotation.image = .init(image: UIImage(named: "Waypoint-\(index + 1)")!, name: "Waypoint-\(index + 1)")`
Where Waypoint-1 for example is an asset from Assets.xcassets where I have separated images for "Any Apppearance" and "Dark"

**Comment by ZiZasaurus** [comment]
@nastasiupta thank you for this code snippet. Would you be able to try using https://developer.apple.com/documentation/uikit/uiimage/1624154-init and passing in the trait collection of your view/view controller?

**Comment by nastasiupta** [comment]
@ZiZasaurus  hmm it works. I didn't know about that.

**Comment by ZiZasaurus** [comment]
@nastasiupta Fantastic! I will close this ticket out but please feel free to reopen out if you have any additional questions.
