### ISSUE TITLE
How to convert cluster expression to `v10`

### ISSUE THREAD

**Issue by LearnWithTung** [mapbox/mapbox-maps-ios#1034]
## New Feature
I'm migrating the mapbox from `v6` to `v10` and running into a problem with expression

In `v6` I have

    let firstExpression = NSExpression(
      format: "sum:({$featureAccumulated, \(Constans.Attributes.clusterOverWalkingDistance)})")
    let secondExpression = NSExpression(
      forKeyPath: "\(Constans.Attributes.overWalkingDistance)")
    let clusterPropertiesDictionary =
      [Constans.Attributes.clusterOverWalkingDistance : [firstExpression, secondExpression]]

and
```
let circleOpacityForCluster = NSExpression(
        forConditional: NSPredicate(format: "\(Constans.Attributes.clusterOverWalkingDistance) >= point_count"),
        trueExpression: NSExpression(forConstantValue: 0.3),
        falseExpression: NSExpression(forConstantValue: 1)
      )
clusterIconLayer?.iconOpacity = circleOpacityForCluster
```

What I've tried in `v10`
```
let firstExpression = Exp(.sum) {
      Exp(.get) {
        Constans.Attributes.clusterOverWalkingDistance
      }
    }
    
let clusterPropertiesDictionary =
      [Constans.Attributes.clusterOverWalkingDistance : firstExpression]
```

and
```
clusterIconLayer?.iconOpacity = .expression(Exp(.switchCase) {
        Exp(.eq) {
          Exp(.gte) {
            Exp(.get) { Constans.Attributes.clusterOverWalkingDistance }
            Exp(.get) { "point_count" }
          }
          "true"
        }
        0.3
        1.0
      })
```

But it's not working. Any suggestion to fix it. Thanks in advance.

**Comment by ZiZasaurus** [comment]
@LearnWithTung as this is more of an implementation Issue than a Platform/Android specific issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/?
