### ISSUE TITLE
There is white area on the top when constraint in process of changing

### ISSUE THREAD

**Issue by forafontov98** [mapbox/mapbox-maps-ios#1047]
- Xcode version: 13.2.1
- iOS version: 14..<15
- Devices affected: iPhone XR
- Maps SDK Version: 10.2.0

I want to change the height of the map as I swipe. In fact, I'm changing the bottom constraint, and how fast I move my finger determines how much white area appears in the top area of the map.

https://user-images.githubusercontent.com/26205755/150376467-de3ea9a8-f82c-4d80-add8-5ece10378360.mp4

**Comment by macdrevx** [comment]
Could you try setting [`MapView.presentsWithTransaction`](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/MapView.html#/s:10MapboxMaps7MapViewC23presentsWithTransactionSbvp) to true?

**Comment by forafontov98** [comment]
@macdrevx without result(

**Comment by ZiZasaurus** [comment]
@forafontov98, I was only able to reproduce the issue reported once out of over 20 times. It appears that there may be some lag between when is drawn with updated frame and when the metal view renders with updated frame. If you are experiencing this consistently, could you provide us with some additional information as to how you're creating/ adding the bottom drawer?

**Comment by forafontov98** [comment]
@ZiZasaurus hi! On physical device. I have this child of MapView class:
`final class GeographyMapView: MapView {
	private let resourceOptions = ResourceOptions(accessToken: Constants.mapBixApiKey)
	private let styleURI = StyleURI(rawValue: Constants.mapBoxStyleUrl)
	private let indexKey = "index"

	private lazy var annotationsManager = annotations.makePointAnnotationManager()

	private func mapPin() -> UIView {
		let imageView = UIImageView()
		imageView.image = ImageAsset.mapPin.image
		return imageView
	}

	init() {
		let mapInitOptions = MapInitOptions(resourceOptions: resourceOptions, styleURI: styleURI)
		super.init(frame: .zero, mapInitOptions: mapInitOptions)
		ornaments.options.compass.visibility = .hidden
		ornaments.options.scaleBar.visibility = .hidden
		ornaments.options.attributionButton.margins = .init(x: 0, y: -100)
		ornaments.options.logo.margins = .init(x: 0, y: -100)
		autoresizingMask = [.flexibleWidth, .flexibleHeight]
		presentsWithTransaction = true

		annotationsManager.delegate = self
	}

	required init?(coder: NSCoder) {
		super.init(coder: coder)
	}
}`

and in mainView there are these constraints:
`mapView.snp.remakeConstraints {
	$0.left.right.top.equalToSuperview()
	$0.bottom.equalTo(contentView.snp.top).offset(20)
}`

When I change finger position, I change contentView constraints, so mapView constraints are changing automatically

**Comment by ZiZasaurus** [comment]
@forafontov98 thank you for these code snippets. Would you also be able to provide the code for your snp.remakeConstraints method?

**Comment by ZiZasaurus** [comment]
If it's useful, I've included my implementation, which does not reproduce this behavior, below.
[BottomSheetTest.txt](https://github.com/mapbox/mapbox-maps-ios/files/7960827/BottomSheetTest.txt)

**Comment by ZiZasaurus** [comment]
Closing this out but please feel free to reopen if you have additional questions.

**Comment by forafontov98** [comment]
@ZiZasaurus Good evening! I'm sorry for the late reply. Unfortunately still looking for a solution. In your example, you don't change the constraints of the view on which the mapView depends, but you change its frame. This is the key difference with my example. I'm changing the constraints of my bottomsheet, and the moment they change, a white area appears at the top. There is another notable feature: the white area only appears when I drive the bottomsheet down. When I go up, everything is ok.

**Comment by forafontov98** [comment]
@ZiZasaurus please, look at this 2 my view files:
[GeographyView+States.txt](https://github.com/mapbox/mapbox-maps-ios/files/7980483/GeographyView%2BStates.txt)
[GeographyView.txt](https://github.com/mapbox/mapbox-maps-ios/files/7980484/GeographyView.txt)

in GeographyView+States I change my constraints while gesture is working. And in GeographyView I set all properties of view

**Comment by ZiZasaurus** [comment]
@forafontov98 thank you for providing these files. Can you provide us with a sample app that reproduces this behavior? There are references in your files, such as BaseView, that we are unfamiliar with.
