### ISSUE TITLE
Mapbox Maps consumes up to 2 GB RAM until App gets terminated due to supervision limits

### ISSUE THREAD

**Issue by jumbopilot** [mapbox/mapbox-maps-ios#1052]
## Environment

- Xcode version: Version 13.2.1 (13C100)
- iOS version: 15.3
- Devices affected: iPhone 13 (real hardware)
- Maps SDK Version: 10.2.0
- Map Style: own defined (MapStudio) style derived from std outdoors
- Additional layers: using local data from geojson (file size ~ 7MB composed of points and polygons displayed as symbol and polygons)

## Observed behaviour and steps to reproduce
RAM Memory allocation continuously increases in steps of ~1MB during Maps display until iOS limits per App of 2GB is reached. The App is then terminated by iOS supervision. The whole process of memory exhausting takes about 20min.
<img width="537" alt="Screenshot 2022-01-23 at 10 48 59" src="https://user-images.githubusercontent.com/43632124/150680618-98305ccc-20f1-43f1-9579-50eb266612ed.png">

Map is operateable all along.
No performance reduction noticed. It looks like no more required resources are not freed. Memory leak?

If maps is not instantiated, the app RAM consumption is constantly limited to ~40 MB. Maps SDK v6.x with the same functionality consumes ~200 MB.

-- Debug log --
MapboxCoreMaps was compiled with optimization - stepping may behave oddly; variables may not be available.
App name(5959,0x106950580) malloc: Heap corruption detected, free list is damaged at 0x287ec9d80
*** Incorrect guard value: 7985208328
--
<img width="976" alt="Screenshot 2022-01-23 at 14 19 00" src="https://user-images.githubusercontent.com/43632124/150680476-0c4d9af5-0706-4ff4-9e96-be21df5727bf.png">
After ~8 min (even without any user interaction, just location updates while standing still):
<img width="976" alt="Screenshot 2022-01-23 at 14 27 05" src="https://user-images.githubusercontent.com/43632124/150680781-935fbfc9-0339-4b1e-be6b-310a940fc06b.png">

Consumed memory is immediately freed upon map disappearance (deinit).

The issue seems to be triggered once the user location (puck) begins to move.

## Expected behavior
The volatile memory consumption is limited to a reasonable value.

## Notes / preliminary analysis
The user location is tracked and map moves accordingly the user location centered map.
The internet connection (mobile data) is turned off, but local offline map is available.

## Additional links and references
The integrated maps SDK was switched from Maps SDK v6.x to Mapbox V10.2.0.
Compared to iOS Map SDK v6.x, the implemented functionality is basically identical, except the UIViewController is wrapped for SwiftUI.
Offline map download is implemented, but the memory consumption issue remains even turned off.
Using Xcode, I cannot locate precisely the Mapbox module/unit causing such a huge memory consumption. Any hints are welcome.
Turning off all additional layers or switching to the standard map style 'outdoors' does not impact the Map memory consumption.

**Comment by ZiZasaurus** [comment]
@jumbopilot, thank you for reporting this. Is this behavior occurring on a simulator or physical devices? Also, do you have a code snippet or sample app with your map implementation that reproduces this behavior?

**Comment by jumbopilot** [comment]
I've updated the Device Under Test in issue description. I'll try to screw the issue down to a small code snippet.

**Comment by jumbopilot** [comment]
It looks like the issue is caused by mgl::style::GeoJSONSource::Impl malloc'ing at high frequency 144 bytes when reading the geojson source attached:
[airspaces-xa.geojson.zip](https://github.com/mapbox/mapbox-maps-ios/files/7945416/airspaces-xa.geojson.zip)

simply loaded via:
`
DispatchQueue.global(qos: .background).async {
      guard let jsonUrl = Bundle.main.url(forResource: "airspaces-\(self.AirspaceRegion)", withExtension: "geojson") else {
                return }
      guard let jsonData = try? Data(contentsOf: jsonUrl) else {
                return }
      self.jsonDataAll = jsonData
}`

**Comment by jumbopilot** [comment]
repeated mallocs:
   8 MetalTools -[MTLDebugRenderCommandEncoder drawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:]
   9 MapboxCoreMaps mbgl::metal::Program<mbgl::LineProgram>::draw(mbgl::gfx::Context&, mbgl::gfx::RenderPass&, mbgl::gfx::DrawMode const&, mbgl::gfx::DepthMode const&, mbgl::gfx::StencilMode const&, mbgl::gfx::ColorMode const&, mbgl::gfx::CullFaceMode const&, mbgl::gfx::UniformValues<mbgl::TypeList<mbgl::uniforms::matrix, mbgl::uniforms::units_to_pixels, mbgl::uniforms::pixels_to_tile_units, mbgl::uniforms::device_pixel_ratio, mbgl::uniforms::scale, mbgl::uniforms::texsize, mbgl::uniforms::dash_from, mbgl::uniforms::dash_to, mbgl::uniforms::mix, mbgl::uniforms::image_height, mbgl::InterpolationUniform<mbgl::attributes::blur>, mbgl::InterpolationUniform<mbgl::attributes::color>, mbgl::InterpolationUniform<mbgl::attributes::floorwidth>, mbgl::InterpolationUniform<mbgl::attributes::gapwidth>, mbgl::InterpolationUniform<mbgl::attributes::offset>, mbgl::InterpolationUniform<mbgl::attributes::opacity>, mbgl::InterpolationUniform<mbgl::attributes::pattern_to>, mbgl::InterpolationUniform<mbgl::attributes::pattern_from>, mbgl::InterpolationUniform<mbgl::attributes::pixel_ratio_to>, mbgl::InterpolationUniform<mbgl::attributes::pixel_ratio_from>, mbgl::InterpolationUniform<mbgl::attributes::width>, mbgl::uniforms::blur, mbgl::uniforms::color, mbgl::uniforms::floorwidth, mbgl::uniforms::gapwidth, mbgl::uniforms::offset, mbgl::uniforms::opacity, mbgl::uniforms::pattern_to, mbgl::uniforms::pattern_from, mbgl::uniforms::pixel_ratio_to, mbgl::uniforms::pixel_ratio_from, mbgl::uniforms::width> > const&, mbgl::gfx::DrawScope&, mbgl::gfx::AttributeBindings<mbgl::TypeList<mbgl::attributes::pos_normal, mbgl::attributes::data<unsigned char, 4ul>, mbgl::attributes::linesofar, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::blur>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::color>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::floorwidth>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::gapwidth>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::offset>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::opacity>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::pattern_to>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::pattern_from>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::pixel_ratio_to>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::pixel_ratio_from>, mbgl::ZoomInterpolatedAttribute<mbgl::attributes::width>, mbgl::attributes::packed> > const&, mbgl::gfx::TextureBindings<mbgl::TypeList<mbgl::textures::dash_image, mbgl::textures::gradient_image> > const&, mbgl::gfx::IndexBuffer const&, unsigned long, unsigned long) /Users/distiller/project/internal/src/mbgl/metal/program.hpp:208
  10 MapboxCoreMaps draw<mbgl::gfx::Triangles> /Users/distiller/project/src/mbgl/programs/program.hpp:141
  11 MapboxCoreMaps mbgl::RenderLineLayer::render(mbgl::PaintParameters&) /Users/distiller/project/src/mbgl/renderer/layers/render_line_layer.cpp:255
  12 MapboxCoreMaps mbgl::(anonymous namespace)::LayerRenderItemImpl::render(mbgl::PaintParameters&) const /Users/distiller/project/src/mbgl/renderer/render_orchestrator.cpp:66
  13 MapboxCoreMaps mbgl::Renderer::Impl::render(mbgl::RenderTree const&) /Users/distiller/project/src/mbgl/renderer/renderer_impl.cpp:278
  14 MapboxCoreMaps mbgl::Renderer::render(std::__1::shared_ptr<mbgl::UpdateParameters> const&) /Users/distiller/project/src/mbgl/renderer/renderer.cpp:51
--- 3 frames omitted ---
  18 MapboxCoreMaps -[MBMMetalViewDelegate drawInMTKView:] /Users/distiller/project/internal/platform/ios/src/metal/view_delegate.mm:9

Is this related to the drawn polygons with partial opacity?

**Comment by ZiZasaurus** [comment]
@jumbopilot thank you for following up. Please make sure you're reusing your PointAnnotationManager (see our Updating Point Annotation position example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/UpdatePointAnnotationPositionExample.swift)), rather than recreating new ones when updating your markers. If you have an annotation manager you no longer want to use, you can destroy it using [removeAnnotationManager(withId:) ](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/AnnotationOrchestrator.html#/s:10MapboxMaps22AnnotationOrchestratorC06removeC7Manager6withIdySS_tF
).

Was there something in particular about the API design that we should improve to make it's usage more clear or straightforward? Is there a certain way that you expected this API to work? Please feel free to provide us with feedback about our APIs so we can make them easier to use in the future.

**Comment by jumbopilot** [comment]
@ZiZasaurus Thanks for confirmation of memory persistency of AnnotationManager created by e.g. makePolylineAnnotationManager(id:layerPosition:). I'm fine with the API itself.

As this is a design decision which is not transparent to SDK users, I'd suggest to document such property in the [Class Reference](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/AnnotationOrchestrator.html#/s:10MapboxMaps22AnnotationOrchestratorC012makePolylineC7Manager2id13layerPositionAA0fcG0CSS_AA05LayerJ0OSgtF) creating those objects needing attention from memory consumption point of view and check for similar APIs requiring own memory allocation management.

Finally, creating one instance of a type-specific AnnotationManager all over the map life cycle and re-using it is fine with me and resolved the issue. Precisely reading the class reference documentation again, another solution to prevent raising memory consumption beside removeAnnotationManager(withId:) is to (re-)create an AnnotationManager with the same 'id', thus replacing the existing one. I did not yet verify that one.

**Comment by ZiZasaurus** [comment]
@jumbopilot the API docs have been updated and should reflect these changes with our next release.
