### ISSUE TITLE
Clustering custom objects

### ISSUE THREAD

**Issue by anya-sverdlova** [mapbox/mapbox-maps-ios#1071]
Hi. This is more question than bug. I have an array of custom objects with coordinates and I'd like to cluster them on map but I couldn't find a way to do it without using JSON. As I can understand there were such possibility in previous version. Is it possible to create source for layer without using JSON in v10?

**Comment by ZiZasaurus** [comment]
@anya-sverdlova can you provide me with some additional information on your use case and what type of objects you're trying to cluster?

**Comment by ZiZasaurus** [comment]
@anya-sverdlova a source can be any of the types listed in our documentation [here](https://docs.mapbox.com/ios/maps/api/10.2.0/Enums/SourceType.html#/s:10MapboxMaps10SourceTypeO6vectoryA2CmF), but at the moment we only support geojson source clustering.
