### ISSUE TITLE
Support for 3D Lines and points

### ISSUE THREAD

**Issue by jeradhoy** [mapbox/mapbox-maps-ios#108]
Is there now or is there going to be support for 3D lines and points? For example, you may want to view the flight path of an aircraft in 3D - above the ground.

Can you do this now?

**Comment by sbma44** [comment]
This capability isn't yet available. We're still finalizing the best way to support these kinds of use cases across Mapbox--you can expect to see it in our web SDK, too, when available. Vertical offsets for markers will likely arrive sooner, which might be applicable to what you have in mind.
