### ISSUE TITLE
Tapping compass no longer resets orientation to due North in 10.3.0-rc.1

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#1082]
## Environment

- Xcode version: 13.2.1
- iOS version: 15.3
- Devices affected: All
- Maps SDK Version: 10.3.0-rc.1

## Observed behavior and steps to reproduce

If you rotate the map, and have the compass visible, tapping the compass does nothing.

## Expected behavior

Tapping the compass should rotate the map back around to 0°.

**Comment by macdrevx** [comment]
Thanks for the report. Regressed in #1058.
