### ISSUE TITLE
Feature request: Set touch area of Circle Annotation

### ISSUE THREAD

**Issue by niklassaers** [mapbox/mapbox-maps-ios#1088]
## New Feature
Set touch area of Circle Annotation

## Why
By default, the circles are nice and small. But touching them is hard. Following the HIG, a 44x44 touch target would be good for a finger. Can we increase touch target without increasing the circle?

## Current workarounds
1. Use ViewAnnotations instead (is this performant for 310-340 views?)
or
2. set circleStrokeColor to .clear and have a nice, wide circleStrokeWidth

**Comment by ZiZasaurus** [comment]
@niklassaers thank you for reaching out. We'll consider this feature request for a future update.

**Comment by macdrevx** [comment]
Fixed by https://github.com/mapbox/mapbox-maps-ios/pull/1283
