### ISSUE TITLE
[Question]: Polygon border fade-out / smooth border

### ISSUE THREAD

**Issue by andreas-ullrich** [mapbox/mapbox-maps-ios#1115]
Dear Mapbox team,

if i use fil-in pattern in ios sdk with a geojson file it creates a straight border or better so say sharp edges.
Is there a possibility to fade out the border or to give the appearance of more smooth border.
See my example:

<img width="302" alt="153747624-e9d53485-4cae-46ae-8b56-1724fd873d88" src="https://user-images.githubusercontent.com/68023686/153818604-5f4d2dfd-e45a-463a-b024-7a418d83a72d.png">

Is it possible to make those corners more round?
even if i use a pattern that is round with transparency around it the border is still sharp and square.

This is the code i use to display the polygon with overlay:

        let polygon = Polygon(polygon)
                
        let polygonAnnotationManager: PolygonAnnotationManager
        
        polygonAnnotationManager = mapView.annotations.makePolygonAnnotationManager(id: managerID, layerPosition: nil)
        
        // Create the polygon annotation
        var polygonAnnotation = PolygonAnnotation(polygon: polygon)
                
        // Style the polygon annotation
        polygonAnnotation.fillPattern = imageName
        polygonAnnotationManager.fillAntialias = true
        
        // Add the polygon annotation to the manager
        polygonAnnotationManager.annotations = [polygonAnnotation]

Thank you in advance!
Best regards,
Andreas

**Comment by ZiZasaurus** [comment]
@andreas-ullrich at the moment this feature is not supported, however, we will consider allowing rounded polygon corners for a future update.
