### ISSUE TITLE
How can I select a PointAnnotation Manually

### ISSUE THREAD

**Issue by tavakoli-ali** [mapbox/mapbox-maps-ios#1135]
Hi 
I'm trying to migrate our project from v 6.3 to v 10.3 but I can't find any function like this in new version.
https://docs.mapbox.com/ios/maps/api/6.4.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)selectAnnotation:animated:
I want to select a PointAnnotation manually in code.

can you help me about it?

**Comment by ZiZasaurus** [comment]
@tavakoli-ali have you seen our Select Annotation Example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SelectAnnotationExample.swift)? 

In the future, as this is more of an implementation Issue than a Platform/iOS specific issue, please create a support ticket at https://support.mapbox.com/hc/en-us/.
