### ISSUE TITLE
LocationPermissionsDelegate

### ISSUE THREAD

**Issue by rgmyyw** [mapbox/mapbox-maps-ios#1138]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

`LocationPermissionsDelegate` does not comply with Anyobject, please add!

```swift
public protocol LocationProviderDelegate: AnyObject {
}
```

```swift
@objc public protocol LocationPermissionsDelegate { 
}
```

**Comment by ZiZasaurus** [comment]
@rgmyyw thank you for your suggestion. Could you please provide us with some additional information as to why `LocationPermissionsDelegate` doesn't work for you in its current state?

**Comment by rgmyyw** [comment]
The OC main project is mixed with swift. Swift calls mapboxs,  cannot be found  `LocationPermissionsDelegate`

![截屏2022-02-23 下午7 27 26](https://user-images.githubusercontent.com/20027844/155310926-7e9c39b8-5890-4eb2-9629-53ba199024c8.png)


![截屏2022-02-23 下午7 32 48](https://user-images.githubusercontent.com/20027844/155311574-b7c38150-abe7-4555-9111-8473b3f0fbb6.png)

**Comment by rgmyyw** [comment]
The project is very old. The main project bridges swift and generates `-Swift.h` file . It is normal for me to call other interfaces, only the protocol cannot work

**Comment by ZiZasaurus** [comment]
@rgmyyw thank you for providing these screenshots. To better assist you, can you please provide us more of your WeTalk-Swift.h file so we can see where it imports MapboxMaps? Additionally, how are you integrating Mapbox Maps (cocoapods, carthage, etc)?

I've attached a sample project that demonstrates the incorporation of the `LocationProviderDelegate` without it having to conform to AnyObject, however, if you’re still experiencing issues you can also implement a wrapper to reference the Swift code in your ObjC Xcode project.

[https://app.zenhub.com/files/330733892/1b4a2ba2-eec9-4655-914d-d9a9ff8605c4/download](https://app.zenhub.com/files/330733892/1b4a2ba2-eec9-4655-914d-d9a9ff8605c4/download)
