### ISSUE TITLE
How to get all the markers from MapView and zoom camera to them in v10.x?

### ISSUE THREAD

**Issue by MahdiRB** [mapbox/mapbox-maps-ios#1142]
There was a function in version 6 of Mapbox which we could get annotations on the map and zoom the camera to them, just like this: https://github.com/mapbox/mapbox-gl-native-ios/issues/118#issuecomment-578383864

I have not find any ability like this in v10 and above.

**Comment by ZiZasaurus** [comment]
@MahdiRB you can use [queryRenderedFeatures(in:options:completion:) ](https://docs.mapbox.com/ios/maps/api/10.3.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC21queryRenderedFeatures2in7options10completionySo6CGRectV_So23MBMRenderedQueryOptionsCSgys6ResultOySaySo17MBMQueriedFeatureCGs5Error_pGctF) to get the annotations on your map and / or [camera(for: camera:rect:)](https://docs.mapbox.com/ios/maps/api/10.3.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC6camera3for7padding7bearing5pitchAA13CameraOptionsVSaySo22CLLocationCoordinate2DVG_So12UIEdgeInsetsVSdSgAPtF) with coordinates or [camera(for:padding:bearing:pitch:)](https://docs.mapbox.com/ios/maps/api/10.3.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC6camera3for7padding7bearing5pitchAA13CameraOptionsVSaySo22CLLocationCoordinate2DVG_So12UIEdgeInsetsVSdSgAPtF) with geometry to set the camera to annotations on your map.
