### ISSUE TITLE
SymbolLayer.predicate is missing

### ISSUE THREAD

**Issue by metaine** [mapbox/mapbox-maps-ios#1151]
## New Feature

Mapbox GL layers has predicate property of NSPredicate type allowing to filter output of source data. 
I see no substitute for this in new version. 

## Why

New property for Layer (iconVisibility for instance) taking Expression as input would be handy, to support data filtering before rendering it to the map. Or maybe make it clear in docs/examples how to migrate without it.

**Comment by ZiZasaurus** [comment]
@metaine, we do possess a filter property for layers [here](https://docs.mapbox.com/ios/maps/api/10.3.0/Structs/SymbolLayer.html#/s:10MapboxMaps5LayerP6filterAA10ExpressionVSgvp) which can be seen in action in our [Multiple Geometries example](https://github.com/mapbox/mapbox-maps-ios/blob/de3800d042e0c095321fefac4cbc6c03d40b75c1/Apps/Examples/Examples/All%20Examples/MultipleGeometriesExample.swift).

**Comment by metaine** [comment]
Thanks. I ovelooked this one.
