### ISSUE TITLE
SwiftUI Cannot find 'MapEvents' in scope

### ISSUE THREAD

**Issue by AVatch** [mapbox/mapbox-maps-ios#1156]
## Environment

- Xcode version: 13.2.1 (13C100)
- iOS version: 15.x
- Devices affected:
- Maps SDK Version: 10.3.0

## Observed behavior and steps to reproduce

Using the provided [SwiftUI example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SwiftUIExample.swift) Xcode throws an error that MapEvents can't be found in scope
 
## Expected behavior

This error should not be thrown and MapEvents should appear in auto-complete

**Comment by ZiZasaurus** [comment]
@AVatch are you running the example by itself or are you running it inside the Examples app? I'm not experiencing any errors running the example?

**Comment by AVatch** [comment]
Hey @ZiZasaurus I’m running it in a stand-alone project. I’ll try to share a repo when I get home today.

**Comment by AVatch** [comment]
Ok, check this out, just a vanilla SwiftUI project and me copying over the sample data (and adding mapbox as a dependency) 

The funny thing is that it compiles, but the errors still pop up.

https://github.com/AVatch/mapbox-swiftui-test

<img width="848" alt="Screen Shot 2022-03-01 at 2 42 54 PM" src="https://user-images.githubusercontent.com/1807958/156237539-7384535f-49bc-4c2a-a07e-1d01efb0f6ca.png">

<img width="857" alt="Screen Shot 2022-03-01 at 2 41 43 PM" src="https://user-images.githubusercontent.com/1807958/156237542-c802a8f5-a4ba-4680-8009-dd260d11540a.png">

**Comment by ZiZasaurus** [comment]
@AVatch the project you provided was empty, however this may be related to your Xcode version, as I ran the example in both Xcode 13.0 and Xcode 13.2.1 and I only received errors in Xcode 13.2.1.

**Comment by AVatch** [comment]
Sorry for that, but yeah you're correct, I'm running `Version 13.2.1 (13C100)`

**Comment by ZiZasaurus** [comment]
@AVatch, thank you for confirming your version. Can you please provide an updated project that reproduces the behavior you reported?

**Comment by AVatch** [comment]
@ZiZasaurus pushed to the repo https://github.com/AVatch/mapbox-swiftui-test

**Comment by ZiZasaurus** [comment]
@AVatch thank you for providing the updated project. I was able to reproduce the errors and used the following steps to resolve them: 

1. Make sure your Command Line Tools are set to the version of Xcode you're currently using. (Xcode > Preferences > Locations)
2. Restart Xcode 
3. Clean your build folder 
4. Reset your package caches 

Please let me know if these steps help resolve the errors you're getting.

**Comment by AVatch** [comment]
Hey @ZiZasaurus Thank you for investigating and sharing these steps. 

I no longer am getting the errors in Xcode after reseting the build folder / cache. 

For my own curiosity is this an artifact of the Xcode package manager and how it imports the package? Just trying to figure out how to spot this in the future.
