### ISSUE TITLE
Add map layers asynchronously 

### ISSUE THREAD

**Issue by tungvustarglobal** [mapbox/mapbox-maps-ios#1174]
## Environment

- Xcode version: 13.2.1
- iOS version: 15.2
- Devices affected: devices and simulator
- Maps SDK Version: 10.3.0

## Observed behavior and steps to reproduce
In our application we have hundreds on layers (lines, polygons,...) to render at a time. When user change the view port, we'll fetch new data, once we have that data we remove the old layers and renders the new one.
But since we're using `style.addSource`, `style.addLayer` on main thread so I notice there's a bit lag.
I've tried to move it off the main thread but It causes flashy animation (layers disappeared then appeared again), we don't want that.
## Expected behavior
Move render mechanism off main thread correctly.

**Comment by ZiZasaurus** [comment]
@tungvustarglobal can you please provide us with a scenario reproducing the lag you're experiencing on the main thread?

**Comment by tungvustarglobal** [comment]
When I'm panning around the map while data is loading, once data loaded, I got about 500 layers (including point PointLayer (with image), Polyline, Polygon,...)  for example, the map get lag for a half of second before layers are rendered on the map.

**Comment by ZiZasaurus** [comment]
@tungvustarglobal, are you referring to [annotations](https://docs.mapbox.com/ios/maps/guides/annotations/annotations/)?  If so, this method is Inefficient for adding more than 250 markers to the map. Instead, we recommend using [StyleLayers](https://docs.mapbox.com/android/maps/guides/annotations/style-layers/).

**Comment by tungvustarglobal** [comment]
No, I'm rendering Style Layers. Please take a look at this instance.
![Simulator Screen Shot - iPhone 11 Pro Max 2 - 2022-03-14 at 12 02 13](https://user-images.githubusercontent.com/92707740/158289331-9fe6924b-bf3a-4a62-8412-20274e613688.png)

**Comment by LearnWithTung** [comment]
We're having three types of layers - point, lines, and polygon. We're fetching entities from server and with each entity contains coordinates, from that coordinates we create these three layers (we calculate centroid for point layer) then add to a source and display to the map. 
And yeah, most of response contains roughly 500 entities

**Comment by tungvustarglobal** [comment]
We're having three types of layers - point, lines, and polygon. We're fetching entities from server and with each entity contains coordinates, from that coordinates we create these three layers (we calculate centroid for point layer) then add to a source and display to the map. 
And yeah, most of response contains roughly 500 entities

**Comment by ZiZasaurus** [comment]
@tungvustarglobal apologies for the delay in my response. You should edit your style only from main thread. As this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
