### ISSUE TITLE
Map will only move down after setCamera to zoom level 13

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#119]
## Environment

- Xcode version: 12.3
- iOS version: 14.3 on simulator and actual device
- Devices affected: simulator, iPhone 6s, 11Pro
- Maps SDK Version: 10.0.0-beta.13

## Observed behavior and steps to reproduce

With terrain, after animating camera to a map location at zoom level 13, on any swipe gesture to move the map up, down, left, or right, the map will only move down, and appears to move down faster on a down gesture than either left or right or up.

Steps to recreate:

After creating a `MapView` and adding it as subview of the view controller view, do:
```
mapView.update { mapOptions in
    mapOptions.location.showUserLocation = true
    mapOptions.ornaments.showsScale = true  //default value
    mapOptions.camera.maximumPitch = 85
    mapOptions.camera.maximumZoomLevel = 21
}
```

Then set initial camera:
```
self.mapView.isUserInteractionEnabled = false
let centerCoordinate = CLLocationCoordinate2D(latitude: 39.39305, longitude: -97.56589)
self.mapView.cameraManager.setCamera(centerCoordinate: centerCoordinate, zoom: 2.0, bearing: 0, pitch: 0)
```

```
mapView.on(.mapLoadingFinished) { [weak self] event in
    guard let self = self else { return }
    let mtHood = CLLocationCoordinate2D(latitude: 45.37373, longitude: -121.69704)
    let startLocation = self.mapView.locationManager.latestLocation?.coordinate ?? mtHood
    let cameraOptions = CameraOptions(center: startLocation, zoom: 13.0, bearing: 0, pitch: 30.0)
    self.mapView.cameraManager.setCamera(to: cameraOptions, animated: true, duration: 0.6) { _ in
        self.mapView.isUserInteractionEnabled = true
    }
}
```
Video:
https://user-images.githubusercontent.com/39099029/108400390-fce58000-71cf-11eb-834d-4e1d2c2cc9fe.mov
Note that after a zoom out gesture, the issue is resolved. Not shown in the video, but any pinch zoom gesture, in or out, resolves the issue.

Interestingly, if the center point is `nil`, in which case the camera center remains the `centerCoordinate` value above, then the issue does not occur:
`let cameraOptions = CameraOptions(center: nil, zoom: 13.0, bearing: 0, pitch: 30.0)`
https://user-images.githubusercontent.com/39099029/108402444-66668e00-71d2-11eb-9efc-7a9c89fbe716.mov

Perhaps the issue depends on the elevation of the initial center point. The location that the simulator zooms to for user location is latitude: 36.75744, longitude: -121.40073.

Also see the issue on actual device, which uses my actual location in Portland, OR.

If I change the zoom value to 11.0 in `CameraOptions`, the issue does not occur.

If I set initial pitch to 0, when move completes immediately pitch the camera up, then issue reverses itself: any swipe gesture only moves the camera forward. Again, any zoom gesture restores expected behavior.

## Expected behavior

Map gestures work correctly after the sequence of events above at any map location, zoom level, pitch, and orientation.

## Notes / preliminary analysis

Much detail above. Happy to experiment with other situations that you might suggest.

**Comment by macdrevx** [comment]
Thanks for your feedback. Gesture support for 3D terrain is still in development, and we will have an update soon.

**Comment by jmkiley** [comment]
Thank you for the report. I'm not able to replicate this issue. Let us know if you are still seeing it!
