### ISSUE TITLE
Setting active icon state to Annotations on selection on Mapbox iOS SDK

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [mapbox/mapbox-maps-ios#1205]
I am trying to achieve following use case in our iOS app using Mapbox SDK.

Use case: Annotations are drawn on the map. Once annotations are drawn, on annotation selection, annotation should have an active state (active annotation needs to be highlighted by changing the annotation image) So far, we couldn’t find any relevant example to achieve this. We got this kinda behaviour working by a dirty way which is as following:

Create global reference of all drawn mappers by doing var lastAnnotations = PointAnnotation
Whenever annotations are drawn over map, update the lastAnnotations global array.
When annotation is tapped, the didDetectTappedAnnotations is executed, here, travers previous global array and create a new annotation list (but with the selected annotation’s image updated). Create a new annotation manager and re-assign this list to new manager. Like:

```
func annotationManager(_ manager: AnnotationManager, didDetectTappedAnnotations annotations: [Annotation]) {
    if let annotation = annotations.first, let pointAnnotation = annotation as? PointAnnotation {
      var tempAnnotations = [PointAnnotation]()
       
      for(_, tempAnnotation) in lastAnnotations.enumerated() {
        if tempAnnotation.id == pointAnnotation.id {
          var newAnnotation = tempAnnotation
          newAnnotation.image = .init(image: .init(named: "bullet_1")!, name: "bullet_1")
          tempAnnotations.append(newAnnotation)
        } else {
          tempAnnotations.append(tempAnnotation)
        }
      }
       
      let pointAnnotationManager = mapView.annotations.makePointAnnotationManager(id: CustomMapView.annotationManagerId)
      pointAnnotationManager.delegate = self
      pointAnnotationManager.iconAllowOverlap = false
      pointAnnotationManager.iconIgnorePlacement = false
      pointAnnotationManager.annotations = tempAnnotations
          
      addPointAnnotation(pointAnnotation)
    }

```

Above approach works, but this doesn’t seem to be a proper way to achieve the given use case. With this approach, if map is panned/zoomed, the markers are redrawn for new annotations. But previously selected annotation active icon is not retained. To retain the selected state again, we might need to capture/track last selected annotation, and again match with the new response whenever map is panned/zoomed (just like above example) This approach seems very naive, hacky and doesn’t seem maintainable. Is there any other way where Mapbox iOS sdk handles this kind of behaviour with some properties? We couldn’t find anything relevant in the docs. If you could direct us to the right documentation/steps that would be very helpful. 

Thanks!

**Comment by ZiZasaurus** [comment]
@pushkardeshmukh1992, as this is more of a product support Issue,  our support team will be happy to get you the answers you need.
