### ISSUE TITLE
Setting showsUserLocation = false is canceled by UserTrackingMode = .followWithHeading

### ISSUE THREAD

**Issue by NickBrinsmade** [mapbox/mapbox-maps-ios#1206]
## Environment

- Xcode version: 12.5.1
- iOS version: 14.2
- Devices affected: All
- Maps SDK Version: 6.4.0

## Observed behavior and steps to reproduce

In my makeUIView() function in my UIViewRepresentable map, I'd like to make the user location invisible but at the same time have userTrackingMode be .followWithHeading.  Unfortunately, it doesn't seem like these can be set at the same time. Is there a workaround? 

I track user heading, location, and the actual mapView in my state file so I tried manually doing mapView.setDirection(myHeading, animated: true) and mapView.setCenter(myCoordinates, animated: true). This didn't work--for some reason, the direction updated fine, but the mapView doesn't seems to be frozen in place without updating the center coordinate. The pseudo-boilerplate code for this is below:

```
func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
    self.appState.compassMap.setCenter(manager.location.coordinate, animated: false)
}

func locationManager(_ manager: CLLocationManager, didUpdateHeading newHeading: CLHeading) {
    let degrees = newHeading.trueHeading
    self.appState.compassMap.setDirection(degrees, animated: true)
}
```

Because of this, if there's a simple workaround to removing user annotation and just setting .followWithHeading so I don't have to worry about it, that would be ideal.

**Comment by ZiZasaurus** [comment]
@NickBrinsmade, you can use the `CustomUserLocationAnnotationView` class from our [UserLocationAnnotation example](https://github.com/mapbox/ios-sdk-examples/blob/main/Examples/Swift/UserLocationAnnotationExample.swift), set the dot size to 0 and set CustomUserLocationAnnotationView as the annotation view in [-mapView:viewForAnnotation:](https://docs.mapbox.com/ios/maps/api/6.4.1/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:viewForAnnotation:)

https://user-images.githubusercontent.com/44972592/160851313-6672e6c1-f6b6-48c8-97d5-207ab098cc9f.mp4

As this is more of a product support Issue, if you have additional questions, please feel free to create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
