### ISSUE TITLE
`|` symbol in URL is not supported

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-maps-ios#1211]
## Environment

- Xcode version: all
- iOS version: all
- Devices affected: all
- Maps SDK Version: 10.x

## Observed behavior and steps to reproduce

When trying to build `ExternalVectorSourceExample` with the URL from the public [GL JS sample](https://docs.mapbox.com/mapbox-gl-js/example/third-party/) it will fail to download tiles, because the tiles URL contains `|` symbols. The error in logs is: 
`Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL"`

## Expected behavior

iOS SDK should accept URLs with `|` symbols since the GL JS library already supports them.

## Notes / preliminary analysis

Replacing `|` with `%7C` will resolve the problem, however, it would be nice if iOS Maps SDK can support this and other nonpopular symbols.

**Comment by ZiZasaurus** [comment]
@azarovalex while we probably don't want to support these symbols, as pipes are not traditionally used in URLs, maps common could check to make sure the URL isn't nil and if it is, provide a more useful error message.
