### ISSUE TITLE
Issue in iOS version 10.4.0 but fine in 10.3.0

### ISSUE THREAD

**Issue by rhondadevore** [mapbox/mapbox-maps-ios#1212]
## Environment

- Xcode version: 13.2
- iOS version: 15.2
- Devices affected: iPhone 8 
- Maps SDK Version: 10.4.0

## Observed behavior and steps to reproduce

Setup: Simple map contained in a collectionView cell. Single circle annotation added to the map. 
`
var circleAnnotation = CircleAnnotation(point: Point(LocationCoordinate2D(latitude: lat, longitude: lon)))
circleAnnotation.circleRadius = 50.0
circleAnnotation.circleStrokeColor = StyleColor(.black)

let annotationManager = mapView.annotations.makeCircleAnnotationManager()
        annotationManager.annotations = [circleAnnotation]
        
mapCenter = CLLocationCoordinate2DMake(lat, lon)
mapZoom = 15.0

mapView.mapboxMap.setCamera(to: CameraOptions(center: mapCenter, zoom:mapZoom ))
`

Using SDK 10.3.0 works as expected. 
Using SDK 10.4.0 crashes giving this information: 

> [CAMetalLayer nextDrawable] returning nil because allocation failed.
validateRenderPassDescriptor:991: failed assertion `RenderPass Descriptor Validation
No rendertargets set in RenderPassDescriptor.

## Expected behavior

Circle annotation renders and doesn't crash

## Notes / preliminary analysis

I've tested out and and can say it crashes 9/10 times. I've tested with both a point annotation and circle annotation. The type of annotation doesn't seem to make a difference. It did work one single time with a point annotation. 

I'll be switching back to sdk version 10.3.0 in the meantime.

**Comment by macdrevx** [comment]
Does this happen on simulator, or only on device? Are you able to share a full crash report? What installation method are you using?

**Comment by rhondadevore** [comment]
I've updated the title of this because as I've been testing further, it looks like it isn't fully crashing, but hitting that assertion failure and I cannot continue to run in the debugger. 

My map isn't on screen when the viewController loads and this seems to happen consistently if I scroll fast down to the map. 

I've tested on the following simulators/devices
iPhone 8 Simulator running iOS 15.2
iPhone 8 Simulator running iOS 14.0.1
iPhone 12 Pro device running iOS 15.3.1

All seem to have the same result (when running via the debugger it hits the assertion failure and I can't continue past the Xcode break, but when running without the debugger, the Ui only seems to have a slight hitch when rendering on screen)

The sdk is installed via swift packages and an .netrc file on the local machine. 

Here is a screenshot of the issue as it happens: 
<img width="972" alt="Screen Shot 2022-03-27 at 9 24 11 AM" src="https://user-images.githubusercontent.com/3603603/160291868-40f61e67-7b4d-40af-9dc3-d9aa6199a29e.png">

**Comment by macdrevx** [comment]
Thanks for the additional info. I'm trying to repro using the following, but haven't had any luck so far:

```
final class DebugViewController: UIViewController {

    var mapView: MapView!

    override func viewDidLoad() {
        super.viewDidLoad()

        let scrollView = UIScrollView(frame: view.bounds)
        scrollView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(scrollView)

        let contentView = UIView(frame: CGRect(x: 0, y: 0, width: view.bounds.width, height: 3 * view.bounds.height))
        contentView.backgroundColor = .white
        contentView.translatesAutoresizingMaskIntoConstraints = false
        scrollView.addSubview(contentView)

        mapView = MapView(frame: view.bounds)
        mapView.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(mapView)

        NSLayoutConstraint.activate([
            scrollView.topAnchor.constraint(equalTo: view.topAnchor),
            scrollView.leftAnchor.constraint(equalTo: view.leftAnchor),
            scrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            scrollView.rightAnchor.constraint(equalTo: view.rightAnchor),
            contentView.topAnchor.constraint(equalTo: scrollView.topAnchor),
            contentView.leftAnchor.constraint(equalTo: scrollView.leftAnchor),
            contentView.bottomAnchor.constraint(equalTo: scrollView.bottomAnchor),
            contentView.rightAnchor.constraint(equalTo: scrollView.rightAnchor),
            contentView.widthAnchor.constraint(equalTo: view.widthAnchor),
            contentView.heightAnchor.constraint(equalTo: view.heightAnchor, multiplier: 3),
            mapView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor),
            mapView.leftAnchor.constraint(equalTo: contentView.leftAnchor),
            mapView.rightAnchor.constraint(equalTo: contentView.rightAnchor),
            mapView.heightAnchor.constraint(equalTo: view.heightAnchor, multiplier: 0.5)
        ])
    }
}
```

Can you think of anything that might be different about the setup in your app? If we can come up with a minimal reproducible test case, that will greatly accelerate our ability to debug and fix this issue.

**Comment by macdrevx** [comment]
Updated sample code that I'm using to try to repro (still no luck):

```
final class DebugViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate {

    var mapView: MapView?

    override func viewDidLoad() {
        super.viewDidLoad()

        let layout = UICollectionViewFlowLayout()
        layout.itemSize = CGSize(width: 300, height: 400)

        let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: layout)
        collectionView.dataSource = self
        collectionView.delegate = self
        collectionView.register(UICollectionViewCell.self, forCellWithReuseIdentifier: "abcd")
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(collectionView)

        NSLayoutConstraint.activate([
            collectionView.topAnchor.constraint(equalTo: view.topAnchor),
            collectionView.leftAnchor.constraint(equalTo: view.leftAnchor),
            collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            collectionView.rightAnchor.constraint(equalTo: view.rightAnchor)
        ])
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        10
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "abcd", for: indexPath)

        if indexPath.row == 9 {
            let mapView: MapView
            if let m = self.mapView {
                mapView = m
            } else {
                mapView = MapView(frame: view.bounds)
                mapView.translatesAutoresizingMaskIntoConstraints = false

                var circleAnnotation = CircleAnnotation(point: Point(LocationCoordinate2D(latitude: 0, longitude: 0)))
                circleAnnotation.circleRadius = 50.0
                circleAnnotation.circleStrokeColor = StyleColor(.black)

                let annotationManager = mapView.annotations.makeCircleAnnotationManager()
                annotationManager.annotations = [circleAnnotation]

                let mapCenter = CLLocationCoordinate2D(latitude: 0, longitude: 0)
                let mapZoom = 15.0

                mapView.mapboxMap.setCamera(to: CameraOptions(center: mapCenter, zoom: mapZoom))
                self.mapView = mapView
            }

            cell.contentView.addSubview(mapView)

            NSLayoutConstraint.activate([
                mapView.bottomAnchor.constraint(equalTo: cell.contentView.bottomAnchor),
                mapView.leftAnchor.constraint(equalTo: cell.contentView.leftAnchor),
                mapView.rightAnchor.constraint(equalTo: cell.contentView.rightAnchor),
                mapView.topAnchor.constraint(equalTo: cell.contentView.topAnchor)
            ])
        } else if mapView?.superview === cell.contentView {
            mapView?.removeFromSuperview()
        }

        return cell
    }
}
```

**Comment by macdrevx** [comment]
Do you have more than 1 cell that contains a MapView? If so, how many, and how are they distributed throughout the collection view?

**Comment by rhondadevore** [comment]
I'll work on creating a viewController that I can share here to reproduce. There is only one cell that contains a MapView. 

I am using a compositional layout with a diffable data source for the collectionView.

**Comment by rhondadevore** [comment]
With the following view controller, I'm able to recreate the issue:

    class MapboxDebugController:UIViewController
    {
        enum SectionType:CaseIterable
        {
            case single
        }
                                
        class Item:DiffableItem
        {
            enum ItemType:CaseIterable
            {
                case text, map
            }

            let type:ItemType

            init(_ type:ItemType)
            {
                self.type = type
            }
        }

        var text:String = ""
        var lat:Double = 0.0
        var lon:Double = 0.0

        private var dataSource: UICollectionViewDiffableDataSource<SectionType, Item>? = nil

        override func viewDidLoad()
        {
            super.viewDidLoad()
            
            self.text = "When the cheese comes out everybody's happy everyone loves cheeseburger. Bocconcini croque monsieur cheesy grin cream cheese hard cheese cauliflower cheese monterey jack stinking bishop. Brie cream cheese cheese slices cheese slices say cheese chalk and cheese chalk and cheese lancashire. Cheese slices roquefort melted cheese airedale monterey jack roquefort dolcelatte fromage frais. Bocconcini stilton paneer cheese slices.\n\nCheesy feet cauliflower cheese taleggio. Cheddar the big cheese fromage croque monsieur caerphilly say cheese feta cheese and biscuits. Ricotta dolcelatte fromage frais cheesy grin queso squirty cheese everyone loves parmesan. Cheese and wine roquefort caerphilly.\n\nPepper jack hard cheese chalk and cheese. Squirty cheese squirty cheese croque monsieur dolcelatte who moved my cheese cauliflower cheese paneer croque monsieur. Say cheese cheesecake fromage mascarpone cow manchego edam cheeseburger. Hard cheese pepper jack swiss danish fontina babybel stilton cottage cheese melted cheese. St. agur blue cheese taleggio edam cheddar.\n\nRubber cheese cauliflower cheese blue castello. Everyone loves gouda hard cheese rubber cheese feta caerphilly cheeseburger bavarian bergkase. Chalk and cheese cream cheese cut the cheese cheese slices st. agur blue cheese mascarpone cheese and biscuits mozzarella. Cow when the cheese comes out everybody's happy fromage swiss.\n\nGouda hard cheese ricotta. Pepper jack the big cheese pepper jack emmental cream cheese cheese slices edam cheesy grin. Camembert de normandie airedale cow smelly cheese everyone loves paneer manchego red leicester. Bocconcini say cheese fromage frais.\n\nCow swiss goat. Cheddar the big cheese airedale pecorino pecorino bocconcini macaroni cheese babybel. Cheese strings stinking bishop taleggio cheese and wine smelly cheese port-salut everyone loves edam. Cheese on toast monterey jack gouda cheesy grin everyone loves boursin fromage frais.\n\nDanish fontina camembert de normandie chalk and cheese. Lancashire cheese triangles roquefort cheese and wine caerphilly st. agur blue cheese roquefort feta. Cheddar fromage frais cow red leicester cheese and biscuits cheeseburger hard cheese st. agur blue cheese. Croque monsieur cheese triangles the big cheese macaroni cheese roquefort everyone loves stinking bishop chalk and cheese. Cheese and biscuits stilton caerphilly smelly cheese.\n\nSquirty cheese paneer rubber cheese. Who moved my cheese cottage cheese fondue blue castello mozzarella pecorino cut the cheese cheese strings. Blue castello feta pepper jack croque monsieur paneer pepper jack halloumi cheese triangles. Cheese and wine cottage cheese cheese triangles.\n\nCheesy feet mascarpone red leicester. Goat cheese slices stinking bishop hard cheese babybel squirty cheese boursin cottage cheese. Cheeseburger brie cauliflower cheese fromage frais roquefort smelly cheese cheese slices emmental. Emmental stinking bishop fondue squirty cheese cheesy feet.\n\nQueso goat cheese triangles. Say cheese monterey jack taleggio paneer swiss boursin fondue croque monsieur. Cheese on toast mozzarella fondue goat squirty cheese manchego melted cheese say cheese. Edam.\n\n"
            
            self.lat = 45.4351663
            self.lon = -122.7676828
            
            var snapshot = NSDiffableDataSourceSnapshot<SectionType, Item>()
            snapshot.appendSections([.single])
            snapshot.appendItems([Item(.text), Item(.map)], toSection: .single)
            self.dataSource?.apply(snapshot, animatingDifferences: false)
        }

        //MARK: View Creation
        override func loadView()
        {
            super.loadView()
            
            view.backgroundColor = .white
                    
            view.addSubview(collectionView)
            collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
            collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
            collectionView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
            collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
            
            collectionView.register(VariableHeightTextCell.self, forCellWithReuseIdentifier: VariableHeightTextCell.reuseIdentifier)
            collectionView.register(MapCell.self, forCellWithReuseIdentifier: MapCell.reuseIdentifier)
            
            let layout = UICollectionViewCompositionalLayout
            { (sectionIndex: Int, layoutEnvironment:NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection? in
                let sectionType = SectionType.allCases[sectionIndex]
                switch sectionType
                {
                case .single:
                    let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .estimated(1000))
                    let item = NSCollectionLayoutItem(layoutSize: itemSize)
                    let group = NSCollectionLayoutGroup.horizontal(layoutSize: itemSize, subitem: item, count: 1)
                    let section = NSCollectionLayoutSection(group: group)
                    section.contentInsets = .zero
                    return section
                }
            }
            
            collectionView.collectionViewLayout = layout
            
            
            self.dataSource = UICollectionViewDiffableDataSource<SectionType, Item>(collectionView: collectionView)
            { (collectionView:UICollectionView, indexPath: IndexPath, item: Item) -> UICollectionViewCell? in
                
                switch item.type
                {
                case .text:
                    guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: VariableHeightTextCell.reuseIdentifier, for: indexPath) as? VariableHeightTextCell else
                    {
                        fatalError("Couldn't dequeue VariableHeightTextCell!")
                    }
                    cell.label.text = self.text
                    return cell
                    
                case .map:
                    guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MapCell.reuseIdentifier, for: indexPath) as? MapCell else
                    {
                        fatalError("Couldn't dequeue MapCell!")
                    }
                    cell.setup(self.lat, self.lon)
                    return cell
                }
            }
        }

        let collectionView:UICollectionView = {
            let layout = UICollectionViewFlowLayout()
            layout.scrollDirection = .vertical
            
            let c = UICollectionView(frame: .zero, collectionViewLayout: layout)
            c.translatesAutoresizingMaskIntoConstraints = false
            c.backgroundColor = .white
            
            return c
        }()
        }

        fileprivate class MapCell:UICollectionViewCell
        {
        static var reuseIdentifier:String
        {
           return String(describing: Self.self)
        }

        func setup(_ lat:Double, _ lon:Double)
        {
            var circleAnnotation = CircleAnnotation(point: Point(LocationCoordinate2D(latitude: lat, longitude: lon)))
            circleAnnotation.circleRadius = 50.0
            circleAnnotation.circleStrokeColor = StyleColor(UIColor(white: 0.00, alpha: 0.30))
            circleAnnotation.circleStrokeOpacity = 0.70
            circleAnnotation.circleStrokeWidth = 1.0
            circleAnnotation.circleBlur = 0.5

            let annotationManager = mapView.annotations.makeCircleAnnotationManager()
            annotationManager.annotations = [circleAnnotation]

            mapView.mapboxMap.setCamera(to: CameraOptions(center: CLLocationCoordinate2DMake(lat, lon), zoom:15.0 ))
        }

        override init(frame: CGRect)
        {
            super.init(frame: frame)
            setupView()
        }

        required init?(coder: NSCoder)
        {
            fatalError("init(coder:) has not been implemented")
        }

        private func setupView()
        {
            contentView.backgroundColor = .white
            
            contentView.addSubview(mapView)
            mapView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 20).isActive = true
            mapView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 10).isActive = true
            mapView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -20).isActive = true
            mapView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -10).isActive = true
           
            mapView.heightAnchor.constraint(equalTo: mapView.widthAnchor, multiplier: (2/3)).isActive = true
        }

        private let mapView:MapView = {
            let myResourceOptions = ResourceOptions(accessToken: Prefs.mapboxToken)
            let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
            
            let v = MapView(frame: .zero, mapInitOptions: myMapInitOptions)
            v.translatesAutoresizingMaskIntoConstraints = false
            v.backgroundColor = .lightGray
            v.gestures.options.panEnabled = false
            v.gestures.options.pinchEnabled = false
            v.gestures.options.pinchRotateEnabled = false
            v.gestures.options.pinchZoomEnabled = false //v10.4.0
            v.gestures.options.pinchPanEnabled = false  //v10.4.0
            v.gestures.options.pitchEnabled = false
            v.gestures.options.doubleTapToZoomInEnabled = false
            v.gestures.options.doubleTouchToZoomOutEnabled = false
            v.gestures.options.quickZoomEnabled = false
            return v
        }()
        }

        fileprivate class VariableHeightTextCell:UICollectionViewCell
        {
        static var reuseIdentifier:String
        {
           return String(describing: Self.self)
        }

        override init(frame: CGRect)
        {
            super.init(frame: frame)
            setupView()
        }

        required init?(coder: NSCoder)
        {
            fatalError("init(coder:) has not been implemented")
        }

        override func prepareForReuse()
        {
            self.label.text = nil
            super.prepareForReuse()
        }

        private func setupView()
        {
            contentView.backgroundColor = .white
            
            contentView.addSubview(label)
            label.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 20).isActive = true
            label.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 10).isActive = true
            label.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -20).isActive = true
            label.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -10).isActive = true
        }

        let label:UILabel = {
            let v = UILabel()
            v.translatesAutoresizingMaskIntoConstraints = false
            v.textColor = .black
            v.numberOfLines = 0
            v.font = UIFont.systemFont(ofSize: 16, weight: .regular)
            v.textAlignment = .left
            return v
        }()
    }

**Comment by macdrevx** [comment]
Thanks, we'll take a look

**Comment by macdrevx** [comment]
I can repro using this code sample (had to modify it slightly by changing `class Item:DiffableItem` to `struct Item: Hashable` since I don't have `DiffableItem`).

**Comment by macdrevx** [comment]
Reverting https://github.com/mapbox/mapbox-maps-ios/pull/1157 prevents this crash.

**Comment by macdrevx** [comment]
Due to the severity of this issue, we've decided to release a patch (v10.4.1) that will revert https://github.com/mapbox/mapbox-maps-ios/pull/1157.

**Comment by macdrevx** [comment]
[v10.4.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.4.1) has been released. We plan to dig deeper to identify the root cause of this crash and will determine whether we can restore the changes from #1157 with modifications. We will also look for ways to add automated tests to avoid repeating this regression.

**Comment by rhondadevore** [comment]
Thanks!
