### ISSUE TITLE
Feature query when long press the map

### ISSUE THREAD

**Issue by carlodenardin** [mapbox/mapbox-maps-ios#1213]
## New Feature

I'm new in the Mapbox world. I'm following the tutorial on the Mapbox website on the iOS sdk v10 but I'm not getting how to query the layer to get the information of the features in a certain points.

I need some tutorials or documentations but it is very difficult to find something.

Someone has some suggestions?

**Comment by ZiZasaurus** [comment]
@carlodenardin Welcome! We have [this example](https://github.com/mapbox/mapbox-maps-ios/blob/69e9d106028090929340b717776c3e9f4ccb1750/Apps/Examples/Examples/All%20Examples/FeaturesAtPointExample.swift) that demonstrates querying features. We also have documentation [here](https://docs.mapbox.com/help/glossary/feature-querying/) regarding querying features on the map. 

If you have any additional questions regarding product support, please feel free to create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
