### ISSUE TITLE
Can I restrict the heat map within the polygon as in the screenshot?

### ISSUE THREAD

**Issue by R1ick** [mapbox/mapbox-maps-ios#1224]
@macdrevx @OdNairy @jmkiley 
![image](https://user-images.githubusercontent.com/96225594/160649380-66cc8d43-0d31-4487-8ee7-960e6ce7f6a0.jpeg)

**Comment by ZiZasaurus** [comment]
@R1ick yes, you can. I used an arbitrary polygon to achieve the use case below: 

You would need to define the coordinates you'd like the heatmap to stay inside and then use a `within` expression.

```swift

        let polygonCorners = [
            CLLocationCoordinate2D(latitude: 42.130601, longitude: -124.427334),
            CLLocationCoordinate2D(latitude: 42.130601, longitude: -120.032803),
            CLLocationCoordinate2D(latitude: 39.027489, longitude: -120.032803),
            CLLocationCoordinate2D(latitude: 39.027489, longitude: -124.427334),
            CLLocationCoordinate2D(latitude: 42.130601, longitude: -124.427334)]

        var polygon = Feature(geometry: .polygon(Polygon([polygonCorners])))

        // Create a heatmap layer
        self.heatmapLayer.filter = Exp(.within) {
            GeoJSONObject.feature(polygon)
        }
```

Unfiltered             |  Filtered
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 11 - 2022-03-30 at 16 59 13](https://user-images.githubusercontent.com/44972592/160930153-72459238-3080-4f9b-82d2-2fd4aebbe002.png) |  ![Simulator Screen Shot - iPhone 11 - 2022-03-30 at 16 58 45](https://user-images.githubusercontent.com/44972592/160930154-0b5c71e9-0ccc-4e37-8d94-ce59cb64ff25.png)
