### ISSUE TITLE
Add back MGLUserTrackingMode

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#1229]
## New Feature

The old version of Mapbox had a MGLUserTrackingMode.
So the ability to 1. locate the user, 2. follow the user and 3. follow the user with heading.
Those were very convenient and seem to be missing in V10?!?

## Why
It is a very convenient feature for the user to orientate himself on the map

**Comment by georgbachmann** [comment]
Is there any update on this @ZiZasaurus ?!? (Hope it's fine to mention you here, but you answered previous requests of mine)

The problem is that it's quite hard to do that manually. Especially detecting the part where the user interacts with the map manually (by dragging on it) that would end the whole user-tracking-mode thing.

MapKit maps has this feature and the old version did as well.
For our app this is a quite important feature and currently a blocker for us, beside the very sluggish user-heading arrow
(https://github.com/mapbox/mapbox-maps-ios/issues/1230) and the not so nice to use zooming (https://github.com/mapbox/mapbox-maps-ios/issues/755) (the later is very important for us)

We'd really like to make the switch to V10 soon, but for us, where the map is a very essential part of the app, those are blockers.

Would be great to know if those bug/missing features will be addressed and if so a time-frame would be awesome! :)
Thanks a lot for reading!

**Comment by ZiZasaurus** [comment]
@georgbachmann happy to help! Have you seen our tracking mode example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/TrackingModeExample.swift)?

**Comment by Args** [comment]
Agree! `MGLUserTrackingMode` is very convenient.

**Comment by ZiZasaurus** [comment]
Hi all, [viewport](https://docs.mapbox.com/ios/maps/api/10.4.3/Classes/Viewport.html) is the replacement for `MGLUserTrackingMode`. We have an example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/ViewportExample.swift) that demonstrates its usage.
