### ISSUE TITLE
Crucial changes in text-max-width property

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#1249]
## Environment

iOS SDK 10+
Android SDK 10+
Web SDK 2.2

## Observed behavior and steps to reproduce

In old SDK on all platform setting `"text-max-width": 0` make width infinity. In new SDK it works in strange way

## Expected behavior

0 mean infinity like it was in old SKD:
![Screenshot 2022-04-06 at 10 36 35](https://user-images.githubusercontent.com/24453199/161935455-db1c5e56-a240-419f-a455-eb12b2e860b3.png)

Right now it looks:
![Screenshot 2022-04-06 at 10 36 27](https://user-images.githubusercontent.com/24453199/161935507-75b04142-2c54-46c6-8fce-fe540b1cc544.png)

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT the feature is behaving as expected, as the specification doesn't say anywhere [that setting max text width to 0](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-text-max-width) equals to infinite max text width. If needed, you can set the max text width to infinity or max numeric value.

**Comment by MaciejPachciarekSMT** [comment]
So why did it work on old sdk? What does mean now 0, Because 0 width does not make any sense. How I can set the infinity value now (In specification we can pass only number greater than or equal to 0).
We generated more than 1 million different styles and for us is not possible to regenerate it.

**Comment by ZiZasaurus** [comment]
The default value is set to 10  but you can override this value for your use case by setting the value at runtime from 0 to the maximum numeric value for your millions of pre-generated styles. Please note that the `maxmiumTextWidth` property in [v6](https://docs.mapbox.com/ios/maps/api/6.4.1/Classes/MGLSymbolStyleLayer.html#/c:objc(cs)MGLSymbolStyleLayer(py)maximumTextWidth) and `withTextMaxWidth` in [v9 ](https://docs.mapbox.com/android/plugins/api/annotation/0.9.0/com/mapbox/mapboxsdk/plugins/annotation/SymbolOptions.html#withTextMaxWidth-java.lang.Float-)correspond to the same `text-max-width` Mapbox Style Specification property as `textMaxWidth` in [iOS](https://docs.mapbox.com/ios/maps/api/10.4.3/Structs/SymbolLayer.html#/s:10MapboxMaps11SymbolLayerV12textMaxWidthAA5ValueOySdGSgvp) and [Android](https://docs.mapbox.com/android/maps/api/10.4.2/mapbox-maps-android/com.mapbox.maps.extension.style.layers.generated/-symbol-layer/text-max-width.html).

**Comment by MaciejPachciarekSMT** [comment]
In old versions, it wasn't work in the same way as you see on screenshots. I know that the default value is 10 but what does it mean 0. How I can set the infinity value.

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT 0 means render text at smallest width. For example, with line breaking applied, "a a a" will be rendered as a single character at each line.

You can set the maximum value using `symbolLayer.textMaxWidth = .constant(Double.infinity)`.

**Comment by ZiZasaurus** [comment]
Closing this ticket, but please feel free to reopen if you experience additional issues with this property.
