### ISSUE TITLE
setStyleImage scale is hardcoded to 3

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-maps-ios#127]
The passed in scale is unused and here it is hardcoded to 3:

https://github.com/mapbox/mapbox-maps-ios/blob/3b567502422f2efa129848e6aeed2d77a9f3fc20/Mapbox/MapboxMapsStyle/Style.swift#L139

**Comment by patrickkempff** [comment]
This is fixed by https://github.com/mapbox/mapbox-maps-ios/pull/269 and can be closed
