### ISSUE TITLE
Currently it doesn't seem to be able to control showing and hiding the ModelLayer

### ISSUE THREAD

**Issue by Args** [mapbox/mapbox-maps-ios#1277]
I use this method:
```
public func updateLayer<T>(withId id: String,
                               type: T.Type,
                               update: (inout T) throws -> Void) throws where T: Layer
```
But I can't get `ModelLayer` because it's `internal`

**Comment by ZiZasaurus** [comment]
@Args, while the ModelLayer is internal, you can still use our lower-level API `setLayerProperties(for layerId: String, properties: [String: Any])` to show/ hide your layer based on its properties. 

Please be aware that while you can use the internal ModelLayer definition to determine the properties you'd like to change, this definition is subject to change in future iterations of the Maps SDK

**Comment by Args** [comment]
Ok ,thank you~
