### ISSUE TITLE
Style.getStyleImage(with:) should return a UIImage

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-maps-ios#128]
`Style.getStyleImage(with:)` returns an Image, which is inconvenient for iOS developers and inconsistent with how `setStyleImage(image:with:sdf:stretchX:stretchY:scale:imageContent:)` accepts a UIImage:

https://github.com/mapbox/mapbox-maps-ios/blob/3b567502422f2efa129848e6aeed2d77a9f3fc20/Mapbox/MapboxMapsStyle/Style.swift#L151

/cc @mapbox/maps-ios

**Comment by 1ec5** [comment]
Currently, the method returns an MBXImage, so developers have to call `cgImage()` to get an unmanaged CGImage, then call `takeUnretainedValue()` or `takeRetainedValue()` depending on the situation. This is error-prone and could lead to crashes or memory leaks such as the one fixed in mapbox/mapbox-navigation-ios#2880. I think it would be pretty important for a Swift-first SDK (or even an Objective-C-first SDK) to avoid exposing unmanaged memory to client code.

/cc @mapbox/maps-ios

**Comment by zugaldia** [comment]
Would the recommendation require breaking API changes?

**Comment by zugaldia** [comment]
Why was this ticket closed?

**Comment by 1ec5** [comment]
This appears to have been fixed in #321.

**Comment by S2Ler** [comment]
Fixes another leak: https://github.com/mapbox/mapbox-maps-ios/pull/562
