### ISSUE TITLE
FlyTo missing smooth padding transition

### ISSUE THREAD

**Issue by naftalibeder** [mapbox/mapbox-maps-ios#1286]
My apologies for eschewing the template, but this is a very simple bug.

The update method in `FlyToCameraAnimator` [is missing padding](cbcffe75d398ab12d4c8bfea8d656/Sources/MapboxMaps/Camera/FlyToCameraAnimator.swift#L134), which means that when using the 'fly-to' camera transition, the padding does not change during the transition, and then updates instantly when the transition completes.

**Comment by ZiZasaurus** [comment]
@mfazekas this behavior has been resolved in our most recent release, v10.7.
