### ISSUE TITLE
`MapEvents.EventKind` documentation incorrectly notes that `offline-data` is non-optional

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#1290]
The documentation for `MapEvents.EventKind.resourceRequest` indicates that [offline-data](https://github.com/mapbox/mapbox-maps-ios/blob/8e928e8d8076f7120decb20fa1bc273766d93e6d/Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift#L238) is non-optional.

In my experience this value is optional. It's unclear if this is a documentation issue, or an implementation issue.

**Comment by macdrevx** [comment]
Looks like the iOS documentation of the event structures is out-dated. We'll update the docs.
