### ISSUE TITLE
Well-formed map event types

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#1291]
## New Feature

The [MapEvents](https://github.com/mapbox/mapbox-maps-ios/blob/8e928e8d8076f7120decb20fa1bc273766d93e6d/Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift#L75=) file has a lot of documentation about the structure of the objects that are contained in `MBMEvent.data`. The documentation is excellent (although there are [occasional errors](https://github.com/mapbox/mapbox-maps-ios/issues/1290)) but it is a little tedious to write our own parsers, especially since it is hard to validate that our parsers are correct.

The Android SDK ships with [well-formed types](https://github.com/mapbox/mapbox-maps-android/tree/main/sdk-base/src/main/java/com/mapbox/maps/extension/observable/eventdata) and it would be useful to have parity.

**Comment by pjleonard37** [comment]
Thanks for the feature request! Well-formed map event types were added in [v10.7.0](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.7.0), specifically in [this PR](https://github.com/mapbox/mapbox-maps-ios/pull/1362). 🎉 

As such, closing this out, but please re-open with any questions.
