### ISSUE TITLE
How should I use the linePattern property of LineLayer

### ISSUE THREAD

**Issue by jokerping** [mapbox/mapbox-maps-ios#1299]
I want to add an arrow image to the LineLayer and I see that there is a linePattern property, but it does not work. 
I checked the documentation and examples, but I didn't find how to use it

I use it like this:
```swift
someLineLayer.linePattern = .constant(.name("arrow"))
```

The path for arrow is Assets\arrow

**Comment by jokerping** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/11515705/165061815-2e4f4a83-d45f-4e92-aa8d-b0a0fa647199.png">


try? self.mapView.mapboxMap.style.addImage(arrow, id: "arrow",sdf: true,stretchX: [] , stretchY: [])

it doesn't seem right

**Comment by jokerping** [comment]
I don't want the black part of the map to appear, but when I add an image it appears

**Comment by ZiZasaurus** [comment]
@jokerping when I add an arrow image to my map I don't experience that issue (see screenshot below). Please note that I'm just creating image without the stretch X and stretch Y. 

```swift
        let image = UIImage(named: "arrow")!
        try! mapView.mapboxMap.style.addImage(image, id: "arrow")

        var lineLayer = LineLayer(id: "line-layer")
        lineLayer.source = geojsonSourceID
        lineLayer.linePattern = .constant(.name("arrow"))
        lineLayer.lineWidth = .constant(20)
        try! mapView.mapboxMap.style.addLayer(lineLayer)
```
![Simulator Screen Shot - iPhone 11 - 2022-04-25 at 10 59 47](https://user-images.githubusercontent.com/44972592/165118776-042e6cad-7663-4db8-be79-d6a9431dd940.png)

**Comment by jokerping** [comment]
When I use the default map style (no MapInitOptions-styleURI set) it is correct, when I load the styleURI （a small partial map）the black appears.

**Comment by ZiZasaurus** [comment]
@jokerping can you please share the styleURI that you are using when you experience this issue?

**Comment by jokerping** [comment]
URi：mapbox://styles/winann/ckwg6yghu0z4x14o2l1ph5twl/draft

image：
![arrow](https://user-images.githubusercontent.com/11515705/165677610-a4647ada-917c-4525-87d4-6a0a2d00029a.png)
：

**Comment by ZiZasaurus** [comment]
Zooming in, I do see what looks like artifacts of your line layer, which appears to be related to the black box you're seeing. By setting the `stretchX` and `stretchY` to the following, the box/artifacts no longer appear: 

```swift
 try! mapView.mapboxMap.style.addImage(image, id: "arrow",
                                              stretchX: [ImageStretches(first: 0, second: 0)],
                                              stretchY: [ImageStretches(first: 0, second: 0)])
```
Can you make these changes on your end and confirm that the result is what you expect?

**Comment by jokerping** [comment]
Thank you very much, using this method shows correctly
