### ISSUE TITLE
Features disappear after adding icons to style. 

### ISSUE THREAD

**Issue by imurashov-belkacar** [mapbox/mapbox-maps-ios#1307]
## Environment

- Xcode version: 13.3.1 (13E500a)
- iOS version: 13.3, 15.4
- Devices affected: iPhone 6S, iPhone 13 mini
- Maps SDK Version: 10.4.3,  6.4.0

## Observed behavior and steps to reproduce

I have a layer with a approximately 1500 features on it. Application get icons for these features from network (~40-50 icons) and then I add them to the style one by one. After first start of app, part of icons disappear, then they can appear and disappear again. It's going on not in 100% of cases, but often enough.

## Expected behavior

Icons not disappear from viewport.

## Notes / preliminary analysis

When it started, Mapbox emits StyleImageRemoveUnused event and in log I see repeated message like this with different icon id.
`[Mapbox] [Warning, maps-core]: {}[Style]: Unused image 'some unique icon key' will be removed. Subscribe to StyleImageRemoveUnused event to control removal of unused images.`

But icons are used. They are on screen.

## Additional links and references

I can attach video if it would be helpful.

**Comment by imurashov-belkacar** [comment]
Looks like this issue https://github.com/mapbox/mapbox-gl-native-ios/issues/627 still exist in Mapbox 10.

**Comment by ZiZasaurus** [comment]
@imurashov-belkacar thank you for reporting. If you can add a video, as well as any additional information/ code snippets pertaining to how you're adding your icons, that would be most appreciated.

**Comment by imurashov-belkacar** [comment]
Hi, @ZiZasaurus 
Sure here is the code:
```
 imageRequestConfigs.forEach { imageRequestConfig in
            if let urlString = imageRequestConfig.url, let url = URL(string: urlString) {
                
                let imageProcessor = ImageProcessors.Resize(
                    size: imageRequestConfig.size,
                    unit: .points,
                    contentMode: .aspectFit,
                    crop: false,
                    upscale: true
                )
                
                let request = ImageRequest(
                    url: url,
                    processors: [imageProcessor],
                    priority: .veryHigh,
                    options: options,
                    userInfo: [.imageIdKey: imageRequestConfig.id]
                )
                
                nukeImageLoader?.loadImage(with: request) { [weak self] result in
                    switch result {
                    case .success(let response):
                        self?.mapView.mapboxMap.style.addImage(response.image, id: imageRequestConfig.id)
                    case .failure(_):
                        self?.mapView.mapboxMap.style.addImage(imageRequestConfig.defaultImage, id: imageRequestConfig.id)
                    }
                }
                
            } else {
                mapView.mapboxMap.style.addImage(imageRequestConfig.defaultImage, id: imageRequestConfig.id)
            }
        }
```
Here I load images with Nuke library, but it's doesn't matter, with other image loading libraries the same.

**Comment by imurashov-belkacar** [comment]
@ZiZasaurus This is how it's looking on device. Images,  are blinked and missed.
It's going on only on first launch. 
Keys for icons on map are unique, of course.   

https://user-images.githubusercontent.com/102508913/166636551-7c9b855e-581e-4336-beb8-a8212e68144a.mp4

**Comment by ZiZasaurus** [comment]
@imurashov-belkacar Thank you for the snippet and the video. When are you making your request for the images? Are you requesting them when the map loads, goes idle or at another time?
