### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1314]
## Environment

- Xcode version: 13.2.1
- iOS version: 15.4
- Devices affected: 
- Maps SDK Version: sdk 10 + 

## Observed behavior and steps to reproduce
When removing annotations from Mapbox it doesn't seem to clear up all the memory, I have thousands of markers rendering which spikes memory usage to 2gb but when I remove all of them the max memory recovered is 1gb, is it possible to clear it even more?

**Comment by SergeyPetrachkov** [comment]
I also see the issue with the memory consumption. The new version of the Mapbox takes up to 10x more RAM than the old one for me. I dunno if that's intended.

**Comment by ZiZasaurus** [comment]
@JenishKananiLime thank you for reporting. Could you please provide us with what type of annotations you're adding and whether there are images involved?

**Comment by ZiZasaurus** [comment]
@JenishKananiLime Could you please provide the following information: 
- What type of annotations are you're adding?
-  Are there are images involved?
-  When do you create the PointAnnotationManager in your app?

**Comment by ZiZasaurus** [comment]
@JenishKananiLime are you still experiencing this issue?
