### ISSUE TITLE
Mapbox v10 touch target accuracy.

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1319]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
 investigating on using Mapbox, but one issue I found comparing all three GMAps, AppleMaps, And Mapbox, is that touch target on Mapbox when zoomed out is pretty big, google provides a pretty accurate marker selection when tapping.

**Comment by JenishKananiLime** [comment]
root cause seems to be 
    @objc private func handleTap(_ tap: UITapGestureRecognizer) {
        let managers = annotationManagersByIdInternal.values.filter { $0.delegate != nil }
        guard !managers.isEmpty else { return }

        let layerIds = managers.map { $0.layerId }
        let options = RenderedQueryOptions(layerIds: layerIds, filter: nil)
        let point = tap.location(in: tap.view)
        mapFeatureQueryable.queryRenderedFeatures(
            in: CGRect(origin: point, size: CGSize.zero).insetBy(dx: -20.0, dy: -20.0),
            options: options) { (result) in

            switch result {

            case .success(let queriedFeatures):

                // Get the identifiers of all the queried features
                let queriedFeatureIds: [String] = queriedFeatures.compactMap {
                    guard case let .string(featureId) = $0.feature.identifier else {
                        return nil
                    }
                    return featureId
                }

                for manager in managers {
                    manager.handleQueriedFeatureIds(queriedFeatureIds)
                }
            case .failure(let error):
                Log.warning(forMessage: "Failed to query map for annotations due to error: \(error)",
                            category: "Annotations")
            }
        }
    }

-20, and 20, can u make this a configurable figure?

**Comment by JenishKananiLime** [comment]
func annotationManager(_ manager: AnnotationManager, didDetectTappedAnnotations annotations: [Annotation], point: CGPoint) {
    var minDistance = Float(Int.max - 1)
    var minDistanceAnnotation: PointAnnotation?

    for annotation in annotations {
      if let annotation = annotation as? PointAnnotation, let manager = manager as? PointAnnotationManager {
        if let annotationPoint = mapbox?.mapboxMap.point(for: annotation.point.coordinates) {
          let distance = hypotf(Float((annotationPoint.x - point.x)), Float((annotationPoint.y - point.y)))
          if Float(minDistance) > distance {
            minDistance = distance
            minDistanceAnnotation = annotation
          }
        }
      }


    }

    if let minDistanceAnnotation = minDistanceAnnotation,  let manager = manager as? PointAnnotationManager {
      var toChangeAnnotation = minDistanceAnnotation
      toChangeAnnotation.image = .init(image: AppTheme.current.images.LimeTCarImage, name: minDistanceAnnotation.id)
      manager.annotations.removeAll { ann in
        ann.id == minDistanceAnnotation.id
      }

      manager.annotations.append(toChangeAnnotation)
    }
//    mapbox?.handleTap()
  }


benefitial also to provide the touch point? so we can do stuff like this

**Comment by ZiZasaurus** [comment]
@JenishKananiLime thank you for reaching out. If possible, can you provide the following: 
- a list of annotations
- a camera
- a location to tap that doesn't give the desired results

If you are able to provide us with a minimal sample project that contains the information above that would be extremely helpful.

**Comment by mic12130** [comment]
Same issue here. I made a minimal sample to reproduce the issue, hope it helps. @ZiZasaurus 

```swift
import UIKit
import MapboxMaps

class TestViewController: UIViewController {
    var mapView: MapView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let resourceOptions = ResourceOptions(accessToken: Bundle.main.object(forInfoDictionaryKey: "MGLMapboxAccessToken") as! String)
        let cameraOptions = CameraOptions(center: CLLocationCoordinate2D(latitude: 0, longitude: 0))
        let mapInitOptions = MapInitOptions(resourceOptions: resourceOptions, cameraOptions: cameraOptions)
        mapView = MapView(frame: self.view.bounds, mapInitOptions: mapInitOptions)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        self.view.addSubview(mapView)
        
        let makeAnnotation = { (id: String, coord: CLLocationCoordinate2D) -> PointAnnotation in
            var annotation = PointAnnotation(id: id, coordinate: coord)
            annotation.image = .init(image: UIImage(named: "red_pin")!, name: "red_pin") // Resource provided in Examples
            return annotation
        }
        
        let annotationManager = mapView.annotations.makePointAnnotationManager()
        annotationManager.annotations = [
            makeAnnotation("left", .init(latitude: 0, longitude: 0)),
            makeAnnotation("right", .init(latitude: 0, longitude: 20)),
            makeAnnotation("top", .init(latitude: 25, longitude: 10))]
        annotationManager.delegate = self
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        let points = mapView.mapboxMap.points(for: [
            .init(latitude: 0, longitude: 0),
            .init(latitude: 0, longitude: 20),
            .init(latitude: 25, longitude: 10)])
        
        // Represents the annotation's size in pixels
        let coverView = UIView(frame: CGRect(x: points[0].x - 11, y: points[0].y - 18, width: 22, height: 36))
        coverView.backgroundColor = UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 0.5)
        self.view.addSubview(coverView)
        
        // Add views to visualize tap detection boxes
        points.forEach { point in
            // Width = 22 (annotation's width) + 20 (threshold of tap detection range) * 2 = 62
            // Height = 36 (annotation's height) + 20 (threshold of tap detection range) * 2 = 76
            let rectView = UIView(frame: CGRect(x: point.x - 31, y: point.y - 38, width: 62, height: 76))
            rectView.backgroundColor = UIColor(red: 0.0, green: 0.0, blue: 1.0, alpha: 0.5)
            rectView.isUserInteractionEnabled = false
            self.view.addSubview(rectView)
        }
    }
}

extension TestViewController: AnnotationInteractionDelegate {
    func annotationManager(_ manager: AnnotationManager, didDetectTappedAnnotations annotations: [Annotation]) {
        print("Tapped: \(annotations.map { $0.id }.joined(separator: ", "))")
    }
}
```

Result:
<img width="190" alt="截屏2022-05-10 12 37 12" src="https://user-images.githubusercontent.com/26357139/167543580-973d037e-7420-4769-8ef2-75f5710304d0.png">

In this sample, I created 3 annotations to test the tap behavior. Then based on the threshold of tap detection range (20px) found above, 3 blue rectangles that extend the annotation size by 20px were also added, representing the current tap detection range.

To test the tap detection, click somewhere on the map and the annotations being tapped will be printed out. For example, click the overlapped area of left and top rectangle (marked with a red dot):

<img width="190" alt="clicked" src="https://user-images.githubusercontent.com/26357139/167546685-1f29d9a5-93b4-4931-b5d8-3c41840b7dd3.png">

The output will be `Tapped: left, top`

Note: this sample only shows a case with a fixed camera position. But at least in my project, this issue persists despite the camera's center and zoom level.

IMO the current 20px is not a reasonable value as a threshold of tap detection - it will lead to countless unintended taps. I agree with @JenishKananiLime that making it configurable would be preferred.

**Comment by JenishKananiLime** [comment]
I modified the pod library and set the value to 0,0 and its very accurently I don't understand reason behind the -20, 20

**Comment by mic12130** [comment]
Update: the cause seems to be a tweak from #1283 where intended to conform to the HIG (then I figured out why everything worked just fine before the 10.5 release). I understand a larger tap target is somehow recommended by the HIG, but it's not ideal to come at the cost of unintended taps. Just imagine about Apple Maps: there were two annotations on both sides of a street, it would never happen that one was tapped but another responded.

Some possible solutions: (?)
- As suggested above, would be great if make the threshold configurable
- Revert the changes made by the PR
- Keep the current threshold, but sort the tapped annotation array by their distance from the tap point
