### ISSUE TITLE
How to get a reliable rect of the whole mapview?

### ISSUE THREAD

**Issue by kushsolitary** [mapbox/mapbox-maps-ios#1321]
Hi,

So I've been struggling with this for some time. I wish to know the CGRect of the whole map. The issue I am facing right now is that due to the wrapping of the map, the `x` of the top-left coordinate keeps switching between a negative and a positive value as I move around the map. This results in the width of the map also changing.

I tried restricting the camera bounds to prevent wrapping and it does that job perfectly, but it still doesn't help with `x` switching between positive/negative as I move around the map.

```swift
let extremeBounds = CoordinateBounds(
    southwest: CLLocationCoordinate2D(latitude: -62.59334083012023, longitude: -141.328125),
    northeast: CLLocationCoordinate2D(latitude: 82.85338229176081, longitude: 167.34375)
)

try? view.mapboxMap.setCameraBounds(with: CameraBoundsOptions(bounds: extremeBounds))
```

This is how I am calculating the rect on `cameraChange`:
```swift
mapView.mapboxMap.rect(for: self.extremeBounds)
``` 

Is there an official way of disabling the wrapping of the map so that the northwest coordinate always appears at the top left side of the map? Or maybe my approach is incorrect and there's an easier way of finding out the rect of the map?

**Comment by endanke** [comment]
Hi @kushsolitary!

Could you provide a bit more context and describe how would you like to use the CGRect?
One other problematic case would be when the map gets rotated or pitched, so a more appropriate representation would be an irregular rectangle with the 4 corner points of the map. At the moment querying points outside of the map view's boundaries is not fully supported, but you can try this workaround: https://github.com/mapbox/mapbox-maps-ios/issues/788#issuecomment-1134379707

However, if you can share more details about your use-case, we can check if there's an easier way to achieve the same results.
