### ISSUE TITLE
PointAnnotation IconRotate should Rotate relative to north, not the device

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-maps-ios#1323]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution -

The Idea is simple: A PointAnnotation customized with the Attribute "IconRotate" currently rotates the Icon as expected, but is only in the right direction when the Map points North. As soon as you start rotating the Map, the PointAnnotation sticks to its original IconRotate direction, relative to the device, not north on the map. There should either be a second, similar Variable or the current one should be changed to always rotate relative to north. Meaning: if I have a PointAnnotation with the IconRotate Variable set to 0, it's heading directly north if the Map is pointed north. Now imagine rotating the map to be oriented south (180*), then the PointAnnotation should be rotating with it, to still point South, meaning it should rotate exactly as much as the map gets rotated. 
>

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? -
There are many use cases where this would be valuable, but the easiest one is to correctly display Annotations that are not round but rather show some kind of direction. For example, CLLocation saves the socalled "course", a device is currently traveling in. Imagine wanting to display that on another map, with an arrow. The Arrow should be oriented to the course of the user on the map at all times.
>

**Comment by ZiZasaurus** [comment]
@JanTG1 thank you for reaching out, This is the expected behaviour. If you wish to customize the icon to always pointing to some direction relative to the device, you can implement it by using the camera position updates and listening for the bearing.
