### ISSUE TITLE
Mapbox 10 CPU and RAM utilisation

### ISSUE THREAD

**Issue by SergeyPetrachkov** [mapbox/mapbox-maps-ios#1337]
## Environment

- Xcode version: 13.3.1 (13E500a)
- iOS version: 15.4.1
- Devices affected: iPhone 8, iPhone 12, iPhone 13 Pro
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce

After migrating from Mapbox 6.3 to 10.5 we’ve noticed that the RAM and CPU utilisation have increased significantly and this leads to decrease of performance in our app. Even though the API is completely different now, we’ve managed to convert our codes to work with the current API.

A little bit of background:

On our map, we show users trips that consist of Steps and Routes between steps. A step can either be a small dot or a circle with an image inside. A route is a line between two steps.

So, now for the same trip with the same amount of steps and routes we’re seeing up to 4 times higher consumption of RAM which in turn leads to memory warnings and could lead to the iOS killing the app. We also see 1.5x higher CPU utilization. 

![image](https://user-images.githubusercontent.com/7995896/168989736-7cb37108-d1eb-4f99-8c06-e8e0740fff83.png)

Old version:

![image](https://user-images.githubusercontent.com/7995896/168989841-57d1228e-28b6-4fb1-8754-4ff5faa24607.png)
![image](https://user-images.githubusercontent.com/7995896/168990026-da40d0a8-f3b8-4b26-9085-b771170dc4a9.png)

On the new version the same screen in the same place after the same actions has this:

![image](https://user-images.githubusercontent.com/7995896/168990352-119fd6e7-00ba-4012-be49-e113c736fe72.png)

![image](https://user-images.githubusercontent.com/7995896/168990404-105420ca-27a1-4852-95e6-adc84b546118.png)

![image](https://user-images.githubusercontent.com/7995896/168990718-709b8d21-87ac-44d1-bd50-faf9ec58bedb.png)

The new version also renders the map slower than the old one.

## Expected behavior

The new version to consume less resources and renders the map faster.

## Notes / preliminary analysis

Objects to show on map:

Zelda Steps: 9905 (Clustering enabled)

Steps: 68 (this means that there are 68 image thumbnails to show)

9973 lines to draw (FeatureCollection)

68 points to draw (FeatureCollection)

## Additional links and references

A few videos that demonstrate some of the described above:

[Link](https://drive.google.com/drive/folders/1meKux8vJUyQtcM2FY8dbJR1KFTRPBhL8?usp=sharing)

**Comment by alexshalamov** [comment]
@SergeyPetrachkov could you tell what v10 features do you use? Do you use 3D terrain? Do you have measurements for an application that uses v6 SDK?

**Comment by SergeyPetrachkov** [comment]
@alexshalamov hey, I don't use any brand new v10 features. At this point, I only tried to update the Mapbox version and restore the functionality from v6. So it's the basic usage: load the map style from a JSON file, load some data from our server (geo-locations), and create GeoJSON sources (we use the latest Turf library) for that data. We also have some camera manipulations to navigate between points, for that we use something like:
```swift
let duration = // our own logic how to calculate the duration
camera.fly(to: newCamera, duration: duration)
```

It is impossible to calculate the precise RAM  for the both new and old versions, because the app has quite some other background processes running and also once we hit the memory warning we do the cleanup, so I'd say that with the new versions of Mapbox the memory warning hits 3-4 times faster. 
For a simple small trip, when we don't have to load dozens of points and draw hundreds of lines it's usually like 60MB on the old version and ~200MB on the new one. But again, it's kinda tricky to calculate this thing accurately, because there are other processes within the app. Thanks for understanding. 

To add/update a feature collection we use something like this:
```Swift
/// Check if the map has the source with the provided ID. Update if it does, otherwise, create a new source and assign FeatureCollection to its data.
    /// - Parameters:
    ///   - featureCollection: the FeatureCollection to add
    ///   - identifier: ID of the source added to the map
    ///   - clusteringOptions: the options for clustering algorithm. Can be nil, that would mean that there will be not clustering.
    ///   - map: PSBaseMapView that will display the GeoJSONSource
    func ensureFeatureCollectionAdded(featureCollection: FeatureCollection, sourceIdentifier: String, clusteringOptions: ClusteringOptions? = nil, to map: PSBaseMapView) {
        if let _ = try? map.mapboxMap.style.source(withId: sourceIdentifier) {
            do {
                print("ℹ️ Try to update \(sourceIdentifier) with feature collection")
                try map.mapboxMap.style.updateGeoJSONSource(withId: sourceIdentifier, geoJSON: featureCollection.geoJSONObject)
                print("✅ Updated \(sourceIdentifier) with feature collection")
            } catch {
                print("❌ Could not update \(sourceIdentifier); \(error)")
            }
        } else {
            var source = GeoJSONSource()
            source.promoteId = .string(sourceIdentifier)
            source.data = GeoJSONSourceData.featureCollection(featureCollection)
            if let clusteringOptions = clusteringOptions {
                source.cluster = true
                source.clusterRadius = clusteringOptions.clusterRadius
                source.clusterProperties = clusteringOptions.clusterProperties
            }
            do {
                print("ℹ️ Try to add \(sourceIdentifier) source")
                try map.mapboxMap.style.addSource(source, id: sourceIdentifier)
                print("✅ Added \(sourceIdentifier) source")
            } catch {
                print("❌ Could not add \(sourceIdentifier); \(error)")
            }
        }
    }
```

on the old version we would just use:
```swift
let data = try? JSONEncoder().encode(feature)
let shape = data.flatMap { try? MGLShape(data: $0, encoding: String.Encoding.utf8.rawValue) }
let shapeSource = MGLShapeSource(identifier: identifier.rawValue, features: .empty)
style?.addSource(source)
shapeSource.shape = shape
```

**Comment by okcoker** [comment]
I'm noticing a similar slow down trying to upgrade from v6 to v10.

I had a similar transition as the example above (minus the clustering) and for drawing a `FeatureCollection` with muti-polygon features within a game loop, it seems like calling `updateGeoJSONSource` is what causes the slowdown for me. I'll probably have to come up with a better caching strategy to avoid this call unless necessary but it didn't seem like a problem in v6 when calling `shapeSource.shape = shape` over and over.

**Comment by okcoker** [comment]
Another thing that might be helpful to know is the polygons that I'm rendering are around the world and I'm not yet doing any optimizations as far as rendering only polygons visible within the viewport. Not sure if something has changed from v6 to v10 in that regard

**Comment by jumbopilot** [comment]
Hi guys, I do experience pretty same resource consumption issue with V10.6.0 (also since I've migrated from V6) on iOS 15/16.

In my case, I do programmatically display and dismiss one and the same Mapview a second time in a separate view that overlays the basic one.

Mapbox seems to be making **excessive memory allocations** every time a map view is presented, but **not releasing them when the views are dismissed.** We ran a few different memory allocation traces and **was consistently able to have the app allocate well over 1GB of memory** before it was killed. This issue also occurs on iOS 15, so it is not a new Apple issue with iOS 16+

The display and dismiss of the 2nd MapView happens e.g. every 10 seconds.

The crash file shows like
———
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: FRONTBOARD 2343432205 
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<domain.subdomain.appstring>:9900 exhausted real (wall clock) time allowance of 10.00 seconds
———

Consequently, this section of the crash report indicates the main thread of the application did not respond within 10 seconds. The excessive memory use is causing the app to appear sluggish, and eventually the map-view logic on the main thread becomes so delayed that it does not respond to the watchdog in time, and is sent a SIGKILL signal to be terminated.

Here are a couple of links that hopefully help to identify and reduce the sources of the excessive memory growth:
https://developer.apple.com/documentation/xcode/gathering-information-about-memory-use
https://developer.apple.com/documentation/xcode/making-changes-to-reduce-memory-use

Hope this helps. If not, please get in touch for more details or traces.

**Comment by OdNairy** [comment]
@SergeyPetrachkov Do you still experience > 1GB RAM with MapView?

**Comment by SergeyPetrachkov** [comment]
@OdNairy I no longer work at Polarsteps, can't really say. You can probably try @JaviLorbada

**Comment by JaviLorbada** [comment]
Hey @OdNairy, we are no experience that much of RAM usage at the moment in a different part of the app, if that was the case we would open a new issue. Thanks.
