### ISSUE TITLE
Vector layer not working

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1340]
## Environment
![Screen Shot 2022-05-20 at 1 19 51 AM](https://user-images.githubusercontent.com/79174176/169455910-81dc2632-9025-4398-a9bb-9ef9873c2587.png)

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
Nothing shows up for this on map its renders as normal

## Expected behavior
Layer should appear

**Comment by JenishKananiLime** [comment]
@ZiZasaurus I dont see anything on the map there isn't any errors just nothing rendered on map

**Comment by ZiZasaurus** [comment]
@JenishKananiLime you can use our [ExternalVectorSource example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/ExternalVectorSourceExample.swift) in our [iOS Examples app](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/README.md).

**Comment by ZiZasaurus** [comment]
@JenishKananiLime closing this issue, but please feel free to reopen if you encounter any additional issues.
