### ISSUE TITLE
Custom layer download timing out

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1341]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
When downloading vector layer the networks requests are getting timed out

**Comment by ZiZasaurus** [comment]
Do you have an example URL that you are using that produces this timeout error?

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you encounter additional issues.
