### ISSUE TITLE
Fps issue

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1345]
## Environment

- Xcode version: 
- iOS version: 15.4
- Devices affected: all
- Maps SDK Version:

## Observed behavior and steps to reproduce
I have a login screen, once the user logs in and we load the map the map is slow, fps of 25-30, once we kill the app and from there on its always 60fps, any suggestions what could be causing this slow fps when signing in? Any help would be grateful thank you.

**Comment by rgmyyw** [comment]
+1 

Version: 'MapboxMaps', '10.5.0' 
Device: iPhone8P
OS: iOS13.3

**Comment by ZiZasaurus** [comment]
@JenishKananiLime, @rgmyyw Can you please let me know if you're still experiencing this on the newest version of our SDK, v10.7?

**Comment by ZiZasaurus** [comment]
Closing this issue. Please feel free to reopen if you have additional questions.
