### ISSUE TITLE
Pinch to Zoom Gestures often Not Recognized

### ISSUE THREAD

**Issue by christopheclc** [mapbox/mapbox-maps-ios#1350]
## Environment

- Xcode version: 13.3.1
- iOS version: 15.4
- Devices affected: All
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce

I've noticed maybe about 10-20% of the time when I try to pinch to zoom with two thumbs, the map does not zoom or pan, as if the gesture wasn't recognized at all.

I'm new to Mapbox so I'm not sure if this is a regression or not.

## Expected behavior

The map should always zoom when pinching with two fingers.

**Comment by ZiZasaurus** [comment]
@christopheclc I'm not experiencing this behavior. Do you have an other custom gestures that may be interfering?
