### ISSUE TITLE
Map lag when panning around

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1351]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
after a quick swipe to move map around the map on the very few decelerations stutters, even though nothing is rendering.

**Comment by JenishKananiLime** [comment]
https://user-images.githubusercontent.com/79174176/170080849-af7e7278-6022-4619-8938-254c27ed5c3b.MP4

for example, as i pan around the very last moments of when map is above to stop moving u can see micro lags

**Comment by ZiZasaurus** [comment]
Thank you for reporting. At the moment, I am unable to reproduce this behavior, however if you can provide answers to the following questions I can investigate further. 

- What version of the SDK are you running? 
- What version of iOS?
- Are you seeing this across multiple devices? 
- Are you seeing the same behavior with one of the default Mapbox styles (say, Streets or Light)?
- Can you provide us with the style url for this particular style so we can investigate further?

**Comment by JenishKananiLime** [comment]
mapbox://styles/jkanani/cl3f03g8800bh15s2xhhj6kbi, latest sdk verision, ios 15, 12 pro max, yes i see same issue on default mapbox box style as well

**Comment by JenishKananiLime** [comment]
@ZiZasaurus any updates?

**Comment by EdGonzalez-** [comment]
I am experiencing the same issue. It seems limited to version 10.5 of the SDK and I am using iOS 15.5. I've experienced the issue on multiple devices and also in the simulator, as have other developers on our team. 

It does not occur all of the time.  When the app first opens, the view is white for a few seconds before the map even renders. Force quitting the app and reopening sometimes resolves 99% of the lag, but it still remains a bit jittery.  Switching back to version 10.2 of the SDK resolves the issue completely.

mapbox://styles/aeroapps/ckrfgaln44exp17p3n9zspp8x

**Comment by EdGonzalez-** [comment]
I can duplicate it fairly consistently when updating a build of our app using SDK 10.3 to SDK 10.5.  Here is a video.

https://user-images.githubusercontent.com/10816717/171302599-bf62fd91-cb6e-4b81-bbcf-6384d0a31331.mov

**Comment by JenishKananiLime** [comment]
tested mapbox v10.4 more smoohter then 10.5

**Comment by EdGonzalez-** [comment]
Not an issue in 10.3 or 10.5, started in 10.5

**Comment by hingarn** [comment]
We are also seeing this issue with 10.5 (the lag makes the map unusable), not an issue on 10.4. Reproducible on iOS 15 devices including simulators (iPhone 13 Pro, iPhone 13, iPhone 11, haven't tried others), Xcode 13.4.1

**Comment by OdNairy** [comment]
We released the [v10.5.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.5.1) that should address that issue.

**Comment by hingarn** [comment]
@OdNairy confirmed that it's no longer an issue for us, thank you!
