### ISSUE TITLE
View Annotation with custom long press gesture disables mapView's pan gesture

### ISSUE THREAD

**Issue by val-yoonet** [mapbox/mapbox-maps-ios#1352]
## Environment

- Xcode version: 13.2.1
- iOS version: 15.4.1
- Devices affected: 
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce
I added a custom annotation using ViewAnnotation with custom long-press and pan gestures to enable dragging annotations. So far, everything is working as expected, one thing I only experienced, is that whenever I do long-press gesture, the mapView's pan gesture state turns into failed.

(didDragAnnotation:)[L:174] <UIPanGestureRecognizer: 0x10700a460; 
state = Failed; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PanGestureHandler 0x281bd9d90>)>; must-fail-for = {
        <UIPinchGestureRecognizer: 0x10700f710; state = Failed; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PinchGestureHandler 0x2802b1e00>)>>,
        <UIPanGestureRecognizer: 0x10700f8a0; state = Failed; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PitchGestureHandler 0x283973bc0>)>>
    }>

## Expected behavior
The expected state of mapViews' pan gesture should be possible when dragging annotations.

(didDragAnnotation:)[L:64] <UIPanGestureRecognizer: 0x10700a460; 
state = Possible; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PanGestureHandler 0x281bd9d90>)>; must-fail-for = {
        <UIPinchGestureRecognizer: 0x10700f710; state = Possible; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PinchGestureHandler 0x2802b1e00>)>>,
        <UIPanGestureRecognizer: 0x10700f8a0; state = Possible; view = <MapboxMaps.MapView 0x10719ceb0>; target= <(action=handleGesture:, target=<MapboxMaps.PitchGestureHandler 0x283973bc0>)>>
    }>

**Comment by ZiZasaurus** [comment]
Thank you for reporting. Is your expectation to be able to pan the map and drag your annotation simultaneously or are you saying that the map pan functionality doesn't resume after dragging has ended?

**Comment by val-yoonet** [comment]
Hi @ZiZasaurus Thank you for your comment. It means a lot.

As of now, I was able to simultaneously enable dragging view annotation and made the mapView's pan gesture possible. 

One thing, I have this scenario wherein if I drag an annotation to the edges of the screen, the map should also update. For example, when I drag a view annotation to the rightmost part of the screen, the map should also go to the right.

When I'm using the camera's ease(to: ...)/fly(to:..) function, the map doesn't update. When I'm using the mapView.mapboxMap.setCamera(to: CameraOptions(center: sampleCoordinate)) the camera and/or mapview is updating but it updates too fast which is not my intended behavior. 

This is possible in v6 when I'm using mapView.setCenter function wherein my annotation view is a subclass of MGLAnnotation View.
