### ISSUE TITLE
PointAnnotations under all layers, delegate method don't work

### ISSUE THREAD

**Issue by R1ick** [mapbox/mapbox-maps-ios#1353]
## Environment

- Xcode version: 13.2
- iOS version: 15.5
- Devices affected: iPhone 11, Simulators
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce
Map loaded
Add FillLayer
Add PointAnnotations
Add CircleLayer
Add HeatmapLayer

<img width="95" alt="image" src="https://user-images.githubusercontent.com/96225594/170033999-40fadda4-86f8-417d-a456-fb0616fe8313.png">

## Expected behavior

method didDetectTappedAnnotations works
## Notes / preliminary analysis

method didDetectTappedAnnotations works

**Comment by R1ick** [comment]
> ## Environment
> * Xcode version: 13.2
> * iOS version: 15.5
> * Devices affected: iPhone 11, Simulators
> * Maps SDK Version: 10.5.0
> 
> ## Observed behavior and steps to reproduce
> Map loaded Add FillLayer Add PointAnnotations Add CircleLayer Add HeatmapLayer
> 
> <img alt="image" width="95" src="https://user-images.githubusercontent.com/96225594/170033999-40fadda4-86f8-417d-a456-fb0616fe8313.png">
> 
> ## Expected behavior
> method didDetectTappedAnnotations works
> 
> ## Notes / preliminary analysis
> when I try to click on the annotation, it doesn't work, since it is under all layers, regardless of the order in which they are added to the map.
> 
> ## Additional links and references

**Comment by JenishKananiLime** [comment]
From what I have done is the initialization order of the annotation manager detected which layer is on top so I just initialized the layer I want on top at very last, + u can do something like this 

  zonesAnnotationManager = mapBox.annotations.makePolygonAnnotationManager(id: "5")
    zoneBoundryAnnotationManager = mapBox.annotations.makePolylineAnnotationManager(id: "4", layerPosition: .above(zonesAnnotationManager!.layerId))
    zoneMarkerAnnotationManager = mapBox.annotations.makePointAnnotationManager(id: "3", layerPosition: .above(zoneBoundryAnnotationManager!.layerId))
    parkingPinAnnotationManager = mapBox.annotations.makePointAnnotationManager(id: "2", layerPosition: .above(zoneMarkerAnnotationManager!.layerId))
    vehiclePinsAnnotationManager = mapBox.annotations.makePointAnnotationManager(id: "1", layerPosition: .above(parkingPinAnnotationManager!.layerId))

**Comment by ZiZasaurus** [comment]
@R1ick I am unable to reproduce this behavior. In the screenshot below, I have added my point annotation below the "road-primary" layer and am still able to detect the tap. Please make sure that you are referencing the subclass `AnnotationInteractionDelegate` and its protocol stubs as well as setting the delegate on your point annotation manager to self as indicated [here](https://github.com/mapbox/mapbox-maps-ios/blob/63fe28a3969877d043b39e600142420d960400c0/Apps/Examples/Examples/All%20Examples/Annotations/CircleAnnotationExample.swift#L19). 

![IMG_190430F02B86-1](https://user-images.githubusercontent.com/44972592/170105174-c530e542-000d-4ee8-8f85-67ff38321aef.jpeg)

**Comment by ZiZasaurus** [comment]
@R1ick I am unable to reproduce. Can you provide a small test project that reproduces this behavior?

**Comment by R1ick** [comment]
@ZiZasaurus yep, I will text u

**Comment by R1ick** [comment]
@ZiZasaurus hi. I realized my mistake working with the delegate method, but the point annotation layer is still under the others (see screenshot). How can I raise it above?
<img width="176" alt="image" src="https://user-images.githubusercontent.com/96225594/170434659-d589e8be-3bfb-448f-9f5b-9de69999802e.png">

**Comment by ZiZasaurus** [comment]
@R1ick for placement of the point annotation, as mentioned by @JenishKananiLime, you would need to add this layer last so that it can be seen above the other layers. 

Please note, if you are adding view annotations (rather than point annotations) those will always be displayed on top.
