### ISSUE TITLE
Seeing crash after upgrading to latest, 10.6.1 beta commit

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1354]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce

<img width="725" alt="Screen Shot 2022-05-24 at 12 04 18 PM" src="https://user-images.githubusercontent.com/79174176/170081590-e67923b8-ac76-47ea-91ae-d7e3b434c08e.png">

**Comment by ZiZasaurus** [comment]
@JenishKananiLime if you're referring to 10.6.0-beta.1, can you please try the most recent 10.6.0-rc.1 and let me know if you're still experiencing crashing? Additionally, where/when are the crashes occurring (on map load, after performing a certain action, etc)?

**Comment by ZiZasaurus** [comment]
Closing this ticket. Please feel free to reopen if you encounter further issues.
