### ISSUE TITLE
Fps issue

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1355]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
After opening app again after staying in backgrounded for a while map doesn't feel smooth. I checked memory consumptions are quite low but map doesn't feel as smooth as initial load.

**Comment by ZiZasaurus** [comment]
@JenishKananiLime thank you for reporting. Can you please provide the following information: 

- What devices are you seeing this on?
- How long have you left the map/app in the background before re-opening?
- What version of the SDK are you using?
- Is this a custom or default style? If custom, what style url are you using to display your map?

**Comment by JenishKananiLime** [comment]
Hi, its a 12 pro max, 30 minutes or more in background, latest sdk verision from git, custom style mapbox://styles/jkanani/cl3f03g8800bh15s2xhhj6kbi

**Comment by EdGonzalez-** [comment]
This is probably the same issue as #1351

**Comment by EdGonzalez-** [comment]
I tested 10.6.0. It's much better, but momentum scrolling is a bit jerky. Sometimes there is no momentum scrolling at all.

**Comment by JenishKananiLime** [comment]
yes I agree with the scrolling still is bit jerky, pre v 10.5 it was smooth

**Comment by ZiZasaurus** [comment]
@JenishKananiLime, @EdGonzalez- are you still experiencing this behavior with 10.7?

**Comment by JenishKananiLime** [comment]
@ZiZasaurus this issue is solved thanks for the help
