### ISSUE TITLE
'getSource` crashes or returns arbitrary, unconfigured `Source`

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#136]
## Environment

- Xcode version: 12.4
- iOS version: 14.4
- Devices affected: all
- Maps SDK Version: beta.13

## Observed behavior and steps to reproduce

Stylesheet contains a source with identifier "aerial". Asking for the source from `style` results in a crash.
```
mapView.on(.styleLoadingFinished) { [weak self] event in
    let result = self.mapView.style.getSource(identifier: "aerial", type: RasterSource.self) // CRASH
    ...
}
```
```
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.mapbox.bindgen Code=-2 "*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: bounds)" UserInfo={NSUnderlyingErrorKey=*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: bounds), NSLocalizedFailureReason=*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: bounds)}: file MapboxMaps/Style.swift, line 271
```
Style.swift Line 271:
`let sourceProps = try! self.styleManager.getStyleSourceProperties(forSourceId: identifier)`

Alternatively, do not do the line above, and after `on(.mapLoadingFinished)` add a `PointAnnotation`. This triggers two events: `.sourceChanged` and `.styleFullyLoaded`.  The identifier of the source that changed is `com.mapbox.AnnotationManager.DefaultSourceLayer`. So do:
```

func handle<T>(result: Result<T, SourceError>) {
    switch result {
    case .success(let source):
        log("source is \(source)")
    case .failure(let error):
        log("getSource failed: \(error)")
    }
}

let identifier: String = "com.mapbox.AnnotationManager.DefaultSourceLayer"
handle(result: style.getSource(identifier: identifier, type: VectorSource.self))
handle(result: style.getSource(identifier: identifier, type: RasterSource.self))
handle(result: style.getSource(identifier: identifier, type: RasterDemSource.self))
handle(result: style.getSource(identifier: identifier, type: GeoJSONSource.self))
handle(result: style.getSource(identifier: identifier, type: ImageSource.self))
handle(result: style.getSource(identifier: identifier, type: ModelSource.self))
```
Output:
```
[style] source is VectorSource(type: MapboxMaps.SourceType.geoJson, url: nil, tiles: nil, bounds: nil, scheme: nil, minzoom: nil, maxzoom: nil, attribution: nil, volatile: nil, prefetchZoomDelta: nil, minimumTileUpdateInterval: nil, maxOverscaleFactorForParentTiles: nil)
[style] source is RasterSource(type: MapboxMaps.SourceType.geoJson, url: nil, tiles: nil, bounds: nil, minzoom: nil, maxzoom: nil, tileSize: nil, scheme: nil, attribution: nil, volatile: nil, prefetchZoomDelta: nil, minimumTileUpdateInterval: nil, maxOverscaleFactorForParentTiles: nil)
[style] source is RasterDemSource(type: MapboxMaps.SourceType.geoJson, url: nil, tiles: nil, bounds: nil, minzoom: nil, maxzoom: nil, tileSize: nil, attribution: nil, encoding: nil, volatile: nil, prefetchZoomDelta: nil, minimumTileUpdateInterval: nil, maxOverscaleFactorForParentTiles: nil)
[style] source is GeoJSONSource(type: MapboxMaps.SourceType.geoJson, data: nil, maxzoom: nil, attribution: nil, buffer: nil, tolerance: nil, cluster: nil, clusterRadius: nil, clusterMaxZoom: nil, clusterProperties: nil, lineMetrics: nil, prefetchZoomDelta: nil)
[style] source is ImageSource(type: MapboxMaps.SourceType.geoJson, url: nil, coordinates: nil, prefetchZoomDelta: nil)
[style] source is ModelSource(type: MapboxMaps.SourceType.geoJson, models: nil)
```

## Expected behavior

No crash in the first case. A `GeoJsonSource` in the latter case.

## Notes / preliminary analysis

Discovered this while trying to access the source for `PointAnnotations` so as to configure the way the source clusters.

The documentation states: _"new approach to annotations is that they are all powered internally by the use of​ ​style layers​."_. I do not know how to access these stylelayers, but I noticed that after the `.onSourceChange` above, `mapView.style.styleManager.getStyleSources()` returns an array in which the last element has the "com.mapbox.AnnotationManager.DefaultSourceLayer" identifier, and `type` is `geojson`, so I tried to update the `cluster` property of this source using `updateSourceProperty(id:property:value:)`, but couldn't figure out what the value of `value` argument should be. So then I thought to get the source, and then discovered that I got one with all internal properties set to `nil`, so I tried a different type of `Source`, and discovered that `getSource` never fails when asked for one with that identifier, it returns any `Source` type you ask for, just with `nil` properties. So then I thought to get a different source, one that I knew was added by the stylesheet, but got the crash.

**Comment by tyofemi** [comment]
fixed in RC1
