### ISSUE TITLE
Xcode 13.4 - Swift Version Conflict: this SDK is not supported by the compiler. Please select a toolchain which matches the SDK.

### ISSUE THREAD

**Issue by gemmakbarlow** [mapbox/mapbox-maps-ios#1363]
## Environment

- Xcode version: Xcode 13.4
- iOS version: iOS 15.5 (iOS 14.0 minimum)
- Devices affected: N / A
- Maps SDK Version: 10.5.0

## Observed behavior and steps to reproduce

We are using the Mapbox Maps `.zip` file available for download in our codebase, and running into the following error trying to compile using Xcode 13.4 / Swift 5.6 compiler - 

![image](https://user-images.githubusercontent.com/337963/170880674-ee2e1713-c3bb-4541-a19c-3f3ef5558316.png)

## Expected behavior

- No Mapbox dependency change is required to upgrade from Xcode 13.2.1 (our current Xcode version) to Xcode 13.4, using their respective default compiler versions.

## Notes / preliminary analysis

Two options I can see to correct this issue - 

- Publish a version of the framework (.zip) that has been built with the Swift 5.6 compiler. [RealmSwift](https://github.com/realm/realm-swift) is an example of an SDK that takes this approach. 
- Adjust the settings to publish a version that ensures ABI compatibility - https://stackoverflow.com/a/70562356/189711

Would strongly recommend the second option, if possible. 

To keep us running for the moment we've adjusted our setup to use SPM, but would like to return to the download strategy in future.

## Additional links and references
- https://developer.apple.com/videos/play/wwdc2019/416/)
- https://www.swift.org/blog/library-evolution/

**Comment by ZiZasaurus** [comment]
@gemmakbarlow, I'm not experiencing that issue on 13.4.1 with swift compiler 5.6.1 and the direct download v10.5.0 of the Maps SDK. Could you provide some additional information about the steps that you took so I could attempt to reproduce this behavior? Additionally, have you [reset Xcode, cleaned, clear module cache, derived Data and Xcode Caches](https://gist.github.com/maciekish/66b6deaa7bc979d0a16c50784e16d697)?

**Comment by gemmakbarlow** [comment]
Thanks for looking into this @ZiZasaurus - you're right, much to my surprise, I couldn't reproduce this on a sample project I tried to whip up just now with 10.5.0 and 13.4.1. 

I think it's fine to assume that we had some kind of caching issue (our dependency management system internally is custom and a little complex) and close this issue out. Appreciate you investigating !

**Comment by ZiZasaurus** [comment]
You are most welcome! :)

**Comment by memolopezmx** [comment]
<img width="1721" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/21284474/6b24dace-7166-477c-a001-e569651c6310">
