### ISSUE TITLE
Camera animation not working when map is touched

### ISSUE THREAD

**Issue by mbappinte** [mapbox/mapbox-maps-ios#1377]
**What I want :**

I would like to perform a long press on the map and as soon as the long press is detected, move the center of the camera to the location of the long press.

**Problem :**

` self.mapView.camera.ease` is not called as long as the finger is on the map.
It is only called when long press is ended.

How to do ?

**Comment by val-yoonet** [comment]
I have the same intended behavior. Waiting for the mapbox team update on this issue.

**Comment by ZiZasaurus** [comment]
Thank you for your patience while I investigated. You can use our experimental annotation for the Maps SDK (`@_spi(Experimental) import MapboxMaps`) and set `mapView.viewport.options.transitionsToIdleUponUserInteraction = false` to achieve the behavior you're looking for. Please note that this API is not in a completely stable state and is subject to change.

**Comment by Knapiii** [comment]
This worked
