### ISSUE TITLE
Redundancy MapView.screenCoordinate(:for) vs BaseMapView.point(:for)

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-maps-ios#138]
The result of call evaluates to the same, when default parameter is used with BaseMapView.point.
MapView doesn't have unproject method - BaseMapView has `coordinate(for point: CGPoint, in view: UIView? = nil)`
It seems like MapView.screenCoordinate(:for) is a leftover.

![Screen Shot 2021-02-24 at 14 56 11](https://user-images.githubusercontent.com/549216/109003746-7ee21700-76b0-11eb-8f5f-f9289f3bfb36.png)

**Comment by tyofemi** [comment]
Closed - Stale
