### ISSUE TITLE
Style / Layers cache refresh 

### ISSUE THREAD

**Issue by hamernikT** [mapbox/mapbox-maps-ios#1380]
## Environment
- Maps SDK Version: 10.5.0

## Problem

We are trying to invalidate / refresh map style cache containing layers from Mapbox Studio on demand. As there is a change published to the map style it's not propagated for some time which is a relevant issues for our business case. 

In documentation I have found https://docs.mapbox.com/ios/maps/api/10.5.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC9clearData10completionyys5Error_pSgc_tF  but it doesn't seems to do anything

We have also tries to load style again with https://docs.mapbox.com/ios/maps/api/10.5.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC12loadStyleURI_10completionyAA0eF0V_ys6ResultOyAA0E0Cs5Error_pGcSgtF also without any results

In the lates SDK version I have also found this method but as well without result https://docs.mapbox.com/ios/maps/api/10.5.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC14triggerRepaintyyF

## Question

Is there any way how to force refresh map style and its layers based on the latest published version on demand?

**Comment by ZiZasaurus** [comment]
@hamernikT, you could to use [clearData](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC9clearData3for10completionyAA15ResourceOptionsV_ys5Error_pSgctFZ) to accomplish this.

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @ZiZasaurus, https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC9clearData3for10completionyAA15ResourceOptionsV_ys5Error_pSgctFZ

This is not working for me.
