### ISSUE TITLE
GestureManager does not notify delegate for tap or quickZoom

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#140]
## Environment

- Xcode version: 12.4
- iOS version: 14.4
- Devices affected: any
- Maps SDK Version: beta.13

## Observed behavior and steps to reproduce

- Assign an instance of a `GestureManagerDelegate` adopting type to a `MapView`'s `gestureManager.delegate` property
- note that `GestureManagerDelegate` method `gestureBegan(for:)` is not called for `GestureType` of `tap` or `quickZoom`, but that it is called for `pinch`, `pan`, `rotate` and `pitch`.

## Expected behavior

A tap gesture should invoke `gestureBegan(for:)`

## Notes / preliminary analysis

Tried assigning the `gestureManager.delegate` at different points in a `MapView`'s lifecycle to no avail.

**Comment by johnkassebaum** [comment]
After further consideration on the `GestureManager`, is there possibly not a `UITapGestureRecognizer` for single taps (because a single tap does nothing) and that we add one via `gestureRecognizerShouldBegin(_:)`? Still, single touch double tap and double finger single tap, which do exist, would qualify as taps -- but how are they different from `quickZoom`?

**Comment by jmkiley** [comment]
Noting that I do see `gestureBegan` being called for quick zoom, but not for single tap. The single tap gesture recognizer is managed by the `AnnotationManager`s and doesn't seem to be connected to the `GestureManagerDelegate`.

**Comment by landyrev** [comment]
@jmkiley looks like it is still the issue for a global MapView GestureManagerDelegate

Following delegate not receiving tap gestures in RC4:
```swift
mapView.gestures.delegate = self
```
