### ISSUE TITLE
Can't Add  pod 'MapboxMaps' in my Project

### ISSUE THREAD

**Issue by AnkitGabani** [mapbox/mapbox-maps-ios#1422]
Hello, 
When i try  install pod 'MapboxMaps', i got some Error

![Screenshot 2022-07-04 at 10 00 33 AM](https://user-images.githubusercontent.com/31876788/177081754-e71483b5-b747-4243-9588-6a3834ecb18c.png)
6edac753.png)

![Screenshot 2022-07-04 at 9 54 34 AM](https://user-images.githubusercontent.com/31876788/177081798-868bb423-bb2b-4ccd-a8ce-7ab3eca21968.png)

**Comment by ZiZasaurus** [comment]
This was addressed in the comment of another ticket. Closing.
