### ISSUE TITLE
Can't Add pod 'MapboxMaps' in my Project

### ISSUE THREAD

**Issue by iOSvnerds** [mapbox/mapbox-maps-ios#1425]
## Environment

- Xcode version: 13.4
- iOS version: 15
- Maps SDK Version: pod 'MapboxMaps', '10.6.0'

Hello,
When i try install pod 'MapboxMaps', i got some Error

![177081754-e71483b5-b747-4243-9588-6a3834ecb18c](https://user-images.githubusercontent.com/108710828/177247267-bc94b8f4-a7cc-413d-ba5a-934cd5e672eb.png)

********************************

![177081798-868bb423-bb2b-4ccd-a8ce-7ab3eca21968](https://user-images.githubusercontent.com/108710828/177247281-a8487cff-e6aa-4a0d-a6c5-3c9e4bf1c245.png)

**Comment by ZiZasaurus** [comment]
Closing ticket - duplicate.
