### ISSUE TITLE
cannot add Swift package

### ISSUE THREAD

**Issue by iOSvnerds** [mapbox/mapbox-maps-ios#1426]
## Environment

Xcode version: 10.4.0
iOS version: not relevant
Devices affected: not relevant
Maps SDK Version: 10.5.2, 10.6.0

When trying to add https://github.com/mapbox/mapbox-maps-ios.git as a dependency to iOS project in Xcode:

Version format for tags is not the one SPM is expecting (Mapbox is using v prefix for tags which is [not recognized](https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845/2) by SPM)
When using a commit, the packages are failing to resolve with the following error:

Showing Recent Errors Only
invalidManifestFormat("Swift/ContiguousArrayBuffer.swift:575: Fatal error: Index out of range", diagnosticFile: Optional(<AbsolutePath:"/Users/temporaryadmin/Library/Developer/Xcode/DerivedData/Foodora-clupsydvygiebegriopzuyktanag/SourcePackages/ManifestLoading/mapbox-common-ios.dia">)) in https://github.com/mapbox/mapbox-common-ios.git

**Comment by ir-fuel** [comment]
Xcode is at version 13.4.1.
10.4 is ancient.

**Comment by ZiZasaurus** [comment]
@iOSvnerds are you still experiencing this issue?

**Comment by Degtyarserg** [comment]
I have the same issue. 
Xcode  Version 13.4.1

**Comment by ZiZasaurus** [comment]
Closing this issue. Please feel free to reopen if you have additional questions.
