### ISSUE TITLE
Mapbox doesn't load and crashes the app on only one device

### ISSUE THREAD

**Issue by kushsolitary** [mapbox/mapbox-maps-ios#1433]
## Environment

- Xcode version: 13.4.1
- iOS version: 15.5
- Devices affected: iPhone 11
- Maps SDK Version: 10.4.3

## Observed behavior and steps to reproduce

Hi, we have a Mapbox map that loads at the launch of the app. It works great but for one particular user, most of the time the map doesn't load at all and it crashes the app with the following trace:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/650476/177612362-b5ef66fa-a784-48fe-8b25-a5169c012e2f.png">

**Comment by AnkitGabani** [comment]
Hello @kushsolitary,
i am try pod 'MapboxMaps', but i got Error
Pls help me
![Screenshot 2022-07-07 at 5 56 30 PM](https://user-images.githubusercontent.com/31876788/177772863-fa6b5b38-605e-46c7-b20c-c416a234dffa.png)

**Comment by ZiZasaurus** [comment]
@kushsolitary, is your application currently running on 10.4.3? Our most recent stable version is 10.6.0. Can you update your application to our most recent version and let us know if that crash is still being reported?

@AnkitGabani, as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by kushsolitary** [comment]
@ZiZasaurus we cannot upgrade Mapbox because of this change https://github.com/mapbox/mapbox-maps-ios/pull/1195
We heavily rely on this feature.

**Comment by ZiZasaurus** [comment]
@kushsolitary are you able to provide us with a minimal sample application that reproduces this behavior?

**Comment by kushsolitary** [comment]
@ZiZasaurus, unfortunately, the behavior is not reproducible, and it's happening only to one of our users -- iPhone 11 running iOS 15.5. All I can share right now is the stack trace. I am trying to get my hands on the phone to investigate further but is it possible to identify the issue from the stack trace?

**Comment by AnkitGabani** [comment]
> @kushsolitary, is your application currently running on 10.4.3? Our most recent stable version is 10.6.0. Can you update your application to our most recent version and let us know if that crash is still being reported?
> 
> @AnkitGabani, as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

@kushsolitary Thank you!
