### ISSUE TITLE
CoreLocation - This method can cause UI unresponsiveness

### ISSUE THREAD

**Issue by jhoanarango** [mapbox/mapbox-maps-ios#1437]
## Environment

- Xcode version: Beta 3
- iOS version: 16
- Devices affected:
- Maps SDK Version: 10.6.0

## Observed behavior and steps to reproduce

Behavior normal, but get a warning from the console.

**"/Users/distiller/project/Sources/MapboxMobileEvents/MMEEventsManager.m:356: warning run: This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first."**

## Additional links and references

**See Image Below**

<img width="1428" alt="Screen Shot 2022-07-08 at 3 06 05 PM" src="https://user-images.githubusercontent.com/14069813/178055522-79713dfd-ec90-44eb-978e-0c4f3dba1daa.png">

**Comment by ZiZasaurus** [comment]
@jhoanarango, can you provide additional information/ a code snippet of what is happening in your code when you receive that message?

**Comment by jhoanarango** [comment]
Hello, 

So there is not code snippet that I can't point to from my code, however following this trace it leads me to MapBox's EventsManager.sendTurnstile(). I will post screenshots here, since it seems is the best way to show you. Also, I am on XCode Beta 5 now.

<img width="1696" alt="Screen Shot 2022-08-18 at 11 53 32 AM" src="https://user-images.githubusercontent.com/14069813/185440154-ba833842-0577-4c6a-9d7b-11b21774ffc9.png">

**Comment by srinivaskasala** [comment]
@jhoanarango Where you able to find a fix for it? I'm seeing the exact same thing as you. 
CC: [ZiZasaurus](https://github.com/ZiZasaurus)

**Comment by jhoanarango** [comment]
@srinivaskasala , hey sorry I didn't answer earlier. But not, till this day I have not been able to do anything about this. I think this is more on the MapBox side. They should take a look since I do not have access.

**Comment by azarovalex** [comment]
@jhoanarango @srinivaskasala Here is the PR with the fix: https://github.com/mapbox/mapbox-events-ios/pull/344
It was released as part of [MapsSDK 10.8](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.8.0).
There are some cases when you still can see this issue but I can assure you that aside from the Xcode warning, this problem has no impact on the stability of the SDK. It was blocking the main thread for a small amount of time, but it happens only during the MapView initialization as you can see from the stack trace, so it doesn't affect the map after it has been created.

**Comment by jhoanarango** [comment]
@azarovalex, thank you for the update. Will update to the latest SDK.

**Comment by Surferdude667** [comment]
I am running 10.8.1 with iOS 16 and I get this warning every time the MapView initializes.

**Comment by Adraesh** [comment]
Same issue on my side with 10.8.1:

<img width="1755" alt="Screen Shot 2022-10-17 at 09 23 34" src="https://user-images.githubusercontent.com/3873988/196114098-ba6100fc-1764-4543-ab69-4d94e6101275.png">

**Comment by pradeeplobo86** [comment]
Hi, I observe the same runtime as @Adraesh.

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/99631125/199822839-c8d5a280-4193-45f9-929e-dfc57b222988.png">

**Comment by evil159** [comment]
This warning is addressed by in [v10.9.0](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.9.0).

**Comment by fatihmerickoc** [comment]
I AM GETTING THE SAME ERROR, WHY DID YOU CLOSE THE ISSUE???
