### ISSUE TITLE
Terrain with small pitch results in black screen

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-maps-ios#1438]
## Environment

- Xcode version:  13.4.1
- iOS version: 15.5
- Devices affected: iPod touch 7th Gen, Simulator
- Maps SDK Version:10.6.0

## Observed behavior and steps to reproduce

Adding terrain renders black screen until a certain pitch is reached.

- Pitch less than 60 degrees: completely black
<img width="325" alt="image" src="https://user-images.githubusercontent.com/52435/178108548-1b8b3081-6bf2-4690-a362-d7877d40d5e8.png">
- Pitch until about 70 degrees: partially black
<img width="320" alt="image" src="https://user-images.githubusercontent.com/52435/178108577-d4a96d59-eaaf-447b-8c9b-3fa5c2922581.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/52435/178108597-ac32642a-d4a8-41a9-840d-c133fba10de0.png">
- Then normal sky appears
<img width="323" alt="image" src="https://user-images.githubusercontent.com/52435/178108608-196ddce6-464f-4696-badc-eb6013d38fc6.png">

```swift
class ViewController: UIViewController {
  
  internal var mapView: MapView!

  override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view.
    
    let myResourceOptions = ResourceOptions(accessToken:accessTokenSch)
    let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions, styleURI: StyleURI.streets)
    mapView = MapView(frame: view.bounds, mapInitOptions: myMapInitOptions)
    mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
    
    mapView.mapboxMap.onNext(.styleLoaded) { _ in
      var source = RasterDemSource()
      let sourceId = "raster-dem-source"
      source.tileSize = 512
      source.url = "mapbox://mapbox.mapbox-terrain-dem-v1"
      source.minzoom = 0.0
      source.maxzoom = 29.0
      try! self.mapView.mapboxMap.style.addSource(source, id: sourceId)
      var terrain = Terrain(sourceId: sourceId)
      terrain.exaggeration = Value.constant(20.0)
      try! self.mapView.mapboxMap.style.setTerrain(terrain)
      
      
      var skyLayer = SkyLayer(id: "sky-layer")
      skyLayer.skyType = .constant(.atmosphere)
      skyLayer.skyAtmosphereSun = .constant([0.0, 0.0])
      skyLayer.skyAtmosphereSunIntensity = .constant(15.0)
      
      try! self.mapView.mapboxMap.style.addLayer(skyLayer)
      
      self.mapView.camera.fly(to: CameraOptions(center:
                                                  CLLocationCoordinate2D(latitude: 33.448376, longitude: -112.074036),
                                                zoom: 10.0
                                               ))
      
    }
    
    DispatchQueue.main.asyncAfter(deadline: .now() + 10.0) {
      print("setting pitch")
      self.mapView.camera.fly(to: CameraOptions(pitch: 69.8),duration: 10.0)
    }
    
    self.view.addSubview(mapView)
  }


}
```

## Expected behavior

Render map, no black screen.

**Comment by ZiZasaurus** [comment]
@mfazekas thank you for reporting. Are you still experiencing this issue? When I try to reproduce in our latest version I am unable to.


https://user-images.githubusercontent.com/44972592/185449729-87a34a8f-c20a-4173-9999-bc82915d28cb.MP4

**Comment by mfazekas** [comment]
@ZiZasaurus I can't seem to repro it either. I've tried with 1.7.0 this time.
