### ISSUE TITLE
Return clustering

### ISSUE THREAD

**Issue by itissvyatoslavTT** [mapbox/mapbox-maps-ios#1441]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->

Good afternoon!
I need to show all the marks on the map at once, regardless of the zoom. Couldn't find how to do it in version 10. GeoJSONSource.cluster = nil and false don't help to solve the problem. I came across on StackOverflow that clustering is now automatic. Thank you in advance!

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->
I need flexible configuration of clustering on the map

**Comment by ZiZasaurus** [comment]
Hi there, have you seen our clustering examples below: 
- [Symbol clustering example ](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Annotations/SymbolClusteringExample.swift)
- [Point clustering example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/PointClusteringExample.swift)

**Comment by itissvyatoslavTT** [comment]
Hello
You have submitted code examples where clustering is used (clustering = true). But if in the same example we fix it to clustering = false or clustering = nil, then clustering still remains. I have a task not to use clustering, can you tell me how to do it? Thank you!

**Comment by ZiZasaurus** [comment]
@itissvyatoslavTT, this is not my experience. When I set `cluster` to false for the [Symbol clustering example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Annotations/SymbolClusteringExample.swift), I receiving the following:

![Simulator Screen Shot - iPhone 12 - 2022-08-18 at 12 55 11](https://user-images.githubusercontent.com/44972592/185451976-07a1ef75-c358-4729-8f46-82e53f918ff4.png)

compared to when `clustering` is set to true: 

![Simulator Screen Shot - iPhone 12 - 2022-08-18 at 12 54 04](https://user-images.githubusercontent.com/44972592/185451990-32a06e50-d6ec-407c-838d-2e563470c998.png)

Clustering also performs as expected with point annotations.
