### ISSUE TITLE
Being able to move annotations/layers front/back

### ISSUE THREAD

**Issue by ir-fuel** [mapbox/mapbox-maps-ios#1444]
## New Feature

The possibility to move annotation manager / layers around

## Why

Right now the order is completely determined at map initialisation which is annoying.
If I add my polyline annotation manager in the completion block of the `mapView.mapboxMap.onNext(.mapLoaded)` call, it shows on top of the puck. If I add it before calling `mapView.mapboxMap.onNext(.mapLoaded)` it shows below the puck.

I want it below, but this means everything needs to be initialised in the right order up front, making it very confusing, inflexible and not developer friendly to choose what appears on top of what.

**Comment by ZiZasaurus** [comment]
@ir-fuel, per our documentation, you can set the [position of your annotation managers](https://docs.mapbox.com/ios/maps/api/10.6.0/Classes/AnnotationOrchestrator.html#/AnnotationOrchestrator). Similarly, you can set the position of your [symbol layers](https://docs.mapbox.com/ios/maps/api/10.6.0/Classes/Style.html#/Layers2). If you don't specify the order, they will be added to the map in the same order they were added in the code. Please note that view annotations will always be visualized on top of the map view.

**Comment by ZiZasaurus** [comment]
If you click on one of the references in the AnnotationOrchestrator class (for example, [makePointAnnotationManager(id:layerPosition:)](https://docs.mapbox.com/ios/maps/api/10.6.0/Classes/AnnotationOrchestrator.html#/s:10MapboxMaps22AnnotationOrchestratorC09makePointC7Manager2id13layerPositionAA0fcG0CSS_AA05LayerJ0OSgtF)), it will provide more information.

**Comment by ir-fuel** [comment]
> per our documentation, you can set the [position of your annotation managers](https://docs.mapbox.com/ios/maps/api/10.6.0/Classes/AnnotationOrchestrator.html#/AnnotationOrchestrator).

I checked every method declared there and ok, it seems we need to use `layerPosition` for this. If you click around a bit more you will find that `AnnotationManager` has a `layerId`, and it seems we can use that in `LayerPosition` to position the manager.

But this still doesn't explain me how I can add a layer afterwards that's below the puck? I don't find any `layerId` info in `LocationOptions` or `PuckType`?

For you it's maybe straightforward, but for people that don't know the internals it's extremely hard to figure out how to do some basic stuff. This is not in the docs, nor is there an example of inserting annotations and moving their order around.

**Comment by ZiZasaurus** [comment]
@ir-fuel thank you for the feedback, I'm happy to bring it to the team. To find the id of your location puck, it should be named "puck", but you can also use `mapView.mapboxMap.style.allLayerIdentifiers` to verify.

**Comment by skg54** [comment]
This works for me

    try mapView.mapboxMap.style.moveLayer(withId: "puck", to: .below(pointAnnotationManager.layerId))
