### ISSUE TITLE
Overriding heading in custom LocationProvider

### ISSUE THREAD

**Issue by joshkopecek** [mapbox/mapbox-maps-ios#1452]
## Environment

- Xcode version: 13.4.1
- iOS version: 15.5
- Devices affected: All
- Maps SDK Version: 10.6.0

## Observed behavior and steps to reproduce

Override `LocationProvider`.

## Expected behavior

Be able to override the heading parameter.

## Notes / preliminary analysis

The `LocationProvider` allows us to override the default location provider in order to implement our own data sources. The major issue here is that the [`heading`](https://docs.mapbox.com/ios/maps/api/10.6.0/Protocols/LocationProvider.html#/s:10MapboxMaps16LocationProviderP7headingSo9CLHeadingCSgvp) parameter is set to a [`CLHeading`](https://developer.apple.com/documentation/corelocation/clheading) instance, which Apple restrict from being able to override or set properties (they all error as 'get-only properties').

I can't see a way to get around this. As it is, the only way to provide heading is to send it the value reported from a `CLLocationManager` instance which is immutable, which restricts the flexibility that I thought the `LocationProvider` subclassing was supposed to provide.

Any tips or pointers would be greatly appreciated.

``` swift
extension InternalLocationManager: LocationProvider {
    
    ...
    
    public var heading: CLHeading? {
        var heading = CLHeading()
        heading.trueHeading = 45.0 // throws 'get-only property' error
        return heading
    }
...
```

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if any additional questions arise.
