### ISSUE TITLE
Customizable Annotation styling

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#147]
## New Feature
Currently `PointAnnotation`s are clustered. It would be nice to be able to configure whether or not clustering is used, or control its radius and max zoom, like with `GeoJSONSource`. It would also be nice to be able to set an image offset as currently the image center is placed coincident with the ray cast from the camera's perspective point to the `coordinate`. For the default red marker pin, this has the effect that the pin does not point at the coordinates and as one rotates a pitched map, the pointer refers to an infinite number of other map coordinates, just never the actual `coordinate`.

Currently `LineAnnotation`s are thin and black. This styling is not ideal for all background tile appearances, such as atop aerial imagery. It would be nice to be able to customize the styling of `LineAnnotations`, i.e., color, width, pattern, endpoints, and to be able to add edge labels.

Currently `ShapeAnnotation`s are black and opaque. It would nice to be able to separately control edge color, width, pattern and endpoints, and to be able to add edge labeling. It would also be nice to be able to control fill color and fill opacity, as well as add a label at a smart center point in the polygon.

## Why
Point annotations should be able to point directly to a map coordinate.
Clustering of point annotations is not always preferred.
Customizable styling of line and polygon annotations would allow adapting appearance for optimal readability, as well as for other considerations.
Labeling annotations allows for presenting additional pertinent information such as distance or area..

**Comment by sbma44** [comment]
Thanks for this, @johnkassebaum. We're going to be improving the usability of annotations, including better ergonomics for styling and making clustering configurable.

For the padding/anchor point issue: in the short term, can you adjust the padding by adding transparent pixels around the edge of the image? This should provide a temporary workaround, albeit one with implications for the hitbox of the annotation.

**Comment by sbma44** [comment]
Let me also offer this example, which might be a superior workaround: https://github.com/mapbox/mapbox-maps-ios/pull/190/files

If you're able to avoid using the `AnnotationManager`, you can employ `IconAnchor` and `IconOffset`. We'll be making these available via the AnnotationManager eventually.

**Comment by avi-c** [comment]
@johnkassebaum - If you need help employing the techniques used in the sample that @sbma44 refers to above, please let me know.

**Comment by tobrun** [comment]
Annotations have been refactored and can be styled
