### ISSUE TITLE
Mapbox spams log at app startup

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#1474]
The first lines my app logs at startup are these:

2022-07-18 11:07:45.617279-0700 Peakbagger[43307:1113905] [Mapbox] [Info, common]: Using Mapbox Common SDK v22.0.0(559753e5)
2022-07-18 11:07:45.617852-0700 Peakbagger[43307:1113905] [Mapbox] [Info, maps-core]: Using Mapbox Core Maps SDK v10.6.0(0289db54d7)

These (along with similar spam from other libraries) make debugging more difficult.  Can these be removed, or at least can we turn them off somehow?

**Comment by ZiZasaurus** [comment]
Generally log levels would be controlled with `LogConfiguration.setLoggingLevelForUpTo(LoggingLevel.error.rawValue as NSNumber)`, however, the logs in question appear to occur on initialization of core/common sdks, and are not able to be removed.

**Comment by akirmse** [comment]
@ZiZasaurus Can you please change this to a bug, then?  Between Mapbox and Firebase, I get over a dozen spam log messages when starting up.

**Comment by akirmse** [comment]
That suggestion doesn't work for me.  The proposed solution suggests adding the setting for Simulator SDKs, but I'm not using the simulator.  If I instead add the environment variable for "Any Architecture | Any SDK", there are two suggested values for the variable.  Setting to "default" has no effect, while setting to "disable" disables all system logging messages, including important errors like NSLayoutConstraint conflicts.  I don't see a way to get rid of just Mapbox spam.

**Comment by ZiZasaurus** [comment]
@akirmse I'm happy to bring this to the team to consider in a future update, however, currently we have the aforementioned `LogConfiguration.setLoggingLevelForUpTo(LoggingLevel.error.rawValue as NSNumber)` and `LogConfiguration.registerLogWriterBackend(forLogWriter: <#T##LogWriterBackend?#>)`, either of which can be used to reduce the amount of logs that are returned.

**Comment by akirmse** [comment]
Thanks.  As you mentioned in your first comment, those calls don't affect the logs I listed.

**Comment by evil159** [comment]
These logs cannot be disabled indeed, as they are being logged during the initialisation of the Maps SDK. All other logs should abide either setting the log level of providing a custom log backend.

**Comment by akirmse** [comment]
Can you file a bug on the Maps SDK for me?  I'm not familiar with which
github repo that is (if any).

**Comment by evil159** [comment]
This is the repo, thank you for your report, we'll consider this in a future update.
