### ISSUE TITLE
Question: Is there a way to modify the postal/zip code on the map?

### ISSUE THREAD

**Issue by michael94ellis** [mapbox/mapbox-maps-ios#1487]
I want to modify the Zip Code to display only numbers instead of something like "USP12345". Is that possible?

I see options to modify font, style, etc. but not one for manipulating the string value of the zip codes

**Comment by ZiZasaurus** [comment]
@michael94ellis as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
