### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by Degtyarserg** [mapbox/mapbox-maps-ios#1504]
## Environment

- Xcode version: 13.4.1
- iOS version: not relevant
- Devices affected: not relevant
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

When trying to add https://github.com/mapbox/mapbox-maps-ios.git as a dependency to iOS project in Xcode following this installation guide https://docs.mapbox.com/ios/maps/guides/install/ error appears:

Showing All Messages
invalidManifestFormat("Swift/ContiguousArrayBuffer.swift:575: Fatal error: Index out of range", diagnosticFile: Optional(<AbsolutePath:"/Users/serhii/Library/Developer/Xcode/DerivedData/test-cfupafledkubfxbnbxqnyfxezoft/SourcePackages/ManifestLoading/mapbox-core-maps-ios.dia">)) in https://github.com/mapbox/mapbox-core-maps-ios.git

## Expected behavior

It is possible to add Mapbox as an SPM dependency.

**Comment by trevordevelops** [comment]
How did you resolve this?

**Comment by bilics** [comment]
Wondering the same thing - I am facing the same problem

**Comment by bilics** [comment]
> 

Found the problem in my case - my token did not had the Downloads:Read permission set.
