### ISSUE TITLE
Crash on index out of range

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1515]
## Environment

- Xcode version:
- iOS version:
- Devices affected:

- Maps SDK Version:

## Additional links and references

<img width="1728" alt="Screen Shot 2022-08-04 at 4 01 04 PM" src="https://user-images.githubusercontent.com/79174176/182941991-1a15f854-5504-47d3-bda5-8cebf149f36c.png">

**Comment by ZiZasaurus** [comment]
@JenishKananiLime can you provide the following information so that we can attempt to reproduce this behavior on our side? 
- What version of the SDK are you seeing this on?
- How have you created your annotations

**Comment by JenishKananiLime** [comment]
10.7, using a serial queue inside a global queue

**Comment by evil159** [comment]
I think this issue is happening because annotation managers don't react well to being accessed from multiple threads, safe bet would be to update `annotations` property from the main thread.
