### ISSUE TITLE
PolygonAnnotation can't set stroke width

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#1516]
PolygonAnnotation does not have a property for stroke width; it is always 1 pixel, which is pretty much invisible on mobile.  I am guessing this is a limitation of the underlying library, as it's not supported on Android either.

The Google Maps SDK supports stroke width on both Android and iOS:

https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/Polygon

https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_polygon#a1d30f259dbeb3cc95dddbff15b5020c7

**Comment by ZiZasaurus** [comment]
@akirmse thank you for reporting this behavior. I have brought this to the appropriate team's attention, however, in the meantime, you can add a polyline layer on top of your polygon and then control the width with the polyline layer. If you are using a fill Layer to create your polygon, you can accomplish the same workaround using an overlaid line layer.

**Comment by akirmse** [comment]
@ZiZasaurus Thanks, that's a good suggestion.

**Comment by ZiZasaurus** [comment]
@akirmse, just wanted to follow back up with you on this ticket. Currently, the workaround I provided is the best way to accomplish your use case, as there are no immediate plans to allow setting polygon stroke width.

**Comment by akirmse** [comment]
That's too bad that Mapbox can't match Google.  This is trivial to do in the Google SDK.
