### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1519]
## New Feature
can you provide example of zoom based steps resolved image?

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by ZiZasaurus** [comment]
@JenishKananiLime can you provide more information about what you're trying to do? Are you trying to display an image of a certain size at specific zoom levels?

**Comment by DamonFish** [comment]
Hi, @ZiZasaurus 

I think what he meant to say was:
Display different images at different zoom levels.

Something like this：
https://docs.mapbox.com/android/legacy/maps/examples/symbol-switch-on-zoom/



`        let stops: [Double: String] = [
            0:  Constants.BLUE_ICON_ID,
            14: Constants.RED_ICON_ID,
        ]

        let imageExpression = Exp(.interpolate) {
            Exp(.zoom)
            stops
        }
        layer.iconImage = .expression(imageExpression)`

The above code does not work.
