### ISSUE TITLE
Pinch gesture not registering 

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1557]
## Environment

- Xcode version:
- iOS version: 
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
When user is in pan gesture and they attempt to zoom in with two fingers they aren't able to until they finish pan gesture movement. pre v10 this wasn't a issue, and all other maps platform allow this.

## Additional links and references

https://user-images.githubusercontent.com/79174176/188695233-235851ea-bdd7-45cf-a3fa-12f333637320.mp4

**Comment by ZiZasaurus** [comment]
@JenishKananiLime to confirm, you are trying to pinch while keeping the finger you were using to pan on the screen? You aren't removing your finger before attempting the pinch gesture?

**Comment by shinriyo** [comment]
pinch gesture also ignores the range of size.

**Comment by OdNairy** [comment]
@JenishKananiLime this issue was addressed a while ago and cannot be reproduced at least in the `main` branch.

> pinch gesture also ignores the range of size.

@shinriyo can you elaborate what did you mean?
