### ISSUE TITLE
Bearing arrow option when showing user location

### ISSUE THREAD

**Issue by jeradhoy** [mapbox/mapbox-maps-ios#156]
In the old mapbox version, you could easily show the user location with "mapView.showsUserHeadingIndicator = true".

There is even an asset for it here: https://github.com/mapbox/mapbox-maps-ios/tree/6f0555d0727c92b9ffafbf1adde2d450253271a6/Sources/MapboxMaps/Location/Pucks/IndicatorAssets.xcassets/triangle.imageset

I have not found any easy way to just add this triangle to the location puck. You can't use it in creating a new puck because of an 'internal' protection level.

Is there a way to do this currently, or will this be added in the future?

**Comment by ajbraudev** [comment]
We are in need of this as well. Would be great to know if an easy solution is coming, or if we should start figuring out another solution. Thanks Mapbox team!

**Comment by neelmistry94** [comment]
@jeradhoy and @ajbraudev In V10, we have deprecated support for these visuals but have now put the customizations in your hands. 

See [this](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Custom2DPuckExample.swift) example for how to provide your own image to the location puck.

**Comment by macdrevx** [comment]
This was fixed by https://github.com/mapbox/mapbox-maps-ios/pull/980 and https://github.com/mapbox/mapbox-maps-ios/pull/1064 and is available as of 10.3.0-rc.1
