### ISSUE TITLE
Puck2D crashes 

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1568]
## Environment

- Xcode version: 13
- iOS version: 15+
- Devices affected:
- Maps SDK Version: 10.7.0 - 10.8.0

## Additional links and references

<img width="1104" alt="Screen Shot 2022-09-08 at 1 01 11 PM" src="https://user-images.githubusercontent.com/79174176/189182448-b1483e9e-8bda-47f5-a1aa-134d1e5ecbcb.png">

**Comment by JenishKananiLime** [comment]
@ZiZasaurus this is internal Mapbox crash can you suggest when fix will occur this can be a launch blocker for us as this crash is happening within the library and already to 11 users in 1 day

**Comment by JenishKananiLime** [comment]
@ZiZasaurus any updates we have seen this crash for 100 users so far

**Comment by ZiZasaurus** [comment]
@JenishKananiLime is this ticket a duplicate? If so, can you please let us know what is happening in the app prior to / at the moment of the crash?

**Comment by JenishKananiLime** [comment]
@ZiZasaurus this crash is reported on the fire base and we don’t know what’s happening prior to this crash as the threads don’t show anything particularly happening prior. Our code is only adding the puck2d we aren’t making any updates or any sort of changes to the puck, so this seems to be library crash it self. We are using 10.8.0

**Comment by JenishKananiLime** [comment]
I was looking at the puck2d class and it seems the mapbox library does a try! Maybe a try catch might help in not crashing this?

**Comment by JenishKananiLime** [comment]
@ZiZasaurus I am happy to setup a zoom call to investigate this further.

**Comment by ZiZasaurus** [comment]
@JenishKananiLime, while I'm not able to get on a zoom call, I'm happy to continue troubleshooting with you. Are you able to update to our most recent version, v10.8.1? We released this on Friday to resolve a conflict within our frameworks.

**Comment by JenishKananiLime** [comment]
@ZiZasaurus yes we will update to the latest, we will get data if the updated fix would fix it or next week due to our release process, will keep updated if this fixes the issue or not

**Comment by JenishKananiLime** [comment]
@ZiZasaurus this is something that the library does internally we aren't updating the location pucks value

**Comment by ZiZasaurus** [comment]
Is there anything about the puck (image, size, etc) that you are updating?

**Comment by JenishKananiLime** [comment]
nope we are only using whats available by default

**Comment by JenishKananiLime** [comment]
mapBoxMapView?.location.options.puckType = .puck2D()

**Comment by ZiZasaurus** [comment]
Understood. Did this work in a previous version of the SDK?

**Comment by JenishKananiLime** [comment]
We aren't sure we just released mapbox to public with this version

**Comment by ZiZasaurus** [comment]
Thank you for providing this information. I am unable to reproduce this behavior. Can you please provide steps for reproduction so that I can investigate further?

**Comment by JenishKananiLime** [comment]
We aren’t able to reproduce it’s reported to fire base when our users are using it

**Comment by JenishKananiLime** [comment]
Can’t the try! be replaced with try? If the mapbox sdk is throwing this error?

**Comment by ZiZasaurus** [comment]
Are you referring to the try [here](https://github.com/mapbox/mapbox-maps-ios/blob/3813c38553bb99049af5a31b71cbb01b39ca0fb8/Sources/MapboxMaps/Location/Puck/Puck2D.swift#L206)?

**Comment by JenishKananiLime** [comment]
Yes I’m not saying the would fix it but it probably safer to do a optional try

**Comment by JenishKananiLime** [comment]
Also we updated our sdk to 10.8.1 and will roll out next week we can wait to see if the new sdk fixed this issue

**Comment by ZiZasaurus** [comment]
Fantastic! We are currently investigating the issue for you, but in the meantime can you let me know what location provider you are using? Is it the default?

**Comment by JenishKananiLime** [comment]
Yes it’s the default

**Comment by JenishKananiLime** [comment]
@ZiZasaurus its still crashing after 10.8.1

**Comment by ZiZasaurus** [comment]
@JenishKananiLime as I am unable to reproduce, can you please provide us with a sample project that reproduces the crash you are experiencing? This will allow us to see your implementation and find the root of the issue.

**Comment by JenishKananiLime** [comment]
@ZiZasaurus can you share your email I can provide sample proj

**Comment by JenishKananiLime** [comment]
@ZiZasaurus if we can make the try! try? in the puck2d setstyleproperties, that way it might be able to prevent this crash?

**Comment by JenishKananiLime** [comment]
@ZiZasaurus this crash is fixed, we moved to 10.9.0 beta and moved all calls to Mapbox api to main thread.

**Comment by ZiZasaurus** [comment]
@JenishKananiLime fantastic news! Thank you for updating us.
