### ISSUE TITLE
Energy Impact Seems Unreasonably High

### ISSUE THREAD

**Issue by Jason0705** [mapbox/mapbox-maps-ios#1574]
## Environment

- Xcode version: 13.4.1
- iOS version: 15.4.1
- Devices affected: iPhone X
- Maps SDK Version: 10.8.0

## Observed behavior and steps to reproduce

I tested with a basic MapView on SwiftUI View. My implementation is very minimal. The energy impact stays at high if the map is not moving. It turns to very high if map is constantly scrolled.

Code screenshots:
<img width="1051" alt="Screen Shot 2022-09-09 at 4 41 13 PM" src="https://user-images.githubusercontent.com/14986001/189459507-a402d407-cb9e-4985-95e3-0246dc67fe9a.png">
<img width="970" alt="Screen Shot 2022-09-09 at 4 41 23 PM" src="https://user-images.githubusercontent.com/14986001/189459516-1422df93-4264-49c7-b847-9713214229fc.png">

Energy impact with map not moving:
<img width="1082" alt="Screen Shot 2022-09-09 at 4 34 58 PM" src="https://user-images.githubusercontent.com/14986001/189459554-ed24a74e-fe3b-4121-8a41-2e529c497c38.png">

Energy impact with map moving:
<img width="1038" alt="Screen Shot 2022-09-09 at 4 37 07 PM" src="https://user-images.githubusercontent.com/14986001/189459577-907826c5-cb5c-4c5e-a3f1-5937dd06d83c.png">

## Expected behavior

A lower energy impact.

## Notes / preliminary analysis

Telemetry is disabled.

**Comment by Jason0705** [comment]
<img width="1278" alt="Screen Shot 2022-09-12 at 2 07 28 PM" src="https://user-images.githubusercontent.com/14986001/189758883-e05b8ae7-ae84-4abb-8236-b01ea5a7cb66.png">

Also noticed the rendering takes a lot of cpu power and causing battery drain and the device to heat up rather quickly.

**Comment by ZiZasaurus** [comment]
@Jason0705 thank you for reporting this behavior to us. I have brought this issue to the larger team and we are investigating the root cause.

**Comment by evil159** [comment]
@Jason0705 I think what you are observing here is quite normal, Xcode's energy impact measurements are affected quite a bit by the "Display" section making ~60% of the impact.
In the screenshot below I measured energy impact of a completely empty app which renders just a plain white view on iPhone 13 Pro Max - and the average energy impact never drops to low:
<img width="1223" alt="Blank_app" src="https://user-images.githubusercontent.com/1478430/192516011-96942fd1-b0e6-4fbf-8b00-503ae1375212.png">

As for the energy impact when moving - it's bit tricky to measure as rendering can vary depending on map style, zoom level, pitch, camera location. Here I recorded two sessions where camera follows a fixed route - one for MapKit and one for Mapbox maps:

| MapKit | MapboxMaps |
| ----- | ----- |
| <img src="https://user-images.githubusercontent.com/1478430/192517223-a059e23e-89b9-4db8-912e-d6753ec85bae.png" width = 1000/> | <img src="https://user-images.githubusercontent.com/1478430/192517343-ca6f221f-8247-49e8-9aca-9f44082a717a.png" width = 1000 /> |

The average energy impact looks quite comparable between the two. 

If you want to lessen the rendering burden you can try lowering map view's refresh rate(`MapView.preferredFrameRateRange/MapView.preferredFramesPerSecond`). Another quite energy-heavy component is the GPS module - you can use `LocationOptions.desiredAccuracy` and `LocationOptions.distanceFilter` options to configure the default location manager to a less power-hungry mode.

Here's the GPX file that I used to simulate the route - [gpxgenerator_path.gpx.zip](https://github.com/mapbox/mapbox-maps-ios/files/9655184/gpxgenerator_path.gpx.zip).
