### ISSUE TITLE
Location Consumer 90% CPU usage and high enery impact 

### ISSUE THREAD

**Issue by rohan-59** [mapbox/mapbox-maps-ios#1581]
- Xcode version: 14.0
- iOS version: 16.0
- Devices affected: iPhone 11
- Maps SDK Version: Demo app

I am running example app. When I open "Display the user's location" page which is using Location consumer, CPU usage goes to 100% and High energy impact. I want to develop a feature which moves camera with user's current location change while walking, running and driving. I tried to use ViewPort API but bearing type course is very jerky. Puck moves even if I put device onto flat surface. 

<img width="1440" alt="Screenshot 2022-09-16 at 3 36 22 PM" src="https://user-images.githubusercontent.com/87698502/190616438-27abf0be-75ab-46e9-8311-32d190bdb72e.png">

<img width="1508" alt="Screenshot 2022-09-16 at 3 36 15 PM" src="https://user-images.githubusercontent.com/87698502/190616527-af1181c3-bf2d-4f43-8f7b-bb491f67b3b3.png">

**Comment by ZiZasaurus** [comment]
@rohan-59 thank you for reporting this behavior. The team will look into the root cause and report back soon.

**Comment by evil159** [comment]
Hello @rohan-59, I don't see anything suspicious here - there is indeed some CPU load which is the cost of drawing a map. One thing to note that the CPU usage shown by Xcode is not in 0-100% scale but 0-(number of cores * 100), e.g. it is 0-600% in my case:
<img width="510" alt="Screenshot 2022-09-27 at 15 06 50" src="https://user-images.githubusercontent.com/1478430/192522280-e9912191-50d3-4ed0-9f57-2d1693a379fa.png">

As for the energy impact, I think what you are observing here is quite normal, Xcode's energy impact measurements are affected quite a bit by the "Display" section.
In the screenshot below I measured energy impact of a completely empty app which renders just a plain white view on iPhone 13 Pro Max - and the average energy impact never drops to low:
<img width="1223" alt="Blank_app" src="https://user-images.githubusercontent.com/1478430/192516011-96942fd1-b0e6-4fbf-8b00-503ae1375212.png">
