### ISSUE TITLE
iOS: Change Icon on layer by click doesn't work

### ISSUE THREAD

**Issue by MaxOkuneev** [mapbox/mapbox-maps-ios#1603]
## Environment

- Xcode version: Version 14.0 (14A309)
- iOS version: 16.0
- Devices affected: Simulator, Iphone 13
- Maps SDK Version: 10.3.0

## Observed behavior and steps to reproduce

I try to change Icon Image from black pin to red pin when clicking by this pin (it's not change color, it's change Image), but changing doesn't work. 
For example, I used example code from this repo, in file  **FeatureStateExample** I change CircleLayer to SymbolLayer:
Comment this code: 

```
//        // Add earthquake-viz layer
//        var earthquakeVizLayer = CircleLayer(id: Self.earthquakeLayerId)
//        earthquakeVizLayer.source = Self.earthquakeSourceId
....
//        earthquakeVizLayer.circleColorTransition = StyleTransition(duration: 0.5, delay: 0)

```

and add this:
```
        var earthquakeVizLayer = SymbolLayer(id: Self.earthquakeLayerId)
        earthquakeVizLayer.source = Self.earthquakeSourceId

        earthquakeVizLayer.iconImage = .expression(
            Exp(.switchCase) {
                Exp(.boolean) {
                    Exp(.featureState) { "selected" }
                    false
                }
                "newMapPinRed"
                "newMapPinBlack"
            }
        )

        do {
            try  mapView.mapboxMap.style.addImage(UIImage(named: "newMapPinBlack") ?? UIImage(), id: "newMapPinBlack", sdf: false, stretchX: [], stretchY: [])
            try  mapView.mapboxMap.style.addImage(UIImage(named: "newMapPinRed") ?? UIImage(), id: "newMapPinRed", sdf: false, stretchX: [], stretchY: [])

            try mapView.mapboxMap.style.addLayer(earthquakeVizLayer)
        } catch {
            print("Ran into an error adding a layer: \(error)")
        }
    }

```
Also add newMapPinBlack and newMapPinRed in assets
func findFeatures and setSelectedState was not changed:

```
@objc public func findFeatures(_ sender: UITapGestureRecognizer) {
        let tapPoint = sender.location(in: mapView)

        mapView.mapboxMap.queryRenderedFeatures(
            with: tapPoint,
            options: RenderedQueryOptions(layerIds: ["earthquake-viz"], filter: nil)) { [weak self] result in

            guard let self = self else { return }

            switch result {
            case .success(let queriedfeatures):

                // Extract the earthquake feature from the queried features
                if let earthquakeFeature = queriedfeatures.first?.feature,
                   case .number(let earthquakeIdDouble) = earthquakeFeature.identifier,
                   case .point(let point) = earthquakeFeature.geometry,
                   case let .number(magnitude) = earthquakeFeature.properties?["mag"],
                   case let .string(place) = earthquakeFeature.properties?["place"],
                   case let .number(timestamp) = earthquakeFeature.properties?["time"] {

                    let earthquakeId = Int(earthquakeIdDouble).description

                    // Set the description of the earthquake from the `properties` object
                    self.setDescription(magnitude: magnitude, timeStamp: timestamp, location: place)

                    // Set the earthquake to be "selected"
                    self.setSelectedState(earthquakeId: earthquakeId)

                    // Reset a previously tapped earthquake to be "unselected".
                    self.resetPreviouslySelectedStateIfNeeded(currentTappedEarthquakeId: earthquakeId)

                    // Store the currently tapped earthquake so it can be reset when another earthquake is tapped.
                    self.previouslyTappedEarthquakeId = earthquakeId

                    // Center the selected earthquake on the screen
                    self.mapView.camera.fly(to: CameraOptions(center: point.coordinates, zoom: 10))
                }
            case .failure(let error):
                self.showAlert(with: "An error occurred: \(error.localizedDescription)")
            }
        }
    }

    // Sets a particular earthquake to be selected
    func setSelectedState(earthquakeId: String) {
        self.mapView.mapboxMap.setFeatureState(sourceId: Self.earthquakeSourceId,
                                               sourceLayerId: nil,
                                               featureId: earthquakeId,
                                               state: ["selected": true])
    }

```
map loaded, pin set blackIcon by clicking pin, map is zooming but not change to redIcon

![IMG_0722D5556223-1](https://user-images.githubusercontent.com/92374063/192502668-6195245b-bd42-4502-abe5-b5c986b0938a.jpeg)
![IMG_B4BC526C2AE8-1](https://user-images.githubusercontent.com/92374063/192502932-4dbde6d1-bf39-4df8-a7a7-e2cee71f9d70.jpeg)

Icons:
![Property 1=Pin, Property 2=Default, Icon=no, Color=red@3x](https://user-images.githubusercontent.com/92374063/192504523-2c7a9d7f-d1f8-4628-9456-81e9dce0da8b.png)
![Property 1=Pin, Property 2=Default, Icon=no, Color=black@3x](https://user-images.githubusercontent.com/92374063/192504619-aee9efff-52fa-46c5-ae00-4d7c0f3b6207.png)

## Expected behavior

Pin change Image to newMapPinRed

## Notes / preliminary analysis

Also I try this scheme with LineLayer and try change line color, it also doesn't work.

**Comment by ZiZasaurus** [comment]
@MaxOkuneev i noticed you reported this issue as occurring on 10.3, is that correct? If so, can you please try this on the most recent version of our SDK, v10.8.1?

**Comment by MaxOkuneev** [comment]
Hi! I update version to 10.8 and it doesn't help. Also I create a zero point with simple example and It also doesn't work Here is code, may be I do something wrong? 

`
import UIKit
import MapboxMaps

class ViewController: UIViewController {

    private var options: MapInitOptions {
        let resourceOptions = ResourceOptions(accessToken: "")
        let centerCoordinate = CLLocationCoordinate2D(latitude: 39.368279, longitude: -97.646484)
        let cameraOptions = CameraOptions(center: centerCoordinate, zoom: 15.0)
        let mapOption = MapInitOptions(resourceOptions: resourceOptions, cameraOptions: cameraOptions)

        return mapOption
    }

    lazy var mapView: MapView = {
        let mapView = MapView(frame: self.view.bounds, mapInitOptions: options)

        mapView.mapboxMap.onNext(event: .mapLoaded) { _ in
            self.addSource()
            self.setupLayers()
        }

        mapView.gestures.options.quickZoomEnabled = false
        mapView.gestures.options.doubleTapToZoomInEnabled = false
        mapView.gestures.options.panEnabled = false
        mapView.gestures.options.pinchEnabled = false

        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(findFeatures))
        mapView.addGestureRecognizer(tapGesture)

        view.addSubview(mapView)

        mapView.translatesAutoresizingMaskIntoConstraints = false

        mapView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 0).isActive = true
        mapView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: 0).isActive = true
        mapView.topAnchor.constraint(equalTo: view.topAnchor, constant: 0).isActive = true
        mapView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: 0).isActive = true

        return mapView
    }()


    override func viewDidLoad() {
        super.viewDidLoad()
        _ = mapView
    }

    // add Source
    func addSource() {
        var feature = Feature(geometry: Geometry.point(Point(LocationCoordinate2D(latitude: 39.368279, longitude: -97.646484))))
        feature.identifier = FeatureIdentifier("feauteId1")
        let featureCollection = FeatureCollection(features: [feature])
        let data = GeoJSONSourceData.featureCollection(featureCollection)
        var source = GeoJSONSource()

        source.data = data
        do {
            try self.mapView.mapboxMap.style.addSource(source, id: "pointSource")
        } catch {
            print("Ran into an error adding a source: \(error)")
        }
    }

    // add layer
    func setupLayers() {
        var pointLayer = SymbolLayer(id: "pointLayer")

        let expression = Exp(.switchCase) {
            Exp(.boolean) {
                Exp(.featureState) { "selected" }
                false
            }
            "newMapPinRed"
            "newMapPinBlack"
        }

        pointLayer.iconImage = .expression(expression)
        pointLayer.source = "pointSource"
        do {
            try  mapView.mapboxMap.style.addImage(UIImage(named: "newMapPinBlack") ?? UIImage(), id: "newMapPinBlack", sdf: false, stretchX: [], stretchY: [])
            try  mapView.mapboxMap.style.addImage(UIImage(named: "newMapPinRed") ?? UIImage(), id: "newMapPinRed", sdf: false, stretchX: [], stretchY: [])
            try self.mapView.mapboxMap.style.addLayer(pointLayer)
        } catch {
            print("Ran into an error adding a layer: \(error)")
        }
    }

    // search feature
    @objc func findFeatures(_ sender: UITapGestureRecognizer) {
        let tapPoint = sender.location(in: mapView)

    mapView.mapboxMap.queryRenderedFeatures(
        with: tapPoint,
        options: RenderedQueryOptions(layerIds: ["pointLayer"], filter: nil)) { [weak self] result in

            guard let self = self else { return }

            switch result {
            case .success(let queriedfeatures):
                if queriedfeatures.first?.feature.identifier == FeatureIdentifier("feauteId1") {
                    self.setSelectedState(id: "pointLayer")
                }
            case .failure(_):
                print("can't find feature")
            }
        }
}

    // set state
    func setSelectedState(id: String) {
        self.mapView.mapboxMap.setFeatureState(sourceId: "pointSource",
                                               sourceLayerId: nil,
                                               featureId: id,
                                               state: ["selected": true])
    }
}
`

**Comment by maios** [comment]
Hi @MaxOkuneev, `feature-state`only supports `paint` properties that support data-driven styling, in your example, `SymbolLayer/iconImage`is [not a paint property](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Generated/Layers/SymbolLayer.swift#L453), if you want to change the icon image upon selected/deselected, please take a look at the example that @ZiZasaurus posted above.

Source: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#feature-state

We will update our documentation about this to avoid any confusion in the future.

**Comment by sussia-trend** [comment]
@ZiZasaurus, could you please provide the code how to reproduce your vid using [icon size change example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Annotations/IconSizeChangeExample.swift)?
