### ISSUE TITLE
iOS: what is the algorithm of the mapbox cluster?

### ISSUE THREAD

**Issue by himchan05** [mapbox/mapbox-maps-ios#1605]
hello. I am a Korean student who wants to develop a cluster module.
What cluster algorithm did Mapbox use?

**Comment by evil159** [comment]
Hello @himchan05, thanks for checking by. In Mapbox we use a variation of hierarchical greedy clustering, you can read more about it [here](https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97).

**Comment by himchan05** [comment]
> Hello @himchan05, thanks for checking by. In Mapbox we use a variation of hierarchical greedy clustering, you can read more about it [here](https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97).

thanks for your reply
