### ISSUE TITLE
Legacy offline map downloads failing with 401 status

### ISSUE THREAD

**Issue by mysport12** [mapbox/mapbox-maps-ios#1615]
## Environment

- Xcode version: 14.0.1
- iOS version: 16
- Devices affected: iPhone X and 13 Pro (simulator)
- Maps SDK Version: 10.7.0

## Observed behavior and steps to reproduce

When doing a legacy region download, the download fails almost instantly with an HTTP 401 error response. We are setting the access token when initializing the OfflineRegionManager and we have no issues accessing the Mapbox style and we also had success downloading tiles using the new method. Unfortunately, the 750 tile count limit (with no ability to increase that limit currently) does not work for us and as such we are trying to get the legacy method working with v10 (worked fine in v6). We understand this method of downloading is deprecated, but until the tile count limit can be increased using the new method we need to find a way to get this up and running. Any help would be appreciated.

## Expected behavior

Successful download of offline regions using legacy method

## Notes / preliminary analysis

Here are some snippets from our offline module code related to the offline download..

We tried a number of different things and the closest we came was a download that made it part of the way through and then failed midway with a 401 status.

```
lazy var offlineManagerLegacy : OfflineRegionManager = {
    return OfflineRegionManager.init(resourceOptions: .init(accessToken: MGLModule.accessToken!))
  }()

@objc
  func createPackLegacy(_ options: NSDictionary, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
    DispatchQueue.main.async {
      do {
        let metadataStr = options["metadata"] as! String
        let metadata = try JSONSerialization.jsonObject(with: metadataStr.data(using: .utf8)!, options: []) as! [String:Any]
        let id = metadata["name"] as! String

        let boundsStr = options["bounds"] as! String
        let boundsData = boundsStr.data(using: .utf8)
        let boundsFC = try JSONDecoder().decode(FeatureCollection.self, from: boundsData!)

        var geometry = self.convertPointPairToBounds(RCTMGLFeatureUtils.fcToGeomtry(boundsFC))
        
        let regionOptions = OfflineRegionGeometryDefinition(
          styleURL: options["styleURL"] as! String,
          geometry: geometry,
          minZoom: options["minZoom"] as! Double,
          maxZoom: options["maxZoom"] as! Double,
          pixelRatio: Float(UIScreen.main.scale),
          glyphsRasterizationMode: .ideographsRasterizedLocally
        )
        self.offlineManagerLegacy.createOfflineRegion(for: regionOptions) { result in
          let region = try? result.get()
          region?.setOfflineRegionDownloadStateFor(OfflineRegionDownloadState(rawValue: 1)!)
          region?.setOfflineRegionObserverFor(RegionObserver(name: id, offlineModule: self))
        }
        resolver([
          "bounds": boundsStr,
          "metadata": String(data:try! JSONSerialization.data(withJSONObject: metadata, options: [.prettyPrinted]), encoding: .utf8)
        ])
      } catch {
        print("error", error)
        rejecter("createPack", error.localizedDescription, error)
      }
    }
  }
```

**Comment by mysport12** [comment]
Update: Download works fine if I use the Mapbox Streets style, but when I put our styleURL (mapbox:// format) it fails

**Comment by mysport12** [comment]
@ZiZasaurus Yeah and it's only with the custom style we are having issues with. Here is the url

mapbox://styles/overlandbound/cl0sezuw8002214ny3fvbvi7i

**Comment by mysport12** [comment]
I can try that and report back here. I believe it was originally created in Studio. For what it's worth, the new download method works just fine in our app with this style and access token combo, it's just the legacy that isn't working.

**Comment by mysport12** [comment]
I duplicated the style, and referenced that within the app but no luck. I first deleted the app from the simulator, cleaned the build folder, and rebuilt the app in Xcode. Still getting a 401 status error on download. We are using the default public token from our account (created 4 years ago) as the access token.

**Comment by mysport12** [comment]
@ZiZasaurus I believe I figured out what the issue is. In our style, we have the mapbox raster-dem source/terrain enable. I tried one of our slightly older styles that did not have that included and it downloads fine. With that said, is there any way to get legacy downloads to work with the raster-dem/terrain included or do we need to pursue an alternate option?

**Comment by ZiZasaurus** [comment]
@mysport12 my apologies for the delay. I am able to see terrain and download these tiles successfully using the legacy offline region manager. 
![Simulator Screen Shot - iPhone 12 - 2022-11-04 at 17 39 58](https://user-images.githubusercontent.com/44972592/200079372-b19bd862-73b2-4fb4-a4f2-a590397f5386.png)

**Comment by ZiZasaurus** [comment]
@mysport12 can you share the styleurl with me? Additionally, are you referencing a style that already has terrain turned on or uses the raster dem source or are you adding this layer at runtime?

**Comment by mysport12** [comment]
@ZiZasaurus I shared the style url earlier in the conversation. As mentioned, turning on 3D terrain or adding the raster-dem source in Studio causes the issue. Adding the raster-dem source client side at runtime is fine. But adding it at runtime does not allow us to download it for offline use since it is not part of the style.

**Comment by ZiZasaurus** [comment]
Which seems odd, because I'm able to enable 3D terrain in the Studio style and then reference it in the offline example with no issues. Can you please try this on the newest version of our SDK, v10.9.1?

**Comment by ZiZasaurus** [comment]
One additional question for you -- are you seeing this behavior in the examples app or in your app? If it's in your app, can you please test this out in our Examples app instead? Your app is built using React Native, correct?
