### ISSUE TITLE
Can't set PointAnnotation Anchor as init value doesn't exist????

### ISSUE THREAD

**Issue by jay-cohen** [mapbox/mapbox-maps-ios#1620]
The `ViewAnnotationOptions` calls for an anchor using `ViewAnnotationAnchor` that doesn't exist inside the framework.

Seeing the pull request for this feature: https://github.com/mapbox/mapbox-maps-ios/pull/776
It was added but never finished, yet passing the PR???

How are we supposed to pin annotations to anchor points when the code doesn't exist and the documentation states it defaults to centre, which is untrue - it defaults to nil as seen here inside the framework:

```
 public init(geometry: GeometryConvertible? = nil,
                width: CGFloat? = nil,
                height: CGFloat? = nil,
                associatedFeatureId: String? = nil,
                allowOverlap: Bool? = nil,
                visible: Bool? = nil,
                anchor: ViewAnnotationAnchor? = nil, // ViewAnnotationAnchor doesn't exist!!
                offsetX: CGFloat? = nil,
                offsetY: CGFloat? = nil,
                selected: Bool? = nil) {
        self.geometry = geometry?.geometry
        self.width = width
        self.height = height
        self.associatedFeatureId = associatedFeatureId
        self.allowOverlap = allowOverlap
        self.visible = visible
        self.anchor = anchor
        self.offsetX = offsetX
        self.offsetY = offsetY
        self.selected = selected
    }

```

**Comment by evil159** [comment]
Hi @jay-cohen, `ViewAnnotationOptions` is defined in another module(`MapboxCoreMaps`), [here's](https://docs.mapbox.com/ios/maps/api/10.8.1/core/Enums/MBMViewAnnotationAnchor.html) the documentation for it .

You can use it as any other Swift enum, e.g.: `let anchor: ViewAnnotationAnchor = .topLeft`.

If anchor parameter is not specified explicitly(like you pointed out is the case with public initializer) - view annotation will be centered relatively to given geometry.
