### ISSUE TITLE
Customize user location bearing image

### ISSUE THREAD

**Issue by Zakalicious** [mapbox/mapbox-maps-ios#1624]
## New Feature

1) Heading and course are currently the 2 choices for bearing source. I would like to enter my own angle of rotation of the bearing image.

2) Color the user location image. 
let image = UIImage(systemName: "location.north.circle.fill") // works
 i?.withTintColor(.red) //  is being ignored

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

These features would be helpful for me, as I want to indicate which direction the user is supposed to go. The color would be an indicator how far the user is straying from this direction (red when they are going in the wrong direction, orange to get their attention, green when all is good.

**Comment by ZiZasaurus** [comment]
Thank you for reaching out to support. You can use the following snippet below to accomplish your use case.

```
        if #available(iOS 13.0, *) {
            let image = UIImage(systemName: "location.north.circle.fill", withConfiguration: UIImage.SymbolConfiguration(pointSize: 8))
            if let data = image?.withTintColor(.red).pngData() {
                let config = Puck2DConfiguration(topImage: UIImage(data: data))
                mapView.location.options.puckType = .puck2D(config)
            }
        }
```
