### ISSUE TITLE
Mapbox v10.2 to v10.7 upgrade crashes on GeoJSONSourceData updates...

### ISSUE THREAD

**Issue by amirkrdz** [mapbox/mapbox-maps-ios#1640]
## Environment
Any env. Debug/release etc.

- Xcode version: 13.2.1
- iOS version: 14.5
- Devices affected: iPhone 11 (simulators), iPhone 7/8 real devices.
- Maps SDK Version: 10.7

## Observed behavior and steps to reproduce

- Upgraded Mapbox **v10.2** to **v10.7**.
- Crashes when loading `symbolLayers` in a specific map `GeoJSONSource`.

Specific map source flow:
- Fetch the data.
- Create `GeoJSONSource`.
- Assign the data to the `GeoJSONSourceData`.
- Add the source and the data.
- When next batch of data comes in, use `updateGeoJSONSource()` to update the data set from same source.
- This happens multiple times, inside a `main.async` block, and crashes sometime in between here.

No log or print statements besides:
`MapboxCoreMaps was compiled with optimization - stepping may behave oddly; variables may not be available`. Which happens sometime after or before the `updateGeoJSONSource()` call in this specific source and layers.

## Expected behavior

No crash. Just loads symbols.

## Notes / preliminary analysis

Was working fine on 10.2 for a while.

Was repeatable for a while. But then stopped and stopped being repeatable. I am assuming the data set might have been bigger before, is there a data or symbol layer max that might crash it?

## Additional links and references

Did not work:
https://stackoverflow.com/questions/32772573/project-name-was-compiled-with-optimization-stepping-may-behave-oddly-varia

**Code Block:**

```
DispatchQueue.main.async {
                // Create 1 source, 1 source only, and add to its data if need be. This is more efficient...
                /// Check if exists
                if weakSelf.mapView.mapboxMap.style.sourceExists(withId: weakSelf.sourceID) {
                    /// Exists, so modify/update the data
                    if let featureCollection = weakSelf.getFeatureCollectionData(for: AWKFeatureCollection(features: features)),
                       let temp = weakSelf.sourceData, let data = temp + featureCollection
                    {
                        try? weakSelf.mapView.mapboxMap.style.updateGeoJSONSource(withId: weakSelf.sourceID, geoJSON: .featureCollection(data))
                    }
                }
                else {
                    /// Create new source / first time load
                    if let featureCollection = weakSelf.getFeatureCollectionData(for: AWKFeatureCollection(features: features)) {
                        var symbolSource = GeoJSONSource()
                        symbolSource.data = .featureCollection(featureCollection)
                        weakSelf.sourceData = featureCollection
                        try? weakSelf.mapView.mapboxMap.style.addSource(symbolSource, id: weakSelf.sourceID)
                    }
                }
                
                for (date, mappedFeatures) in strikesByDate {
                    // Break the strikes up into groups. Don't add all the strikes into one source as this hurts performance
                    let numOfSlices = Int(ceil(Double(mappedFeatures.count) / Double(weakSelf.strikesPerSource)))
                    for i in 0 ..< numOfSlices {
                        let slice = mappedFeatures[i * weakSelf.strikesPerSource ..< min((i + 1) * weakSelf.strikesPerSource, mappedFeatures.count)]
                        weakSelf.addPoints(for: Array(slice), date: date, index: i)
                    }
                    
                    weakSelf.drawSelectedStrikes()
                }
            }
```

**Comment by ZiZasaurus** [comment]
@amirkrdz thank you for reaching out to support. Can you please let me know roughly how many points /objects you're adding to your map?

**Comment by ZiZasaurus** [comment]
Are you still experiencing this issue on the most recent version of our SDK? If so, depending on the amount of features you're adding to your maps, you can take a look at the [Mapbox Tiling Service](https://docs.mapbox.com/mapbox-tiling-service/guides/) (MTS), a tool for creating vector tilesets. With MTS, you use sets of configuration options ([tileset recipes](https://docs.mapbox.com/help/glossary/tileset-recipe/)) to transform your geospatial data into vector tiles and the resulting tiles will be hosted on Mapbox servers for use in your applications.
