### ISSUE TITLE
"Value of type 'MGLMapView' has no member 'gestures'" ----Very bad documentation

### ISSUE THREAD

**Issue by Rohit737-star** [mapbox/mapbox-maps-ios#1642]
## Environment

- Xcode version: 13.0
- iOS version: minimum deplyment target 12.4
- Devices affected: not device issue i am sure 
- Maps SDK Version: pod 'MapboxNavigation', '~> 0.16'

i have added code from mapbox documentation for gesture 

// Declare the map's gesture manager delegate
mapView.gestures.delegate = self //HERE IS CODE

mapView is     internal var mapView:MGLMapView!
 but I'm getting compile time error- 

"Value of type 'MGLMapView' has no member 'gestures'"

what is issue please let me know

Thanks

**Comment by ZiZasaurus** [comment]
@Rohit737-star feedback is always welcome, however, I have edited your comment to comply with Mapbox's Code of Conduct [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/CODE-OF-CONDUCT.md).

Please note that Navigation v 0.16 is an outdated version of the Navigation SDK that is no longer supported. Please update to v2.0 + for assistance.
