### ISSUE TITLE
Camera `bearing` in layer expression

### ISSUE THREAD

**Issue by naftalibeder** [mapbox/mapbox-maps-ios#1662]
## New Feature

Enable camera bearing as an expression style property.

## Why

Currently, [layers can react](https://github.com/mapbox/mapbox-maps-ios/blob/cb2f97131b41c8917ecdc1d4779bf962cec369fc/Sources/MapboxMaps/Style/Generated/Expressions/AllExpressions.swift#L266) to changes in the camera's `zoom` level. It would be useful to have the same interactivity with the `bearing` value.

For example, this would enable layer elements to visually point in the same cardinal direction, no matter which way the camera is rotated.

**Comment by ZiZasaurus** [comment]
@naftalibeder thank you for reaching out. To better assist you, can you please provide us with your use case, as well as what specific layer elements you would want to display with this feature?

**Comment by naftalibeder** [comment]
@ZiZasaurus thanks for the response!

The use case is to display iconography that appears to rotate with the map - for instance, displaying an arrow pointing along a road.

The default behavior of a layer (e.g. a `SymbolLayer`) is to maintain its rotation in screen coordinate space, regardless of the map coordinate space rotation:

![image](https://user-images.githubusercontent.com/2423291/197578655-c5be22fd-fe20-4ed2-b255-611d89b9fdc1.png)

If an expression could use the camera's bearing, then layers could react to that value:

![image](https://user-images.githubusercontent.com/2423291/197578725-72045b56-dd5b-46f8-b67a-1f542be72711.png)

At the moment, the only way to achieve this behavior is to manually update layer styles as the camera's bearing changes. This loses a lot of the performance gain of using expressions.

Please let me know if I can clarify anything else.

**Comment by NiwakaDev** [comment]
@naftalibeder 

Would the following sample code be helpful?
https://github.com/mapbox/mapbox-maps-ios/blob/v10.8.1/Apps/Examples/Examples/All%20Examples/AnimateLayerExample.swift

https://github.com/mapbox/mapbox-maps-ios/blob/v10.8.1/Apps/Examples/Examples/All%20Examples/AnimateLayerExample.swift#L112 :
```
            geoJSON.properties = ["bearing": .number(coordinate.direction(to: nextCoordinate))]
```

https://github.com/mapbox/mapbox-maps-ios/blob/v10.8.1/Apps/Examples/Examples/All%20Examples/AnimateLayerExample.swift#L85-L89 : 
```
        // Get the "bearing" property from the point's feature dictionary,
        // and use that value to determine the rotation angle of the airplane icon.
        airplaneSymbolLayer.iconRotate = .expression(Exp(.get) {
            "bearing"
        })
```

I'm sorry if they're wrong .

**Comment by naftalibeder** [comment]
`iconRotationAlignment` was exactly what I was looking for! Thanks!
