### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AlexaderDNT** [mapbox/mapbox-maps-ios#1677]
## Environment

- Xcode version:
- iOS version: 16.0.2
- Devices affected: IPhone 13 Pro Max
- Maps SDK Version: 10.8.1

I dont know what this is.

![image](https://user-images.githubusercontent.com/64775721/199210106-0a143c60-f853-46c5-9964-3c44b762a9be.png)

**Comment by AlexaderDNT** [comment]
Im not sure, this is in production. Have no more info than firebase.

But i have this crash. When i zoom all out, it crash.

https://user-images.githubusercontent.com/64775721/199238801-aba4cf1f-5335-4077-bcab-ccc84b4b66f3.MOV

**Comment by AlexaderDNT** [comment]
The crash goes away If i remove two SymbolLayer from the map. Is it any restriction for how many SymbolLayer you can add?

**Comment by AlexaderDNT** [comment]
This happens on older phones like iphone 11 and not iphone 14. So i think it is a memory issue. It happens on zoom level 1 to 3. Any fix for problems like this? @ZiZasaurus

**Comment by ZiZasaurus** [comment]
@AlexaderDNT, do you have a minimal sample app that you can provide that reproduces this crash?

**Comment by AlexaderDNT** [comment]
No, but i fixed it. I created more layers with 2000 as a source limit on every layer.

**Comment by AlexaderDNT** [comment]
When i update to 10.9.1  @ZiZasaurus  
Fatal Exception: Bindgen internal error

Fatal Exception: Bindgen internal error
0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0xf9c58 __CFDictionaryCreateGeneric
3  MapboxCoreMaps                 0x385c4 (Missing UUID eb6c9e5648933676b5d6945535786a58)
4  UT                             0x17609b8 @nonobjc MBMStyleManager.setStyleLayerPropertiesForLayerId(_:properties:) (<compiler-generated>)
5  UT                             0x17608e8 protocol witness for StyleManagerProtocol.setStyleLayerPropertiesForLayerId(_:properties:) in conformance MBMStyleManager (<compiler-generated>)
6  UT                             0x175658c closure #1 in Style.setLayerProperties(for:properties:) + 542 (Style.swift:542)
7  UT                             0x1752688 handleExpected<A, B>(closure:) + 1065 (Style.swift:1065)
8  UT                             0x1753dd0 Style.setLayerProperties(for:properties:) + 541 (Style.swift:541)
9  UT                             0x175a0c8 protocol witness for StyleProtocol.setLayerProperties(for:properties:) in conformance Style (<compiler-generated>)
10 UT                             0x1628fe8 Puck2D.updateLayerLocationFastPath() + 255 (Puck2D.swift:255)
11 UT                             0x16289c0 Puck2D.latestLocation.didset + 51 (Puck2D.swift:51)
12 UT                             0x162702c Puck2D.latestLocation.setter + 47 (Puck2D.swift:47)
13 UT                             0x1626f68 closure #1 in Puck2D.isActive.didset + 19 (Puck2D.swift:19)
14 UT                             0x1625470 thunk for @escaping @callee_guaranteed (@unowned InterpolatedLocation) -> (@unowned Bool) (<compiler-generated>)
15 UT                             0x15f9228 closure #1 in ObservableValue.observe(with:) + 27 (ObservableValue.swift:27)
16 UT                             0x15f8d14 ObservableValue.Observer.invokeHandler(with:) + 52 (ObservableValue.swift:52)
17 UT                             0x15f8c40 closure #1 in ObservableValue.notify(with:) + 20 (ObservableValue.swift:20)
18 UT                             0x15f8c7c partial apply for closure #1 in ObservableValue.notify(with:) (<compiler-generated>)
19 libswiftCore.dylib             0xe53b8 Sequence.forEach(_:)
20 UT                             0x15f8bb0 ObservableValue.notify(with:) + 19 (ObservableValue.swift:19)
21 UT                             0x1625350 ObservableInterpolatedLocation.notify(with:) + 21 (ObservableInterpolatedLocation.swift:21)
22 UT                             0x1625f88 protocol witness for ObservableInterpolatedLocationProtocol.notify(with:) in conformance ObservableInterpolatedLocation (<compiler-generated>)
23 UT                             0x16199bc InterpolatedLocationProducer.participate() + 146 (InterpolatedLocationProducer.swift:146)
24 UT                             0x16199e8 protocol witness for DisplayLinkParticipant.participate() in conformance InterpolatedLocationProducer (<compiler-generated>)
25 UT                             0x15e5ee0 MapView.updateFromDisplayLink(displayLink:) + 574 (MapView.swift:574)
26 UT                             0x15e6acc closure #1 in MapView.didMoveToWindow() + 619 (MapView.swift:619)
27 UT                             0x15d0d74 ForwardingDisplayLinkTarget.update(with:) + 12 (ForwardingDispalyLinkTarget.swift:12)
28 UT                             0x15d0dc0 @objc ForwardingDisplayLinkTarget.update(with:) (<compiler-generated>)
29 QuartzCore                     0x28f9c CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
30 QuartzCore                     0x3a8a4 display_timer_callback(__CFMachPort*, void*, long, void*)
31 CoreFoundation                 0x7b820 __CFMachPortPerform
32 CoreFoundation                 0x98d00 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
33 CoreFoundation                 0x9a908 __CFRunLoopDoSource1
34 CoreFoundation                 0x7c13c __CFRunLoopRun
35 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific
36 GraphicsServices               0x1368 GSEventRunModal
37 UIKitCore                      0x3a23d0 -[UIApplication _run]
38 UIKitCore                      0x3a2034 UIApplicationMain
39 SwiftUI                        0x1d1014 OUTLINED_FUNCTION_895
40 SwiftUI                        0x13216c block_copy_helper.1
41 SwiftUI                        0x11b4bc OUTLINED_FUNCTION_901
42 UT                             0x38d7c4 static UTApp.$main() (<compiler-generated>)
43 UT                             0x38d86c main (UTApp.swift)
44 ???                            0x1bc27c960 (Missing)
