### ISSUE TITLE
MapboxMap doesn't return elevation information for visible area

### ISSUE THREAD

**Issue by lpeancovschi** [mapbox/mapbox-maps-ios#1693]
## Environment

- Xcode version: 14.0 (14A309)
- iOS version: 16.0
- Devices affected: iPhone 14 Pro (probably all of them)
- Maps SDK Version: 10.9.0

## Observed behavior and steps to reproduce

1. Load the map and zoom in at a small scale (less than 8) - now you can see that the map reflects correct altitudes on surfaces
2. Try to load elevation data via `MapView`:
```
mapView.mapboxMap.elevation(at: currentLocation)
```
`currentLocation` - is a location within the visible area on screen.

## Expected behavior

Calling `elevation(at:)` should return correct elevation, but instead it returns `nil` for any location within visible region on screen.

**Comment by ZiZasaurus** [comment]
@lpeancovschi thank you for reaching out. When/ how are you trying to obtain the elevation on the map? Perhaps the map has not yet loaded when you're trying to obtain the elevation? I am able to get the elevation to return using the following code: 

```
        mapView.mapboxMap.onEvery(event: .mapLoaded) { _ in
            print("elevation:", self.mapView.mapboxMap.elevation(at: self.mapView.mapboxMap.cameraState.center))
        }
```

**Comment by lpeancovschi** [comment]
Thanks for your reply @ZiZasaurus, 

I still can't extract the elevation data. I created a new project to try it out, here's the code:

```
class ViewController: UIViewController {
    
    internal var mapView: MapView!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let myResourceOptions = ResourceOptions(accessToken: "<token>")
        let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
        mapView = MapView(frame: view.bounds, mapInitOptions: myMapInitOptions)
        mapView.mapboxMap.setCamera(to: CameraOptions(center: CLLocationCoordinate2D(latitude: 57.44326, longitude: 26.40006),
                                                              zoom: 12))
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        mapView.mapboxMap.onEvery(event: .mapLoaded) { _ in
        }
         
        self.view.addSubview(mapView)
        
        let button = UIButton()
        button.translatesAutoresizingMaskIntoConstraints = false
        button.setTitle("Tap me", for: .normal)
        button.addTarget(self, action: #selector(printElevation), for: .touchUpInside)
        
        self.view.addSubview(button)
        
        NSLayoutConstraint.activate([
            button.centerXAnchor.constraint(equalTo: self.view.centerXAnchor),
            button.centerYAnchor.constraint(equalTo: self.view.centerYAnchor)
        ])
    }

    @objc
    func printElevation() {
        print("elevation:", self.mapView.mapboxMap.elevation(at: self.mapView.mapboxMap.cameraState.center))
    }

}
```

The elevation still returns `nil` every time I try to access it... Can you please share your map initialization code?

Thank you

**Comment by lpeancovschi** [comment]
Kind ping @ZiZasaurus,

Would you be able to share your map configuration or suggest if any other config is required?

Thank you 🙏

**Comment by ZiZasaurus** [comment]
@lpeancovschi it doesn't seem as though you are have a raster DEM source added to the map, which is where that elevation data would be coming from. If you add that layer, like in [this example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/TerrainExample.swift) and attempt to find the elevation at a point you should receive elevation data.

**Comment by lpeancovschi** [comment]
That worked, thank you @ZiZasaurus!
