### ISSUE TITLE
Annotation touch events not triggering in v10.10

### ISSUE THREAD

**Issue by JenishKananiLime** [mapbox/mapbox-maps-ios#1697]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

**Comment by ZiZasaurus** [comment]
@JenishKananiLime can you please provide additional information regarding what with the touch events is broken? We introduced the ability to use long press to drag annotations in v10.10. Is the issue with long press recognition or tapping?

**Comment by JenishKananiLime** [comment]
Hi @ZiZasaurus the gesture event callbacks aren't being triggered 

func gestureManager(_ gestureManager: GestureManager, didBegin gestureType: GestureType) {}

  func gestureManager(_ gestureManager: GestureManager, didEnd gestureType: GestureType, willAnimate: Bool) {
    if !willAnimate {
      handleGesture(gestureType: gestureType)
      lastGesture = gestureType
      lastMapCenter = mapView?.mapboxMap.cameraState.center ?? lastMapCenter
    }
  }

  func gestureManager(_ gestureManager: GestureManager, didEndAnimatingFor gestureType: GestureType) {
    handleGesture(gestureType: gestureType)
    lastGesture = gestureType
    lastMapCenter = mapView?.mapboxMap.cameraState.center ?? lastMapCenter
  }

it works on v9 and then upgrading to v10 stops working without any code changes from our side

**Comment by JenishKananiLime** [comment]
@ZiZasaurus doesn't even get fired in the Mapbox library its self, there isn't any code changes we do we just update the library to v10.10 and tap stopps working completely

**Comment by ZiZasaurus** [comment]
@JenishKananiLime thank you for reporting. A fix will be included in the next release.
