### ISSUE TITLE
Using custom tiles in Offline manager

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-maps-ios#1698]
I'm trying to implement the Offline manager in our iOS app (latest version of Mapbox SDK - https://docs.mapbox.com/ios/maps/guides/offline/). This works fine as long as I use tiles hosted in my mapbox account. When I use my own raster tiles (hosted on my server), nothing happens when I try to download the offline maps.

Can you no longer download your own hosted maps for offline use in v10? Or is there some sort of LegacyOffline Manager like in Android to do that?

**Comment by ZiZasaurus** [comment]
@nijs9, Please use the OfflineRegionManager if you would like to use third party tiles. We have an example of its use [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/OfflineRegionManagerExample.swift).
