### ISSUE TITLE
High battery usage while in the background

### ISSUE THREAD

**Issue by mihahoz** [mapbox/mapbox-maps-ios#1704]
## Environment

- Xcode version: 14.1 (14B47b)
- iOS version: 16.1
- Devices affected: All
- Maps SDK Version: v10.9.0

## Observed behavior and steps to reproduce

When a user gives us the "Always" location permission and we use our own [custom location provider](https://docs.mapbox.com/ios/maps/guides/user-location/#custom-location-providers), as described in the developer docs, the app consumes a lot of battery in the background, even though we stop the location updates when the user moves to the background and restart them when he comes back to the foreground. The app requires "Always" permission for some map-unrelated features. This gives us very bad battery statistics (23h in background).

To reproduce, please check my sample project here: https://github.com/mihahoz/mb-background. I modified your sample code for [displaying user's location](https://docs.mapbox.com/ios/maps/examples/tracking-mode/) by adding a custom location provider.

1. Clone the repo
2. Install pods - Mapbox dependency
3. Open workspace
4. Edit Info.plist - enter Mapbox key
5. Setup signing
6. Run the app on the device
7. Give "While in use" location permission and then go to the app's settings and change it to "Always"
8. Start simulating location changes by selecting the "Lake" entry (it's a circular drive). I was not able to reproduce this without moving 
<img width="432" alt="Screenshot 2022-11-09 at 09 10 29" src="https://user-images.githubusercontent.com/34736840/200791309-3c5b61ac-9b56-4e95-af48-3413ccc906a1.png">

9. Put the app in the background
10. Open debug navigator and select "Energy Impact"
11. Leave it running for a minute or two

You will notice that while in the background the app starts using location services, which keeps the app running and thus the system does not suspend it: 

<img width="978" alt="s2" src="https://user-images.githubusercontent.com/34736840/200789439-42fa495b-3120-45b3-96d9-16c534e9298d.png">

If you replace the view controller with the one at the bottom of the demo, which removes the Mapbox view, the issue is no longer present.

## Expected behavior

The map view should respect our custom location provider implementation and not do any location-related actions on its own.

**Comment by ZiZasaurus** [comment]
@mihahoz thank you for reporting. I have brought this to the larger team for investigation and once we have updates we will post them here.

**Comment by OdNairy** [comment]
Thanks for you report. 
After some investigations I can conclude that it working as expected.

**Comment by mihahoz** [comment]
@OdNairy just to be sure, is this the expected behaviour, or have you fixed (changed) this?

**Comment by OdNairy** [comment]
@mihahoz It is an expected behaviour.
