### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fawzirifai** [mapbox/mapbox-maps-ios#1757]
## Environment

- Xcode version: 14.1
- iOS version: iOS 16.0
- Devices affected: iPhone 8 Plus
- Maps SDK Version: 10.6.0

The application has crashed only once.
<img width="1440" alt="Screenshot 2022-11-27 at 2 24 37 PM" src="https://user-images.githubusercontent.com/109214745/204132712-604b840d-0835-480e-a17a-ea90726dcd7d.png">

**Comment by ZiZasaurus** [comment]
@fawzirifai, thank you for reporting. As this has only happened once, can you please attempt to reproduce on the latest version of our SDK, v10.9.1 and let us know if it occurs again?
