### ISSUE TITLE
Migration Issue (MGLUserLocationAnnotationView)

### ISSUE THREAD

**Issue by Lyle-Grandworks** [mapbox/mapbox-maps-ios#1761]
## Environment

- Xcode version: 14
- iOS version: 16.1.1
- Devices affected:
- Maps SDK Version: v10.9.0

## Expected behaviour

MGLUserLocationAnnotationView used to display the Annotation (Pointer Image at User Location)
Called via:
```
extension NavigateViewController: MGLMapViewDelegate {
    func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        if annotation is MGLUserLocation && mapView.userLocation != nil {
            currentLocation = mapView.userLocation
            return CustomUserLocationAnnotation()
        }
        return nil
    }
}
```

## Notes / preliminary analysis
Is there any substitute for this? or alternate way of implementation 
"import Mapbox" in files has been replaced by "import MapboxMaps"
Would appreciate any help/guides to follow.

## Additional links and references

![image](https://user-images.githubusercontent.com/119398515/204462821-c22aa0c3-b001-428f-ba92-fdf054cba189.png)

**Comment by ZiZasaurus** [comment]
@Lyle-Grandworks, please see our location marker examples below: 
- [BasicLocationPulsingExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/BasicLocationPulsingExample.swift)
- [Custom2DPuckExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Custom2DPuckExample.swift)
- [Custom3DPuckExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Custom3DPuckExample.swift)
- [TrackingModeExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/TrackingModeExample.swift)

Additionally, please see our migration guide for v10 [here](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/).

**Comment by ZiZasaurus** [comment]
Closing this ticket, but if you have additional questions regarding this, please feel free to create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
