### ISSUE TITLE
Migration Issue (DrawRoute())

### ISSUE THREAD

**Issue by Lyle-Grandworks** [mapbox/mapbox-maps-ios#1762]
## Environment

- Xcode version: 14
- iOS version: 16.1.1
- Devices affected:
- Maps SDK Version: v10.9.0

## Observed behavior and steps to reproduce
Upgrading Mapbox-iOS-SDK v6.3.0 to MapboxMaps v10.9.0
Unable to find migration code from Mapbox-iOS-SDK v6.3.0 to MapboxMaps v10.9.0
DrawRoute() function Syntax change as MGL Library has been dropped in MapboxMaps v10.9.0.

## Additional links and references
<img width="1162" alt="Screenshot 2022-11-28 at 7 05 55 PM" src="https://user-images.githubusercontent.com/119398515/204462063-b7c740d0-e390-4045-aeca-9c87961e64db.png">

## Notes / preliminary analysis
"import Mapbox" in files has been replaced by "import MapboxMaps"
'MGLPolylineFeature', 'MGLShapeSource', 'MGLLineStyleLayer' along with Style syntax seems to be replaced/removed in the latest version.
Is there any substitute for this? or alternate way of implementation 
Would appreciate any help/guides to follow.

**Comment by ZiZasaurus** [comment]
`MGLPolylineFeature` has been replaced by LineString, `MGLShapeSource` has been replaced by [GeojsonSource](https://docs.mapbox.com/ios/maps/api/10.9.1/Structs/GeoJSONSource.html) and `MGLLineStyleLayer` has been replaced by [LineLayer](https://docs.mapbox.com/ios/maps/api/10.9.1/Structs/LineLayer.html).

For more information on migrating from v6 to v10, you can find the migration guide for the Maps SDK [here](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/).

Please note, as these are product support Issues, in the future, you can create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.

**Comment by Lyle-Grandworks** [comment]
Noted, Thanks.
This really helped out. Much appreciated @ZiZasaurus

**Comment by ZiZasaurus** [comment]
@Lyle-Grandworks you're most welcome!
