### ISSUE TITLE
Migration Issue (showWaypoints)

### ISSUE THREAD

**Issue by Lyle-Grandworks** [mapbox/mapbox-maps-ios#1763]
## Environment

- Xcode version: 14
- iOS version: 16.1.1
- Devices affected:
- Maps SDK Version: v10.9.0

## Observed behaviour and steps to reproduce
Currently unable to find the Syntax change for showWaypoints in the process of Upgrading Mapbox-iOS-SDK v6.3.0 to MapboxMaps v10.9.0
Unable to find migration code from Mapbox-iOS-SDK v6.3.0 to MapboxMaps v10.9.0

## Expected behaviour
To show waypoint after route generation

## Notes / preliminary analysis
Is there any substitute for this? or alternate way of implementation 
Would appreciate any help/guides to follow.

## Additional links and references

![image](https://user-images.githubusercontent.com/119398515/204465421-c205d795-4c19-4624-88bc-a15e95c24d4c.png)

**Comment by ZiZasaurus** [comment]
Please take a look at our Advanced Navigation example [here](https://docs.mapbox.com/ios/navigation/examples/advanced/), which demonstrates how to add and display waypoints along your route. 

Additionally, you can find the migration guide for the Navigation SDK [here](https://docs.mapbox.com/ios/navigation/guides/migrate-to-v2/).

**Comment by Lyle-Grandworks** [comment]
Thank you so much for the quick and helpful response @ZiZasaurus.
I'm now using: @IBOutlet weak var mapView: NavigationMapView!
Upon doing this and following the implementation, I have faced a new error.

I'm currently unable to set the MapStyle with a URL via "MapInitOptions".
Is there another implementation for this?or is there any documentation or example I could follow up on.
Much appreciated.

**Comment by ZiZasaurus** [comment]
@Lyle-Grandworks, for setting/ changing the map style, please take a look at our documentation on [customizing the map style ](https://docs.mapbox.com/ios/navigation/guides/map-and-camera/maps/#customize-the-map-style).
