### ISSUE TITLE
Migration Issue (removeOverlays )

### ISSUE THREAD

**Issue by Lyle-Grandworks** [mapbox/mapbox-maps-ios#1764]
## Environment

- Xcode version: 14
- iOS version: 16.1.1
- Devices affected:
- Maps SDK Version: v10.9.0

## Observed behaviour and steps to reproduce
Currently unable to find the Syntax change for removeOverlays in the process of Upgrading Mapbox-iOS-SDK v6.3.0 to MapboxMaps v10.9.0

## Expected behaviour
Remove MapView Overlays

## Notes / preliminary analysis
Is there any substitute for this? or alternate way of implementation 
Would appreciate any help/guides to follow.

## Additional links and references

![image](https://user-images.githubusercontent.com/119398515/204465137-9dc95ae8-1714-46fd-a863-b4b3f27c05d5.png)

**Comment by Lyle-Grandworks** [comment]
Noted, Thanks.
This really helped out. Much appreciated @ZiZasaurus

**Comment by ZiZasaurus** [comment]
You're most welcome!
