### ISSUE TITLE
NavigationMapView ('NSUnknownKeyException')

### ISSUE THREAD

**Issue by Lyle-Grandworks** [mapbox/mapbox-maps-ios#1778]
## Environment

Xcode version: 14
iOS version: 16.1.1
Devices affected:
Maps SDK Version: v10.9.0

## Observed behavior and steps to reproduce

Currently unable to run NavigationMapView.
While migrating from v6 to v10

## Expected behavior

The Map is supposed to load but the App crashes

## Notes / preliminary analysis
Trying to use NavigationMapView via Story board, but App crashes as soon as the NavigationMapView loads.
@IBOutlet weak var mapView: NavigationMapView!
Any help would be appreciated.

## Additional links and references
<img width="805" alt="Screenshot 2022-12-06 at 1 32 00 PM" src="https://user-images.githubusercontent.com/119398515/205855146-35de48e2-993b-4803-916d-d2d840790160.png">
<img width="1440" alt="Screenshot 2022-12-06 at 1 35 00 PM" src="https://user-images.githubusercontent.com/119398515/205855165-3e398b4f-6eb3-413a-a905-bdc76b24676a.png">
<img width="1069" alt="Screenshot 2022-12-06 at 1 35 41 PM" src="https://user-images.githubusercontent.com/119398515/205855175-4aae79cb-e726-4abb-bc4c-dfafcab51fb3.png">

**Comment by ZiZasaurus** [comment]
@Lyle-Grandworks your view controller may have the wrong class in your xib or you may have a bad connection in your xib. Please check your storyboard connections. 

As this is more of a product support Issue, in the future can you please create a support ticket at https://support.mapbox.com/hc/en-us/ and our support team will be happy to get you the answers you need.
