### ISSUE TITLE
Mapbox memory leaks at deinitialisation leading to app crash by Apple watchdog

### ISSUE THREAD

**Issue by jumbopilot** [mapbox/mapbox-maps-ios#1795]
## Environment

- Xcode version: Version 14.1 (14B47b)
- iOS version: 16.2
- Devices affected: iPhone13 Mini
- Maps SDK Version: 10.6.0

## Action
I do programmatically **display and dismiss** one and the same **Mapview** (SwiftUI) a second time in a separate view that overlays the basic one.

The display and dismiss of the 2nd MapView happens e.g. every 10 seconds.
Basic map features being used:

PolylineAnnotationManager (multiple)
CircleAnnotationManager (multiple)
PointAnnotationManager (multiple)
sources are either geojson (GeoJSONSource) or own CLLocation arrays (FeatureCollection)
queryRenderedFeatures
CameraLocationConsumer
OfflineManager
various map styles
viewAnnotations
additional map layers (dispatched in DispatchQueue.global(qos: .background).async { ... } )

## Observed behavior and steps to reproduce
Mapbox seems to be making **excessive memory allocations every time a map view is presented**, but **not releasing** them when the views are dismissed. We ran a few different **memory allocation traces** and was consistently able to have the app **allocate** well over **1GB of memory** (even while the user location keeps unchanged since first map load) before it was killed. This issue also occurs on iOS 15, so it is not a new Apple issue with iOS 16+, but intrinsic to Mapbox V10.

It takes ~3-5 min until the app is killed. The crash file shows like
———
Exception Type: EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: FRONTBOARD 2343432205
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<domain.subdomain.appstring>:9900 exhausted real (wall clock) time allowance of 10.00 seconds
———

Consequently, this section of the crash report indicates the main thread of the application did not respond within 10 seconds. The excessive memory use is causing the app to appear sluggish, and eventually the map-view logic on the main thread becomes so delayed that it does not respond to the watchdog in time, and is sent a SIGKILL signal to be terminated.

Issue is easily reproducible by display and quit of mapview using SwiftUI wrapper.

## Expected behavior
**Mapbox releases dynamically allocated memory** once a mapview data is deinitialised.

## Notes / preliminary analysis
Xcode debugger and instruments show large number of unreleased data allocation not being used any more, leading to excessive memory consumption and app latency/freeze/crash.

## Additional links and references
Here are a couple of links that hopefully help to identify and reduce the sources of the excessive memory growth:
https://developer.apple.com/documentation/xcode/gathering-information-about-memory-use
https://developer.apple.com/documentation/xcode/making-changes-to-reduce-memory-use

**Comment by ZiZasaurus** [comment]
@jumbopilot are you able to reproduce this behavior on the most recent version of our SDK, v10.10?

**Comment by jumbopilot** [comment]
@ZiZasaurus I do confirm the memory consumption and especially the memory release has been improved with v10.10. 

Record of Mapbox's memory consumption over time while repeatedly instantiating/dismissing a second mao view:
<img width="997" alt="Screenshot 2022-12-18 at 08 11 00" src="https://user-images.githubusercontent.com/43632124/208286384-22b77d7d-11b0-4a9b-b459-393c34224c2d.png">

Didn't notice in the release notes that the memory management has been improved since v10.6.1.
Thanks for your hint/resolution.

**Comment by jumbopilot** [comment]
Tested with Mapbox V11: this issue is no more reproducible with V11.
