### ISSUE TITLE
badResponseStatusCode(401) Unable to download 

### ISSUE THREAD

**Issue by baihualinxin** [mapbox/mapbox-maps-ios#1796]
## Environment

- Xcode version: 13.4.1
- iOS version:ios 15
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce
open Apps/Apps.xcworkspace  Unable to work mapbox framework

failed downloading 'https://api.mapbox.com/downloads/v2/mapbox-events-ios/releases/ios/packages/1.0.10/MapboxMobileEvents.zip' which is required by binary target 'MapboxMobileEvents': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/23.2.1/MapboxCommon.zip' which is required by binary target 'MapboxCommon': badResponseStatusCode(401)
failed downloading 'https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/10.10.0/MapboxCoreMaps.xcframework-dynamic.zip' which is required by binary target 'MapboxCoreMaps': badResponseStatusCode(401)

**Comment by vladpre92** [comment]
Hi @baihualinxin . Probably you didn't configure the access token properly: https://docs.mapbox.com/help/getting-started/access-tokens.
Please see: https://github.com/mapbox/mapbox-maps-ios/issues/797

**Comment by wiulma** [comment]
same error here. I follow all the previous instructions, but I get this error while pod install is running.
`
[!] Error installing MapboxCommon
[!] /usr/bin/curl -f -L -o /var/folders/36/vvy8x2194lv3f0ywc1v8bp080000gn/T/d20230204-99391-fdqio0/file.zip https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/23.2.1/MapboxCommon.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    39    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
`
any suggestions? thanks :-)

**Comment by StephenHodgson** [comment]
I'm also getting this error. I had this up and running for some time and was onboarding a new dev when we ran into this. 

Our token hasn't changed and we've created the .netrc file in their home directory.

**Comment by StephenHodgson** [comment]
okay after some playing around we realized that it was _how_ we were creating the file. We had just created a new file in VS Code and saved it in the home directory as `~/.netrc` but didn't work. 

We had to delete the file and recreate it in the terminal. It had the _same exact information_ but this creation method does something special to the file encoding or something 🤷‍♂️ 

```
echo "machine api.mapbox.com" > ~/.netrc
echo "login mapbox" >> ~/.netrc
echo "password <INSERT API TOKEN>" >> ~/.netrc
```

**Comment by Sang-Nguyen-Sunny** [comment]
> okay after some playing around we realized that it was _how_ we were creating the file. We had just created a new file in VS Code and saved it in the home directory as `~/.netrc` but didn't work.
> 
> We had to delete the file and recreate it in the terminal. It had the _same exact information_ but this creation method does something special to the file encoding or something 🤷‍♂️
> 
> ```
> touch ~/.netrc
> echo "machine api.mapbox.com" > ~/.netrc
> echo "login mapbox" >> ~/.netrc
> echo "password <INSERT API TOKEN>" >> ~/.netrc
> ```

I am also facing the same problem as above

**Comment by pjleonard37** [comment]
Thanks for sharing these reports. 

> I am also facing the same problem as above
@Sang-Nguyen-Sunny -- were you able to resolve this issue by creating the file in terminal as well? Or are you still unable to download here?

**Comment by Sang-Nguyen-Sunny** [comment]
> as

<img width="1233" alt="Screenshot 2023-02-09 at 15 23 36" src="https://user-images.githubusercontent.com/15792841/217756741-39f9c7a3-ebf1-486e-968c-4a51449c04cb.png">
@pjleonard37 I just updated the macos from Monterey to Ventura 13.2, then .netrc has edited many times but still not working.

**Comment by OdNairy** [comment]
@Sang-Nguyen-Sunny It is required to have a valid private token to download binary dependencies. 
Can you please confirm that your token starting with `sk.`?

**Comment by Vasant-Patel** [comment]
Having the same issue with new M2 pro mac mini with cocoapods 1.11.3
Tried everything .. created new secret key on mapbox with proper READ permissions and also tried recreating .netrc file with terminal and verified that its in correct location but still keep getting that same error




```
[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/p4/80zkydnj2lsc_37z85ps7ct40000gn/T/d20230209-4424-1bqgfyp/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.4.1/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    39    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
```

**Comment by StephenHodgson** [comment]
I was having an issue on my Mac mini Intel. I don't think it's a device chip architecture problem.

**Comment by Vasant-Patel** [comment]
> I was having an issue on my Mac mini Intel. I don't think it's a device chip architecture problem.
> 
> I think it has something to do with the line endings or the encoding of the file. [See my comment above about specifics](https://github.com/mapbox/mapbox-maps-ios/issues/1796#issuecomment-1416930249).
> 
> After some playing around we were able to get it to work eventually.

I can confirm that this fixed the issue .. no idea why but it did

**Comment by huszzsolt** [comment]
In my case was a missing end of line on the `password` (last) line of `.netrc`

**Comment by rouuuge** [comment]
> In my case was a missing end of line on the `password` (last) line of `.netrc`

@huszzsolt thanks!!!!

**Comment by RolandTalvarComodule** [comment]
> okay after some playing around we realized that it was _how_ we were creating the file. We had just created a new file in VS Code and saved it in the home directory as `~/.netrc` but didn't work.
> 
> We had to delete the file and recreate it in the terminal. It had the _same exact information_ but this creation method does something special to the file encoding or something 🤷‍♂️
> 
> ```
> touch ~/.netrc
> echo "machine api.mapbox.com" > ~/.netrc
> echo "login mapbox" >> ~/.netrc
> echo "password <INSERT API TOKEN>" >> ~/.netrc
> ```

Fixed for me, thanks!

**Comment by heroly** [comment]
> > okay after some playing around we realized that it was _how_ we were creating the file. We had just created a new file in VS Code and saved it in the home directory as `~/.netrc` but didn't work.
> > We had to delete the file and recreate it in the terminal. It had the _same exact information_ but this creation method does something special to the file encoding or something 🤷‍♂️
> > ```
> > touch ~/.netrc
> > echo "machine api.mapbox.com" > ~/.netrc
> > echo "login mapbox" >> ~/.netrc
> > echo "password <INSERT API TOKEN>" >> ~/.netrc
> > ```
> 
> I am also facing the same problem as above

Thanks for the tip! It finally worked. I originally used touch ~/.netrc and then open .netrc to add the details using text edit but that didn't work.

**Comment by rlindgren** [comment]
If after following all of the above instructions and exhausting all other possible reasons for this to fail (missing Downloads:read scope, wrong file permissions [0600], invalid/missing public key, etc) this is still not working for you, try quitting Xcode, re-opening and then resetting package cache again...... 🙃
