### ISSUE TITLE
[Question] Is it possible to draw annotation with an altitude?

### ISSUE THREAD

**Issue by cukingpro** [mapbox/mapbox-maps-ios#180]
Hi,
Can I draw markers, lines with altitude in 3d mode?
Just like this image.
Thank you
<img width="896" alt="Screen Shot 2021-03-15 at 14 17 36" src="https://user-images.githubusercontent.com/9702625/111117229-d7168580-8599-11eb-9412-d2eb29b11066.png">

**Comment by julianrex** [comment]
This is not currently available. I have added this as a feature request.

**Comment by txaiwieser** [comment]
Is there a workaround to implement this behavior?

**Comment by cukingpro** [comment]
> Is there a workaround to implement this behavior?

I use another map library.

**Comment by txaiwieser** [comment]
> > Is there a workaround to implement this behavior?
> 
> I use another map library.

Can you say which one?

**Comment by cukingpro** [comment]
> > > Is there a workaround to implement this behavior?
> > 
> > 
> > I use another map library.
> 
> Can you say which one?

It's HERE maps.

**Comment by OdNairy** [comment]
We are now rolling out altitude rendering support (checkout the `zOffset` property). 
Supported objects are:
- [`FillLayer`](https://docs.mapbox.com/ios/maps/api/11.9.0/documentation/mapboxmaps/filllayer/fillzoffset)
- [`SymbolLayer`](https://docs.mapbox.com/ios/maps/api/11.9.0/documentation/mapboxmaps/symbollayer/symbolzoffset)
- [`LineLayer`](https://docs.mapbox.com/ios/maps/api/11.9.0/documentation/mapboxmaps/linelayer/linezoffset)
- [`PolygonAnnotation`](https://docs.mapbox.com/ios/maps/api/11.9.0/documentation/mapboxmaps/polygonannotation/fillzoffset).
