### ISSUE TITLE
Terrain enabled, gesture transitions are smooth on first gesture swipe.. bumpy if current transition is interrupted  

### ISSUE THREAD

**Issue by Gnative** [mapbox/mapbox-maps-ios#1809]
## Environment

- Xcode version: 14,1
- iOS version: 15 - 16
- Devices affected: All
- Maps SDK Version: Any v10 versions

## Observed behavior and steps to reproduce

When **Terrain** is enabled on the first gesture swipe, to move to a new location, the resulting transition is smooth.. if you interrupt this transition with another gesture swipe then the transition becomes bumpy.. as if effected by the elevation data. Letting the transition come to a complete stop then then re-swiping the transition is smooth again.  

https://user-images.githubusercontent.com/1758875/207674518-25c0fc64-3133-4d1d-9d32-d8492653e298.mov

## Expected behavior

Always be smooth..  I guess if a higher elevation that the current camera elevation is hit then raise to that elevation

**Comment by ZiZasaurus** [comment]
Thank you for reporting this behavior. I have brought this to our larger team for investigation and will update you as soon as anything changes.

**Comment by Gnative** [comment]
Looks like this was resolved in a recent update - closing
