### ISSUE TITLE
Support Cluster inspection methods

### ISSUE THREAD

**Issue by lunarmayor** [mapbox/mapbox-maps-ios#182]
## New Feature
It doesn't seem like I can access the cluster inspection methods at this point. would love to be able to get the expansion zoom and leaves from a cluster id

## Why
Clusters are pretty hard to work with if you can't get any information about them. Not sure if these methods are not available or I can't find them in the documentation

**Comment by mmackh** [comment]
Is there a way to disable clustering with the current release?

**Comment by ZiZasaurus** [comment]
@lunarmayor our [API reference](https://docs.mapbox.com/ios/maps/api/10.0.0-rc.8/Structs/GeoJSONSource.html#/s:10MapboxMaps13GeoJSONSourceV7clusterSbSgvp) outlines the properties available (cluster_Id and point_count, point count abbreviated and cluster). For additional reference, please take a look at our Symbol Clustering example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SymbolClusteringExample.swift). 

For cluster inspection you can use the [feature extension API](https://docs.mapbox.com/ios/maps/api/10.0.0-rc.8/Classes/MapboxMap.html#/s:10MapboxMaps19MapFeatureQueryableP05queryD9Extension3for7feature9extension0J5Field4args10completionySS_4Turf0D0VS2SSDySSypGSgys6ResultOySo010MBMFeatureG5ValueCs5Error_pGctF).

To disable clusters, you would set the clustering properties directly on the source using `source.cluster = false`

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
