### ISSUE TITLE
Setting custom delegate for tracking location updates removes puck from the map

### ISSUE THREAD

**Issue by IvanBogdantsev** [mapbox/mapbox-maps-ios#1830]
## Environment

- Xcode version: 14.0.1
- iOS version: 15
- Devices affected: Iphone 12 Pro
- Maps SDK Version: 10

## Observed behavior and steps to reproduce

Setting custom delegate for LocationProvider with func provided by Mapbox SDK removes puck from the MapView.
Custom delegate however receives location updates: 

`func locationProvider(_ provider: MapboxMaps.LocationProvider, didUpdateLocations locations: [CLLocation]) {
       print(locations[0].coordinate)
    }`

I suppose that setting delegate isn't going to do everything by itself and there are some extra steps to avoid this behaviour, but your documentation obviously lacks this information. 

There isn't event much to add to it, it is pretty straightforward: custom delegate = no puck on the map.

Also I apologise for marking this issus as a "bug", but it is definitely not a feature demand. 

Thanks in advance for your help

**Comment by evil159** [comment]
@IvanBogdantsev There is a note about setting custom delegate in here: https://github.com/mapbox/mapbox-maps-ios/blob/8b79a407b658aceaadefa92bd3f43c55f7ccb3c4/Sources/MapboxMaps/Location/LocationProvider.swift#L24-L28

If you want to receive location updates I suggest using `LocationManager.addLocationConsumer(newConsumer:)`
https://github.com/mapbox/mapbox-maps-ios/blob/8b79a407b658aceaadefa92bd3f43c55f7ccb3c4/Sources/MapboxMaps/Location/LocationManager.swift#L58-L59
