### ISSUE TITLE
FillLayer set gradient color as fillColor

### ISSUE THREAD

**Issue by rohan-59** [mapbox/mapbox-maps-ios#1832]
## New Feature

I am trying to set a gradient color to FillLayer added on Map but can not find any way right now. Can you please let me know if there is a way to add gradient color?

**Comment by pjleonard37** [comment]
Hi @rohan-59 -

Are you still running into this issue or have you resolved it on your side?

**Comment by rohan-59** [comment]
Hi @pjleonard37, I haven't found any solution so went with one colour instead of gradient. But would love to get a solution if you have.

**Comment by pjleonard37** [comment]
Hi @rohan-59 - 

Depending on your use case, fillPattern may be an option for you (see [here](https://docs.mapbox.com/ios/maps/api/10.12.2/Structs/FillLayer.html#/s:10MapboxMaps9FillLayerV11fillPatternAA5ValueOyAA13ResolvedImageOGSgvp)). If you need additional assistance with implementation, please reach out to our Support team: https://support.mapbox.com/hc/en-us.
