### ISSUE TITLE
[Question] Do you support iOS background modes during TileStore.loadTileRegion

### ISSUE THREAD

**Issue by marclefrancois** [mapbox/mapbox-maps-ios#1833]
Put simply, we want to make sure the downloads started by a user completes even if he puts our app in the background before downloads are completed. 

Is this already taken care of by the SDK ?

Thanks

**Comment by ZiZasaurus** [comment]
While we do not handle this out of the box within the SDK, you can request it yourself using https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask

**Comment by marclefrancois** [comment]
Thanks for the confirmation, that was my backup plan

**Comment by marclefrancois** [comment]
Hi @ZiZasaurus 
After some quick investigation, beginbackgroundtask does not cut it. On recent iOS version, it is limited to 30 secondes of background execution time in good conditions.

Any way to access the `URLSession` to provide it with a `URLSessionConfiguration` configured for background execution ?

**Comment by pjleonard37** [comment]
Closing in favor of https://github.com/mapbox/mapbox-maps-ios/issues/1889
