### ISSUE TITLE
Setting custom delegate for tracking location updates removes puck from the map (re-raised )

### ISSUE THREAD

**Issue by IvanBogdantsev** [mapbox/mapbox-maps-ios#1836]
## Environment

I re-raise the issue #1830 closed by @evil159. 
I appreciate your answer, however I'am not blind yet not to notice this mention of LocationConsumer: 

https://github.com/mapbox/mapbox-maps-ios/blob/8b79a407b658aceaadefa92bd3f43c55f7ccb3c4/Sources/MapboxMaps/Location/LocationProvider.swift#L24-L28

If this could possibly solve my issue, you would have not seen it here. 
Can you please tell me, how would I be able to manually set puck location on the map if all properties of any importance are private/internal? I guess here is the range of code that manages puck location on the map: 

https://github.com/mapbox/mapbox-maps-ios/blob/6681e9bf0c2ce707fcb7407f6d44b5fb664abac0/Sources/MapboxMaps/Location/Puck/Puck2D.swift#L11-L21

If I add location consumer, what would I do with these updates to render the puck if I have no access to Puck class neither directly neither via PuckManager etc. I searched through the documentation/opensource and found no way to get out of this problem. 

I also do not understand the point of enclosing delegate methods, this makes nearly impossible to get a good reactive delegate because of that. 

I am sorry, maybe I miss en evident solution, but I think documentation should cover such topics.

Don't close the issue until we can find the solution of any kind

Have a good day.

P.S. you can close the issue of course if there is no solution whatsoever

**Comment by evil159** [comment]
Hi @IvanBogdantsev, it seems I misunderstood your intent initially. If you want to provide custom location for the location puck, you'd need to:
* Implement a custom location provider by conforming to `LocationProvider` protocol - e.g. https://github.com/mapbox/mapbox-maps-ios/blob/6681e9bf0c2ce707fcb7407f6d44b5fb664abac0/Apps/Examples/Examples/All%20Examples/NavigationSimulator.swift#L5
* Pass the location provider to the SDK with `LocationManager. overrideLocationProvider(with:)`, e.g.: https://github.com/mapbox/mapbox-maps-ios/blob/6681e9bf0c2ce707fcb7407f6d44b5fb664abac0/Apps/Examples/Examples/All%20Examples/NavigationSimulatorExample.swift#L47
* Make sure that your location provider emits at least one event of https://github.com/mapbox/mapbox-maps-ios/blob/6681e9bf0c2ce707fcb7407f6d44b5fb664abac0/Sources/MapboxMaps/Location/LocationProviderDelegate.swift#L12

Let me know if the steps above work for your case.

**Comment by IvanBogdantsev** [comment]
Thanks @evil159 ! Please do not close this issue for now, I am going to give you the feedback ASAP. I thought of it as a possible solution, but was hoping for a less bulky one. However if this is indeed gonna get solve my problem I will be quite happy. 
Thank you for the help ! 
Have a good a day.

**Comment by IvanBogdantsev** [comment]
@evil159  I apologise for the delay, I just tried your solution and it works like charm, thank you!

**Comment by pjleonard37** [comment]
Closing as resolved. Thanks for flagging.
