### ISSUE TITLE
Map not showing up when running UITests on CI

### ISSUE THREAD

**Issue by EugeneVovkDroneUp** [mapbox/mapbox-maps-ios#1837]
## Environment

- Xcode version: 14
- iOS version: 16.2
- Devices affected:
- Maps SDK Version: 10.10.1

After migrating to V10, the map is not displayed when passing UITests for CI (Bitrise), locally everything works fine, on V6 there was no such problem

**Comment by ZiZasaurus** [comment]
Our examples tests, which are pretty much that, seem to be working fine. Can you provide some additional information? Are there any errors in the logs, map/styleLoadingErrors?

**Comment by EugeneVovkDroneUp** [comment]
@ZiZasaurus  I don’t see  map/styleLoadingErrors errors in the logs, do I need to do something additional on Bitrise to display maps?

**Comment by EugeneVovkDroneUp** [comment]
@ZiZasaurus Any updates?

**Comment by EugeneVovkDroneUp** [comment]
Hello team, I'm still waiting for help on this issue

**Comment by pjleonard37** [comment]
Hi @EugeneVovkDroneUp - 

As everything seems to be working fine locally this is likely an issue with your CI setup. Are you using devices that support Metal?

**Comment by EugeneVovkDroneUp** [comment]
Hi @pjleonard37 -

For tests on CI, we use the simulator `iPhone 12 Pro Max`

**Comment by OdNairy** [comment]
@EugeneVovkDroneUp Maps v10 was migrated from OpenGL to Metal API. Unfortunately most CI services doesn't have an access to the Metal device which technically leads to the missing map view. 
Internally we use a [special function](https://github.com/mapbox/mapbox-maps-ios/blob/a151b620f660fa016fe2a5829336db6e7ce45d6e/Tests/MapboxMapsTests/Helpers/XCTestCase%2BGuardForMetalDevice.swift#L4-L9) to skip unsupported tests on simulator's run and run tests on the iOS devices. 
There are also early reports that Apple Silicon based VM's has GPU support.
As a workaround you can launch self-hosted mac mini to enable Metal in Unit and UI tests.
