### ISSUE TITLE
'Apps.xcworkspace' is locked and does not support editing after following relevant README.md for Examples.

### ISSUE THREAD

**Issue by djryanash** [mapbox/mapbox-maps-ios#1841]
## Environment

- Xcode version: 14.1 (14B47b)
- iOS version: 16.1
- Devices affected: Mac & iPhone Simulator on Mac
- Maps SDK Version: 10.10.1

## Observed behavior and steps to reproduce

1.    I followed all instructions to install Mapbox here: https://docs.mapbox.com/ios/maps/guides/install/
2.   I ran the application and I saw see a map on the screen.
3.   I read the README.md here: https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/README.md
4.   I went back to my project and navigated to the same README.md in the Package Dependencies tree using  Project Navigator.
5.   I right-clicked on the 'Apps' folder in the 'MapboxMaps 10.10.1' Package and selected 'Show in Finder'.
6.   I double-clicked the 'Apps' folder in Finder and then double-clicked the 'Apps.xcworkspace' file to open it.
7.   The file opened in Xcode with the following alert: '“Apps Workspace” is locked for editing and you will not be able to save your changes. “Apps Workspace” is currently locked because it does not support editing. <<OK>>'
8.  I clicked <<OK>>
9.   Another alert popped up: 'The file “Apps.xcworkspace” could not be unlocked. The item does not support editing. <<OK>>'
10. I clicked <<OK>>
11.  The alert from 9 above popped up again.
12. I typed Cmd-R to Run.
13. The alert from 9 above popped up again.
14. Xcode said "build failed".
15. The alert from 9 above popped up again.
16. The alert from 9 above popped up again.
17. The alert from 9 above popped up again.
18. The alert from 9 above popped up again.
19. The alert from 9 above popped up again.
20. The alert from 9 above popped up again.
21. I also tried the following commands from the 'Product->Scheme' menu in Xcode, but didn't know what I was doing, so quickly abandoned that route: 'Choose Scheme', 'Select New Scheme' , 'Edit Scheme', etc.
22. I also tried to drag-and-drop the 'Apps.xcworkspace' file into my project but the icon always shows up as red and doesn't seem to work.
23. I went 'File->Add Files to "MapboxExample"...' and was able to add 'Apps.xcworkspace' but when I ran the project, it didn't seem to make any difference and none of the examples were available for me.

<img width="1440" alt="Screenshot 2023-01-11 at 3 20 22 PM" src="https://user-images.githubusercontent.com/103509041/211752381-511a5b13-8036-46f6-ac0f-e76f40003de5.png">

<img width="1440" alt="Screenshot 2023-01-11 at 3 23 49 PM" src="https://user-images.githubusercontent.com/103509041/211752434-7239f4bd-c900-4e72-a95b-dd61b8e28618.png">

## Expected behavior

After following the instructions in the applicable 'README.md', particularly this part, "Next, open `Apps/Apps.xcworkspace` and select the Examples scheme to build and run the Examples app.", I expected that I would be able to open the 'Apps.xcworkspace' file and be able to load up the examples and have a look how they are put together and test out the different functionalities.

My expectations are based on the instructions in the 'README.md file' here: https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/README.md

## Notes / preliminary analysis

Being new to development in general, I'm not clear how to figure this out.  After following the instructions to the 'T', I was not able to load up the examples.  The lack of clarity in the instructions has made this – what in my estimation should a relatively simple task – difficult to complete.

Please be kind and remember: we were all newbies once. :)

**Comment by djryanash** [comment]
I tried it again now and it still doesn't work.  Either I'm dumb or the instructions are not clear.

**Comment by OdNairy** [comment]
@djryanash We do not lock any files in the repo, most likely there are some issues on your computer/filesystem.
You also can check Lock status for certain files from the repo by going to the Finder, selecting file/folder, Cmd+I and observe the Locked checkmark.
