### ISSUE TITLE
Add hsl support to StyleColor

### ISSUE THREAD

**Issue by paulsUsername** [mapbox/mapbox-maps-ios#1847]
## New Feature

Add hsl support to StyleColor

## Why
Hsl is convenient for colors, and is heavily used in Mapbox own documentation.

**Comment by tobrun** [comment]
I agree, have created an internal task to track this feature request

**Comment by maios** [comment]
Hi @paulsUsername, this is now supported in [v11.0.0-beta.4](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.0.0-beta.4).
