### ISSUE TITLE
Problem with UserTrackingMode.follow when GPS is enabled (Problem)

### ISSUE THREAD

**Issue by mpasdan** [mapbox/mapbox-maps-ios#1850]
I develop an app in Xamarin forms iOS by using the Mapbox API v. 6.4.1. I have a problem with the property UserTrackingMode. If it sets to UserTrackingMode.follow then it follows the location of the user and and it zooms to 22 zoomlevel, that is something I want to prevent. From the other hand, if I set the property to UserTrackingMode.None then the zoomLevel takes the zoom input I give but doesn't follow the location of the user and I do not know what to do, thank you for your help. I appreciate it a lot!! I want the map follows the user's location but also don't zoom in when I use UserTrackingMode.follow, there is any way to prevent that?

**Comment by pjleonard37** [comment]
Hi @ruslanSanarkhin --

This repo is for v10+ of the Mapbox iOS Maps SDK. As this report is for an earlier version, [this](https://github.com/mapbox/mapbox-gl-native-ios) repo is a better place for your report. As such, I'll close this issue.

Do note that v6.4.1 of the SDK is no longer under development. Additionally, that project will cease to receive updates, including compatibility and bugfixes, after April 4, 2023.

We recommend upgrading to the latest version of our SDK: v10.10.1, which is developed in this repo. We have a migration guide on our documentation page [here](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/) to assist with migrating your app.
