### ISSUE TITLE
Scrolling Anti-Meridian Causes Invalid bounds.contains(forPoint Results

### ISSUE THREAD

**Issue by Joseph-Sam** [mapbox/mapbox-maps-ios#1887]
## Environment

- Xcode version:  14.2
- iOS version: 16.2
- Devices affected: iPhone 13 Pro
- Maps SDK Version: 10.10.1 (main)

## Observed behavior and steps to reproduce

Wrapping around the anti-meridian causes `bounds.contains(forPoint` to return true when it's not in fact true.

## Expected behavior

contains(forPoint should be returning false for a point the entire time when scrolling from Hawaii to China. However, it's returning true for some sections of this scroll.

## Notes / preliminary analysis

Pre V10 versions of map box did not have this issue when using `mapView.convert(inputCoord, toPointTo: mapView).x > mapView.frame.width` and `mapView.convert(inputCoord, toPointTo: mapView).x < 0`.

**Comment by pjleonard37** [comment]
Hi @Joseph-Sam -- 

Thanks for reporting. We're investigating this issue on our side.

**Comment by Joseph-Sam** [comment]
Hi @pjleonard37 do you have an update on this issue? I'm revisiting this feature and don't want to have to roll back to v6.
Thank you!

**Comment by pjleonard37** [comment]
Hi @Joseph-Sam - 

I wasn't able to reproduce the issue your are describing locally with `bounds.contains` in our latest version: 10.13.1. Can you share a code sample which reproduces the issue?

**Comment by baleboy** [comment]
Closing as non-reproducible, feel free to reopen if you can reproduce with the latest version and add reproduction steps, thank you!
