### ISSUE TITLE
Empty MGLMapView on screen 

### ISSUE THREAD

**Issue by ruslanSanarkhin** [mapbox/mapbox-maps-ios#1890]
## Environment

- Xcode version: 13.4.1
- iOS version: iOS 15.5
- Devices affected: all real devices - test on iPhone 7 Plus, iPhone X
- Maps SDK Version: 6.4.1

## Observed behavior and steps to reproduce

Opening MapView is empty. Only white screen without grids and map objects. No changes in code. Problem found about 5-6 days ago. Stanger that it work of simulators in Xcode.

**Comment by pjleonard37** [comment]
Hi @ruslanSanarkhin -- 

This repo is for v10+ of the Mapbox iOS Maps SDK. As this report is for an earlier version, [this](https://github.com/mapbox/mapbox-gl-native-ios) repo is a better place for your report. I see that you have already opened a similar issue there: https://github.com/mapbox/mapbox-gl-native-ios/issues/666. As such, I'll close this issue in favor of that one. 

Do note that v6.4.1 of the SDK is no longer under development. Additionally, that project will cease to receive updates, including compatibility and bugfixes, after April 4, 2023.

We recommend upgrading to that latest version of our SDK: v10.10.1, which is developed in this repo. We have a migration guide on our documentation page [here](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/) to assist with migrating your app.
