### ISSUE TITLE
ViewAnnotation renders inconsistently

### ISSUE THREAD

**Issue by brendanw** [mapbox/mapbox-maps-ios#1924]
## Environment

- Xcode version: 14.2
- iOS version: 16.3.1
- Devices affected: iphone 14 simulator, iphone 13 pro
- Maps SDK Version: 10.11.1

## Observed behavior and steps to reproduce
ViewAnnotation does not render unless you fling the map after clearing previously added point annotations.

I have attached a screen recording from the forked version of the Debug app in this repository, as well as the forked code. 

Steps to reproduce:

1. load map with a large set of PointAnnotation's
2. tap PointAnnotation and observe associated ViewAnnotation
3. tap `Simulate filter` button which removes all existing PointAnnotations from the annotation manager and replaces with a smaller set of PointAnnotation's.
4. tap PointAnnotation. observe that no ViewAnnotation is displayed.
5. fling the globe around the world once. observe that ViewAnnotation associated with previously tapped PointAnnotation is now displayed.

Video recording: https://basebeta-east.s3.amazonaws.com/mapboxViewAnnotationIssue.gif

Code for reproducing: https://github.com/brendanw/mapbox-maps-ios/blob/main/Apps/DebugApp/DebugApp/DebugViewController.swift

## Expected behavior

ViewAnnotation should always appear when PointAnnotation is tapped. Odd that the ViewAnnotation only shows up after a fling of the globe.

## Notes / preliminary analysis

I've played around with `setNeedsDisplay()` and `presentsWithTransaction` to no avail.

## Additional links and references
Video recording: https://basebeta-east.s3.amazonaws.com/mapboxViewAnnotationIssue.gif

Code for reproducing: https://github.com/brendanw/mapbox-maps-ios/blob/main/Apps/DebugApp/DebugApp/DebugViewController.swift

**Comment by persidskiy** [comment]
Hi @brendanw, thanks for the report!
I checked out your branch and tried to replicate it but had no luck - view annotation always appear when expected.

https://user-images.githubusercontent.com/1527181/223777435-a828901a-246f-4cb5-b668-c16a35afcc87.mp4

The only change I made is used the `mapbox://styles/mapbox/outdoors-v12` as  style StyleURI, because I have no access to your custom style. Theoretically this can affect behavior.

Can you check if it helps for you?

**Comment by baleboy** [comment]
Hi @brendanw did this help?

**Comment by brendanw** [comment]
@persidskiy @baleboy Apologies for the delay in responding. I found a fix after posting the issue by calling `removeAnnotationManager` and re-adding the annotation manager in between each filter operation. And I was using the sample app to debug, so y'all likely ran with my last commit which has the fix.

I've pushed the reproduction to a specific branch that does not have my hacky workaround: 
https://github.com/brendanw/mapbox-maps-ios/tree/reproduce

PR diff between reproduction code and how I resolved:
https://github.com/brendanw/mapbox-maps-ios/pull/1/files

I am going to see if I can reproduce w/ `mapbox://styles/mapbox/outdoors-v12` style and on latest mapbox version (10.13.1) and will report back.

**Comment by brendanw** [comment]
I updated the mapbox style to `mapbox://styles/mapbox/outdoors-v12` on the `reproduce` branch and can still reproduce on mapbox ios version ~10.11.0

**Comment by brendanw** [comment]
Ok just pulled latest mapbox code (10.13.1) and rebased my `reproduce` branch and can still reproduce the issue.

You can reproduce by building ios sample at
https://github.com/brendanw/mapbox-maps-ios/tree/reproduce

using the same steps I shared in the original video
https://basebeta-east.s3.amazonaws.com/mapboxViewAnnotationIssue.gif

**Comment by brendanw** [comment]
just tested this example on v11 here -> https://github.com/brendanw/mapbox-maps-ios/tree/repro

I can no longer reproduce this issue as of v11 rc.1

thanks!
