### ISSUE TITLE
Snapshotter crashes when trying to generate multiple snapshots

### ISSUE THREAD

**Issue by vladpre92** [mapbox/mapbox-maps-ios#1928]
## Environment

- Xcode version: 14.2
- iOS version: 16.2
- Devices affected: All
- Maps SDK Version: 10.11.1

## Observed behavior and steps to reproduce

Using a shared `Snapshotter`, we reproduced the following scenarios:

1. Start generating 1 snapshot: snapshot is generated.
2. Start generating 2 snapshots (for loop): snapshot 1 cancelled, snapshot 2 cancelled.
3. Start generating 3+ snapshots (for loop): app crashes.

## Expected behavior

1. Start generating 1 snapshot: snapshot is generated.
2. Start generating 2 snapshots (for loop): snapshot 1 cancelled, snapshot 2 is generated.
3. Start generating 3+ snapshots (for loop): snapshot 1 cancelled, snapshot 2 cancelled, last snapshot is generated.

## Notes / preliminary analysis
1. Simultaneous access to any `Snapshotter` instance is not safe.
2. `Mapbox 10.11.1` documentation states that when you call `start(overlayHandler:completion:)` on a `Snapshotter` instance, any pending work is cancelled. From our tests, this is not the actual behaviour. When we try to generate 2 snapshots, both of the processes are cancelled.
3. If is not used correctly, the `Snapshotter` can be a crash generator.

## Additional links and references

https://docs.mapbox.com/ios/maps/api/10.11.1/Classes/Snapshotter.html

I attached a demo project that reproduces the above mentioned problems. 
`ViewController.swift` is the class containing the tests. 
Of course you must provide a valid public token for the `Info.plist` file.

[DemoMapboxSnapshotterCrash.zip](https://github.com/mapbox/mapbox-maps-ios/files/10960749/DemoMapboxSnapshotterCrash.zip)

Thank you!

**Comment by OdNairy** [comment]
Thank for your contribution and very detailed report. 
I will add it to the backlog and report back when fix will arrive.

**Comment by maios** [comment]
hi @vladpre92, I'm happy to inform that we have addressed this issue in our latest [v10.16.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.16.1) release. Please check it out and let us know if the same issue still persists by reopening this.

**Comment by wladuardo** [comment]
Did you load this changes to main branch? I am facing this issue and using code from beta-test on main branch

**Comment by maios** [comment]
> Did you load this changes to main branch? I am facing this issue and using code from beta-test on main branch

Hi @wladuardo, it should be included in the latest main now, along with our beta release [v11.0.0-beta.5](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.0.0-beta.5)

**Comment by wladuardo** [comment]
I'm trying to create a Snapshot using Snapshotter. I'm creating two Snapshots simultaneously. However, the snapshotter.start function still gives an error "snapshot canceled." I also tried not creating multiple snapshots simultaneously and attempted to create just one, but I still get the same error.
I'm using the latest available beta version.

**Comment by maios** [comment]
We don't allow multiple snapshot, if you attempt to start a snapshot, any pending snapshot will get cancelled. Could you provide some code to reproduce your issue 
>  I also tried not creating multiple snapshots simultaneously and attempted to create just one, but I still get the same error.
