### ISSUE TITLE
The question of the completeness of the map of China

### ISSUE THREAD

**Issue by liamfend** [mapbox/mapbox-maps-ios#1933]
## Environment

- Xcode version: 14
- iOS version: ios9-ios16.2
- Devices affected:
- Maps SDK Version:5.9

## Expected behavior

I would like to show it like this, because Chinese policy requires this red dotted line
<img width="1164" alt="Screenshot 2023-03-22 at 19 32 51" src="https://user-images.githubusercontent.com/7407249/226893579-54c44039-3460-4158-ba74-0389dedc2b9f.png">

If the official method is not provided, how can I do it? Otherwise we will have to choose Chinese map vendors again, which has some workload for us

**Comment by iOSBoy** [comment]
@liamfend   Hi are you solved this issue. i met the same issue,could you help me to solve this issue, thanks

**Comment by iOSBoy** [comment]
@liamfend  Thank you very much, your answer is helped me a lot
