### ISSUE TITLE
Centering camera between coordinates bug

### ISSUE THREAD

**Issue by jhoanarango** [mapbox/mapbox-maps-ios#1950]
## Environment

- Xcode version: 14.3
- iOS version: 15 +
- Devices affected: All
- Maps SDK Version: 10.12.2

## Observed behavior and steps to reproduce

_The following code is only used for centering the camera, other code such as adding the annotations and poly lines is not shown on this example and they are working properly._

Centering the map in between a list of coordinates is not working in all cases. I am using the following coordinates as an example.

``` swift
/// Los Angeles Airport
let LAX = CLLocationCoordinate2D(latitude: 33.94, longitude: -118.40)

/// Honolulu Airport 
let HNL = CLLocationCoordinate2D(latitude: 21.31, longitude: -157.92)

/// Sydney Airport
let SYD = CLLocationCoordinate2D(latitude: -33.94, longitude: 151.177)

/// Ota Airport Japan
let HND = CLLocationCoordinate2D(latitude: 35.55, longitude: 139.77)
```

To set the center of the camera between the coordinates I do the following. 

```swift

/// Using only LAX - HNL
let padding = UIEdgeInsets(top: 200, left: 100, bottom: 220, right: 45)
let camera  = mapView.mapboxMap.camera(for: [LAX, HNL], padding: padding, bearing: 0, pitch: nil)
mapView.camera.ease(to: camera, duration: 0.2)

```

The result of this example works as expected, it centers the camera between LAX and HNL. 

<img width="383" alt="Screenshot 2023-04-12 at 1 29 16 PM" src="https://user-images.githubusercontent.com/14069813/231537475-e65e81ce-277d-414f-9719-c29ebf2a75b2.png">

However, when using the coordinates from HNL to SYD, the camera fails to center. The poly lines and annotation work as expected, they are drawn on the correct coordinates, but the user is forced to center the camera manually, instead of the map doing it on its own.

```swift

/// Using only HNL - SYD
let padding = UIEdgeInsets(top: 200, left: 100, bottom: 220, right: 45)
let camera  = mapView.mapboxMap.camera(for: [HNL, SYD], padding: padding, bearing: 0, pitch: nil)
mapView.camera.ease(to: camera, duration: 0.2)

```

This is the result: Fails to center automatically 👎🏻 

<img width="364" alt="Screenshot 2023-04-12 at 1 35 49 PM" src="https://user-images.githubusercontent.com/14069813/231538667-5517f80e-ef8e-40c1-8430-f9888ed9bba3.png">

And this is after scrolling to center the map to show the "route". 

<img width="361" alt="Screenshot 2023-04-12 at 1 37 05 PM" src="https://user-images.githubusercontent.com/14069813/231538900-8d9ac429-b383-4878-b1c5-001893cdeb7a.png">

As you can see, the camera fails to center when the route is between Hawaii and Australia. 

I've also done the following test between these coordinates. 

1. Ota Japan to Sydney - It Centers 👍🏻 
2. Ota Japan to Los Angeles - It Fails 👎🏻 
3. Los Angeles to Sydney - It Fails 👎🏻 

## Expected behavior

The expected behavior is to center between the coordinates given to the camera. However, it seems like every time is asked to center between 2 points that crosses the pacific ocean it breaks. Some scenarios such as LAX - HNL behaves as expected. But if it goes further than that it breaks. 

## Conclusion

If someone else can replicate this, or has a solution for it please post it on here and is greatly appreciated.

**Comment by jhoanarango** [comment]
I am wondering if anyone is working on looking into these issues?

**Comment by baleboy** [comment]
I can confirm that we are able to reproduce the issue and are looking into it.

**Comment by jhoanarango** [comment]
> I can confirm that we are able to reproduce the issue and are looking into it.

Perfect, thank you! Please let me know if there is a walk around or fix soon.

**Comment by baleboy** [comment]
@jhoanarango not yet, I will update as soon as our team has had a chance to look into the issue.

**Comment by jhoanarango** [comment]
> @jhoanarango not yet, I will update as soon as our team has had a chance to look into the issue.

Perfect, thank you very much.

**Comment by endanke** [comment]
@jhoanarango one workaround you can try is to wrap the negative longitudes around the globe before passing them to calculate the camera bounds.
So in the case of Honolulu you can add 360 degrees to `-157.92`, so you'd pass it as `CLLocationCoordinate2D(latitude: 21.31, longitude: 202.92)` and that way the bound calculations will use the shortests path between them.
I tried it out and it seems to work, but please confirm if it works for you too.

**Comment by jhoanarango** [comment]
@endanke, the workaround works. Thank you.
