### ISSUE TITLE
Build mapbox-gl-native old SDK for deployment on targets above iOS 12.

### ISSUE THREAD

**Issue by HamidrezaJamshidi** [mapbox/mapbox-maps-ios#1951]
I want to export and build an old SDK as both dynamic and static in a new version of Xcode and iOS. I followed the instructions, but encountered an error when using the command

**make iframework FORMAT=static BUILDTYPE=Release**

<img width="1180" alt="Screenshot 1402-01-29 at 12 07 30" src="https://user-images.githubusercontent.com/59960693/232721592-c4edf5dc-540e-4754-b630-b6976a0c44b4.png">

<img width="1106" alt="Screenshot 1402-01-29 at 12 11 40" src="https://user-images.githubusercontent.com/59960693/232722836-c39f44fd-5f66-4e9b-a29d-19c476b49222.png">

How to export and fix it?

**Comment by pjleonard37** [comment]
Hi @HamidrezaJamshidi -- 

On April 4, 2023 the [old SDK](https://github.com/mapbox/mapbox-gl-native-ios) was sunsetted, and it will no longer receive updates. Please see this note from that repo's [readme](https://github.com/mapbox/mapbox-gl-native-ios#mapbox-maps-sdks-for-ios-and-macos): 

> Mapbox maintains this repo to address bug fixes and security vulnerabilities. Please note that this project will cease to receive updates, including compatibility and bugfixes, after April 4, 2023. [Here is a helpful guide](https://docs.mapbox.com/ios/maps/guides/) about our latest SDK features and how to migrate to our latest version.

As such, I'm going to close out this issue. If you identify an issue with the current version of the SDK (this repo) please open a new issue.
