### ISSUE TITLE
Pan gesture doesn't work as expected

### ISSUE THREAD

**Issue by chuhlomin** [mapbox/mapbox-maps-ios#1953]
## Environment

- Xcode version: 14.3 (14E222b)
- iOS version: 16.4 (20E247)
- Devices affected: iPhone 14, ?
- Maps SDK Version: 10.12.2

## Observed behavior and steps to reproduce

Default map pan gesture works only when you try pan on a straight line, but not if I hold the finger, move map around and then trying to pan. See attached video. This behavior is different from MapBox GL JS, Apple Maps and Google Maps.

## Expected behavior

Map should register a pan gesture and "scroll".

## Additional links and references

https://user-images.githubusercontent.com/3620471/233807147-9dfa3d34-e046-4ad2-9da6-7516751694ff.MP4

**Comment by OdNairy** [comment]
Thanks for the report, 
Ticket added to the backlog.

**Comment by OdNairy** [comment]
@chuhlomin Good news – the issue was fixed in the 10.13.0-beta.1.
Can you please confirm that?

**Comment by chuhlomin** [comment]
Yep, can confirm it is fixed in 10.13.0-beta.1
Thank you!
