### ISSUE TITLE
Annotation.value.geometry?.geoJSONObject problem

### ISSUE THREAD

**Issue by IhorStasiv** [mapbox/mapbox-maps-ios#1954]
## New Feature
I propose to rework the retrieval of coordinates from annotations

<- Convert geoJSONObject to a variable with coordinates that will be easily accessed ->

## Why
<-  I draw a lot of annotations on the map. And when the user changes the position of the map, I need to delete those annotations that have gone beyond the screen, and draw new coordinates that are now on the screen. Also, I need to check whether some of the annotations that have already been drawn are still in the user's field of vision, if so, then I leave them, and therefore cannot use the RemoveAll method.
  I am trying to extract the coordinates from the annotation.value.geometry?.geoJSONObject property and this property does not parse as JSON. The description of this property returns the string "[geometry(Turf.Geometry.point(Turf.Point(coordinates: __C.CLLocationCoordinate2D(latitude: 38.4745195, longitude: -5.5650095), foreignMembers: [:])))]".
And in order to get the coordinates, I have to do this

                guard let geoJSONDescription = annotation.value.geometry?.geoJSONObject.expressionArguments.description else { continue }
        
                if let range = geoJSONDescription.range(of: "__C.CLLocationCoordinate2D(latitude: ") {
                    let startIndex = range.upperBound
                    let endIndex = geoJSONDescription.range(of: ",", range: startIndex..<geoJSONDescription.endIndex)!.lowerBound
                    let latitudeString = geoJSONDescription[startIndex..<endIndex]
                    let latitude = Double(latitudeString)
        
                    let longitudeRange = geoJSONDescription.range(of: "longitude: ", range: endIndex..<geoJSONDescription.endIndex)!
                    let longitudeStartIndex = longitudeRange.upperBound
                    let longitudeEndIndex = geoJSONDescription.range(of: ")", range: longitudeStartIndex..<geoJSONDescription.endIndex)!.lowerBound
                    let longitudeString = geoJSONDescription[longitudeStartIndex..<longitudeEndIndex]
                    let longitude = Double(longitudeString)
        
                    if let latitude = latitude, let longitude = longitude {
                        print("Latitude: \(latitude), Longitude: \(longitude)")
                    }
                }
                
 If you could convert this inconsistency to a regular <Coordinates> variable, it would improve the lives of many I'm sure.
 Or I could be wrong, do you have any way to get the coordinates from the annotation in another way, then I will be happy if you share it, thanks.
 ->

**Comment by OdNairy** [comment]
@IhorStasiv `Annotation/geometry` is an enum of the `Turf.Geometry` type. To get access to the point coordinate you have to unwrap case value:

```swift
    func test(annotation: Annotation) {
        if case let .point(point) = annotation.geometry {
            print(point.coordinates.latitude, point.coordinates.longitude)
        }
    }

```

**Comment by IhorStasiv** [comment]
Aw thanks for the help -_-
