### ISSUE TITLE
touchesEnded on MapView not invoked

### ISSUE THREAD

**Issue by ngerdzhikov** [mapbox/mapbox-maps-ios#1960]
## Environment

- Xcode version: 14.2
- iOS version: 16.2
- Devices affected: All
- Maps SDK Version: 10.13.1

## Observed behavior and steps to reproduce

Overriding the `touchesEnded` for `MapView` class either by subclassing or by extension on the `MapView`
`touchesEnded` never called.

For example `touchesBegan` and `touchesMoved` are called as expected.

## Expected behavior

`touchesEnded` to be called.

## Notes / preliminary analysis

To reproduce I created a new project, added MapBox as dep and a simple ViewController as follows

```
import UIKit
import MapboxMaps

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let myResourceOptions = ResourceOptions(accessToken: "pk.someAccessToken")
        let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
        let mapView = MapView(frame: view.frame, mapInitOptions: myMapInitOptions)
//        let mapView = CustomMapView(frame: view.frame, mapInitOptions: myMapInitOptions)
        
        mapView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
        view.addSubview(mapView)
    }
}

class CustomMapView: MapView {
    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        print("touchesEnded") // doesn't work
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        print("touchesBegan") // works
    }
}


extension MapView {
    open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        print("touchesBegan") // works
    }
    
    open override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        print("touchesEnded") // doesn't work
    }
}
```

## Additional links and references

**Comment by persidskiy** [comment]
Hi @ngerdzhikov, thank you for the report!

You observe the default behavior of UIKit which cancels touches when `UIGestureRecognizer` recognizes the gesture. In your example the `touchesCancelled` will be called instead.

If you want the `touchesEnded` to be called, you can configure it:
```swift
mapView.gestureRecognizers?.forEach { 
  $0.cancelsTouchesInView = false
}
```
