### ISSUE TITLE
ViewportStatusObserver, mapView.viewport.addStatusObserver not working

### ISSUE THREAD

**Issue by ngerdzhikov** [mapbox/mapbox-maps-ios#1961]
## Environment

- Xcode version: 14.2
- iOS version: 16.2
- Devices affected: All
- Maps SDK Version: 10.13.1

## Observed behavior and steps to reproduce

subclass ViewportStatusObserver
Add status observer to mapView.
Move map around.
subclass protocol method `viewportStatusDidChange` not invoked.

## Expected behavior

`viewportStatusDidChange` to be invoked.

## Notes / preliminary analysis
Use the following code to reproduce:
```
import UIKit
import MapboxMaps

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let myResourceOptions = ResourceOptions(accessToken: "pk.someAccessToken")
        let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
        let mapView = MapView(frame: view.frame, mapInitOptions: myMapInitOptions)
        
        let viewportListener = ViewportListener()
        mapView.viewport.addStatusObserver(viewportListener)
        
        mapView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
        view.addSubview(mapView)
    }
}

class ViewportListener: ViewportStatusObserver {
    func viewportStatusDidChange(from fromStatus: MapboxMaps.ViewportStatus, to toStatus: MapboxMaps.ViewportStatus, reason: MapboxMaps.ViewportStatusChangeReason) {
        print(fromStatus)
        print(toStatus)
        print(reason)
    }
}

```

**Comment by evil159** [comment]
@ngerdzhikov The `ViewportStatusObserver`'s `viewportStatusDidChange(from:to)` method will be invoked if you will take viewport(check out the example [here](https://github.com/mapbox/mapbox-maps-ios/blob/b6e67c9502b8aaee661302ca0b5d39256920f188/Apps/Examples/Examples/All%20Examples/ViewportExample.swift)). 
May I ask what kind of data you are trying to obtain with this? E.g. if you are after camera position you can subscribe to the `.cameraChanged` event:
```swift
mapView.mapboxMap.onEvery(event: .cameraChanged) {  event in
    print(event.payload)
}

**Comment by ngerdzhikov** [comment]
I needed the .cameraChanged event exactly. Thank you.
