### ISSUE TITLE
Can't install on SPM(Swift Package Manager)

### ISSUE THREAD

**Issue by croc0909** [mapbox/mapbox-maps-ios#1962]
## Environment

- Xcode version: 14.3
- iOS version: 15.4 16.4
- Devices affected: Macbook Pro
- Maps SDK Version: 10.13.1

## Observed behavior and steps to reproduce

i try to install this package on my project 

but Xcode show me the Error message

![Screenshot 2023-05-17 at 10 30 14 AM](https://github.com/mapbox/mapbox-maps-ios/assets/44914582/48fbee7e-ea8d-477e-bdf8-72b671c656e3)

![Screenshot 2023-05-17 at 10 30 49 AM](https://github.com/mapbox/mapbox-maps-ios/assets/44914582/ef556aef-60dc-4949-bfea-3dd520a2b42c)

**Comment by pjleonard37** [comment]
Hi @croc0909 --

Have you correctly configured your credentials (see guide [here](https://docs.mapbox.com/ios/maps/guides/install/#configure-credentials))? It looks like you may need to add a secret token to you `.netrc` file.

**Comment by jm3rt3ns** [comment]
We are experiencing this issue as well; what we have done:
1. created .netrc file with contents as described (secret token), 0600 permissions, in home directory
2. set permissions on scope of token to Download:Read and placed secret access id in .netrc file
3. add variable MBXAccessToken with public token to the build variables in project
4. add package with URL https://github.com/mapbox/mapbox-navigation-ios.git and setting up to major version 10.13.1
5. receive fatal 401 error pulling package

We have tried moving the .netrc file, adding additional scopes, resetting the package cache and removing the derived data folder

running Xcode 14.3

**Comment by jm3rt3ns** [comment]
For anyone experiencing this issue after going through all the troubleshooting steps, restarting Xcode may resolve this issue. 🙃

**Comment by croc0909** [comment]
thanks for everyone, I did what you said

created .netrc file with contents as described (secret token), 0600 permissions, in home directory

 1. Fire up Terminal
 2. cd ~ (go to the home directory),
 3. touch .netrc (create file)
 4. open .netrc 
 5. placed token id  in the .netrc file 
 
![Screenshot 2023-05-19 at 9 56 30 AM](https://github.com/mapbox/mapbox-maps-ios/assets/44914582/a594b8c9-5de7-4753-bc47-fe8fc3b693ba)

6. back to Xcode, use SPM to download again, i see this message

![Screenshot 2023-05-19 at 9 48 42 AM](https://github.com/mapbox/mapbox-maps-ios/assets/44914582/2c0d7a57-d75f-4b9e-ba63-cb7f840b94bd)

7. it's work !

![Screenshot 2023-05-19 at 9 59 47 AM](https://github.com/mapbox/mapbox-maps-ios/assets/44914582/1d8957d5-6ffc-4afc-b98a-3e9687153e92)

**Comment by pjleonard37** [comment]
I'm glad to see this worked out! 🎉
