### ISSUE TITLE
Setting MGLMapboxMetricsEnabled Doesn't Toggle Events

### ISSUE THREAD

**Issue by JackMoseley2001** [mapbox/mapbox-maps-ios#1964]
## Environment

- Xcode version: 14.2
- iOS version: Any
- Devices affected: Any
- Maps SDK Version: 10.12.0

## Observed behavior and steps to reproduce

- Set MGLMapboxMetricsEnabled to false using `UserDefaults.standard.set(false, forKey: "MGLMapboxMetricsEnabled")`
- Events still being sent to `events.mapbox.com` despite being toggled off
- Event type: `appUserTurnstile`
- Note: same occurs using the inbuilt attribution button

![HTTP Requests](https://github.com/mapbox/mapbox-maps-ios/assets/10659397/ff77c2eb-b333-4b3f-b556-d930105c640c)

## Expected behavior

Telemetry events should be toggled off, with no events being sent back to Mapbox Events to honour the user's decision.

## Notes / preliminary analysis

- Is this a bug? What classes as metrics?
- Noticed that data sent included userIds, OS versions, device models which may not want to be shared from users
- Haven't observed any other events other than `appUserTurnstile` whilst using both `mapbox-maps-ios` and `mapbox-navigation-ios`

## Additional links and references

Attribution documentation for toggling metrics: https://docs.mapbox.com/help/getting-started/attribution/#mapbox-maps-sdk-for-ios

Thank you 🙏

**Comment by evil159** [comment]
@JackMoseley2001 `appUserTurnstile` is not a part of telemetry, it is used to count user sessions, the metadata included to the event is used to correctly count a session(e.g. to ignore multiple requests from the same userId within a certain period).

Telemetry events are not being sent either when user opts out from the attribution dialog or when setting false to the corresponding user default configuration option.
