### ISSUE TITLE
How to find the LatLngBounds in Map using Camera Center and Zoom level

### ISSUE THREAD

**Issue by arslankaleem7229** [mapbox/mapbox-maps-ios#1966]
I am trying to find a way in which I want to get LatLngBounds using Camera Center and zoom level. In short I want to get an area that is visible on screen to send a request to API. But I am unable to find that. eg topLeft, topRight, bottomLeft, bottomRight

**Comment by evil159** [comment]
@arslankaleem7229 You can get bounds of the current viewport using [`MapboxMap.coordinateBounds(for:)`](https://docs.mapbox.com/ios/maps/api/10.13.1/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC16coordinateBounds3forSo013MBMCoordinateE0CSo6CGRectV_tF), e.g.:
```swift
mapView.mapboxMap.coordinateBounds(for: mapView.bounds)
```
