### ISSUE TITLE
Annotations seem empty

### ISSUE THREAD

**Issue by emretekince** [mapbox/mapbox-maps-ios#197]
## Environment

- Xcode version: 12.4
- iOS version: 14
- Devices affected:
- Maps SDK Version: 10.0.0-beta.15

## Observed behavior and steps to reproduce
Annotations are added on styleFullyLoaded event but it shows empty after 10 sec of runtime.

`struct Map: UIViewRepresentable {
    var myPlaneCoords: CLLocationCoordinate2D
    
    private let mapView = MapView(with: .zero, resourceOptions:  ResourceOptions(accessToken: "xxx"), styleURL: .custom(url: URL(string: "xxx")!))
    
    
    func makeUIView(context: UIViewRepresentableContext<Map>) -> MapView {
        print("makeUIView")
        mapView.cameraManager.setCamera(to: CameraOptions(center: myPlaneCoords, zoom: 14))
        DispatchQueue.main.asyncAfter(deadline: .now() + 10) {
            print("annotations delayed", mapView.annotationManager.annotations)
        }
        mapView.on(.mapLoadingFinished) { (event) in
            print("mapLoadingFinished")
            let res =  mapView.annotationManager.addAnnotation(myPlane)
            print(res)
        }
        
        mapView.on(.styleLoadingFinished) { (event) in
            print("styleLoadingFinished")
        }
        
        mapView.on(.styleFullyLoaded) { (event) in
            print("styleFullyLoaded")
            let res =  mapView.annotationManager.addAnnotation(myPlane)
            print(res)
        }
        
        
        mapView.update { (mapOptions) in
            mapOptions.ornaments.showsScale = false
        }
        
        return mapView
    }
 }
    `
**Console output**
styleLoadingFinished
styleFullyLoaded
success(true)
styleFullyLoaded
failure(MapboxMaps.AnnotationManager.AnnotationError.annotationAlreadyExists(Optional("Annotation has already been added.")))
mapLoadingFinished
failure(MapboxMaps.AnnotationManager.AnnotationError.annotationAlreadyExists(Optional("Annotation has already been added.")))
annotations delayed [:]

## Expected behavior

Annotations shouldn't be empty

## Notes / preliminary analysis

Sometimes it shows them in delayed function maybe I'm adding them in the wrong event?

**Comment by macdrevx** [comment]
Hi @emretekince, thanks for sharing this feedback. 

Can you try only adding the annotation on the `.mapLoadingFinished` event to see if that fixes the issue?

Also, it looks like you're using SwiftUI, so you might be interested in our [SwiftUI example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SwiftUIExample.swift) if you haven't already seen it.

**Comment by macdrevx** [comment]
This is probably due to the issue fixed in https://github.com/mapbox/mapbox-maps-ios/pull/246

This will go out in our next release. @emretekince if you're using SPM or CocoaPods and would like to try out the fix, you can point to commit c10c5712660976acecac9fc1981711bf5a38eadf and give it a try. Please reopen this issue if you find that it's still happening (either in the next release or when using that commit).
