### ISSUE TITLE
WatchOS Support

### ISSUE THREAD

**Issue by faaizdaglawala** [mapbox/mapbox-maps-ios#1970]
I need to use map with polylines in WatchOS. I have seen watch app in AppStore which is doing same thing [WorkoutDoors](https://apps.apple.com/us/app/workoutdoors/id1241909999?platform=iphone).
how can I achieve this using Mapbox?

**Comment by OdNairy** [comment]
WatchOS doesn't support Metal-based rendering so it's not possible to have user interactible MapView on it. 
But you can use [Snapshotter](https://docs.mapbox.com/ios/maps/api/10.13.1/Classes/Snapshotter.html) class to generate map images with all power of Mapbox features.
