### ISSUE TITLE
Do we support display like this red dotted line?

### ISSUE THREAD

**Issue by iOSBoy** [mapbox/mapbox-maps-ios#1971]
## Environment

- Xcode version: 14.3
- iOS version: above iOS14
- Devices affected: All
- Maps SDK Version: 10.1

## Additional links and references

<img width="1164" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/11255978/d5db3d09-1e0a-4df9-850a-4dbeaff55f67">

**Comment by OdNairy** [comment]
You can use [LineLayer.lineDasharray](https://docs.mapbox.com/ios/maps/api/10.13.1/Structs/LineLayer.html#/s:10MapboxMaps9LineLayerV13lineDasharrayAA5ValueOySaySdGGSgvp) to render dashed lines.
<img width="1009" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/735178/241dd01d-21ef-4206-8405-33d3bd5501d7">

**Comment by iOSBoy** [comment]
@OdNairy  Hi  Thank for your reply,I want to know if we can support china map completeness show the national boundaries like this map 
<img width="1202" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/11255978/2a80d3d0-5e87-4086-a074-d27bdb2a4510">

**Comment by OdNairy** [comment]
Well, I'm not familiar with China-specific features in Mapbox, there are might be some styles that has that lines out of the box. However, you can make it in runtime by adding an custom GeoJSON source to draw that dashed line.

**Comment by iOSBoy** [comment]
@OdNairy  Tank you very much help , i find the same issue [1933](https://github.com/mapbox/mapbox-maps-ios/issues/1933) ,it shows that we should get another map sdk to solve this issue? but  i can't find any info about of this sdk, 
Could you please help  provide some information about this sdk . thank so much.

**Comment by sbma44** [comment]
hi @iOSBoy, Mapbox styling can accommodate any territorial depiction you need. It's just a question of getting the data into one of your data sources and then configuring your style to display it the way you'd like. As @OdNairy points out, this can be accomplished through the SDK, but it would more commonly be done with a style definition. We provide a default worldview that's works with our default styles to meet this and other expectations of Chinese audiences. You can try it out here: https://demos.mapbox.com/boundaries-explorer/?country=US&layer=adm1&worldview=CN#3.5/12.72/110.65

For more information on using worldviews, please see here: https://docs.mapbox.com/help/glossary/worldview/

**Comment by iOSBoy** [comment]
hi @sbma44  Thank you very much for your detailed reply,  Based on the information you provided ,I know how to solve this problem, thanks again.
