### ISSUE TITLE
Draggable annotation with current drag state and current position on map while dragging

### ISSUE THREAD

**Issue by sravan-poripireddy** [mapbox/mapbox-maps-ios#1972]
**New Feature**
Allow dragging annotations without having to perform a long press gesture and provide updates (location coordinate) on where the annotation is moving and state of it like begin, moving, ended.

**Why**
We have a feature where user can select a region on map by tapping and creating polygon, also can update selected region by moving vertices of the polygon. The shape of the polygon should be updated accordingly when the vertices are moved by the user.

**Comment by evil159** [comment]
Hi @sravan-poripireddy, thank you for bringing this up! We have it on our roadmap to add annotation drag state callbacks in the upcoming releases.
As for dragging annotations without a long press - it is done this way to avoid map pan gesture interfering with the pan gesture tracking annotation dragging. 
As an option you could implement the desired behavior using a custom pan gesture recognizer, I put together some sample code for you as a reference: [DebugViewController.swift.zip](https://github.com/mapbox/mapbox-maps-ios/files/11652370/DebugViewController.swift.zip)
