### ISSUE TITLE
Release Xcframework binary format for Mapbox

### ISSUE THREAD

**Issue by kingnight** [mapbox/mapbox-maps-ios#1973]
Release these Mapbox binary with  Xcframework format
MapboxCommon.xcframework
MapboxCoreMaps.xcframework
MapboxMaps.xcframework
MapboxMobileEvents.xcframework
Turf.xcframework

**Comment by OdNairy** [comment]
XCFrameworks are available for download from the Mapbox Docs website ([link](https://docs.mapbox.com/ios/maps/guides/install/)). It is a _Direct download_ option
<img width="942" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/735178/14f8a9d4-ade7-4297-a652-60c8ba8052b9">

**Comment by OdNairy** [comment]
@kingnight What version of SDK you received? I can download the latest 10.13.1 stable version.
