### ISSUE TITLE
Can't build on M2 Mac

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#1975]
## Environment

- Xcode version: 14.3
- iOS version: N/A
- Devices affected: Simulator
- Maps SDK Version: 10.13.1

## Observed behavior and steps to reproduce

When trying to build for the simulator on an M2 Macbook, I get the error

Build failed because MapboxMaps.swiftmodule is missing a required architecture. Would you like to build for Rosetta instead?

Can you please add the M2 architecture?  I need the simulator build for App Store screenshots, running tests, and debugging tablets.

**Comment by persidskiy** [comment]
@akirmse Hi, thank you for the report!

Can you please share the steps you take to reproduce this issue?

**Comment by OdNairy** [comment]
Cannot reproduce
![image](https://github.com/mapbox/mapbox-maps-ios/assets/735178/fb5dd44a-770b-4294-8f6b-4bf162fdadc2)

**Comment by akirmse** [comment]
I have Mapbox added as an SPM package.  Simply trying to compile my app brings up the error dialog.  It gives me the option of compiling for Rosetta, which works, but is not ideal.

**Comment by OdNairy** [comment]
Are you trying to build an iOS simulator target? What is about Generic iOS device?

**Comment by akirmse** [comment]
Yes, I'm building for iOS simulator targets.

**Comment by OdNairy** [comment]
Can you build your app with `xcodebuild` and share the full build log here? I also need log both for iOS simulator and an iOS device

**Comment by akirmse** [comment]
I haven't built from the command line before, so I'm not sure that I'm doing this right.  Here are logs that both succeeded.  (I had to zip them to stay under the max attachment size.)

```
xcodebuild -configuration Debug -workspace ios/Peakbagger/Peakbagger.xcworkspace -scheme Peakbagger -sdk iphoneos build

xcodebuild -configuration Debug -workspace ios/Peakbagger/Peakbagger.xcworkspace -scheme Peakbagger -sdk iphonesimulator build
```
[logs.zip](https://github.com/mapbox/mapbox-maps-ios/files/11628255/logs.zip)

**Comment by OdNairy** [comment]
Both builds are completed successfully. 
Try to restart Xcode, then MacBook. If it doesn't help you can try to reinstall Xcode.
There is no issue in the Maps SDK
