### ISSUE TITLE
Puck CPU Usage 30-60% even with Pulsing Disabled

### ISSUE THREAD

**Issue by samskinner32** [mapbox/mapbox-maps-ios#1978]
## Environment

- Xcode version: 14.3.1
- iOS version: 16.4
- Devices affected: Simulator
- Maps SDK Version: 10.13.1

## Observed behavior and steps to reproduce

Our map usage is fairly straightforward, but we've noticed that the `puck2D` is causing CPU usage in XCode debugger to hover at 30-60% even while idling on the map. If we remove the puck, we sit at 0-5%, as we'd want. I tried disabling the animation via the following code and it had no effect, but maybe I'm not successfully disabling it?

```
var pulse = Puck2DConfiguration.Pulsing()
pulse.isEnabled = false
map.location.options.puckType = .puck2D(Puck2DConfiguration(pulsing: pulse))
```

## Expected behavior

I would expect the puck to not increase CPU usage so drastically.

**Comment by OdNairy** [comment]
Thanks for the report, @samskinner32. I'm closing this ticket in favor of https://github.com/mapbox/mapbox-maps-ios/issues/1939.
Please, take a look at the provided workaround options: https://github.com/mapbox/mapbox-maps-ios/issues/1939#issuecomment-1594398407
