### ISSUE TITLE
Add event listener prompt event type error

### ISSUE THREAD

**Issue by seekcx** [mapbox/mapbox-maps-ios#1984]
## Environment

- Xcode version: 14.3.1 
- iOS version: nil
- Devices affected:
- Maps SDK Version: main

## Observed behavior and steps to reproduce

<img width="664" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/8244814/a5a22376-6535-46d5-a108-fef7dfa09a54">
<img width="866" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/8244814/fdaa0c62-76b3-4298-a80a-337c1c7f4004">

## Expected behavior

There are no type errors.

**Comment by OdNairy** [comment]
Hello, @seekcx 
Unfortunately, this is a flaky Xcode issue that sometimes appears. We had feedback that Clean and removal of DerivedData sometimes resolves it.
This is only a "Live issue" problem and should have no impact on the actual SDK compilation. 
Please, reopen the ticket if it blocks an application compilation or if you need any additional information.
