### ISSUE TITLE
Efficient Image Display on Mapbox Annotations: Seeking Alternative Approaches

### ISSUE THREAD

**Issue by YoungjunGu** [mapbox/mapbox-maps-ios#1985]
## New Feature

I understand that starting from version 10, MGLAnnotationView is no longer available, and according to the documentation, it suggests using Style Layers for cluster functionality. 
I'm trying to download images from PHAsset and display them on Annotations using SymbolLayer. I have learned how to link images using SymbolLayer and add layers to the style.
However, the issue is that in version 10 and above, I need to preconfigure all the images, which results in increased performance overhead compared to MGLAnnotationView, which provides features like prepareForReuse to minimize the impact(memory). I would like to inquire if there are any alternative approaches available.

<img width='400' src='https://github.com/mapbox/mapbox-maps-ios/assets/33486820/9ed8af40-4634-4a8a-af03-836c80c8b3a1'>

![image](https://github.com/mapbox/mapbox-maps-ios/assets/33486820/3ea52f20-0ca5-4b73-a5ce-9759aba21fa9)

I would like to learn how to handle requesting and canceling PHAsset images when the SymbolLayer is added or removed due to zooming in or out on the mapView. Knowing when the **SymbolLayer is added or removed** (like [MGLMapViewDelegate](https://docs.mapbox.com/ios/maps/api/6.4.1/Protocols/MGLMapViewDelegate.html#/MGLMapViewDelegate)) would allow me to efficiently manage the image requests for PHAssets. Could you please provide guidance on how to achieve this

## Why
I'm looking for alternative approaches to efficiently display images on Annotations using SymbolLayer in Mapbox, as the use of MGLAnnotationView is no longer available starting from version 10, which requires preconfiguring all images. Seeking advice on reducing performance overhead.

**Comment by pjleonard37** [comment]
Thanks for the question, @YoungjunGu. 

We have a general guide to Annotation approaches [here](https://docs.mapbox.com/ios/maps/guides/annotations/) which describes the tradeoffs of using each approach. You may have already seen this, but it is worth reviewing to pick the best approach for your use case. As for knowing when the SymbolLayer is added/removed, I'd recommend reviewing our [documentation on Listening to the Map's Life Cycle](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/#listening-to-the-maps-lifecycle). You can use this event-based approach to understand when certain events happen on the map and then respond appropriately. 

Going forward, we kindly ask you to avoid using the issue tracker in this repository for how-to questions like this and instead use our support channels for implementation advice. You can connect with our developer community by joining our [Discord channel](https://discord.gg/UshjQYyDFw) or reach out to our support team [via our website](https://docs.mapbox.com/help/) for additional guidance.
