### ISSUE TITLE
Annotation list order is not preserved on annotation tap [since v10.13.1]

### ISSUE THREAD

**Issue by emixb** [mapbox/mapbox-maps-ios#1988]
## Environment

- Xcode version: 14.3.1
- iOS version: 16.1; 16.5.1
- Devices affected: iPhone 8, iPhone 12 Pro Max
- Maps SDK Version: since v10.13.1

## Observed behavior and steps to reproduce

1. Add several annotations using an annotation manager (reproduced with point and circle annotation managers).
2. Add tap handling using AnnotationInteractionDelegate

When tapping on an annotation, it seems the order of the annotations changes, leading to some weird glitches.

The issue can be reproduce with the demo app: https://github.com/mapbox/mapbox-maps-ios/blob/cf286de094c7bd413697ab67da0d5866f790009e/Apps/Examples/Examples/All%20Examples/Annotations/CircleAnnotationExample.swift. If annotations overlap, tapping them will likely redraw them in a different Z order. See this video: [CircleAnnotationExample video](https://github.com/mapbox/mapbox-maps-ios/assets/5033297/a744558f-35c9-49d8-9028-ac78c4b6289f).

Also, if you have clustering enabled, clusters will be recomputed twice in a row, when tapping them, leading to weird glitches. Please see this video taken from some custom app [Custom app video](https://github.com/mapbox/mapbox-maps-ios/assets/5033297/1c2834da-d9fb-4f21-821f-50b7b561d219).

## Expected behavior

The list of annotations should not change simply because one annotation was tapped.

## Notes / preliminary analysis

It appears this bug was introduced in v10.13.1. Previous versions of the framework work fine (CircleAnnotationExample.swift for example) - tested with 10.12.2. 

The impact of this issue is significant, as it prevents us from updating to the latest version of the framework, which contains other critical bug fixes.

Any help is appreciated, thanks!

**Comment by maios** [comment]
Thank you for reporting, I can confirm this is a bug and I have created a ticket to add to the team's backlog. We will prioritize and fix it asap.

**Comment by persidskiy** [comment]
@emixb Hi, the issue is fixed as part of Annotations refactoring for SwiftUI support in [v11.0.0-beta.2](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.0.0-beta.2) release.

**Comment by baleboy** [comment]
@emixb unfortunately not, this will be from v11 onwards
