### ISSUE TITLE
JSON expression parse with object

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-maps-ios#1989]
## Environment

- Xcode version: 14.3.1 (14E300c)
- iOS version: 17.0
- Devices affected: Simulator iPhone 14 Pro
- Maps SDK Version: #main (cf286de094c7bd413697ab67da0d5866f790009e)

## Observed behavior and steps to reproduce

```swift
let expressionString =
        """
        [
            "get",
            "akey",
            ["literal",
                {
                    "akey":"aval",
                    "bkey":"bval",
                }
            ]
        ]
        """
        
        let expressionData = expressionString.data(using: .utf8)!
        let expression = try! JSONDecoder().decode(Expression.self, from: expressionData)
        print("?? decode expression \(expression) from \(expressionString)")
```

## Expected behavior

I'd expect that the object is parsed as the argument to literal.
But instead I get an empty format expression:

```log
?? decode expression [get, akey, [literal, format(MapboxMaps.FormatOptions(fontScaleValue: nil, textFontValue: nil, textColorValue: nil))]] from [
    "get",
    "akey",
    ["literal",
        {
            "akey":"aval",
            "bkey":"bval",
        }
    ]
]
```

Also if I serialise the expression I get:
```swift
       let coded = try! JSONEncoder().encode(expression)
        print("=> coded as: \(coded) \(String(data: coded, encoding: .utf8))")
```

```
Optional("[\"get\",\"akey\",[\"literal\",{}]]")
```

**Comment by csimpi** [comment]
@Mapbox-Adam4472 @mapbox-chrisshumaker  What's up with this?

**Comment by OdNairy** [comment]
Hi @mfazekas , @csimpi 
I could reproduce the issue and confirm that our Expression decoding strategy has a bug. 
Let me make a ticket in our internal system (MAPSIOS-1678).

**Comment by OdNairy** [comment]
Hey @mfazekas @csimpi 
Good news - @evil159 has fixed the reported issue (checkout commit https://github.com/mapbox/mapbox-maps-ios/commit/fe949729b02b19e36b5999222f82c4945a2cad8b).
Please check the main branch for a fix to get us proper feedback. 
You could expect those changes to be a part of the `11.10.0` release (ETA mid February 25).

**Comment by csimpi** [comment]
@OdNairy Thank you guys, we are really-really appreciate it. Fingers crossed for the February release.
Merry Christmas
