### ISSUE TITLE
Issue with Connected Routes in Mapbox 10.14.0

### ISSUE THREAD

**Issue by valtrn** [mapbox/mapbox-maps-ios#1990]
## Environment

- Xcode version: 14.3.1
- iOS version: 16
- Devices affected: all
- Maps SDK Version: 10.14.0

## Observed behavior and steps to reproduce

I need to display multiple routes on a map using the Mapbox SDK. However, I'm experiencing an issue where the routes appear to be connected, even though they should be separate lines.

I have followed the Mapbox documentation and tried different approaches, including creating separate LineLayers and using GeoJSONSources for each route. However, despite these efforts, the routes still appear connected on the map.

```
struct Route {
    let id: Int
    let coordinates: [CLLocationCoordinate2D]
}

let routes: [Route] = ...
routes.forEach { route in
    let lineCoordinates = route.coordinates
    let geoJSONSourceId = "geoJSONSource-(route.id)"
    let lineLayerId = "line-layer-(route.id)"

    var geoJSONSource = GeoJSONSource()
    var feature = Feature(geometry: .lineString(.init(lineCoordinates)))
    geoJSONSource.data = .feature(feature)
    try? mapView.mapboxMap.style.addSource(geoJSONSource, id: geoJSONSourceId)

    var lineLayer = LineLayer(id: lineLayerId)
    lineLayer.source = geoJSONSourceId
    lineLayer.lineColor = .constant(StyleColor(.red))
    lineLayer.lineWidth = .constant(2)
    try? mapView.mapboxMap.style.addLayer(lineLayer)
}
```

Here's an example using LineLayer to display multiple routes as separate line layers. Additionally, if you prefer, I can provide an example using PolylineAnnotationManager.

## Expected behavior

Routes are shown separately.

**Comment by maios** [comment]
hi @valtrn, could you provide the screenshot showing how the lines are displayed currently, and how you expect them to be displayed?

**Comment by valtrn** [comment]
Hi @maios, sorry I find an issue on my side.
