### ISSUE TITLE
Failed to add package to xcode project

### ISSUE THREAD

**Issue by kenjichanhkg** [mapbox/mapbox-maps-ios#1995]
<img width="1073" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/7701160/bcd80939-872c-420c-860f-4cc82aa57af6">

## Environment

- Xcode version: 14.3.1 
- iOS version: 16.4
- Devices affected:
- Maps SDK Version: 10.14.0

## Observed behavior and steps to reproduce

When I add mapbox ios package to my project I see this:
<img width="1073" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/7701160/bcd80939-872c-420c-860f-4cc82aa57af6">

## Expected behavior

package added without error

## Additional links and references

I followed this page to add the package.
https://docs.mapbox.com/ios/maps/guides/install/

**Comment by OdNairy** [comment]
Hey
There are a few common issues that lead to failed dependencies download:
1. Missing mapbox token in the `~/.netrc` file
2. Missing `DOWNLOAD:READ` permission in that token
3. Xcode needs a restart to get actual values from the `~/.netrc` file.

**Comment by kenjichanhkg** [comment]
> Hey There are a few common issues that lead to failed dependencies download:
> 
> 1. Missing mapbox token in the `~/.netrc` file
> 2. Missing `DOWNLOAD:READ` permission in that token
> 3. Xcode needs a restart to get actual values from the `~/.netrc` file.

Thanks! It works now.
My token I used doesn't have DOWNLOAD:READ permission.
