### ISSUE TITLE
Failed to start demo

### ISSUE THREAD

**Issue by lsqgithub001** [mapbox/mapbox-maps-ios#1996]
## Environment

- Xcode version:14.2
- iOS version:
- Devices affected:
- Maps SDK Version:

<img width="850" alt="企业微信截图_d944b257-d212-4480-991a-9eb60cdd5577" src="https://github.com/mapbox/mapbox-maps-ios/assets/22098572/a4a36cee-0b83-4afe-919c-ebe5cc26ba89">

<img width="850" alt="企业微信截图_b1aa9bc6-5634-4c0d-bc9f-a61b140bc80e" src="https://github.com/mapbox/mapbox-maps-ios/assets/22098572/1d3d1059-8781-4ca4-9b17-33860379a0df">

 
<img width="1250" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/22098572/d4ee86c8-1d6f-4939-b3e5-1e70ee760f7d">

**Comment by maios** [comment]
Hi @lsqgithub001, we do not have any version that matches your Version rules (11.0.0 - 12.0.0), please check our out Github releases page for the information of the versions we have releases https://github.com/mapbox/mapbox-maps-ios/releases

**Comment by lsqgithub001** [comment]
你好，我已经收到你的邮件了。谢谢你。辛苦咯~！
