### ISSUE TITLE
Mapbox maps sdk ios (v10.14.0) Point annotation manager 

### ISSUE THREAD

**Issue by OffsureDev** [mapbox/mapbox-maps-ios#1999]
## New Feature

Hello, I would like to request the development of the Point annotation drag and drop handler method to detect the coordinates of annotation on Mapview.

## Why
This feature is valuable to detect drag, drop, drag begin, etc.

**Comment by maios** [comment]
Hi @OffsureDev, thank you for the suggestion. This feature request has been added to our backlog https://mapbox.atlassian.net/browse/MAPSIOS-743.
We will keep you updated when it is ready to test.

**Comment by persidskiy** [comment]
Fixed here https://github.com/mapbox/mapbox-maps-ios/issues/2106
