### ISSUE TITLE
Unable to configure new Standard Mapbox style

### ISSUE THREAD

**Issue by stephensilber** [mapbox/mapbox-maps-ios#2001]
## Environment

- Xcode version: 14.3.0
- iOS version: 16.4
- Devices affected: all
- Maps SDK Version: v11.0.0-beta1

## Observed behavior and steps to reproduce

After reading the [documentation](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Documentation.docc/Migrate%20to%20v11.md#21-the-mapbox-standard-style) it seems that there is either a bug in the SDK or some missing steps in the documentation to set any of the 6 configurable properties on the new Mapbox Standard style.

After attempting to get it working in our main project, I created the most barebones-possible sample project to ensure it wasn't something on our end. (attached below)

## Expected behavior

The style's lightPreset property should be set to `night` along with the labels (`pointOfInterestLabels`, `roadLabels`, `transitLabels`) all being hidden.

## Notes / preliminary analysis

The concepts of style imports aren't very clear from the documentation. There are is the following quote which alludes to some behavior around multiple/merged styles but without an example or any further definitions it's difficult to figure out what I'm supposed to do to use this. I'm being told the `standard` style import does not exist but I don't see where I would have any control over that besides explicitly setting the `mapView.mapboxMap.styleURI = .standard` (this does nothing)

---
"To work with styles like Mapbox Standard, we've introduced new Style APIs that allow you to import other styles into the main style you display to your users. These styles will be imported by reference, so updates to them will be reflected in your main style without additional work needed on your side"
---

When I check which style imports are available after the `onMapLoaded` has fired (`StyleManager/styleImports`), I only get a single value back which is `basemap`

## Additional links and references
[MapboxSandbox.zip](https://github.com/mapbox/mapbox-maps-ios/files/12314538/MapboxSandbox.zip)

**Comment by pjleonard37** [comment]
Hi @stephensilber - 

It's great to see that you're working with the Standard style and style importing! You're correct -- both of these import IDs should refer to "basemap" as that is the id for the basemap imported into the Standard style itself. I'll go ahead and approve that PR now. Thanks for submitting it! 

As background, these snippets were based on our Standard Style Example ([here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/StandardStyleExample.swift)) which imports the Standard style into another style `fragment-realestate-NY` (you can see the Style JSON [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Sample%20Data/fragment-realestate-NY.json)), adds that style in the example and adjusts lighting and other configurations in the imported Standard. However, this section of our Migration Guide is referring to working with the Standard style itself and should refer to "basemap". 

> The concepts of style imports aren't very clear from the documentation. There are is the following quote which alludes to some behavior around multiple/merged styles but without an example or any further definitions it's difficult to figure out what I'm supposed to do to use this.

Thanks for sharing this feedback on our documentation, I agree that we should build out better explanations for how to work with these new concepts of style importing, style configurations, and the Standard style. I'll work on an update to the migration guide now which better explains how to work with them. As we makes updates throughout the beta period (and beyond!) please do share any additional feedback you have.

**Comment by stephensilber** [comment]
> Hi @stephensilber -
> 
> It's great to see that you're working with the Standard style and style importing! You're correct -- both of these import IDs should refer to "basemap" as that is the id for the basemap imported into the Standard style itself. I'll go ahead and approve that PR now. Thanks for submitting it!
> 
> As background, these snippets were based on our Standard Style Example ([here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/StandardStyleExample.swift)) which imports the Standard style into another style `fragment-realestate-NY` (you can see the Style JSON [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Sample%20Data/fragment-realestate-NY.json)), adds that style in the example and adjusts lighting and other configurations in the imported Standard. However, this section of our Migration Guide is referring to working with the Standard style itself and should refer to "basemap".
> 
> > The concepts of style imports aren't very clear from the documentation. There are is the following quote which alludes to some behavior around multiple/merged styles but without an example or any further definitions it's difficult to figure out what I'm supposed to do to use this.
> 
> Thanks for sharing this feedback on our documentation, I agree that we should build out better explanations for how to work with these new concepts of style importing, style configurations, and the Standard style. I'll work on an update to the migration guide now which better explains how to work with them. As we makes updates throughout the beta period (and beyond!) please do share any additional feedback you have.

That's super helpful, thank you for the quick response and the examples + context. The Style JSON you pointed me looks like the right direction for us but I have one more question around that:

Is it possible to override any colors of layers on the standard style? I've tried following that example to bring in our own `land` and `water` layers but the results aren't great:
![simulator_screenshot_5E7AE318-5325-4BF0-80BE-91C8AC4FAB4B](https://github.com/mapbox/mapbox-maps-ios/assets/845497/17566636-25c5-4be1-a014-51f3c4ab206e)

If it's not possible, is that something that might be considered in the future? We have some brand-specific colors on our current map style and we'd love to get even a little bit of control over the new Standard colors to align closer with our brand.

**Comment by pjleonard37** [comment]
> Is it possible to override any colors of layers on the standard style?

Standard colors are not modifiable at the moment. The Standard style is a carefully designed experience leveraging a curated color palette to ensure high legibility and contrast. You can, however, customize the overall color by adjusting the 3D light settings or choose colors for your added custom layers to reflect your brand/designs.

To adjust the 3D light settings, you can use [DirectionLight](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Generated/Light/DirectionalLight.swift) and [AmbientLight](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Generated/Light/AmbientLight.swift) like below: 

```
var directionalLight = DirectionalLight(id: "directional-light")
directionalLight.intensity = .constant(0.5)
directionalLight.castShadows = .constant(true)
directionalLight.shadowIntensity = .constant(1)

var ambientLight = AmbientLight(id: "ambient-light")
ambientLight.color = .constant(StyleColor(.green))
ambientLight.intensity = .constant(0.5)

try mapView.mapboxMap.setLights(ambient: ambientLight, directional: directionalLight) 
```

We have a broader example [here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Lab/Lights3DExample.swift) which shows off more configuration options. However, this approach would affect lighting for all layers in the style.

**Comment by stephensilber** [comment]
@pjleonard37 Got it. I think we can live with that restriction for now. The last issue that is a blocker for us is around the colors of our own data layers. It seems like they're impacted by the lighting settings but we'd like to exclude our circle and label layers since they make the colors difficult to see (our colors map to categories and they lose the correlation between our data when the colors don't match due to lighting). If this makes sense as a separate issue let me know and I'm happy to close this and open a new one with more details about what we're trying to accomplish

![image](https://github.com/mapbox/mapbox-maps-ios/assets/845497/e90f1fbc-0bd2-495f-b2ab-06a57169346f)
![image](https://github.com/mapbox/mapbox-maps-ios/assets/845497/1f231371-e0e5-4fb7-9416-23c394e1e38c)

**Comment by stephensilber** [comment]
Nevermind, I just figured out that I can work around this by using the `emissiveStrength` properties of different layer types! I'm closing this. Appreciate all of the help.

Circles: `circleEmissiveStrength`,
Lines: `lineEmissiveStrength`,
Label:  `textEmissiveStrength`, `iconEmissiveStrength`,

and so on
