### ISSUE TITLE
Package Resolution Failed, 11.0.0-beta.2

### ISSUE THREAD

**Issue by nferruzzi** [mapbox/mapbox-maps-ios#2004]
## Environment

- Xcode version: 14.3.1
- iOS version: 16
- Devices affected:
- Maps SDK Version: 11.0.0-beta.2

## Observed behavior and steps to reproduce

attempted to install via SPM 

<img width="1200" alt="Screenshot 2023-08-23 at 17 36 21" src="https://github.com/mapbox/mapbox-maps-ios/assets/1319874/8ba9fdef-8589-443b-ad2a-2f20aa1e1838">

**Comment by OdNairy** [comment]
Right, Xcode requires restart after `.netrc` manipulations.
