### ISSUE TITLE
clearData() does not clear circleLayer that uses tileset from MTS

### ISSUE THREAD

**Issue by martinpolley** [mapbox/mapbox-maps-ios#2005]
## Environment

- Xcode version: 14.2
- iOS version: various 
- Devices affected: various iPhones
- Maps SDK Version: 10.12.2. Also tried 10.15.0 and 11.0.0-beta.2, but the behaviour is the same.

## Observed behavior and steps to reproduce 

Using `clearData()` to clear the cache does not seem to clear circleLayers that were added to the map in Mapbox Studio. The circleLayers come from a tileset in MTS.

The screenshot below shows what the map looks like on a device in airplane mode immediately after calling `clearData()`:

![IMG_9221](https://github.com/mapbox/mapbox-maps-ios/assets/432817/6a1db175-70a2-43c7-b2d5-faa4a5cad32d)

The base map around the current location has not been cleared, which makes sense I guess. In the bottom half of the screenshot (further away from the current location), you can see that the base map _has_ been cleared. _But the circleLayer is still there._

The data in MTS gets updated very frequently, so I need to be able to clear the cache so the map includes the updated data points.

## Expected behavior

I would expect `clearData()` to clear all tiles from the cache, including any layers added from MTS.

## Notes / preliminary analysis

More of an observation, but in v6, `invalidateAmbientCache()` did clear this stuff from the cache, but `clearData()` doesn't.

**Comment by martinpolley** [comment]
Also worth mentioning – my app uses offline maps too. I'm not really clear on how the SDK decides what to render if tiles are in a downloaded pack.

In any case, this behaviour happens whether I have any packs downloaded or not.

(Also not clear from the docs whether you are meant to specify the tile store you use for offline in the resource options you use to initialise the map itself (as it's an optional param)...)

**Comment by martinpolley** [comment]
Another observation. When I call `clearData()` when in airplane mode, it does not preserve all of the MTS layer. 

In these screenshots, you can see that there are clear lines at the eastern and northern edges showing the extent of the data that has been preserved. I've included screenshots of the same locations _with_ an internet connection so you can see that the data extends beyond these extents.

Eastern extent:

![IMG_9234](https://github.com/mapbox/mapbox-maps-ios/assets/432817/09471d63-e233-4ca2-937b-15c80e166767)
![IMG_9236](https://github.com/mapbox/mapbox-maps-ios/assets/432817/c3854ea9-f7e2-43e0-932c-c163c62acd61)

Northern extent:

![IMG_9235](https://github.com/mapbox/mapbox-maps-ios/assets/432817/93b998bf-a4d7-4bda-a8f2-b4dbdb58a8be)
![IMG_9237](https://github.com/mapbox/mapbox-maps-ios/assets/432817/a8a407da-4d35-406d-b999-e335a34609bd)

So it looks to me as though one or both of the following are true:

- The extent of the "local" (i.e., by proximity to the user's location) MTS data that is NOT removed by `clearData()` is much larger than for the base map.
- The MTS data is being cached in a different location from the base map.

I have also tried specifying a `dataPathURL` in the map's `resourceOptions` and then deleting this directory using FileManager, but it does not help.

Is this a bug? Or is there some other way of clearing this cached data?

**Comment by martinpolley** [comment]
Interestingly, the eastern extent of the data I described above is exactly on the Greenwich meridian – 0° (W/E). 

The northern extent does not seem to be a significant number  – it is approximately half a degree north of the user’s position when the cache was cleared.

**Comment by pjleonard37** [comment]
Hi @martinpolley -- 

Again, thanks for writing up this report with all of this detail. Similar to this other report you submitted [here](https://github.com/mapbox/mapbox-maps-ios/issues/2017), can you please submit a technical support request via the form [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231)? That way our [Support team](https://www.mapbox.com/support) can review your report and work with you on next steps.

**Comment by martinpolley** [comment]
Hi @pjleonard37,

Yes, I'll open a request for this one too.

I also have [this ticket](https://github.com/mapbox/mapbox-maps-ios/issues/1969), which I opened here under the iOS SDK, but I'm sure it's not iOS specific. I think it's the map itself.

Am I better off opening a request [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231) for that too?

Thanks,
Martin

**Comment by pjleonard37** [comment]
Great, thank you! 

> I also have https://github.com/mapbox/mapbox-maps-ios/issues/1969, which I opened here under the iOS SDK, but I'm sure it's not iOS specific. I think it's the map itself.
> 
> Am I better off opening a request [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231) for that too?

Yes, that would be best

**Comment by martinpolley** [comment]
Thanks – will do.

**Comment by YoamFarges** [comment]
Hello @martinpolley, did you had any closure on that behaviour? I'm experimenting the same thing were clearing the Tileset generated with MTS seems impossible via `clearData`.

**Comment by martinpolley** [comment]
Hi @YoamFarges. I'm afraid not. I switched back from Mapbox 10 to Mapbox 6 because of this and other issues.

Maybe more recent releases of Mapbox 11 have fixed this, but I haven't tried them...
