### ISSUE TITLE
iOS 17 Dark Mode: StyleColor crash - "Please use a color in the sRGB color space"

### ISSUE THREAD

**Issue by Knapiii** [mapbox/mapbox-maps-ios#2007]
## Environment

- Xcode version: 14.3.1
- iOS version: 17.0
- Devices affected: all iOS 17 devices running Dark Mode
- Maps SDK Version: 10.15.0

## Observed behavior and steps to reproduce
1. Create a `LineLayer`
2. Set the the layers `lineColor` to `StyleColor(.white)`

Then run the code on an iOS 17 beta device running on Dark Mode (Crashes only on Dark Mode)
<img width="435" alt="Skärmavbild 2023-08-24 kl  14 08 31" src="https://github.com/mapbox/mapbox-maps-ios/assets/22640875/8405c0ef-0158-4383-b4fc-b8266d77d5ed">
<img width="993" alt="Skärmavbild 2023-08-24 kl  14 07 24" src="https://github.com/mapbox/mapbox-maps-ios/assets/22640875/d5802c1b-d58f-402e-b053-5674d34d4fa5">

## Expected behavior

That the `lineLayer` color sets to `.white`

## Notes / preliminary analysis
This line of code does not crash on iOS 16.X and below
Only crashes on iOS 17 beta devices running Dark Mode

## Additional links and references
Here is the code that crashes at `StyleColor`:
<img width="661" alt="Skärmavbild 2023-08-24 kl  14 20 19" src="https://github.com/mapbox/mapbox-maps-ios/assets/22640875/28a22354-3d6c-46e4-84a7-c5ad24298b4c">

The `SymbolColor` struct has been updated at this commit 559942acf43d2fd0a28618e985712275b282e689. This commit  has been implemented on [v11.0.0-beta.1](https://github.com/mapbox/mapbox-maps-ios/tree/v11.0.0-beta.1) which is a beta version.

I don't know yet if this will fix my issue but it is a possibility

**Comment by pjleonard37** [comment]
Hi @Knapiii -- 

Thanks for sharing this report with all of this detail. We are reviewing this issue on iOS 17 beta and considering the best approach to address it.

**Comment by Knapiii** [comment]
@pjleonard37
Here is my fix for now. Can now run my project on iOS 17

<img width="673" alt="Skärmavbild 2023-09-18 kl  15 26 41" src="https://github.com/mapbox/mapbox-maps-ios/assets/22640875/2722f4f6-e221-4979-8067-2d58271c3898">

**Comment by evil159** [comment]
@Knapiii Thank you for reporting this! This was fixed in the [10.6.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.16.1) release.
