### ISSUE TITLE
[Feature Request] Expire date setting.

### ISSUE THREAD

**Issue by shinriyo** [mapbox/mapbox-maps-ios#2009]
## New Feature

I logged below

```
        let stylePackDownload = offlineManager.loadStylePack(
            for: .outdoors,
            loadOptions: stylePackLoadOptions) { [weak self] progress in
        } completion: { [weak self] result in
                switch result {
                case let .success(stylePack):
                    print(stylePack.expires) // this
                case let .failure(error):
                    downloadError = true
                }
            }
        }
```

it was about 1 hour 45 minutes.
It is too short.

```
        let tileRegionLoadOptions = TileRegionLoadOptions(
            geometry: .point(Point(tokyoCoord)),
            descriptors: [outdoorsDescriptor],
            metadata: ["tag": "my-outdoors-tile-region"],
            acceptExpired: false,
            // I wanna expire like this
            expiredMinutes: 60 * 24 * 30
        )!
```

## Why

Because, I want to keep about 1month.

**Comment by shinriyo** [comment]
Is mapbox support finished?
no answered.

**Comment by shinriyo** [comment]
Will offline data be deleted automatically? Or will it remain forever unless I delete it?

**Comment by shinriyo** [comment]
https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/OfflineManagerExample.swift#L11

`deleted` means deleted by manual or automatically??

**Comment by shinriyo** [comment]
it should be clarified.

**Comment by pjleonard37** [comment]
Hi @shinriyo --

Thanks for writing in. For questions like this about how to use particular features of the Mapbox Maps SDK, including `offlineManager`, please take advantage of the Support Resources on our website. You can find them [here](https://www.mapbox.com/support). If you have a particular question you can submit a technical support request via a form [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231). For more in-depth support with using Mapbox products we recommend subscribing to a Support Plan. You can learn more about what is offered on each plan [here](https://www.mapbox.com/support).
