### ISSUE TITLE
Logo can be hidden - is that expected? (attribution concern for new developers)

### ISSUE THREAD

**Issue by ax-vasquez** [mapbox/mapbox-maps-ios#2012]
## Environment

- Xcode version: `14.3.1 (14E300c)`
- iOS version: N/A
- Devices affected: N/A
- Maps SDK Version: `10.15.0`

## Observed behavior and steps to reproduce

I've noticed that one can simply set `isHidden` to true for the `logoView` in the `OrnamentsManager`. I recognize that the docs say to not do it this way, but since it does successfully remove the logo from the map (at least, when the `MapView` is created via a `UIViewRepresentable` - I haven't been testing this in UIKit, but SwiftUI), I'm concerned less wary developers may see that as an option and hide it to make the app "look nice". If that's not allowed, I imagine they would run the risk of having their access to the SDK revoked, but I'm not too sure.

Wouldn't this violate the Terms of using the SDK, since attribution is required? If not, that's also useful to know since it might be nice to hide the logo (and instead just keep the 'i' icon that renders the attribution toast).

Example custom `UIViewRepresentable`:
```swift
struct CustomMapView: UIViewRepresentable {
   func makeUIView(context: Context) -> MapView {
      // Code to set up MapView (ResourceOptions and whatnot)...
      let mapView = MapView(frame: .zero, mapInitOptions: myMapInitOptions)
      let manager = mapView.ornaments
      manager?.logoView.isHidden = true   // Offending line - hides the icon - should `isHidden` even exist on logoView if it shouldn't be hide-able?
      mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
      return mapView
   }

   // Rest...
}
```

## Expected behavior

_Unsure - I expected this to not be an option for the logo since I thought it was required to always have it on the map_

## Notes / preliminary analysis

I am a bit rusty with iOS dev, so please forgive any ignorance in my statements here. Still brushing off some dust while pursuing a side project. In my day job, I am a senior web dev, so I do very little with mobile development.

**Comment by pjleonard37** [comment]
Hi @ax-vasquez - 

Thanks for sharing this report. You are correct that hiding the logo is a violation of the terms of using the SDK (as is hiding the attribution for map data sources). We have more information on this in our attribution guide [here](https://docs.mapbox.com/help/getting-started/attribution/) as well as our Legal documentation [here](https://www.mapbox.com/legal/product-terms).

As for your broader concern about a developer unwittingly hiding the logo, this is a reasonable concern. In our in-code documentation we have additional notification that setting the visibility property is a restricted API (see [here](https://github.com/mapbox/mapbox-maps-ios/blob/4435030616fdcbd6d6fef11d6252c62b5b5a37aa/Sources/MapboxMaps/Ornaments/OrnamentOptions.swift#L185)). Nonetheless, I'm going to take this back to our full team and consider other steps we could take here. Again, thanks for raising this and for experimenting with the SDK!
