### ISSUE TITLE
[Feature] load from .mbtiles file of local

### ISSUE THREAD

**Issue by shinriyo** [mapbox/mapbox-maps-ios#2013]
## New Feature

Loading future from the `.mbtiles` file of local assets.

## Why

Because I want to use it for offline use.

**Comment by pjleonard37** [comment]
Hi @shinriyo - 

Thanks for sharing this feature request. As I mentioned in your other ticket [here](https://github.com/mapbox/mapbox-maps-ios/issues/2009#issuecomment-1703082159), please create a support ticket so that the support team can review your request and understand your use case.
