### ISSUE TITLE
Is there any way we can show the recenter button on map?

### ISSUE THREAD

**Issue by satyamrathor16** [mapbox/mapbox-maps-ios#2014]
## New Feature

If we want to recenter the map to our current location there is no ornaments for this like we have the mapView.ornaments.options.compass for hiding and showing this compass view but there is nothing for recenter button.

## Why
There are method for moving to the current location but there is not any simple button which we can show and hide directly. We are working with mapbox ios sdk in react native so if we have any simple way for the recenter button than that very helpful.

**Comment by pjleonard37** [comment]
Hi @satyamrathor16 -- 

Thanks for sharing this feature request. At this time we do not have plans for implementing this feature, however I've created an internal ticket to track this request. 

To achieve a similar effect, you should be able to implement your own button which recenters the map and position it with the [OrnamentsManager](https://docs.mapbox.com/ios/maps/api/10.16.0/Ornaments.html#/c:@M@MapboxMaps@objc(cs)OrnamentsManager).
