### ISSUE TITLE
[Bug] Can't build

### ISSUE THREAD

**Issue by shinriyo** [mapbox/mapbox-maps-ios#2018]
## Environment

- Xcode version:
Version 14.3.1 

- iOS version:
15.6(real Device)

- Devices affected:
- Maps SDK Version:
default

## Observed behavior and steps to reproduce

just git clone and just open `mapbox-maps-ios/Apps/Apps.xcworkspace`

## Expected behavior

<img width="268" alt="スクリーンショット 2023-09-08 15 55 23" src="https://github.com/mapbox/mapbox-maps-ios/assets/396927/756ec2da-fed9-424e-8bbb-89b22d13e14f">

## Notes / preliminary analysis

Buildable project is better.

## Additional links and references

https://github.com/mapbox/mapbox-maps-ios/tree/main/Apps/Examples

**Comment by shinriyo** [comment]
https://github.com/mapbox/mapbox-maps-ios/blob/main/DEVELOPING.md

`Setting Up a Development Environment`

this one?

**Comment by shinriyo** [comment]
I think that the version is stable version, but I couldn't build.
`git checkout v10.13.1`

**Comment by OdNairy** [comment]
Please, follow installation guide to enable SDK downloads
https://docs.mapbox.com/ios/maps/guides/install/
