### ISSUE TITLE
[Feature] Write how to build Example 

### ISSUE THREAD

**Issue by shinriyo** [mapbox/mapbox-maps-ios#2019]
## New Feature

It is bad README, fix it.

## Why

It can't build. If I am author, I don't write such document in `README`.

**Comment by shinriyo** [comment]
for avoid this bug
[Bug] Can't build #2018

**Comment by shinriyo** [comment]
I made PR.
It is helpful for users. (That's okay, but it is better if you make the Japanese one)

**Comment by baleboy** [comment]
If your goal is to build the examples, please follow the instructions in https://docs.mapbox.com/ios/maps/guides/.

As stated in the README: "This README is intended for developers who are interested in contributing to the Mapbox Maps SDK for iOS. Please visit https://docs.mapbox.com/ios/maps/guides/ for general information and instructions on using the Maps SDK in your iOS application."
