### ISSUE TITLE
`.onLongPressGesture` breaks existing map gestures

### ISSUE THREAD

**Issue by Max-Leopold** [mapbox/mapbox-maps-ios#2020]
## Environment

- Xcode version: 14.2
- iOS version: 16.6.1
- Maps SDK Version: v11 beta 3

## Observed behavior and steps to reproduce

Adding a `onLongPressGesture` modifier to a SwiftUI Map view breaks all exisiting map gestures (zoom, pan, drag).

```swift
@main
struct TestApp: App {    
    var body: some Scene {
        WindowGroup {
            Map().onLongPressGesture(perform: { print("Long Press") })
        }
    }
}
```

## Expected behavior

Adding a `onLongPressGesture` modifier should not have an effect on the default map gestures.

**Comment by persidskiy** [comment]
@Max-Leopold Hi, thank you for your feedback. I filed an internal issues to fix that https://mapbox.atlassian.net/browse/MAPSIOS-1081

**Comment by Max-Leopold** [comment]
Oh, very nice, that's even better! Thanks for the update!
