### ISSUE TITLE
gltf/glb animations in ModelLayer 

### ISSUE THREAD

**Issue by MichaelDanielTom** [mapbox/mapbox-maps-ios#2025]
## New Feature

Is there any way to play animations contained within gltf or glb files within `ModelLayer` (keyframe, shape key, or other)? I'm aware that you can animate most style properties with associated transition properties (e.g. if you change `modelOpacity` it will animate to the new value based on `modelOpacityTransition`), or by just updating the properties every frame. 

I'm on [v11.0.0-beta.4](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.0.0-beta.4) - also great work on the v11 betas, the 3d model related stuff is amazing!

**Comment by evil159** [comment]
Hey @MichaelDanielTom, thank you for your question! At the moment `ModelLayer` doesn't support animations within `gltf/glb` files. We are planning to implement the support for this in the future. 

Currently, just as you already pointed out, the only way to animate 3D models is by animating properties of a model layer(e.g. `modelRotate/modelTranslation/modelScale/etc.` either through associated transitions or by updating them every frame manually.
Feel free to reopen the ticket if you have any more questions.
