### ISSUE TITLE
VisionOS platform support

### ISSUE THREAD

**Issue by thib4ult** [mapbox/mapbox-maps-ios#2028]
## New Feature

Could you update all Swift packages to support the visionOS (xrOS) platform. Currently, there is an error when attempting to use them for developing Apple's spatial computing apps and, there is just no way to use MapBox in visionOS right now.

## Why

We need to make our app compatible to visionOS and we use Mapbox heavily in our application. We would have to switch provider if Mapbox doesn't add this support.

**Comment by evil159** [comment]
Thanks for writing in. Currently you can use Maps SDK on visionOS in "Designed for iPad mode". We are looking into prospects of adding a full-featured visionOS support in the future.

**Comment by mmackh** [comment]
We are also looking forward to transitioning our app to visionOS

**Comment by arthurschiller** [comment]
Yes, same issue here. I'm building a native visionOS target, so "Designed for iPad mode" unfortunately isn't an option.
Thank you for considering it!

**Comment by seldon1000** [comment]
We would love to add native visionOS support to our app too. A proper visionOS support would be awesome, thank you for considering!

**Comment by baleboy** [comment]
Native Vision OS support is now available in [v11.2-beta.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.2.0-beta.1), let us know what you think!
