### ISSUE TITLE
ViewAnnotation in SwiftUI with @Bindings not working correctly

### ISSUE THREAD

**Issue by yzoldan** [mapbox/mapbox-maps-ios#2029]
## Environment

- Xcode version: 15.0
- iOS version: 17.0
- Devices affected: iPhone Simulator
- Maps SDK Version: 11.0.0-beta4

## Observed behavior and steps to reproduce

When in SwftUI and using ViewAnnotations passing a view with a binding value it doesn't update when the binding changes.
I'm trying to show a button as an annotation that when selected it changes its font color.
The following code shows what I'm trying to do and how when using native SwiftUI views, eg VStack with ForEach it works but when using Mapbox views it doesn't (ViewAnnotation and ForEvery):

``` swift
Map(initialViewport: .camera(center: vm.initialCoordinates, zoom: 12, bearing: 0, pitch: 0)) {
                ForEvery(vm.deals) { deal in
                    ViewAnnotation(vm.dealCoordinates(deal)) {
                        DealAnnotationView(deal: deal, isSelected: vm.selectedBinding(forDeal: deal)) // <- this is a binding value but the view doesn't update when it changes
                    }
                }
            }
// For reference, here is the code of selectedBinding from the vm:
@Published var selectedDeal: Deal?
func selectedBinding(forDeal deal: Deal) -> Binding<Bool> {
        Binding(
            get: { self.selectedDeal == deal },
            set: { self.selectedDeal = $0 ? deal : nil }
        )
    }
```

If i try to do the same with native SwiftUI it works so it's not a problem with the selectedBinding func:
``` swift
  VStack {
     ForEach(vm.deals) { deal in
          DealAnnotationView(deal: deal, isSelected: vm.selectedBinding(forDeal: deal)) // It works here
      }
  }
```

## Expected behavior

ViewAnnotation should update its child view when a binding in that view changes.

Any help here would be appreciated. Maybe I'm doing something wrong, would love to see a way to do this.

**Comment by maios** [comment]
Hi @yzoldan, thank you for writing. We have confirmed that this is a limitation with ViewAnnotation APIs in SwiftUI and created an internal ticket https://mapbox.atlassian.net/browse/MAPSIOS-1125 to work on this.
Meanwhile, your use case looks like one of our examples [DynamicViewAnnotationExample](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/SwiftUI%20Examples/DynamicViewAnnotationExample.swift), which show a list of annotations that changes its size and content upon selection (there can be only 1 selected annotation in the example). Please take a look to see if you can adopt similar approach.

**Comment by yzoldan** [comment]
Thanks @maios, I followed the example you provided and found that the limitation only occurs when the `@Binding` comes from the view model, ie an `ObservableObject` class. When i moved the binding to a `@State` in the View itself like in the example it worked. Hope this help in solving the underlying issue!

**Comment by persidskiy** [comment]
@yzoldan Hi, we are redesigning the View Annotation API a little bit, there is a new version in the `main` branch. Can you try to update to most recent commit 8a534f3 and see if your case fixed?

Note: you will need to use `MapViewAnnotation` instead of `ViewAnnotation`.
