### ISSUE TITLE
Unable to install mapbox using SPM.

### ISSUE THREAD

**Issue by umair-khan97** [mapbox/mapbox-maps-ios#2030]
Xcode version: 15.0.
<img width="645" alt="Screenshot 2023-10-06 at 4 22 04 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/53686765/f759cccd-7c61-4a2e-81b7-2494b69af22e">

Could you please help me to install it on my iOS app?

**Comment by OgabekDev** [comment]
What is the solution? Please write your solution that is going to help others
