### ISSUE TITLE
Can't set safe area

### ISSUE THREAD

**Issue by FezVrasta** [mapbox/mapbox-maps-ios#2031]
## Environment

- Xcode version: 15.0
- iOS version: 17
- Devices affected:
- Maps SDK Version: 11

## Observed behavior and steps to reproduce

The mapbox logo is not moved to stay within the visible region of the map.

## Expected behavior

The mapbox logo should be positioned not to be covered by the sheet, and update its position if the sheet detent chnges.

## Notes / preliminary analysis

I couldn't find any documentation on how to make this happen manually.

## Additional links and references

![CleanShot 2023-10-07 at 1  40 37@2x](https://github.com/mapbox/mapbox-maps-ios/assets/5382443/4d4894dd-1b8d-4332-99dc-d0722b877375)

**Comment by evil159** [comment]
Hi @FezVrasta You can offset the logo by updating it's margins with `mapView.ornaments.options.logo.margins.y = ...`

**Comment by FezVrasta** [comment]
Thanks, that worked, kinda unfortunate that mapbox can't respect the safe area insets of the parent view though
