### ISSUE TITLE
packaage dependency wont import

### ISSUE THREAD

**Issue by nmn28** [mapbox/mapbox-maps-ios#2033]
<img width="664" alt="asdfasdfsadfads" src="https://github.com/mapbox/mapbox-maps-ios/assets/121139818/a1ea741b-5e92-40b6-a22f-f77b9f246a8e">

**Comment by baleboy** [comment]
Have you configured your environment as described in https://github.com/mapbox/mapbox-maps-ios/blob/main/DEVELOPING.md ?

**Comment by baleboy** [comment]
Are you still experiencing this issue?

**Comment by OdNairy** [comment]
Please, follow the [installation guide](https://docs.mapbox.com/ios/maps/guides/install/) to install Maps SDK dependency.
