### ISSUE TITLE
no such module MapBoxMap

### ISSUE THREAD

**Issue by abylay-kun** [mapbox/mapbox-maps-ios#2036]
## Environment

- Xcode version:
- iOS version:
- Devices affected:
- Maps SDK Version:

**Comment by abylay-kun** [comment]
No such module 'MapboxMaps'
how to handle this issue

**Comment by persidskiy** [comment]
@abylay-kun Hi, please follow the installation guide https://docs.mapbox.com/ios/maps/guides/install/
