### ISSUE TITLE
v11 lineBorderColor/lineBorderWidth not appearing to work as documented

### ISSUE THREAD

**Issue by david-buck** [mapbox/mapbox-maps-ios#2037]
## Environment

- Xcode version: Version 15.0 (15A240d)
- iOS version: 17
- Devices affected: iPhone
- Maps SDK Version: v11.0.0-beta.5

## Observed behavior and steps to reproduce

I'm cross-posting this here from the Discord which doesn't seem to get much attention for iOS issues.

https://docs.tilestream.net/ios/maps/api/latest/documentation/mapboxmaps/polylineannotation 
implies that a polyline can have a lineWidth/lineColor and a lineBorderWidth/lineBorderColor

I have tried this:

```
return PolylineAnnotation(lineCoordinates: coordinates)
  .lineColor(.init(UIColor(colorScheme == .dark ? routeColor : routeColorLight)))
  .lineWidth(8)
  .lineBorderColor(.init(UIColor(colorScheme == .dark ? routeColorLight : routeColor)))
  .lineBorderWidth(4)
  .lineJoin(.round)
```

and the lineBorder never seems to show. 

## Expected behavior

Line is rendered with a border of another thickness and color

**Comment by persidskiy** [comment]
@david-buck Hi, thank you for the report.

Do you use it in SwiftUI, or UIKit application?

**Comment by persidskiy** [comment]
Created internal issue https://mapbox.atlassian.net/browse/MAPSIOS-1152

**Comment by david-buck** [comment]
Swift UI

**Comment by persidskiy** [comment]
@david-buck In the stable release v11.0.0 this issue should be fixed.
