### ISSUE TITLE
Memory leak in SwiftUI

### ISSUE THREAD

**Issue by umair-khan97** [mapbox/mapbox-maps-ios#2038]
## Environment

- Xcode version: 15.0
- iOS version: 17.0
- Devices affected: 1
- Maps SDK Version: 10.16.1

## Observed behavior

/// Callback does not release memory if we write anything inside the callback

        mapView.mapboxMap.onEvery(event: .mapIdle) { data in
            let coordinateBounds = mapView.mapboxMap.coordinateBounds(for: mapView.bounds) /// Including this line doesn't  release memory in swiftui, memory keep increasing on every launch of map
        }

## Expected behavior

It need to clear memory once MapView close

## Additional links and references

/// Full code

    import SwiftUI
    import MapboxMaps

    struct MBXMapView: UIViewRepresentable {
    
    // MARK: - Properties
    
    var currentLocation: CLLocationCoordinate2D
    private let defaultZoomLevel: CGFloat = 10.5
    
    // MARK: - Methods
    
    /// Responsible for intializing and returning mapview to swiftui view
    func makeUIView(context: Context) -> MapboxMaps.MapView {
        /// For providing acces token and other stuff
        let resourceOptions = ResourceOptions(accessToken: Bundle.main.getMBXPublicAccessToken())
        /// For adjusting current position
        let cameraOptions = CameraOptions(center: currentLocation, zoom: defaultZoomLevel)
        /// This will be required to initalizer MapView in which we provide MapView resourse options, camera options, etc
        let mapInitOptions = MapInitOptions(resourceOptions: resourceOptions, cameraOptions: cameraOptions)
        let mapView = MapView(frame: .zero, mapInitOptions: mapInitOptions)
        /// Configuration
        mapView.ornaments.options.logo.position = .bottomLeading
        mapView.ornaments.options.attributionButton.position = .bottomLeading
        mapView.ornaments.options.attributionButton.margins.x = 90
        mapView.ornaments.options.scaleBar.useMetricUnits = true
        mapView.ornaments.options.compass.visibility = .visible
        mapView.location.options.puckType = .puck2D()
    
        /// Callback
        mapView.mapboxMap.onEvery(event: .mapIdle) { data in
            let coordinateBounds = mapView.mapboxMap.coordinateBounds(for: mapView.bounds) /// Including this line doesn't  release memory in swiftui, memory keep increasing on every launch of map
        }
        return mapView
    }
    
    /// Responsible for update changes once swiftui trigger this method on redraw or binding changes
    func updateUIView(_ mapView: MapboxMaps.MapView, context: Context) {
        mapView.camera.fly(to: CameraOptions(center: currentLocation, zoom: defaultZoomLevel), duration: 2.5)
    }
    }

**Comment by persidskiy** [comment]
Hi @umair-khan97 , there is a reference cycle in your code:
```
mapView -> mapboxMap -> closure -> mapView
```

You need  to capture mapView by weak reference
```swift
/// Callback
    mapView.mapboxMap.onEvery(event: .mapIdle) { [weak mapView] data in
        guard let mapView else { return }
        let coordinateBounds = mapView.mapboxMap.coordinateBounds(for: mapView.bounds) /// Including this line doesn't  release memory in swiftui, memory keep increasing on every launch of map
    }
```
