### ISSUE TITLE
Multiple calls to .insets() inconsistent results SwiftUI

### ISSUE THREAD

**Issue by richardjkeys** [mapbox/mapbox-maps-ios#2040]
## Environment

- Xcode version: 15
- iOS version: 17
- Devices affected: iPhone 15 pro
- Maps SDK Version: 11.0.0-beta.5

## Observed behavior and steps to reproduce

When initially setting a viewport with insets, the viewport is displayed as expected.

`self.viewport = .overview(geometry: route.lineString).inset(edges: .all, length: 30)`

![initial](https://github.com/mapbox/mapbox-maps-ios/assets/1065234/fbc8c1f6-6154-448d-a58c-cc50f68f7e68)

Changing the viewport seems to then work as expected:

`self.viewport = .followPuck(zoom: 18).inset(edges: .all, length: 30)`

![276748388-b4455940-8a83-46c1-94cf-6b44eb2e06b0](https://github.com/mapbox/mapbox-maps-ios/assets/1065234/f129502f-aee8-4bb6-b5c0-1bd1044b94d5)

If the viewport is then changed back to the initial viewport, the insets are now different (notice how the polyline is approximately double the distance from the horizontal edges).

`self.viewport = .overview(geometry: route.lineString).inset(edges: .all, length: 30)`

![route](https://github.com/mapbox/mapbox-maps-ios/assets/1065234/276acb1f-4d8c-4aaf-b90b-f57bccf6ed66)

## Expected behavior

The polyline ought to be in the same position upon both settings of the viewport, allowing developers to use insets to dodge UI elements, overlays etc whilst the focus of element(s) is consistent between viewport changes.

## Notes / preliminary analysis

Occurs whether or not viewport is animated

**Comment by persidskiy** [comment]
Hi @richardjkeys, thank you for the report! 

I was able to reproduce it locally, created and internal ticket https://mapbox.atlassian.net/browse/MAPSIOS-1151

**Comment by persidskiy** [comment]
@richardjkeys fixed in v11.0.0-beta.6 
https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.0.0-beta.6

**Comment by richardjkeys** [comment]
Excellent! Thank you. I'll give the new beta a try asap
