### ISSUE TITLE
Swift Package Manager installation instructions failing on Xcode 15

### ISSUE THREAD

**Issue by AttilaTheFun** [mapbox/mapbox-maps-ios#2041]
## Environment

- Xcode version: 15.0
- iOS version: 17.0
- Maps SDK Version: 10.16.1

## Observed behavior and steps to reproduce

I have followed the instructions to install the SDK with Swift Package Manager and the downloads are failing.
I have created the ~/.netrc file with the correct permissions and the error persists.

<img width="1108" alt="Screenshot 2023-10-22 at 7 12 28 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/3255391/94989525-970a-4619-855d-e87338832777">

## Expected behavior

I should be able to install the SDK by following the instructions

**Comment by david-buck** [comment]
I had this issue and the problem was my .netrc file, so it might be worth double checking there.

**Comment by AttilaTheFun** [comment]
@david-buck Thanks! I figured out I had used the public token in my .netrc instead of the private download token. I was able to download the SDK when invoking SPM on the command line, but Xcode was still failing. It fixed itself when I restarted Xcode.

As an aside, is it really necessary to authenticate the SDK download? I understand authenticating the API calls but MapBox is the only SDK I've ever used that required this. Given that it's open source, Github would happily host the files on the releases page: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#

The limits are 2GiB per file and you can have unlimited files per release (e.g. for different architectures -- they expect you would only use one). I'm sure MapBox is well within this limit. LLVM publishes multiple 700MB+ tar.gz archives for their releases: https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.3

**Comment by OgabekDev** [comment]
What is the solution? Please
