### ISSUE TITLE
Annotations positions and order

### ISSUE THREAD

**Issue by OrbitalTech** [mapbox/mapbox-maps-ios#2042]
## Environment

- Xcode version: 15.0.1
- iOS version: 17.0
- Devices affected:
- Maps SDK Version: 11.0.0 beta-5

## Observed behavior and steps to reproduce

I am rebuilding an IOS Application with swiftUI to use the latest mapbox API, what i observed and i couldn't figure out is how do you order annotations so that the user puck will always be on the highest lever?

In the example down below you can see my user puck moving and when we see a view annotation our user puck goes under it which makes it invisible for that time.

![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 13 13 49](https://github.com/mapbox/mapbox-maps-ios/assets/102740244/f7490653-b79d-4609-ab5a-1bbc80c3e900)

![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 13 13 48](https://github.com/mapbox/mapbox-maps-ios/assets/102740244/b6ce6ca5-21fb-421a-b739-29d9bfa3f989)

![Simulator Screenshot - iPhone 15 Pro - 2023-10-24 at 13 13 37](https://github.com/mapbox/mapbox-maps-ios/assets/102740244/9f3abfff-f5cc-4f32-a2a0-55b2ac376047)

The expected behavior is so that the user puck is always on top.

Here is the code for adding the map and annotations:

`@ViewBuilder private var content: some View {
        
        MapReader { proxy in
            Map(viewport: $viewPort, content: {
                
                ForEvery(reportViewModel.reports) { report in
                    ViewAnnotation(report.coordinate, allowOverlap: true, anchor: .bottom, offsetY: -5) {
                        ReportAnnotation(report: report)
                    }
                }
                
                if showUserPuck {
                    createPuck3D()
                }
                
            })
            .onCameraChanged(action: { camera in
                zoomLevel = camera.cameraState.zoom
                pitchLevel = camera.cameraState.pitch
            })
            .mapStyle(.standard(
                lightPreset: .dawn))
            .ornamentOptions(OrnamentOptions(
                scaleBar: ScaleBarViewOptions(visibility: .hidden),
                compass: CompassViewOptions(visibility: .hidden)))
            .onStyleLoaded(action: { _ in
                proxy.map.map { initStyleLayer($0) }
                configureMap()
            })
        }
    }`

**Comment by persidskiy** [comment]
@OrbitalTech Hi, you are using View Annotations, which are SwiftUI views that are rendered on top of the map. The Puck is  rendered inside the map (by metal), so view annotations are always above the Puck. 

If you want to place content inside the map, you use layer annotations https://docs.mapbox.com/ios/maps/api/11.0.0-beta.6-docc/documentation/mapboxmaps/swiftui-user-guide/#Layer-Annotations

Note: `onCameraChanged` triggers on every draw call, it's not recommended update state on every value change, it may lead to high CPU usage
