### ISSUE TITLE
Unlock the North/South Poles when rotating the globe

### ISSUE THREAD

**Issue by Gomu-iOS** [mapbox/mapbox-maps-ios#2049]
New Feature
As on the web version, it's possible to drag/rotate the globe without being locked by the North Pole and South Pole.

Why
Because it's available on the web version, and because it gives more freedom to the user to "play" with the globe to fully explore what shown on the map.
That would be amazing :-)

Thanks

**Comment by pjleonard37** [comment]
Hi @Gomu-iOS  -- 

On mobile you are able to flip the globe like on web by using two fingers. See below using our globe [example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/GlobeExample.swift). 

![Simulator Screenshot - iPhone 14 Plus - 2023-11-13 at 19 24 13](https://github.com/mapbox/mapbox-maps-ios/assets/7976026/72f7f1ef-82f1-48c7-8987-5b48b59a3117)

If this is not the feature you're looking for, can you share a bit more about what your need is?

**Comment by Gomu-iOS** [comment]
First of all, thank you very much for your reply，But this is not what I want
I want to be able to slide the Earth in different directions with one finger，like Google Earth Mobile
do you get me?

**Comment by pjleonard37** [comment]
Hi @Gomu-iOS -- 

I'm not sure what you mean. With the iOS Maps SDK you can pan around the earth with one finger and use two fingers to rotate the globe. I'd recommend downloading and building our examples app (linked in previous comment) to see the full functionality.

**Comment by Gomu-iOS** [comment]
Hi @pjleonard37 

I have downloaded and built this example. The two-finger rotation interaction with the globe is not what I want. I hope to achieve a rotation similar to the Google Earth app, where the globe rotates with a single finger
![Uploading demo.gif…]()

**Comment by Gomu-iOS** [comment]
Hi @pjleonard37

I have downloaded and built this example. The two-finger rotation interaction with the globe is not what I want. I hope to achieve a rotation similar to the Google Earth app, where the globe rotates with a single finger

https://github.com/mapbox/mapbox-maps-ios/assets/12077662/b0640af7-0560-4a69-be0f-5c4eec481c0f

**Comment by pjleonard37** [comment]
Hi @Gomu-iOS -- 

Thanks for clarifying. Our SDK is designed with [default gestures](https://docs.mapbox.com/ios/maps/guides/user-interaction/) (including the two-finger rotation) that serve the majority of use case. However, in an application you build with our SDK you can override these defaults if you would like a different experience (see [here](https://docs.mapbox.com/ios/maps/guides/user-interaction/#specify-custom-behavior)). Do note that writing custom gesture code can be quite complex and we are unable to provide support for any custom logic.

**Comment by Gomu-iOS** [comment]
你好@pjleonard37--
I have tried to solve this problem through custom gestures. as you said, this is a very complicated operation, so I failed. Therefore, I would like to ask you if you can add this requirement to your demo and provide Some implementation ideas, that would be very grateful

**Comment by pjleonard37** [comment]
Hi @Gomu-iOS - 

Our gestures are designed to handle a broad range of use cases so we cannot modify them or add this requirement to our demo. Further, we are not able to offer implementation ideas. If you need assistance with building your implementation I recommend subscribing to one of our [paid support plans](https://www.mapbox.com/support). 

As this repo is used for reporting issues with the Maps SDK itself, I'm going to close out this ticket.
