### ISSUE TITLE
mapView.viewport is not accessible as per the example in the documents

### ISSUE THREAD

**Issue by satyamrathor16** [mapbox/mapbox-maps-ios#2050]
## Environment

- Xcode version: 15.0
- iOS version: 17.0
- Devices affected: 
- Maps SDK Version: 10.1.2

## Observed behavior and steps to reproduce

<img width="784" alt="Screenshot 2023-11-08 at 10 47 13 AM" src="https://github.com/mapbox/mapbox-maps-ios/assets/87350503/598687ff-ffc3-4508-8bc7-f83a013f5566">

## Expected behavior

As per the documents the mapView.viewport should accessible directly. I need to follow the user location as they move and if we move the map with finger and then if we recenter the map it should start follow the user location again.

<img width="1416" alt="Screenshot 2023-11-08 at 10 50 12 AM" src="https://github.com/mapbox/mapbox-maps-ios/assets/87350503/8f4c9399-c51c-478e-9be6-c54bdb9b427d">

## Additional links and references

https://docs.mapbox.com/ios/maps/guides/user-location/#location-tracking

**Comment by maios** [comment]
Hi @satyamrathor16. Thank you for writing in, `Viewport` API is available in [v10.3.0](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.3.0) and the version you are using is v10.1.2, please update to newer versions of MapboxMaps iOS SDK to access more cool features and improvements.

**Comment by satyamrathor16** [comment]
@maios Thank you so much for information.
