### ISSUE TITLE
mapbox.mapbox-terrain-dem-v1 replaces mapbox.terrain-rgb request for altitude and returns the same data

### ISSUE THREAD

**Issue by sunhongjihaha** [mapbox/mapbox-maps-ios#2054]
![tips](https://github.com/mapbox/mapbox-maps-ios/assets/16420834/82c55a10-f0ee-4dde-9a19-efe9a10551c6)

mapbox.mapbox-terrain-dem-v1 is optimized over mapbox.terrain-rgb
[https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-dem-v1/](dem)
But I tried to use mapbox.mapbox-terrain-dem-v1 instead of mapbox.terrain-rgb to request altitude, and returned the same data, is this right? 

Is there other ways to get higher altitude accuracy?

**Comment by pjleonard37** [comment]
Hi @sunhongjihaha  -- 

This repo is for reporting bugs specifically in the [Mapbox Maps SDK for iOS](https://docs.mapbox.com/ios/maps/guides/). For your terrain-related questions, please write a Support question [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231) or write into our Discord server [here](https://discord.com/invite/uMpcC5RmJh).
