### ISSUE TITLE
Mac Catalyst Compilation fails

### ISSUE THREAD

**Issue by arthurschiller** [mapbox/mapbox-maps-ios#2055]
## Environment

- Xcode version: 15.1.0-Beta.3
- iOS version: Mac Catalyst, macOS Sonoma 14.1.1
- Devices affected:
- Maps SDK Version: v10.16.1, v11.0.0-rc.1

## Observed behavior and steps to reproduce
When I try to compile my app with a Mac Catalyst target, it fails indicating »'Polygon' is ambiguous for type lookup in this context«. With iOS as a target, things work fine. Is this a known issue?

## Expected behavior
It should compile successfully.

![Screenshot 2023-11-15 at 18 11 14](https://github.com/mapbox/mapbox-maps-ios/assets/3637723/8055bc58-ad2d-4954-8164-e4fada905fb8)
![Screenshot 2023-11-15 at 18 11 47](https://github.com/mapbox/mapbox-maps-ios/assets/3637723/b5ffa16c-7970-46b0-a01c-b6c01e788627)

**Comment by OdNairy** [comment]
Thank you for the head-ups. The fix will land soon in the `main` and `lts/v10` branches.

**Comment by arthurschiller** [comment]
Thank you, looking forward to it! 😊
