### ISSUE TITLE
Add visionOS Support

### ISSUE THREAD

**Issue by arthurschiller** [mapbox/mapbox-maps-ios#2056]
## New Feature
Currently when trying to use the mapbox SDK on visionOS I get the following build error:
**_…/mapbox-maps-ios/MapboxCoreMaps/MapboxCoreMaps.xcframework:1:1: While building for visionOS Simulator, no library for this platform was found in '…/artifacts/mapbox-maps-ios/MapboxCoreMaps/MapboxCoreMaps.xcframework'._**

## Why
I am building a Cross Apple Platform project and would like to display a mapbox map on visionOS.

**Comment by baleboy** [comment]
Thank for the report. Currently Vision OS is only supported in "Designed for iPad" mode. See https://github.com/mapbox/mapbox-maps-ios/issues/2028

Closing as duplicate.
