### ISSUE TITLE
Add emission support for raster layer

### ISSUE THREAD

**Issue by mic12130** [mapbox/mapbox-maps-ios#2065]
## New Feature
Before the v11, I use a separated map style with a dark color scheme to implement the dark mode. There were also some layers and annotations in different colors to display additional information. Now in v11 (11.0.0-rc2), I'm trying to implement the same thing using the standard style with a night light config:

``` swift
let mapStyle = MapStyle(uri: .standard, importConfigurations: [.standard(importId: "basemap", lightPreset: .night)])
```

After this, all layers and annotations turned into black (except point annotations, which use images). Then I found `LineLayer` and `FillLayer` can be rendered in their original colors by setting their emissive strength to 1.0. However, I cannot repeat this on the raster layer and annotations as they don't have such an emission support.

## Why
If I understand it correctly, it should be a common scene that applying night light config to implement a dark mode map, and it's also common to attach colorful elements for rich information. In this case, emission support would be necessary to avoid elements turning black.

**Comment by baleboy** [comment]
@mic12130 thanks for the report. We have added the `-emissiveStrength` attribute for `FillExtrusionLayer`, `HillShadeLayer` and `RasterLayer` in 11.1.0-beta.1, could you kindly confirm if this resolves your issue?

**Comment by mic12130** [comment]
I made a test on it and everything looks good. Thanks for your works : )
