### ISSUE TITLE
Expose utility functions for CoordinateBounds

### ISSUE THREAD

**Issue by kiryldz** [mapbox/mapbox-maps-ios#207]
## New Feature

Expose functions: `getCenter`, `contains`, `union`, `intersect`, `containsLatitude`, `containsLongitude`, `include`, `getLatitudeSpan`, `getLongitudeSpan` as extension functions for `CoordinateBounds`.

Full definition of Android `LatLngBounds`(ancestor for `CoordinateBounds`) could be found [here](https://github.com/mapbox/mapbox-gl-native-android/blob/main/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java) on Android platform. iOS equivalent for it in previous Maps version is `MGLCoordinateBounds` that also was exposing some functions but not truly aligned with Android.

## Why

Better parity with Android platform.

**Comment by NasH5169** [comment]
Hi all,

Any news on this topic?

Thanks!

**Comment by tobrun** [comment]
@macdrevx this landed upstream, is there any additional work left?

**Comment by macdrevx** [comment]
Yes, we intend to refine some of the new utilities for Swift.
