### ISSUE TITLE
Update geometry with coordinate of ViewAnnotation or ViewAnnotationOptions does change the view's position on the map

### ISSUE THREAD

**Issue by menghaozhang** [mapbox/mapbox-maps-ios#2074]
## Environment

- Xcode version: 15.0
- iOS version: 17.0
- Devices affected:
- Maps SDK Version: v 11.0.0

## Observed behavior and steps to reproduce
The view annotation position does not change after update the coordinate. For both using `ViewAnnotationOptions` and `ViewAnnotation`

**Using ViewAnnotation Options**
- Create a ViewAnnotationOptions with a coordinate for geometry, add the view annotation on the mapView `viewAnnotations`
- Update the coordinate on `annotatedFeature`
- Update the view Annotations with view and the options.

**Using ViewAnnotation**
- Create a ViewAnnotation with a coordinate for geometry, add the view annotation on the mapView `viewAnnotations`
- Update the coordinate on `annotatedFeature`
- Call `setNeedsUpdateSize()`. This is not optional, as we are not updating the size of view annotation, this step will not change the observed behavior.

If I move away from the view annotation, after the annotation is not visible on the map, and move back, the view annotation get updated.

## Expected behavior

No matter if the view annotation is visible or not. By either using `ViewAnnotationOptions` or `ViewAnnotation` the view annotation should  be updated to the new position. 

## Notes / preliminary analysis

It works on v11.0.0 beta.5

**Comment by persidskiy** [comment]
Hi @menghaozhang , thank you for the report. Do you have any minimal code sample where you see this bug?

**Comment by Tapestes** [comment]
Same problem here.  Latest version of iOS.  v11 of mapbox..

```
fileprivate let rangeRing:UIView
fileprivate var rangeRingView:ViewAnnotation
```

```
rangeRing = RangeRingAnnotationView(frame: CGRect(x: 0, y: 0, width: 400, height: 400))
rangeRingView = ViewAnnotation(coordinate: CLLocationCoordinate2D(latitude: 32.0, longitude: -81.0), view: rangeRing)
rangeRingView.variableAnchors = [ViewAnnotationAnchorConfig(anchor: .center, offsetX: 200, offsetY: -200)]
mapView.viewAnnotations.add(rangeRingView)
```

I use this function to update the position via the geometry:

```
internal func moveRangeRing(to coordinate:CLLocationCoordinate2D) { 
          self.rangeRingView.visible = false
          self.rangeRingView.annotatedFeature.geometry = Geometry(Point(coordinate))
  }
```

The view does not move.  However, I have a button that toggles `rangeRingView.visible`.   When I toggle the visible property, the view appears in the correct position.  However, it still does not update as new coordinates come in.  I've tried `setNeedsLayout` on the UIView, `setNeedsUpdateSize` on the ViewAnnotation, and running the update code on the main thread via `DispatchQueue.main {`.

**Comment by menghaozhang** [comment]
> Hi @menghaozhang , thank you for the report. Do you have any minimal code sample where you see this bug?

Hi @persidskiy, sorry for the late reply, but our use cases are similar to the post above, we just create a view annotation and add that to the map

```
let viewAnnotation = ViewAnnotation(
				annotatedFeature: AnnotatedFeature.geometry(Point (coordinate)), 
				view: animatedAnnotationView
			)
			
viewAnnotation.allowOverlap = true
viewAnnotation.visible = true
viewAnnotation.allowOverlapWithPuck = true
viewAnnotation.variableAnchors = [ViewAnnotationAnchorConfig(anchor: .center)]

mapView.viewAnnotations.add(viewAnnotation)
```

Then later we call modify the `viewAnnotation` to update the location whenever we need to, which is pretty often as for example, once per one second.
```
viewAnnotation.annotatedFeature.geometry = .point(Point(Newcoordinate))
```
But only when the `animatedAnnotationView` is not visible, it's location can get updated.

**Comment by persidskiy** [comment]
@menghaozhang @Tapestes 
Hi, thank you for the reports, I managed to reproduce the issue. In my case, it happens when I update position of the annotation while the map is decelerating after the pan gesture it can stuck and not update. If I drag the map without the deceleration animation, the position updates more stable.

Is it the same for you?

**Comment by Tapestes** [comment]
@persidskiy, the annotations are getting stuck for me without the pan gesture.  During updates to the annotation position, I am also updating the centerpoint of the map programmatically.  I was doing that with animation using either

`
lazy var cameraAnimator: BasicCameraAnimator = {
   mapView.camera.makeAnimator(duration: 0.85, curve: .linear) { (transition) in transition.center.toValue = coords }
}()
cameraAnimator.startAnimation()
`

or

`
let cam = mapView.mapboxMap.camera(for: bounds, padding: .zero, bearing: bearing, pitch: 0.0)
mapView.camera.ease(to: cam, duration: 0.85)
`

i tried setting the camera to move without animation via `self.mapView.mapboxMap.setCamera(to: CameraOptions(center: coords))` has no impact on failure of the annotation to update/move.  I'm updating the position of the annotation with `self.rangeRingView.annotatedFeature.geometry = .point(Point(coordinate))`.  As before, annotation moves to correct position when I toggle it's visibility on/off/on with `.visible`.

**Comment by persidskiy** [comment]
Thank you for the feedback, the issue should be fixed in the upcoming release

**Comment by Tapestes** [comment]
Awesome.  Thanks @persidskiy & co.

**Comment by persidskiy** [comment]
@Tapestes @menghaozhang release 11.1.0-rc.1 is out, please take a look at https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.1.0-rc.1.

Feel free to reopen the ticket if you notice any issues.

**Comment by menghaozhang** [comment]
Thank you @persidskiy we will try it out soon 🙌
