### ISSUE TITLE
PointAnnotationManager does not prevent duplicate ids from getting appended, and then causes weird behavior and eventually a crash

### ISSUE THREAD

**Issue by teradyl** [mapbox/mapbox-maps-ios#2077]
## Environment

- Xcode version: 15.0.1
- iOS version: 17.0.1
- Devices affected: Simulator
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

- Create PointAnnotationManager
- append a value to it with id string
- append same value to it with id string
- No warning is issued and the append is allowed, but then I noticed styleLoaded and mapLoaded callbacks stop responding after style changes. And eventually the app crashes.

## Expected behavior

- The 2nd value should not be added, throw a warning, fail, do something

**Comment by persidskiy** [comment]
Hi @teradyl, this is now solved in [`v11.2-beta.1`](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.2.0-beta.1), thank you for the report.
