### ISSUE TITLE
Unable to load custom MapStyle in SwiftUI

### ISSUE THREAD

**Issue by bradleypregon** [mapbox/mapbox-maps-ios#2079]
This issue may fall under the "under construction" icon in the SDK v11.0.0 SwiftUI User Guide documentation [Feature Support header](https://docs.mapbox.com/ios/maps/api/11.0.0/documentation/mapboxmaps/swiftui-user-guide/#Feature-support). Feel free to close this issue/question if it does fall under that category.

I'm unable to load a custom MapStyle in my SwiftUI app by following the example in the user guide:
`Map().mapStyle(MapStyle(uri: StyleURI(rawValue: "CUSTOM_STYLE_URI")!))`

I get an error saying I need to use rawValue instead of uri and drop StyleURI and use a string instead. 
<img width="507" alt="Screenshot 2023-12-12 at 6 58 23 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/93450292/840e2469-0377-41d6-9611-a29b88e62826">

Here is an example snippet: 
```
import SwiftUI
@_spi(Experimental) import MapboxMaps
struct TempMapView: View {
  private let style = "mapbox-custom-url"
  var body: some View {
    Map()
      // doesnt work. Error below
      .mapStyle(MapStyle(rawValue: style)!)
      
      // these both work and load the custom style, but awful quality and heavy aliasing
      .mapStyle(MapboxMaps.MapStyle(uri: StyleURI(rawValue: style)!))
      .mapStyle(.init(uri: StyleURI(rawValue: style)!))
  }
}
``` 
Using `.mapStyle(MapStyle(rawValue: style))` yields 'Cannot convert value of type 'MapStyle?' to expected argument type 'MapStyle'
Using `.mapStyle(MapStyle(rawValue: style)!)` yields 'Cannot convert value of type '(MyProductName).MapStyle' to expected argument type 'MapboxMaps.MapStyle'

Using either of the latter .mapStyle() in my snippet both work, but the text and administrative boundary quality in the map are quite poor.

Using UIViewRepresentable works fine, and the quality is great:
```
import SwiftUI
import MapboxMaps
struct MapboxView: UIViewRepresentable {
  let mapView = MapView(frame: .zero)
  func makeUIView(context: Context) -> MapView {
    mapView.mapboxMap.styleURI = StyleURI(rawValue: "mapbox-custom-url")
    return mapView
  }
  func updateUIView(_ uiView: UIViewType, context: Context) { }
}
```
This leads me to believe that this issue does fall under that "under construction" category in the SwiftUI docs. I'm just wanting to confirm my suspicion since I haven't found much else about it.

I'm not a SwiftUI pro, let me know if I'm blatantly missing or misunderstanding something in my snippet

**Comment by persidskiy** [comment]
@bradleypregon Hi, thank you for this report.

You are doing it right, the `MapStyle` is designed as a "StyleURI + some additional information". In fact, when you use
```
mapView.mapboxMap.styleURI = StyleURI(rawValue: "mapbox-custom-url")
```
the uri gets converted to `MapStyle` under the hood. So there shouldn't be any difference between using the `MapStyle` or `StyleURI` directly.

If you see any rendering artifacts, they are most likely mean that there is a rendering issue. Can you please provide more context, what is the style you are using (if it's public) and what is the expectation/result?

**Comment by bradleypregon** [comment]
@persidskiy Thank you for that information. You can disregard my comments about the map quality discrepancy - it was an "issue" with my own computer screen resolution, and I think I was just tired and rambling.

Actually, with your info, I don't think I have an issue at all then - I'm still able to load my custom style regardless, and I think it's safe to assume the SwiftUI implementation is still in development, which isn't severely impacting me at all. I was just curious why the error using the first `.mapStyle(MapStyle())` method as I like to try to follow things by the book 

I'm on Xcode 15.0.1 with Swift 5 (if that is of significance). Feel free to close unless you wanted more info from me

**Comment by persidskiy** [comment]
>  I was just curious why the error using the first .mapStyle(MapStyle(uri:)) method as I like to try to follow things by the book

The `MapStyle(uri:)` initializer expects `StyleURI` to be passed to `uri` parameter, not a string. 
What book do you mean? Did you see the official documentation where a string is passed instead of the `StyleURI`?
