### ISSUE TITLE
PointAnnotation.userInfo change in v11 silently breaks apps

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#2090]
Before v11, PointAnnotation's userInfo field was a [String: Any]:

https://github.com/mapbox/mapbox-maps-ios/blame/8d1b597fad2985e8bd9422452796aaa086a23741/Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift#L18

In v11, it is still declared as the same type, however, it is internally stored as JSON:

https://github.com/mapbox/mapbox-maps-ios/blame/71e6dbedfa254c30d41745b58870396351869f3b/Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift#L46

This has two problematic effects:

1. If one attempts to store a non-JSON-encodable object in userInfo as an Any value, it is silently converted to nil.
2. It is now inconvenient and inefficient to modify userInfo by adding or changing a single field, since the previous value is entirely overwritten when calling set(). 

Effect #1 is especially bad, since I was using it to store the application-defined object associated with the annotation.  This object is large and not JSON-encodable.  Now, in order to know what object is referred to when (e.g.) a user clicks on an annotation, I would have to maintain my own external map of annotation to application-defined object, which is a significant change to my architecture, because I have a wrapper that hides the Google vs. Mapbox differences, and in the Google API, the corresponding userData field is an Any (i.e. no external map is necessary).

This seems to be undocumented and doesn't match the contract in the Annotation parent interface, where userInfo is simply a [String: Any].  I also don't see a mention of it in the "Migration to v11" page or the v11.0.0 changelog.

**Comment by baleboy** [comment]
Appears to be a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/2059

**Comment by akirmse** [comment]
Closing as duplicate.
