### ISSUE TITLE
Blended polyline colors

### ISSUE THREAD

**Issue by konstantin-tcherkashin** [mapbox/mapbox-maps-ios#2091]
## Environment

- Xcode version: 15.2
- iOS version: 17.0
- Devices affected: any
- Maps SDK Version: 11.0

## Observed behavior and steps to reproduce

Standard (3d) map in night mode applies blending to polyline colors to darken them. No way to preserve normal contrast ratio currently.

## Expected behavior

Polyline colors are always displayed unmodified

-----
Day mode: original color preserved; Night mode - color is darkened so that polyline is barely visible
[
![Simulator Screenshot - iPhone 15 - 2024-01-08 at 18 47 29](https://github.com/mapbox/mapbox-maps-ios/assets/19354777/bcc2e8a2-9966-4826-9c3d-81d23bf70571)
](url)

![Simulator Screenshot - iPhone 15 - 2024-01-08 at 18 47 34](https://github.com/mapbox/mapbox-maps-ios/assets/19354777/c2c5990e-2f3f-4e32-9564-c05c8486acc5)

**Comment by baleboy** [comment]
All layers and features respond to light when using Mapbox Standard, so with less light your route line will be darker. To prevent this, you need to use the [line-emissive-strength](https://docs.mapbox.com/style-spec/reference/light/#-emissive-strength-paint-property) property, see https://docs.mapbox.com/ios/maps/guides/styles/style-layers/#light-driven-styling-in-standard
