### ISSUE TITLE
How to handle Tap Gesture on clustered PointAnnotation in SwiftUI?

### ISSUE THREAD

**Issue by danielhogl** [mapbox/mapbox-maps-ios#2092]
I am using version `11.1.0-rc.1` with the new SwiftUI support. However, it seems like I can't figure out how I can handle a tap gesture on a clustered `PointAnnotationGroup`. Basically, I have a `PointAnnotationGroup` with `ClusterOptions` set and when tapping on a cluster, I want to zoom in to reveal the PointAnnotations within the cluster. 

```
Map(viewport: $viewport) {
   PointAnnotationGroup(locations) { location in
      PointAnnotation(coordinate: location.adress.coordinate)
         .image(pinIcon)
         .onTapGesture {
              viewModel.action(.selectLocation(location))
         }
   }
   .clusterOptions(options)
}
```

I can implement `onTapGesture ` on the `PointAnnotation`, which works fine, but how to achieve that, when those are clustered? I've seen the `.onLayerTapGesture` on `Map`, however clusters are not rendered on a separate layer I guess, so this also does not help.

I feel like this should be easy to achieve, but I am overlooking something. Any help is very appreciated.

**Comment by persidskiy** [comment]
Hi @danielhogl, thank you for the feedback! It helps us understand user demand for the feature.

This use case should be easy to achieve; however, this feature was omitted in the initial release of SwiftUI support. We have it in backlog [MAPSIOS-1193](https://mapbox.atlassian.net/browse/MAPSIOS-1193).

Can I also ask a little bit more about your particular use case? What do you want to do when the user taps the cluster? Do you want to "uncluster the cluster," meaning zoom in to the minimum zoom level that will uncluster the cluster? Or do you want to perform some custom action?

As a workaround right now, you can do something like that:

```swift
let layerId = "my-layer-id"
Map {
    PointAnnotationGroup {
        PointAnnotation(point: ...)
    }
    .layerId(layerId)
}
.onLayerTapGesture("mapbox-iOS-cluster-circle-layer-manager-\(layerId)") { feature, context in
    print("cluster layer is tapped")
    return true
}
```

**Comment by danielhogl** [comment]
Yes exactly, I want to zoom in to the zoom level that shows all points unclustered.

I just tried out your suggestions and with that I can at least intercept the tap on a cluster successfully - thank you very much for that already. However, I am wondering where the `mapbox-iOS-cluster-circle-layer-manager-` prefix for the `layerId` comes from? 😅 Is there some documentation on these prefixes or are these internal and actually not intended to be used in that way? Because I tried the approach with the layer id previously but of course I did not know that this prefix is needed and without it, it didn't work.

Also do you have a suggestion on how I could find out which zoom level is required to show all points unclustered inside of the `onLayerTapGesture` closure?

**Comment by persidskiy** [comment]
Great to hear, that helps!

> I am wondering where the mapbox-iOS-cluster-circle-layer-manager- prefix for the layerId comes from?

That's an internal non-documented thing, coming from the actual implementation of `PointAnnotaitonManager` https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift#L164

The prefix may change over time, as it's not a public API, but realistically, chances are low.

> Also do you have a suggestion on how I could find out which zoom level is required to show all points unclustered inside of the onLayerTapGesture closure?

Yes, you can use [`getGeoJsonClusterExpansionZoom`](https://docs.mapbox.com/ios/maps/api/11.0.0/documentation/mapboxmaps/mapboxmap/getgeojsonclusterexpansionzoom(forsourceid:feature:completion:)) to find that zoom level. However, it's a little bit more complex:

```swift
struct ClusterExpansion: View {
    @State var viewport = Viewport.styleDefault
    var body: some View {
        let layerId = "my-layer-id"
        MapReader { proxy in
            Map(viewport: $viewport) {
                PointAnnotationGroup {
                    PointAnnotation(...)
                }
                .clusterOptions(...)
                .layerId(layerId)
            }
            .onLayerTapGesture("mapbox-iOS-cluster-circle-layer-manager-my-layer") { queriedFeature, context in
                let cluster = queriedFeature.feature
                guard let map = proxy.map,
                    case let .point(clusterCenter) = cluster.geometry else { return false }

                // Effectively, sourceId is equal to layerId in annotations.
                map.getGeoJsonClusterExpansionZoom(forSourceId: layerId, feature: cluster) { result in
                    switch result {
                    case .success(let zoomLevel):
                        withViewportAnimation {
                            viewport = .camera(
                                center: clusterCenter.coordinates,
                                zoom: zoomLevel.value as? CGFloat)
                        }
                    case .failure(let error):
                        print("An error occurred: \(error.localizedDescription)")
                    }
                }
                return true
            }
        }
    }
}

```

**Comment by danielhogl** [comment]
Awesome, this seems to work 🎉  Thank you so much!
Still hope, that this feature will come out of the box any time soon instead of having to use a private API, but for now this is fine.

**Comment by aleksproger** [comment]
@danielhogl we now made it possible to achieve this behaviour out of the box, so you may already try it out in the main branch :)
