### ISSUE TITLE
Zoom levels are not respected

### ISSUE THREAD

**Issue by shahrukh-sc** [mapbox/mapbox-maps-ios#2094]
## Environment
- Xcode version: 15.0
- iOS version: 17.0
- Devices affected: i assume all
- Maps SDK Version: MapboxMaps 10.16.1

## Observed behavior and steps to reproduce
So, we are migrating to `MapboxMaps` from `GoogleMaps` with MapsIndoors.

When we get a venue, we set the min & max zoom levels & restrict Map to the bounds of the venue, but it seems like zoom levels are not respected.

### Code before (GoogleMaps)
```
let bounds = GMSCoordinateBounds(
    coordinate: venue.boundingBox.northEast,
    coordinate: venue.boundingBox.southWest
)

mapView.setMinZoom(15, maxZoom: 25)

mapView.cameraTargetBounds = bounds
mapView.animate(with: GMSCameraUpdate.fit(bounds))
```

### Code after (MapboxMaps)
```
/// Create `bounds` from `venue`
let bounds = CoordinateBounds(
    southwest: venue.boundingBox.southWest,
    northeast: venue.boundingBox.northEast
)
let boundsOptions = CameraBoundsOptions(bounds: bounds, maxZoom: 25.0, minZoom: 15.0)
/// Restrict the camera to `bounds`
try? mapView.mapboxMap.setCameraBounds(with: boundsOptions)
/// Center the camera on the `bounds`
/// Set initial zoom level
let cameraOptions = CameraOptions(center: bounds.center, zoom: 15.0)
mapView.mapboxMap.setCamera(to: cameraOptions)
/// Animate the camera's center coordinate
mapView.camera.ease(to: cameraOptions, duration: 1) { [weak self] _ in
    guard let self = self else { return }
    print("Camera Zoom:", mapView.mapboxMap.cameraState.zoom) // Prints => Camera Zoom: 12.554753418064262
}
```
even if i change the `CameraBoundsOptions`'s `minZoom` to 1, `CameraOptions`'s `zoom` to 1, map looks the same

## Expected behavior
I was expecting it should look the same (what we had before with GoogleMaps & now with MapboxMaps), but it doesn't.

![Comparison b:w GoogleMaps   Mapbox](https://github.com/mapbox/mapbox-maps-ios/assets/92019520/7277af83-096a-4e0b-9f6e-00ac84c69424)

**Comment by pjleonard37** [comment]
Hi @shahrukh-sc  -- 

Thanks for reporting this issue with this level of detail. I have tried to reproduce this issue on my side, but so far I've not been able to. To help me investigate further, could you share a specific set of example bounds? 

> let bounds = CoordinateBounds(
>     southwest: venue.boundingBox.southWest,
>     northeast: venue.boundingBox.northEast
> )

Additionally, we did make a small bug fix for the `setCameraBounds` function in our latest v10 release. Could you try upgrading to v[10.16.4](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.16.4) and confirm if the issue reproduces there?

**Comment by shahrukh-sc** [comment]
Bounds Debug info
------------
southwest: CLLocationCoordinate2D(latitude: 25.2205139, longitude: 55.2844522)
northeast: CLLocationCoordinate2D(latitude: 25.2275563, longitude: 55.2919314)
center: CLLocationCoordinate2D(latitude: 25.224035100000002, longitude: 55.2881918)
latitudeSpan: 0.00704239999999956
longitudeSpan: 0.007479200000005903

Unfortunately we can't go to 10.16.4 as we use MapsIndoorsMapBox pod latest version which restricts it to 10.16.1. I will try in as sample project with manual XCFrameworks integration & come back to you.

**Comment by shahrukh-sc** [comment]
I tried using local MapsIndoorsMapBox Podspec & changing version of MapBoxMaps to 10.16.4, the result is still the same. So, the issue is still there.

**Comment by pjleonard37** [comment]
Hi @shahrukh-sc  -- thanks for checking on that. We're taking a deeper look into this issue now.

**Comment by pjleonard37** [comment]
Hi @shahrukh-sc -- 

I took a deeper look at this today and I'm still not able to reproduce the issue you are seeing. Starting with the [RestrictCoordinateBoundsExample](https://github.com/mapbox/mapbox-maps-ios/blob/v10.16.4/Apps/Examples/Examples/All%20Examples/RestrictCoordinateBoundsExample.swift) from the v10.16 version of our [examples app](https://github.com/mapbox/mapbox-maps-ios/tree/v10.16.4/Apps/Examples), I made the below changes to replicate your implementation. With the below code I get a zoom level between 15 and 25 (specifically 16.3518). If I adjust the min zoom to 17 then the printed zoom level is 17. 

```
    override func viewDidLoad() {
        super.viewDidLoad()

        let mapView = MapView(frame: view.bounds)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(mapView)

        /// Create `bounds` from `venue`
        let bounds = CoordinateBounds(
            southwest: CLLocationCoordinate2D(latitude: 25.2205139, longitude: 55.2844522),
            northeast: CLLocationCoordinate2D(latitude: 25.2275563, longitude: 55.2919314)
        )
        let boundsOptions = CameraBoundsOptions(bounds: bounds, maxZoom: 25.0, minZoom: 15.0)
        /// Restrict the camera to `bounds`
        try? mapView.mapboxMap.setCameraBounds(with: boundsOptions)
        /// Center the camera on the `bounds`
        /// Set initial zoom level
        let cameraOptions = CameraOptions(center: bounds.center, zoom: 15.0)
        mapView.mapboxMap.setCamera(to: cameraOptions)
        /// Animate the camera's center coordinate
        mapView.camera.ease(to: cameraOptions, duration: 1) { [weak self] _ in
            guard let self = self else { return }
            print("Camera Zoom:", mapView.mapboxMap.cameraState.zoom) 
        }
    }
```

Is it possible that your existing code is affecting the zoom level or camera options from another place? Alternatively, is it possible for you to send a minimum code sample which reproduces the issue? 

One side note: the [highest zoom level for Mapbox is 22](https://docs.mapbox.com/help/glossary/zoom-level/) (rather than 25).

**Comment by shahrukh-sc** [comment]
@pjleonard37 Thanks for taking a deeper look, I will try the Example app & get back to you 👍

**Comment by shahrukh-sc** [comment]
@pjleonard37 I tried the example app, i think i kind of understand it better now

> With the below code I get a zoom level between 15 and 25 (specifically _16.3518_)

I was thinking if I set `minZoom` of **_CameraBoundsOptions_** & `zoom` of **_CameraOptions_** both to say 1, then `print("Camera Zoom:", mapView.mapboxMap.cameraState.zoom)` should always print 1.
I guess it depends on the `CoordinateBounds` also what can be the min zoom, for my `CoordinateBounds`, i think it can't go below _16.3518_. Could you confirm?

> If I adjust the min zoom to 17 then the printed zoom level is 17.

It works fine for higher zoom levels than _16.3518_

**Comment by pjleonard37** [comment]
> I guess it depends on the CoordinateBounds also what can be the min zoom, for my CoordinateBounds, i think it can't go below 16.3518. Could you confirm?

That's right -- you can see that by removing the `CoordinateBounds` from your example and just setting `minZoom` on `CameraBoundsOptions`.

**Comment by shahrukh-sc** [comment]
Thanks @pjleonard37, i think now i understand, i will close the issue then
