### ISSUE TITLE
Mapview shaking while zooming in-out

### ISSUE THREAD

**Issue by OffsureDev** [mapbox/mapbox-maps-ios#2103]
## Environment

* Xcode version: 15.0.1
* iOS version: 16.0
* Devices affected: any
* Maps SDK Version: 10.16.3

## Observed behavior and steps to reproduce

MapView is shaking while zooming in-out with two fingers on 3D mode. This issue is also available in Mapbox's official GitHub demo project(v10.16.3)

## Expected behavior

It should render smoothly while zooming. without any stuttering.

## issue video link

 https://github.com/mapbox/mapbox-maps-ios/assets/132354035/0af8ab96-1903-4c20-8028-e43b4de81ebe

**Comment by persidskiy** [comment]
Hi @OffsureDev, this issue is resolved in v11+. The fix won't be ported back to v10.16 as it requires substantial changes in rendering. Please, consider updating to v11.

**Comment by OffsureDev** [comment]
@persidskiy Thanks for update :)
