### ISSUE TITLE
onCameraChange

### ISSUE THREAD

**Issue by Tapestes** [mapbox/mapbox-maps-ios#2105]
## Environment

- Xcode version: 15.5
- iOS version: 17.2
- Maps SDK Version: 11.1

With the following code, I see onCameraChanged events firing about once a second, even when the camera is not moving.  Update occurs many times a second when the camera is moving.

```
@_spi(Experimental) import MapboxMaps

class MapBoxViewController: {
    fileprivate let mapView:MapView
    fileprivate var cancelables = Set<AnyCancelable>()

    init(mapView:MapView) {
        self.mapView = mapView
    
        mapView.mapboxMap.onCameraChanged.observe { [weak self] event in
            guard let self = self else { return }
            print("🛟 change")
        }.store(in: &cancelables)
    }
}
```

My question is, is this expected behavior (once a second updates when the camera stationary)?  If so, is there any way to determine if the camera has in fact moved?  That is, a way to get the cameraState prior to the onCameraChanged event (something like, onCameraWillChange).   Thanks.

**Comment by Tapestes** [comment]
@pjleonard37, thanks for the help.  Read something in the docs that lead me to believe there could be updates without the camera moving.  But, based on your info, I'm good to go.

**Comment by pjleonard37** [comment]
Sounds good 👍
