### ISSUE TITLE
Location puck makes ViewAnnotation disappear if nearby/overlaps

### ISSUE THREAD

**Issue by brendanw** [mapbox/mapbox-maps-ios#2109]
## Environment

- Xcode version: 15.1
- iOS version: 17.2
- Devices affected: iphone 15 pro simulator (also can reproduce on Pixel 7 Pro emulator)
- Maps SDK Version: 11.1.0 (also reproduced on latest beta)

## Observed behavior and steps to reproduce
Here, I am intentionally enabling/disabling the location puck every 2s to demonstrate the bug:
![2024-02-02 18 34 04](https://github.com/mapbox/mapbox-maps-ios/assets/585321/bde7a6b5-1682-4429-9a16-b94d92d454ac)

## Expected behavior

ViewAnnotation should be able to be displayed at the same time as the puck regardless of proximity to puck or overlap.

## Notes / preliminary analysis

You'll need to spoof location on simulator (or emulator) near where a ViewAnnotation is displayed.

This seems to be out of my hands. The best hack I could come up with to allow users to tap the ViewAnnotation is to remove the puck for regular time intervals. It's hacky but will work until their is an underlying library fix.

**Comment by persidskiy** [comment]
Hi @brendanw , can you try setting this flat to true?https://docs.mapbox.com/ios/maps/api/11.2.0-beta.1/documentation/mapboxmaps/viewannotation/allowoverlapwithpuck

**Comment by persidskiy** [comment]
I'm closing this issue as the suggested property should fix it. @brendanw  If it doesn't work, feel free to open this ticket again.

**Comment by brendanw** [comment]
@persidskiy this worked. thank you!
