### ISSUE TITLE
The function that calculates "CameraOptions" to fit a list of coordinates is not setting the padding correctly.

### ISSUE THREAD

**Issue by nalonluana** [mapbox/mapbox-maps-ios#2120]
## Environment

- Xcode version: 15.2
- iOS version: 17.0.3
- Devices affected: iPhone XR
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

After invoking the function that calculates the "CameraOptions" to fit a list of coordinates with a given padding, the returned value has the padding set to null: 
![mapboxBug](https://github.com/mapbox/mapbox-maps-ios/assets/72439806/723bf100-cfa9-486f-98ec-756ffe46ac51)

## Expected behavior

The pading value should be the one passed in the function parameter.

**Comment by aleksproger** [comment]
Hi, @nalonluana thanks for report, I confirm that I was able to reproduce the issue
Created internal ticket for tracking https://mapbox.atlassian.net/browse/MAPSNAT-1797

**Comment by nalonluana** [comment]
Hi, thanks, does anyone know of a workaround I can do to get a result similar to this function?

**Comment by aleksproger** [comment]
@nalonluana actually after discussing with a team we realized that it's correct behaviour (I agree it's very very unobvious and we will address it). Please use [this method](https://docs.mapbox.com/ios/maps/api/11.2.0-beta.1/documentation/mapboxmaps/mapboxmap/camera(for:camera:coordinatespadding:maxzoom:offset:)) instead, it has a better docs and slightly different arguments.
Please, check it out and let me now whether it solves your problem.
The `camera padding` is returned in `CameraOptions` object, but `coordinates padding` is a different thing
