### ISSUE TITLE
ViewAnnotation offset

### ISSUE THREAD

**Issue by miacando** [mapbox/mapbox-maps-ios#2121]
## Environment

- Xcode version: 15.0.1 (15A507)
- iOS version: 17.0
- Devices affected: iPhone Simulator
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce
In v10, I could set the ViewAnnotation offset using:
```
    let options = ViewAnnotationOptions(
            geometry: Point(location),
            width: 50,
            height: 50,
            allowOverlap: true,
            anchor: .center,
            offsetY: 38
    )
```
But the usage is deprecated.
How do I set the offset in V11? I found no property in the new implementation that allows me to set the offset.

## Expected behavior
Being able to set offsets for ViewAnnotations

**Comment by aleksproger** [comment]
Hi👋, @miacando 

The functionality you are interested in may by achieved by setting the `var anchorConfig: ViewAnnotationAnchorConfig?` property of `ViewAnnotation`.
`ViewAnnotationAnchorConfig` exactly serves the purpose of specifying anchoring and offsets for your view annotations.
You may also take a look at `var variableAnchors: [ViewAnnotationAnchorConfig]` property depending on your use case

Feel free to close the issue if the above solutions fits well for you.

**Comment by irra-yoonet** [comment]
Thanks @aleksproger!
Was able to do it using:
`viewAnnotation.variableAnchors = [.init(anchor: .center, offsetY: 38)]`

**Comment by miacando** [comment]
Thanks @aleksproger!
Was able to do it using:
`viewAnnotation.variableAnchors = [.init(anchor: .center, offsetY: 38)]`

**Comment by miacando** [comment]
Thanks @aleksproger!
Was able to do it using:
`viewAnnotation.variableAnchors = [.init(anchor: .center, offsetY: 38)]`
