### ISSUE TITLE
map fly shake

### ISSUE THREAD

**Issue by Gomu-iOS** [mapbox/mapbox-maps-ios#2129]
## Environment

- Xcode version:  14.3.1
- iOS version:  16.5.1
- Devices affected:  iPhone12
- Maps SDK Version:  11.1.0

## Observed behavior and steps to reproduce

method inside the TerrainExample class in the demo project provided by you，call the `mapView.camera.fly(to..)`

code image
![307645764-ce45306c-b587-4b6a-96c3-c057bf0e7cb2](https://github.com/mapbox/mapbox-maps-ios/assets/12077662/d2c0bbb6-9c48-4f15-99de-9ae3b2cfe8fe)

error video

https://github.com/mapbox/mapbox-maps-ios/assets/12077662/078f495f-dfd3-487f-9790-a9412fb25205

**Comment by aleksproger** [comment]
Hey, @Gomu-iOS thanks for submitting the issue, created an internal [ticket](https://mapbox.atlassian.net/browse/MAPSIOS-1355?atlOrigin=eyJpIjoiOWI3NjE0MGVlZTkwNDM4OTk2YWUyNTQ4NTdlMGM0ODciLCJwIjoiamlyYS1zbGFjay1pbnQifQ) to follow this issue

**Comment by aleksproger** [comment]
After discussing it as a team decided that current behaviour is correct and if you want to have smooth fly(to:) animation then before doing animation you should switch from` .terrain` centerAltitudeMode to `.sea`. That will mean that camera will ignore any terrain elevations.
```swift
mapView.mapboxMap.centerAltitudeMode = .sea
mapView.camera.fly(to:)
mapView.mapboxMap.centerAltitudeMode = .terrain
```
