### ISSUE TITLE
SwiftUI - onMapTapGesture triggers even though a MapViewAnnotation has already handled the tap

### ISSUE THREAD

**Issue by MaartenDEV** [mapbox/mapbox-maps-ios#2132]
## Environment

- Xcode version: 15.2
- iOS version: 17.3.1
- Devices affected: iOS
- Maps SDK Version: 11.1.0

## Observed behavior and steps to reproduce

The .onMapTapGesture modifier on a MapView triggers, even though a MapViewAnnotation within the MapView already handles it using a .tapGesture modifier. 
The docs say 'The given action will be executed when other map gestures (such as quick zoom) failed, **and no annotation or layer have handled the tap**.' (https://docs.tilestream.net/ios/maps/api/latest/documentation/mapboxmaps/map/onmaptapgesture(perform:))

## Code example:
```
Map(viewPort: $viewPort) {
                    MapViewAnnotation(coordinate: coordinates) {
                        Circle()
                            .fill(Color.red)
                            .onTapGesture {
                                print("Annotation tap")
                            }
                    }
                }
                .onMapTapGesture {
                    print("Map tap")
                }
```

When tapping the annotation, this produces
```
Annotation tap
Map tap
```

**Comment by aleksproger** [comment]
Hey, @MaartenDEV this is a known problem which we're currently working
Thank you for filling issue and I'll update you after the fix will be landed.
