### ISSUE TITLE
Reset mapView's location provider

### ISSUE THREAD

**Issue by miacando** [mapbox/mapbox-maps-ios#2137]
At one point I override the mapView's location provider to customise the heading with:

```
mapView.location.override(
    locationProvider: Signal(just: [
          Location(coordinate: coordinate)
    ]),
    headingProvider: Signal(just: Heading(direction: direction, accuracy: 0)))
mapView.location.options = LocationOptions(puckType: .puck2D(.makeDefault(showBearing: true)),
                                                     puckBearing: .heading,
                                                     puckBearingEnabled: true)
```

I tried resetting the mapView.location.options but the accuracy would always return nil and the customised heading would also stay.

With this I want to reset the location provider to get the realtime location and heading again. How do I do this without reinitialising the mapView?

**Comment by aleksproger** [comment]
Hey, @miacando you may achieve this by using `AppleLocationProvider()`
```swift
mapView.location.override(provider: AppleLocationProvider())
```

**Comment by miacando** [comment]
I see, never thought of that. Thank you!
