### ISSUE TITLE
Retaining offline packs when upgrading SDK

### ISSUE THREAD

**Issue by crtsajnic-k** [mapbox/mapbox-maps-ios#2139]
We're currently in the process of upgrading Mapbox SDK from v6 to v10/v11 and were wondering if there is currently a way for the user to retain the downloaded offline packs. I did find an example in the [Migrate to v10](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/#retaining-your-offline-cache-from-previous-maps-sdk-versions) section of the documentation but had no success when trying out the provided code.

From what I could gather after observing the file system on a simulator, SDK v10.16.4/v11.X don't have the same file structure as v6.X when storing offline packs on the device. Is there any possibility to retain the offline pack data?

**Comment by pjleonard37** [comment]
Hi @crtsajnic-k - 

Glad to hear you are upgrading! The offline migration process across multiple versions can require some additional modifications. Can you please submit a technical support request via the form [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231)? That way our [Support team](https://www.mapbox.com/support) can review your report and work with you on next steps.
