### ISSUE TITLE
Mapbox crash on orientation change

### ISSUE THREAD

**Issue by crtsajnic-k** [mapbox/mapbox-maps-ios#2142]
## Environment

- Xcode version: 15.3
- iOS version: tried on iOS 16 and iOS 17
- Devices affected: tried on iPhone X and iPhone 12
- Maps SDK Version: 11.2

## Observed behavior and steps to reproduce
In some views on our app where we use the MapView component, a random crash occurs on this location when the devices orientation changes:
<img width="740" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/160708957/01533639-0b55-4154-9d91-1a203ac04ed0">

We unfortunately couldn't find a reliable explanation on why it happens only on certain view controllers.

## Expected behavior
No crash should happen, just like on v10 of Mapbox SDK.

## Notes / preliminary analysis
Seems to be the same error as [HERE](https://github.com/mapbox/mapbox-maps-flutter/issues/432)

## Additional links and references
<img width="676" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/160708957/e0b906fe-fbfe-4129-8932-2d31a5e7e417">

Stacktrace:
<img width="447" alt="image" src="https://github.com/mapbox/mapbox-maps-ios/assets/160708957/275b4248-2d11-4dae-965a-b79e84062283">

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000018891e524 in _swift_runtime_on_report ()
#1	0x00000001889d3460 in _swift_stdlib_reportFatalErrorInFile ()
#2	0x00000001885b26fc in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) ()
#3	0x00000001885b19f0 in _assertionFailure(_:_:file:line:flags:) ()
#4	0x0000000109db4218 in MapView.updateDrawableSize(to:) at {REDACTED_INFO}/Pods/MapboxMaps/Sources/MapboxMaps/Foundation/MapView.swift:589
#5	0x0000000109db5ccc in MapView.sizeTrackingLayer(layer:completeResizingFrom:to:) at {REDACTED_INFO}/Pods/MapboxMaps/Sources/MapboxMaps/Foundation/MapView.swift:703
#6	0x0000000109db5d28 in protocol witness for SizeTrackingLayerDelegate.sizeTrackingLayer(layer:completeResizingFrom:to:) in conformance MapView ()
#7	0x0000000109ede694 in closure #1 in SizeTrackingLayer.bounds.didset at {REDACTED_INFO}/Pods/MapboxMaps/Sources/MapboxMaps/Foundation/SizeTrackingLayer.swift:42
#8	0x0000000109c1ff18 in thunk for @escaping @callee_guaranteed () -> () ()
#9	0x0000000107d94b98 in _dispatch_call_block_and_release ()
#10	0x0000000107d967bc in _dispatch_client_callout ()
#11	0x0000000107da6d58 in _dispatch_main_queue_drain ()
#12	0x0000000107da690c in _dispatch_main_queue_callback_4CF ()
#13	0x0000000189c9d51c in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#14	0x0000000189c9a218 in __CFRunLoopRun ()
#15	0x0000000189c99968 in CFRunLoopRunSpecific ()
#16	0x00000001cdf974e0 in GSEventRunModal ()
#17	0x000000018c10cedc in -[UIApplication _run] ()
#18	0x000000018c10c518 in UIApplicationMain ()
#19	0x000000010163e8c8 in main at {REDACTED_INFO}/AppDelegate.swift:39
#20	0x00000001ad1bad84 in start ()
Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
#0	0x0000000107d9b448 in dispatch_async ()
#1	0x000000018b4d3cec in CA::Transaction::Continuation::unref() ()
#2	0x000000018b353bf8 in schedule_stop_callback(LayerAnimation*, LayerAnimationState*) ()
#3	0x000000018b306c30 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#4	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#5	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#6	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#7	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#8	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#9	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#10	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#11	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#12	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#13	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#14	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#15	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#16	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#17	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#18	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#19	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#20	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#21	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#22	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#23	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#24	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#25	0x000000018b306f28 in CA::Layer::collect_animations_(double, double*, CA::Layer::CollectAnimationsData*) ()
#26	0x000000018b3486e4 in CA::Context::commit_transaction(CA::Transaction*, double, double*) ()
#27	0x000000018b33f1bc in CA::Transaction::commit() ()
#28	0x000000018b33ee64 in CA::Transaction::flush_as_runloop_observer(bool) ()
#29	0x000000018bf8d260 in _UIApplicationFlushCATransaction ()
#30	0x000000018bf8cd78 in _UIUpdateSequenceRun ()
#31	0x000000018bf8c468 in schedulerStepScheduledMainSection ()
#32	0x000000018bf8c524 in runloopSourceCallback ()
#33	0x0000000189c9d62c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#34	0x0000000189c9c8a8 in __CFRunLoopDoSource0 ()
#35	0x0000000189c9b058 in __CFRunLoopDoSources0 ()
#36	0x0000000189c99d88 in __CFRunLoopRun ()
#37	0x0000000189c99968 in CFRunLoopRunSpecific ()
#38	0x00000001cdf974e0 in GSEventRunModal ()
#39	0x000000018c10cedc in -[UIApplication _run] ()
#40	0x000000018c10c518 in UIApplicationMain ()
#41	0x000000010163e8c8 in main at {REDACTED_INFO}/AppDelegate.swift:39
#42	0x00000001ad1bad84 in start ()

**Comment by OdNairy** [comment]
Hi @crtsajnic-k 
Thank you for the report. First of all, let me highlight that we are talking about assert failure. So it would not crash your application in the production. 
Could you please share more information about the way you can reproduce the issue? What is the values of `metalView.contentScaleFactor` and `pixelRatio` that doesn't match on your machine?

**Comment by crtsajnic-k** [comment]
Our MapView is contained inside of multiple scroll views (custom pager view controller). When device orientation changes we update the current view controllers width so it's always full width. Seems like this 'updateFrame' logic was unnecessarily being called multiple times and was triggering the aforementioned error.

In our specific case the 'updateFrame' code was being called inside of UIScrollDelegate.scrollViewDidScroll(_ scrollView: UIScrollView) method. After adding another check that makes sure the 'updateFrame' logic isn't executed when device orientation changes, the error didn't occur anymore.

**Comment by OdNairy** [comment]
Thank you for the details. Glad to hear you were able to solve it on your side. 
We would like to address the issue on the SDK level as well so I would be grateful if you could share the values of `metalView.contentScaleFactor` and `pixelRatio` on the assert.

**Comment by crtsajnic-k** [comment]
Of course. Here are the values in two different scenarios (app was running on an iPhone 12, iOS 17.4):

Values when only the problematic view controller was visible:
![SCR-20240313-ipli](https://github.com/mapbox/mapbox-maps-ios/assets/160708957/1e142981-6654-4d77-ac4e-87e1ac6311f1)

Values when a random view controller was presented on top of the problematic view controller:
![SCR-20240313-ipae](https://github.com/mapbox/mapbox-maps-ios/assets/160708957/ca766553-fa01-4d01-878d-c915f3daabba)
