### ISSUE TITLE
Invalid Bundle, asset valiation failure on upload

### ISSUE THREAD

**Issue by nicolopadovan** [mapbox/mapbox-maps-ios#2146]
## Environment

- Xcode version: 15.3
- iOS version: 15.0+
- Devices affected: *
- Maps SDK Version: -

Packages versions:
- MapboxCommon: 23.6.0
- MapboxCoreMaps: 10.14.0
- MapboxDirections: 2.12.0
- MapboxMaps: 10.14.0
- MapboxMobileEvents: 1.0.10
- MapboxNavigation: 2.14.0
- MapboxNavigationNative: 137.1.7
- MapboxSearch: 1.0.0-rc.7
- MapboxSpech: 2.1.1

## Observed behavior and steps to reproduce

The application builds, runs and archives correctly. However, when uploading (either to App Store or TestFlight only), multiple errors related to the `MapboxCoreSearch` package Info.plist file are yielded.
This only happens after the last Xcode update.
In my specific case, I've installed Mapbox via Swift Package Manager.

The errors that are yielded are:
```
Asset validation failed
The bundle 'Payload/[MyApp].app/Frameworks/MapboxCoreSearch.framework' is missing plist key. 
The Info.plist file is missing the required key: CFBundleShortVersionString. 
Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring
```

```
Asset validation failed
This bundle Payload/[MyApp].app/Frameworks/MapboxCoreSearch.framework is invalid.
The Info.plist file is missing the required key: CFBundleVersion.
Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
```

```
Asset validation failed
Invalid Bundle.
The bundle [MyApp].app/Frameworks/MapboxCoreSearch.framework does not support the minimum OS Version specified in the Info.plist.
```

## Expected behavior

The application should upload normally.

## Notes / preliminary analysis

None of the following works:
- Updating the package to the latest version
- Resolving package version
- Resetting cache
- Cleaning derived data

## Additional links and references

It seems that the Firebase iOS SDK encountered the same issue a couple of weeks ago. [Link](https://github.com/firebase/firebase-ios-sdk/issues/12441)

**Comment by persidskiy** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-search-ios/issues/191
