### ISSUE TITLE
Use custom bearing for the puck

### ISSUE THREAD

**Issue by mayzhao-lime** [mapbox/mapbox-maps-ios#2148]
## New Feature

I am building a navigation UI, and I'm trying to make the puck pointing towards the direction of the navigation route (a calculated bearing value) instead of the device's `heading` or `course` (similar to how we can set the bearing to a constant for `FollowPuckViewportStateBearing`)
I might be missing something here but I have not found a way to do this for puck bearing. 

## Why
This feature would allow more customizations with the puck's UI.

**Comment by persidskiy** [comment]
Hi @mayzhao-lime, the Maps SDK itself implements only the basic bearing data providers, such as `course` and `heading` available in iOS SDK. 

However, you can implement your own provider and override it via the several methods available in the `LocationManager` https://docs.mapbox.com/ios/maps/api/11.2.0/documentation/mapboxmaps/locationmanager#instance-methods
