### ISSUE TITLE
Migration guide missing alternative for dragStart() and dragEnd()

### ISSUE THREAD

**Issue by marcoboerner** [mapbox/mapbox-maps-ios#2155]
We're currently migrating from v10 to v.11 and noticed the `dragStart()` and `dragEnd()` methods have been removed because they are not used anymore. However, we do still use them in our app. It is unclear to me how to migrate those parts properly. Could you please advise if there are alternative methods we should use?

**Comment by aleksproger** [comment]
Hey @marcoboerner did you try to set `GestureManagerDelegate` and listen to pan gesture begin/end events?
You may do it like this 
```swift
 mapView.gestures.delegate = self
 
 func gestureManager(_ gestureManager: GestureManager, didBegin gestureType: GestureType) {
        switch gestureType {
        case .pan:
            print("start drag")
        default:
            break
        }
    }

func gestureManager(_ gestureManager: GestureManager, didEnd gestureType: GestureType, willAnimate: Bool) {
      switch gestureType {
        case .pan:
            print("end drag")
        default:
            break
        }
    }

func gestureManager(_ gestureManager: GestureManager, didEndAnimatingFor gestureType: GestureType) {}
 ```
 Please, let us know whether is solves your use case or not

**Comment by marcoboerner** [comment]
@aleksproger thanks for the info, that seems to work! 👍
