### ISSUE TITLE
invalid archive returned from 'https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/24.3.0-beta.1/MapboxCommon.zip' which is required by binary target 'MapboxCommon'

### ISSUE THREAD

**Issue by vijayprmar** [mapbox/mapbox-maps-ios#2156]
## Environment

- Xcode version:  15.3
- iOS version: iOS 16
- Devices affected: all
- Maps SDK Version: 1.0.0

**Comment by Sabina29** [comment]
Hi! Wondering if you were able to get around this?

**Comment by persidskiy** [comment]
@vijayprmar Hi, please add the steps to reproduce this issue

**Comment by multiusersystem** [comment]
Did you set up .netrc before attempting to add the mapbox-maps-ios package? I didn't, and I got the same error. Here's how I fixed it on my system:

1. Ensure .netrc has permissions 0600 and looks like this:
```
machine api.mapbox.com
login mapbox
password YOUR_SECRET_MAPBOX_ACCESS_TOKEN
```
2. Check your swiftpm cache:

Check if you have any files in ~/Library/Caches/org.swift.swiftpm that contain something like this:
```
{"message":"Not Authorized - No Token","url":"[GET] /downloads/v2/mobile-maps-core/releases/ios/packages/11.2.0/MapboxCoreMaps.xcframework-dynamic.zip","auth":"<no access token>","ua":"Amazon CloudFront"}

{"message":"Not Authorized - Invalid Token","url":"[GET] /downloads/v2/mapbox-events-ios/releases/ios/packages/1.0.5/MapboxMobileEvents.zip?access_token=wrong_password","auth":"wrong_password","ua":"Amazon CloudFront"}
```
if you do, then remove the files:

```bash
for f in $(grep -rIl "Not Authorized" ~/Library/Caches/org.swift.swiftpm); do echo "deleting $f"; rm $f; done
```
3. Restart Xcode

This solved it for me, but it might be possible for one of those "Not Authorized" artifacts to still be in your project cache`~/Library/Developer/Xcode/DerivedData/<your-repo-name>/SourcePackages/artifacts`

<details>
  <summary> This is the part where I was wrong </summary>

I ran into this issue as well. I followed documentation at https://docs.mapbox.com/ios/maps/guides/install/#add-the-dependency for Swift Package Manager

environment:
MacOS 14.1.1
XCode 15.3

repro:
1. add mapbox token to .netrc (Downloads:Read permission, 0600) **---not true**
2. add public token to Info.plist
4. File > Add Package Dependencies, search for https://github.com/mapbox/mapbox-maps-ios.git
5. Dependency Rule: `Up to Next Major Version 11.0.0`
6. Add Package

Swift Package Manager pulls 11.2.0, and produces this output:
```
invalid archive returned from 'https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/24.2.0/MapboxCommon.zip' which is required by binary target 'MapboxCommon'
invalid archive returned from 'https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/11.2.0/MapboxCoreMaps.xcframework-dynamic.zip' which is required by binary target 'MapboxCoreMaps'
```
 
notes:
I specified some exact versions, and this issue only reproduced on 11.2.0. 11.0.0, 11.1.0, 11.2.0-rc.1, and 11.3.0-rc.1 all had no issues.

Interestingly, I was able to get 11.2.0 (11.0.0 - Next Major Version) on a different system following the above repro steps without issue a few weeks ago... ah, I found my issue! I *hadn't* added .netrc on this system before attempting to install.

solution: 
add .netrc and remove cache files
</details>

**Comment by shearos** [comment]
because I also didn't setup the .netrc file properly I had to delete caches.
Make sure to do files in `/Users/samuelshearing/Library/Caches/org.swift.swiftpm/artifacts` also

**Comment by 1plam** [comment]
> /Users/sam

Works like a charm! Much appreciated.

**Comment by 1plam** [comment]
> Did you set up .netrc before attempting to add the mapbox-maps-ios package? I didn't, and I got the same error. Here's how I fixed it on my system:
> 
> 1. Ensure .netrc has permissions 0600 and looks like this:
> 
> ```
> machine api.mapbox.com
> login mapbox
> password YOUR_SECRET_MAPBOX_ACCESS_TOKEN
> ```
> 
> 2. Check your swiftpm cache:
> 
> Check if you have any files in ~/Library/Caches/org.swift.swiftpm that contain something like this:
> 
> ```
> {"message":"Not Authorized - No Token","url":"[GET] /downloads/v2/mobile-maps-core/releases/ios/packages/11.2.0/MapboxCoreMaps.xcframework-dynamic.zip","auth":"<no access token>","ua":"Amazon CloudFront"}
> 
> {"message":"Not Authorized - Invalid Token","url":"[GET] /downloads/v2/mapbox-events-ios/releases/ios/packages/1.0.5/MapboxMobileEvents.zip?access_token=wrong_password","auth":"wrong_password","ua":"Amazon CloudFront"}
> ```
> 
> if you do, then remove the files:
> 
> ```shell
> for f in $(grep -rIl "Not Authorized" ~/Library/Caches/org.swift.swiftpm); do echo "deleting $f"; rm $f; done
> ```
> 
> 3. Restart Xcode
> 
> This solved it for me, but it might be possible for one of those "Not Authorized" artifacts to still be in your project cache`~/Library/Developer/Xcode/DerivedData/<your-repo-name>/SourcePackages/artifacts`
> 
> This is the part where I was wrong

Works like a charm! Much appreciated.
