### ISSUE TITLE
Stop using custom wrappers for existing iOS features. 

### ISSUE THREAD

**Issue by kristjan97** [mapbox/mapbox-maps-ios#2160]
## New Feature
Stop making custom wrappers around existing iOS implementations such as AppleLocationProvider for CLLocationManager and Signal for Combine-related stuff.

## Why
These custom wrappers for things that iOS developers already know how to use are just adding more friction when it isn't necessary.

**Comment by OdNairy** [comment]
Maps SDK is iOS 12 so we need some Combine-like primitives to make a reactive API compatible with Apple's frameworks.
LocationProvider is much more powerful than just a listener of device locations.
