### ISSUE TITLE
How to Load Custom Fonts Locally

### ISSUE THREAD

**Issue by Gomu-iOS** [mapbox/mapbox-maps-ios#2161]
How to Load Custom Fonts Locally

**Comment by pjleonard37** [comment]
Hi @Gomu-iOS  --

This repository is for reporting bugs specifically in the [Mapbox Maps SDK for iOS](https://docs.mapbox.com/ios/maps/guides/). For questions about how to use this SDK or work with Mapbox more broadly, please write a Support question [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231) or write into our Discord server [here](https://discord.com/invite/uMpcC5RmJh).
