### ISSUE TITLE
Polyline "Cannot assign value of type 'String.UnicodeScalarView.SubSequence'"

### ISSUE THREAD

**Issue by petermulsh** [mapbox/mapbox-maps-ios#2175]
## Environment

- Xcode version: 15.3
- iOS version: 17.4.1
- Devices affected: iPhone

Just updated Xcode, cocoa pods, and maps. Getting an error in Polyline for method:

`private func extractNextChunk(_ encodedString: inout String.UnicodeScalarView) throws -> String {
    var currentIndex = encodedString.startIndex
    
    while currentIndex != encodedString.endIndex {
        let currentCharacterValue = Int32(encodedString[currentIndex].value)
        if isSeparator(currentCharacterValue) {
            let extractedScalars = encodedString[encodedString.startIndex...currentIndex]
            encodedString = encodedString[encodedString.index(after: currentIndex)..<encodedString.endIndex]
            
            return String(extractedScalars)
        }
        
        currentIndex = encodedString.index(after: currentIndex)
    }
    
    throw PolylineError.chunkExtractingError
}`

The error: 
> Cannot assign value of type 'String.UnicodeScalarView.SubSequence' (aka 'Substring.UnicodeScalarView') to type 'String.UnicodeScalarView'
for this line:
<img width="1070" alt="Screenshot 2024-05-01 at 5 29 59 AM" src="https://github.com/mapbox/mapbox-maps-ios/assets/17093883/127936e7-0b01-4a15-96bb-afccabee40d7">
`encodedString = encodedString[encodedString.index(after: currentIndex)..<encodedString.endIndex]`

**Comment by pjleonard37** [comment]
Hi @petermulsh - 

Thanks for reporting this issue. I spent time today trying to reproduce this on my side, but I was not able to. Can you share a small project that reproduces this issue so we can investigate further?

**Comment by petermulsh** [comment]
@pjleonard37 

Hi Patrick, 

Thanks for responding. I created a new Xcode project, dragged and dropped the Polyline folder from my other project and getting the same error. 

Here is the [project](https://github.com/petermulsh/PolyLineTest/tree/main)

**Comment by petermulsh** [comment]
cocoa pods version: 1.15.2

**Comment by petermulsh** [comment]
<img width="164" alt="Screenshot 2024-05-02 at 8 42 04 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/17093883/0f9272bf-7441-4af2-be44-98d5c51dbbc6">
<img width="289" alt="Screenshot 2024-05-02 at 8 42 39 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/17093883/1fcc7fba-ade4-4cc0-91b2-44312b47bbaf">

In pod file.lock

**Comment by petermulsh** [comment]
Thanks Patrick! Updated to V3, trying to update all the depreciated methods now.
