### ISSUE TITLE
ITMS-91056: Invalid privacy manifest 

### ISSUE THREAD

**Issue by chekmari** [mapbox/mapbox-maps-ios#2177]
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by chekmari** [comment]
10.2.0

**Comment by maios** [comment]
In that case could you kindly update your MapboxMaps dependencies to v10.17.0 where we have fix for this issue? We also have made several improvements and bug fixes between the version you are using and this latest v10 release :)

**Comment by lavkushry1** [comment]
I am Also Suffering from same issue Can Anyone Guide how to solve this

**Comment by chekmari** [comment]
Update mapbox
