### ISSUE TITLE
No way to customize font on SwiftUI PointAnnotation

### ISSUE THREAD

**Issue by skg54** [mapbox/mapbox-maps-ios#2179]
I'd like to be able to change the font family on the textField property of PointAnnotation.  

The textFont property for SymbolLayers available in previous versions of the SDK does not exist for SwiftUI PointAnnotation.

Thanks!

**Comment by persidskiy** [comment]
Hi, you can find this property in the PointAnnotationGroup https://docs.mapbox.com/ios/maps/api/11.3.0/documentation/mapboxmaps/pointannotationgroup/textfont(_:)

Or, starting from Maps SDK 11.4.0-beta.1 you can use SymbolLayer directly in SwiftUI https://docs.tilestream.net/ios/maps/api/latest/documentation/mapboxmaps/declarative-map-styling/
