### ISSUE TITLE
Xcode 16 beta won't build Mapbox SDK Swift package

### ISSUE THREAD

**Issue by jonblatho** [mapbox/mapbox-maps-ios#2197]
## Environment

- Xcode version: 16.0 beta 1 (16A5171c)
- iOS version: 17 / 18 beta (likely more, too)
- Devices affected: N/A
- Maps SDK Version: 10.x and 11.x

## Observed behavior and steps to reproduce
1. In an Xcode project, link the MapboxMaps Swift package dependency per documentation.
2. Attempt to build.
3. Build fails with the following type error (10.x):  
```
/path/to/my/project/derived/data/.../SourcePackages/checkouts/mapbox-maps-
ios/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift:67:19

Cannot convert return expression of type '[UIView : ViewAnnotationOptions]'
to return type 'Dictionary<String, Optional<JSONValue>>.RawValue' (aka 
'Dictionary<String, Optional<Any>>')
```

## Expected behavior

The build completes successfully.

## Notes / preliminary analysis

Offending code from 10.x:

```swift
public var annotations: [UIView: ViewAnnotationOptions] {
    idsByView.compactMapValues { [mapboxMap] id in
        try? mapboxMap.options(forViewAnnotationWithId: id)
    }
}
```

Not sure if this is an Xcode problem or a Mapbox SDK problem, but wanted to report it anyway. I've confirmed that the issue occurs on both SDK versions 10.x and 11.x, and when building with Swift 5.x or Swift 6 beta. The issue does not occur for me in Xcode 15.4 (latest stable).

This property has been marked deprecated in SDK 11.x. It strikes me as a weird bug and maybe a Swift issue; nothing jumps out at me as obviously wrong here that would cause it to work in earlier Xcode versions but no longer. Unless a workaround is identified, this will block any work on Xcode 16 beta.

## Additional links and references

N/A

**Comment by liyinjie01** [comment]
This problem seems to have arisen on Xcode 15.3

**Comment by liyinjie01** [comment]
This problem seems to have occurred on Xcode 15.3

**Comment by chenjie1219** [comment]
+1

**Comment by AF-cgi** [comment]
The Mapbox SDK is not compilable anymore with Xcode 16 Beta. With Xcode 15.x all things are fine.

**Comment by anvarazizov** [comment]
+1
I have the same issue with Xcode 16 Beta

**Comment by feelingsonice** [comment]
+1

**Comment by fire-at-will** [comment]
Seeing this on the Xcode 16 Beta as well

**Comment by evil159** [comment]
This should be addressed in Maps SDK 11.5.0-beta.1 and 10.8.2

**Comment by DavidZomada** [comment]
+ 1

**Comment by Knapiii** [comment]
+1

**Comment by adesugbaa** [comment]
+1

**Comment by adesugbaa** [comment]
I just tried 11.5.0-beta.1 and get a different error:
```
'Expression' is ambiguous for type lookup in this context
```

- @rnmapbox/maps/ios/RNMBX/RNMBXLayer.swift
- @rnmapbox/maps/ios/RNMBX/RNMBXStyleValue.swift
- @rnmapbox/maps/ios/RNMBX/Extensions/Array+asExpressions.swift

**Comment by jonblatho** [comment]
Can confirm 10.18.2 fixed the issue for me; we haven't migrated to 11.x yet. Thanks! The issue described by @adesugbaa sounds like a separate problem, but I'll leave this open.

**Comment by persidskiy** [comment]
@adesugbaa Hi, can you try to use v11.5.0-rc.1 ?

```
'Expression' is ambiguous for type lookup in this context
```

This error happens due to the introduction of the new `Expression` type in Foundation which is ambiguous with `MapboxMaps.Expression`. Please use the full name `MapboxMaps.Expression`, or a shortcut [`Exp`](https://docs.mapbox.com/ios/maps/api/11.5.0-rc.1/documentation/mapboxmaps/exp) in your code that uses Mapbox.

I'm closing this issue as it should be fixed in the mentioned releases. Feel free to reopen it if you encounter a similar issue.

**Comment by adesugbaa** [comment]
Thanks. Unfortunately, the RC does not work either.

```
Compiling react-native Pods/React-RuntimeApple » RCTLegacyUIManagerConstantsProvider.mm

❌  (/Users/ayorinde/Developer/Git/Others/limeapp/node_modules/@rnmapbox/maps/ios/RNMBX/Extensions/Array+asExpressions.swift:4:33)

  2 | 
  3 | internal extension Array where Element == Any {
> 4 |   func asExpression() throws -> Expression? {
    |                                 ^ 'Expression' is ambiguous for type lookup in this context
  5 |     let filter = self
  6 |     if filter.count > 0 {
  7 |       let data = try JSONSerialization.data(withJSONObject: filter, options: .prettyPrinted)

```

**Comment by persidskiy** [comment]
@adesugbaa This change needs to be done in the rnmapbox package https://github.com/rnmapbox/maps/blob/main/ios/RNMBX/Extensions/Array%2BasExpressions.swift#L4

**Comment by ehtisham-ali-emumba** [comment]
cc @persidskiy any update on rn package? I am having it on v11

**Comment by baleboy** [comment]
@ehtisham-ali-emumba rnmapbox is not maintained by mapbox, please request this change from that project directly by filing an issue. Thanks!

**Comment by yerassyloo** [comment]
I changed the implementation of the `annotations` property from:
```
public var annotations: [UIView: ViewAnnotationOptions] {
    idsByView.compactMapValues { [mapboxMap] id in
        try? mapboxMap.options(forViewAnnotationWithId: id)
    }
}
```
to:
```
public var annotations: [UIView: ViewAnnotationOptions] {
    let values = idsByView.compactMapValues { [mapboxMap] id in
        try? mapboxMap.options(forViewAnnotationWithId: id)
    }
    return values
}
```
and it worked for me. In the project, we are very tied to version 10.12.0 and cannot update due to technical reasons. Therefore, we use this approach to solve the issue.

**Comment by kbqdev** [comment]
@yerassyloo thank its work

**Comment by tkserver** [comment]
I tested @yerassyloo solution and it worked for me! But the problem with this is we will have to hard code this every time we recreate the podfile.

**Comment by edXmO** [comment]
@tkserver There is no need to hardcode it every time, you could patch it with [cocoapods-patch](https://github.com/doublesymmetry/cocoapods-patch).
