### ISSUE TITLE
Invalid Privacy Manifest

### ISSUE THREAD

**Issue by programmergauravgupta** [mapbox/mapbox-maps-ios#2203]
## Environment

- Xcode version: 15.2
-Pods
  pod 'MapboxCoreNavigation', '~> 2.17'
  pod 'MapboxNavigation', '~> 2.17'
  pod 'MapboxGeocoder.swift', '~> 0.14'

Getting following mail after uploading build to testflight

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by baleboy** [comment]
This is resolved in Maps SDK 10.17 and later, and Maps SDK 11.3 and later. See https://github.com/mapbox/mapbox-maps-ios/issues/2145
