### ISSUE TITLE
[Bug] Xcode 16.0 - Cannot convert return expression of type '[UIView : ViewAnnotationOptions]' to return type 'Dictionary<String, Optional<JSONValue>>.RawValue' (aka 'Dictionary<String, Optional<Any>>')

### ISSUE THREAD

**Issue by MatejMa2ur** [mapbox/mapbox-maps-ios#2204]
## Environment

- Xcode version: 16.0 Beta
- iOS version: 18
- Devices affected:
- Maps SDK Version: 11.4.0

## Observed behavior and steps to reproduce

I opened application in beta xcode and I can't run it.

Cannot convert return expression of type '[UIView : ViewAnnotationOptions]' to return type 'Dictionary<String, Optional<JSONValue>>.RawValue' (aka 'Dictionary<String, Optional<Any>>')

**Comment by OdNairy** [comment]
The issue is resolved in the `main` branch and `11.5.0-beta.1` release
