### ISSUE TITLE
Any plan to support building with xcode 16 on 10.12.x?

### ISSUE THREAD

**Issue by xuzhaocheng** [mapbox/mapbox-maps-ios#2208]
## Environment

- Xcode version: 16.0 beta2
- iOS version: 18.0 
- Devices affected: all
- Maps SDK Version: 10.12.2

## Observed behavior and steps to reproduce
The same build error as https://github.com/mapbox/mapbox-maps-ios/issues/2204

## Expected behavior

Can build correctly

**Comment by OdNairy** [comment]
We've addressed Xcode 16 issues in [the 10.18.2 release](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.18.2).
Could you upgrade? Any blockers?

**Comment by xuzhaocheng** [comment]
> We've addressed Xcode 16 issues in [the 10.18.2 release](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.18.2). Could you upgrade? Any blockers?

Thanks for your quick reply. No build issue was found.
