### ISSUE TITLE
Puck snaps to wrong roads

### ISSUE THREAD

**Issue by maikelsgit** [mapbox/mapbox-maps-ios#2214]
## Environment

- Xcode version: 15.4 (15F31d)
- iOS version: 17.5.1
- Devices affected: Tested on iPhone 12 and 13 
- Maps SDK Version: MapboxCommon 24.4.0, MapboxNavigation 3.1.1, MapboxNavigationNative 311.0.0 

## Observed behavior and steps to reproduce

I'm have added Mapbox to my cycling app. 
I have created a Map with the help of your [SwiftUI User guide](https://docs.mapbox.com/ios/maps/api/11.0.0/documentation/mapboxmaps/swiftui-user-guide/) and added a PolylineAnnotation with coordinates from a GPX file and a Puck2D. The Map, Polyline and Puck are displayed correctly when I go for a test ride on my road bike.

I have a issue with the Puck, it's snapping to motorways and does not stay on cycle paths.
If I take a test ride on the bicycle and I ride on a cycle path that starts to run parallel to a motorway, the Puck will snap to the motorway and no longer stay on the cycle path. If the distance between the cycle path and motorway increases, at some point the puck will snap back to the cycle path.

Is this a bug or can I configure the map or puck to focus on cycling?

## Expected behavior

That the puck stays on the cycle path based on my location and does not snap away to it's nearest motorway.

## Examples

![IMG_1531](https://github.com/user-attachments/assets/02bd1d4b-5ebb-42da-97e1-8c5a41f16f75)
![IMG_1530](https://github.com/user-attachments/assets/a288aaa7-7798-4808-854e-2c5cf6cb9733)

**Comment by persidskiy** [comment]
Hi, the Maps SDK focuses on the maps rendering so it doesn't fix the location data to snap to any geometry.

A simple way to achieve what you want would be to adjust the location using Turf's https://docs.mapbox.com/ios/maps/api/11.5.1/documentation/mapboxmaps/linestring/closestcoordinate(to:)/

You can override the location provider that drives the puck

**Comment by maikelsgit** [comment]
Thank you for your response. It's just not clear to me how to apply this to a swiftUI Map?

```
Map(viewport: $viewport) {
            //Instantiate polylines
            ForEvery(Array(tracks), id: \.name) { track in
                ForEvery(Array(track.segments.enumerated()), id: \.offset) { segmentIndex, segments in
                    let coordinates = segments.points.map {
                        CLLocationCoordinate2D(latitude: $0.latitude ?? 0, longitude: $0.longitude ?? 0)
                    }
                    
                    PolylineAnnotationGroup {
                        PolylineAnnotation(lineCoordinates: coordinates)
                            .lineColor(polylineColor(index: segmentIndex))
                            .lineBorderWidth(2)
                            .lineBorderColor(polylineBorderColor(index: segmentIndex))
                            .lineWidth(8)
                            .lineJoin(.round)
                    }
                    .lineCap(.round)
                    //.slot("middle")
                }
            }
            
            Puck2D(bearing: .course)
                .topImage(.mapboxTopImage) // layer 2
                .bearingImage(puckImage) // layer 1
                .shadowImage(UIImage(resource: .mapboxPuckShadow)) // layer 0
                .showsAccuracyRing(false)
        }
        .mapStyle(mapStyle)
```

**Comment by persidskiy** [comment]
@maikelsgit Created a SwiftUI example about it https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/SwiftUI%20Examples/LocationOverrideExample.swift

**Comment by persidskiy** [comment]
I'm closing the issue, please feel free to reopen if you
