### ISSUE TITLE
.netrc file in Github Actions?

### ISSUE THREAD

**Issue by maurovz** [mapbox/mapbox-maps-ios#2223]
## Environment

- Xcode version: 15.4
- iOS version: 17.5
- Devices affected: Any
- Maps SDK Version: Latest

## Observed behavior and steps to reproduce

I'm having compilation issues in Github Actions due to not having the .netrc file. Can someone point me in the right direction on how can I set the .netrc in my CI pipeline?

Thanks in advance

## Expected behavior

App should compile in CI pipeline

**Comment by aleksproger** [comment]
Hello @maurovz, you may try the following approach
```swift
- name: Set up .netrc file
      run: |
        echo "machine api.mapbox.com" > ~/.netrc
        echo "login mapbox >> ~/.netrc
        echo "password ${{ secrets.YOUR_TOKEN }}" >> ~/.netrc
        chmod 0600 ~/.netrc
```

**Comment by maios** [comment]
Hey @maurovz , did you manage to get it work with @aleksproger's suggestion?

**Comment by maurovz** [comment]
Hello guys I apologise for the late response.

@aleksproger I will try it out this week and I'll get back to you. Thanks!

**Comment by maurovz** [comment]
It appears to work! thanks @aleksproger
