### ISSUE TITLE
Crashed: com.mapbox.common.TileStoreFileSource

### ISSUE THREAD

**Issue by 666bsw** [mapbox/mapbox-maps-ios#2226]
## Environment

- Xcode version: 15.4 (15F31d)
- iOS version: 17.5.1
- Devices affected: iPhone 13 Pro, iPhone 11, iPad mini (5th generation), iPhone 15 Pro Max
- Maps SDK Version: 11.6.0

## Observed behavior and steps to reproduce

often occurs when trying to download maps to offline storage.
download code taken from example.

![screen](https://github.com/user-attachments/assets/e49ad434-29a1-49c2-9ad1-691ff2d4609b)

Fatal Exception: std::__1::bad_function_call

com.apple.main-thread
0  libobjc.A.dylib                0x8254 objc_loadWeakRetained + 40
1  UIKitCore                      0x2528c -[_UISceneLifecycleMonitor _scene] + 20
2  UIKitCore                      0x25194 -[_UIWindowSceneFBSSceneLifecycleMonitor currentActivationState] + 116
3  UIKitCore                      0x24f68 -[UIScene activationState] + 76
4  UIKitCore                      0x25000 +[_UISceneLifecycleMultiplexer _compareLifecycleStateOfScene:toScene:] + 72
5  UIKitCore                      0x24e38 __75+[_UISceneLifecycleMultiplexer _mostActiveSceneIncludingInternal:withTest:]_block_invoke.10 + 136
6  CoreFoundation                 0x24b14 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
7  CoreFoundation                 0x8e660 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 92
8  UIKitCore                      0xe7304 +[_UISceneLifecycleMultiplexer _mostActiveSceneIncludingInternal:withTest:] + 340
9  UIKitCore                      0x2a7cc _UIGetCurrentFallbackTraitCollection + 148
10 UIKitCore                      0x11198 +[UITraitCollection _currentTraitCollectionWithFallback:markFallback:] + 192
11 UIKitCore                      0x26c98 _UICurrentImageTraitCollectionDisplayScale + 32
12 UIKitCore                      0x260a0 __78-[_UIAssetManager imageNamed:configuration:cachingOptions:attachCatalogImage:]_block_invoke + 284
13 UIKitCore                      0x26750 -[_UIAssetManager imageNamed:configuration:cachingOptions:attachCatalogImage:] + 300
14 UIKitCore                      0x25710 -[_UIAssetManager imageNamed:configuration:] + 196
15 UIKitCore                      0x202390 +[UIImage imageNamed:inBundle:withConfiguration:] + 360
16 GPX Tracker                    0x2205c TopInstrumentView.body.getter + 35 (TopInstrumentView.swift:35)
17 GPX Tracker                    0x28980 protocol witness for View.body.getter in conformance TopInstrumentView + 4377397632 (<compiler-generated>:4377397632)
18 SwiftUI                        0x202528 dynamic_cast_existential_0_superclass_conditional + 24428
19 SwiftUI                        0x24d738 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 31980
20 SwiftUI                        0x24b3bc -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 22896
21 SwiftUI                        0x1fdb30 dynamic_cast_existential_0_superclass_conditional + 5492
22 AttributeGraph                 0x9010 AG::Graph::UpdateStack::update() + 512
23 AttributeGraph                 0x8bfc AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 424
24 AttributeGraph                 0x87d8 AG::Subgraph::update(unsigned int) + 848
25 SwiftUI                        0x267068 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 136732
26 SwiftUI                        0x26e78c -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 167232
27 SwiftUI                        0x268430 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 141796
28 SwiftUI                        0x265e60 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 132116
29 SwiftUI                        0x265830 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 130532
30 SwiftUI                        0x2639a4 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 122712
31 SwiftUI                        0x2636a0 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 121940
32 SwiftUI                        0x269c40 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 147956
33 SwiftUI                        0x2674e8 -[UIScrollView(SwiftUI) _swiftui_adjustsContentInsetWhenScrollDisabled] + 137884
34 SwiftUI                        0x16513c OUTLINED_FUNCTION_719 + 32912
35 SwiftUI                        0x165048 OUTLINED_FUNCTION_719 + 32668
36 SwiftUI                        0x164ffc OUTLINED_FUNCTION_719 + 32592
37 CoreFoundation                 0x24658 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
38 CoreFoundation                 0x24414 __CFRunLoopDoObservers + 552
39 CoreFoundation                 0x5354c __CFRunLoopRun + 1028
40 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
41 GraphicsServices               0x11a8 GSEventRunModal + 164
42 UIKitCore                      0x40a90c -[UIApplication _run] + 888
43 UIKitCore                      0x4be9d0 UIApplicationMain + 340
44 UIKitCore                      0x638384 keypath_get_selector_hoverStyle + 11024
45 GPX Tracker                    0x7e5ac main + 4377748908 (AppDelegate.swift:4377748908)
46 ???                            0x1c4b5de4c (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7c9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x41e640 -[UIEventFetcher threadMain] + 420
10 Foundation                     0xde718 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  GPX Tracker                    0x3d8e20 FIRCLSMachExceptionServer + 192 (FIRCLSMachException.c:192)
5  libsystem_pthread.dylib        0x606c _pthread_start + 136
6  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.Unspecified Worker 1
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd598 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  MapboxCommon                   0x92838 mapbox::common::SystemInformationProvider::getSystemInformation() + 11024
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.Unspecified Worker 1
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.location.sharedRunloop
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CoreFoundation                 0xc0f04 CFRunLoopRun + 64
8  MapboxCommon                   0x11b780 mapbox::bindgen::mapbox::common::location::LocationServiceObserver::onAccuracyAuthorizationChanged(mapbox::common::location::AccuracyAuthorization) + 18360
9  Foundation                     0xde718 __NSThread__start__ + 732
10 libsystem_pthread.dylib        0x606c _pthread_start + 136
11 libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.AssetFileSource
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

Crashed: com.mapbox.common.TileStoreFileSource
0  GPX Tracker                    0x3ca270 FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
1  GPX Tracker                    0x3ca650 FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
2  GPX Tracker                    0x3d8864 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  GPX Tracker                    0x3d8668 __FIRCLSExceptionRecord_block_invoke + 240 (FIRCLSException.mm:240)
4  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
5  libdispatch.dylib              0x132c4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  GPX Tracker                    0x3d75e4 FIRCLSExceptionRecord + 242 (FIRCLSException.mm:242)
7  GPX Tracker                    0x3d72b0 FIRCLSTerminateHandler() + 413 (FIRCLSException.mm:413)
8  libc++abi.dylib                0x14068 std::__terminate(void (*)()) + 16
9  libc++abi.dylib                0x1735c __cxa_get_exception_ptr + 86
10 libc++abi.dylib                0x172a0 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 306
11 MapboxCoreMaps                 0x10460 std::__1::__throw_bad_function_call[abi:v160006]() + 50
12 MapboxCoreMaps                 0x3f26f8 mbgl::(anonymous namespace)::StylePackRequest::complete(nonstd::expected_lite::expected<mapbox::maps::StylePack, mapbox::maps::StylePackError>&&) + 328
13 MapboxCoreMaps                 0x3f8784 mbgl::(anonymous namespace)::StylePackRequest::StylePackRequest(mbgl::OfflineDownloadParameters, mbgl::TileStoreFileSourceThread*, mapbox::maps::StylePackLoadOptions&&, std::__1::shared_ptr<mapbox::common::TilesetDescriptor>, std::__1::function<void (mapbox::maps::StylePackLoadProgress const&)>&&, std::__1::function<void (nonstd::expected_lite::expected<mapbox::maps::StylePack, mapbox::maps::StylePackError>&&)>&&, std::__1::shared_ptr<mbgl::FileSource>) + 1160
14 MapboxCoreMaps                 0x3f04a0 mbgl::TileStoreFileSourceThread::loadStylePack(long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, mapbox::maps::StylePackLoadOptions&&, std::__1::function<void (mapbox::maps::StylePackLoadProgress const&)>&&, std::__1::function<void (nonstd::expected_lite::expected<mapbox::maps::StylePack, mapbox::maps::StylePackError>&&)>&&) + 368
15 MapboxCoreMaps                 0x148434 mapbox::common::internal::Message<mbgl::DatabaseFileSourceThread, void (mbgl::DatabaseFileSourceThread::*)(long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, mapbox::maps::StylePackLoadOptions&&, std::__1::function<void (mapbox::maps::StylePackLoadProgress const&)>&&, std::__1::function<void (nonstd::expected_lite::expected<mapbox::maps::StylePack, mapbox::maps::StylePackError>&&)>&&), std::__1::tuple<long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, mapbox::maps::StylePackLoadOptions, std::__1::function<void (mapbox::maps::StylePackLoadProgress const&)>, std::__1::function<void (nonstd::expected_lite::expected<mapbox::maps::StylePack, mapbox::maps::StylePackError>&&)>>>::operator()() + 436
16 MapboxCommon                   0x92a40 mapbox::common::SystemInformationProvider::getSystemInformation() + 11544
17 libsystem_pthread.dylib        0x606c _pthread_start + 136
18 libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.LocalFileSource
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.OnlineFileSource
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.ResourceLoaderThread
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.mapbox.common.Logger
0  libsystem_kernel.dylib         0x71cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0xd504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  MapboxCommon                   0x92808 mapbox::common::SystemInformationProvider::getSystemInformation() + 10976
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CFNetwork                      0xfdc90 _CFHostIsDomainTopLevel + 108176
8  Foundation                     0xde718 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CoreFoundation                 0xc0f04 CFRunLoopRun + 64
8  CoreMotion                     0x10210 (Missing UUID e4a6f107b302327ca121c9bebacca8f4)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8559722690

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8559722690

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8559722690

com.google.fira.worker
0  Foundation                     0x95b78 _NSTransmutePathSlashes + 80
1  Foundation                     0x954ec -[NSString(NSPathUtilities) stringByAppendingPathComponent:] + 392
2  GPX Tracker                    0x835228 +[APMAEU isFAS] + 4385837608
3  GPX Tracker                    0x881a68 -[APMMeasurement(Event) createRawEventMetadataWithUserAttributes:] + 4386151016
4  GPX Tracker                    0x883b90 -[APMMeasurement(Event) writeEvent:isPublicEvent:isRealtime:] + 4386159504
5  GPX Tracker                    0x881944 __57-[APMMeasurement(Event) writeFilteredEventOnWorkerQueue:]_block_invoke + 4386150724
6  GPX Tracker                    0x8d0e74 -[APMSqliteStore performTransactionWithError:block:] + 4386475636
7  GPX Tracker                    0x8486d8 -[APMDatabase performTransaction:] + 4385916632
8  GPX Tracker                    0x881698 -[APMMeasurement(Event) writeFilteredEventOnWorkerQueue:] + 4386150040
9  GPX Tracker                    0x881400 -[APMMeasurement(Event) writeEventOnWorkerQueue:] + 4386149376
10 GPX Tracker                    0x880fd8 -[APMMeasurement(Event) handleEventOnWorkerQueue:] + 4386148312
11 GPX Tracker                    0x87557c -[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 4386100604
12 GPX Tracker                    0x875408 -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 4386100232
13 GPX Tracker                    0x875238 __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 4386099768
14 GPX Tracker                    0x8c7eb4 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4386438836
15 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
16 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
17 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
18 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
19 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
20 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
21 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
22 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.apple.SwiftUI.AsyncRenderer
0  libsystem_kernel.dylib         0x1808 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x5008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4f20 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4d60 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7e4c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc7d20 -[NSRunLoop(NSRunLoop) run] + 64
9  SwiftUI                        0x42bf18 OUTLINED_FUNCTION_283 + 643420
10 SwiftUI                        0x42bc10 OUTLINED_FUNCTION_283 + 642644
11 Foundation                     0xde718 __NSThread__start__ + 732
12 libsystem_pthread.dylib        0x606c _pthread_start + 136
13 libsystem_pthread.dylib        0x10d8 thread_start + 8

**Comment by aleksproger** [comment]
Hey, @666bsw thanks for reporting this and sorry for late reply. I created an internal [ticket](https://mapbox.atlassian.net/browse/MAPSNAT-2363) for this and we will take a look at this issue.

**Comment by aleksproger** [comment]
Hey, @666bsw  the issue was resolved and will be included in 11.7 stable. Feel free to reopen if there would be more issues with this

**Comment by 666bsw** [comment]
Hi Alex, thank you.
