### ISSUE TITLE
PointAnnotation not displaying in SwiftUI

### ISSUE THREAD

**Issue by oreillyjf** [mapbox/mapbox-maps-ios#2227]
## Environment

- Xcode version: 15.4
- iOS version: 17.2
- Devices affected: Simulator
- Maps SDK Version: 11.6.0

I'm likely missing something basic but the annotation below is not displaying for some reason.  It seems from docs that this is all that should be needed?

```
 struct ContentView: View {
     @State var center = CLLocationCoordinate2D(latitude: 39.5, longitude: -98.0)

     var body: some View {
         Map(initialViewport: .camera(center: center, zoom: 10)) {
             PointAnnotation(coordinate: center)
         }
     }
 }
 ```

**Comment by oreillyjf** [comment]
Ok, looks like you need to provide `.image()` .....had thought there was default one that would be used.

**Comment by maios** [comment]
Hi @oreillyjf, we don't have a default image for a PointAnnotation it seems, a point annotation can be displayed with an image, a text, or both, so you need to specify which one to display with
