### ISSUE TITLE
Warnings received from App Store when uploading new builds through Xcode 16 beta 6 Organiser

### ISSUE THREAD

**Issue by stuart-j-williams** [mapbox/mapbox-maps-ios#2229]
## Environment

- Xcode version:  Xcode 16 Beta 6
- iOS version: N/A
- Devices affected: N/A
- Maps SDK Version: MapboxCommon 24.6.0, MapboxCoreMaps 11.6.0  for iOS

## Observed behavior and steps to reproduce
Warnings received from App Store when uploading new builds through Organiser

**Upload Symbols Failed**
The archive did not include a dSYM for the MapboxCommon.framework with the UUIDs [6E909B97-8FE9-3577-AD0B-0BC34ECA5A3B]. Ensure that the archive's dSYM folder includes a DWARF file for MapboxCommon.framework with the expected UUIDs.

**Upload Symbols Failed**
The archive did not include a dSYM for the MapboxCoreMaps.framework with the UUIDs [E15C452C-5E22-3640-8107-EE5BDB04F372]. Ensure that the archive's dSYM folder includes a DWARF file for MapboxCoreMaps.framework with the expected UUIDs.

## Expected behavior

No warnings

**Comment by OdNairy** [comment]
We are not distributing debug symbols for private CoreMaps and Common libraries. 
That works like intended.

**Comment by vincekruger** [comment]
@OdNairy 

Fix this in your Podfile.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'MapboxCommon'
      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'DWARF'
      end
    end
  end
end
```
