### ISSUE TITLE
Mapbox forcing location updates while app is in background

### ISSUE THREAD

**Issue by seizler** [mapbox/mapbox-maps-ios#2230]
## Environment

- Xcode version: 15.4
- iOS version: 17.0+
- Devices affected: ALL
- Maps SDK Version: 11.6.0

## Observed behavior and steps to reproduce

Mapbox is forcing location updates while app is in background. This only happens when a user opens a view with a MapBox map while using app and then closes it to background. Then the location updates happen in the background every 5 seconds or so if Always Allow is on.  My app needs Always Allow.

It's almost like Mapbox has its own location manager and I cannot turn it off.

## Expected behavior

When the app closes, Mapbox should not need background location anymore.

**Comment by OdNairy** [comment]
Telemetry collection is a Mapbox feature that improves the quality of Maps, Navigation, and traffic data. A developer could not turn it off.
You could discuss a special agreement for telemetry control with Mapbox representatives.
