### ISSUE TITLE
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in your app’s privacy manifests must be valid.

### ISSUE THREAD

**Issue by Gautham495** [mapbox/mapbox-maps-ios#2232]
## Environment

- Xcode version: 15.4
- iOS version: 17.5
- Devices affected: All Devices
- Maps SDK Version: 11.4.0

## Observed behavior and steps to reproduce

When I deploy the app to the appstore with help of rnmapbox in react native, the android works, but the iOS gives this error which is causing a lot of headaches.

I am in the latest version and still this issue happens.

<img width="730" alt="Screenshot 2024-09-10 at 1 53 17 PM" src="https://github.com/user-attachments/assets/460484a8-0b78-4b12-96da-35ddb79c82c8">

## Expected behavior

The app has to go through the verification process in apple

## Notes / preliminary analysis

The PrivacyInfo.xcprivacy is completely wrong or non usuable so the apple system rejects it when i push it to production. This has impacted our app's production flow.

This has to be fixed. Why is the privacy manifest file not in the correct format in the pod files? Why is this crucial step missed in testing phase.

Please fix it asap.

## Additional links and references

Nope.

**Comment by baleboy** [comment]
This was resolved in 11.3 and 10.17. For the React Native integration, which is not developed by Mapbox, this comment might help: https://github.com/mapbox/mapbox-maps-ios/issues/2145#issuecomment-2211309455.
