### ISSUE TITLE
Can't download Mapbox-Map Version 11.6.1

### ISSUE THREAD

**Issue by RebinX1** [mapbox/mapbox-maps-ios#2234]
## Environment

- Xcode version: 15.4
- Maps SDK Version: 11.6.1

## Observed behavior and steps to reproduce

I am trying to rebuild my application which uses Mapbox Map Version 11.4.0 to use Mapbox Version 11.6.1, however during the installation process i get "mapbox-maps-ios could not be resolved" however if i install exact version 11.4.0 i dont get that issue.

<img width="1840" alt="Screenshot 2024-09-11 at 4 10 12 PM" src="https://github.com/user-attachments/assets/0f848db0-3825-4d83-891c-c8e46f744ccb">

**Comment by warmachinesocial** [comment]
Sometimes it could be xcode issue, did you try reset cache? Or clean build?

**Comment by aleksproger** [comment]
Hey @RebinX1 , as already mentioned above most probably it's some local cache error, so I'd recommend to clean Xcode derived data and remove spm caches (`rm -rf ~/.swiftpm`). I have vaidated that package resolution finishes successfully on clean fresh xcode project.
