### ISSUE TITLE
Incompatibility Between Mapbox SDK 11.6.1 and Xcode 16.0 Causing Build Errors

### ISSUE THREAD

**Issue by chrisferdian** [mapbox/mapbox-maps-ios#2241]
## Environment

- Xcode version: 16.0
- iOS version: 18.0
- Devices affected:
- Maps SDK Version: 11.6.1

## Observed behavior and steps to reproduce

- After updating Xcode from version 15 to 16, the Mapbox library (SDK version 11.6.1) throws errors when trying to build or run the project.
- The code was working fine with Xcode 15 and Maps SDK version 11.0.

| error |
| --- |
| <img width="1535" alt="image" src="https://github.com/user-attachments/assets/7d1eb9d3-d15d-432f-bbb2-a16e7b03beb9"> |

### Steps to reproduce:

Open the project in Xcode 16.
Build and run the project.

## Expected behavior

The Mapbox library should function as expected, as it did on Xcode 15 with Maps SDK 11.0, without throwing any build or runtime errors.

## Notes / preliminary analysis

- This issue appears to be related to an incompatibility between Xcode 16 and the Mapbox SDK version 11.6.1.
- It’s possible that some APIs or build settings in the new Xcode version might conflict with this version of Mapbox.
- Updating Mapbox to the latest version or modifying specific build settings might resolve the issue.

**Comment by aleksproger** [comment]
Hey, @chrisferdian v11.6.1 is updated to compile with Xcode 16, and the code snipet you're pointing to was indeed a source of problem, but on your screenshot it's clearly fixed version.
So, I'd recommend to clear DerivedData. I validated with new sample project that 11.6.1 builds properly on my machine.

**Comment by chrisferdian** [comment]
Hey @aleksproger , You were totally right. I cleared the DerivedData and everything is building perfectly now. My bad for not trying that sooner. Thanks a lot for the help, I really appreciate it!
