### ISSUE TITLE
How to load OBJ on mapbox ios

### ISSUE THREAD

**Issue by adamdam08** [mapbox/mapbox-maps-ios#2253]
I am working on a Mapbox iOS project using SDK version 11.7.0 and need to programmatically add .OBJ object to a MapView. Any guidance or examples on how to achieve this would be appreciated!

**Comment by pjleonard37** [comment]
Hi @adamdam08 -

This repository is for reporting bugs specifically in the [Mapbox Maps SDK for iOS](https://docs.mapbox.com/ios/maps/guides/). For questions about how to use this SDK or work with Mapbox more broadly, please file a Support question [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231) or write into our Discord server [here](https://discord.com/invite/uMpcC5RmJh).
