### ISSUE TITLE
XCode Cloud, map will not load

### ISSUE THREAD

**Issue by kaspesi** [mapbox/mapbox-maps-ios#2255]
## Environment

- Xcode version: 16.0
- iOS version: 18
- Devices affected: Simulator iPhone 16 (all versions like max etc...)
- Maps SDK Version: v11.6.1

## Observed behavior and steps to reproduce

When testing my application locally, and in the cloud using github actions I see no issue.  When testing with XCode cloud even setting a delay for over 1 minute, the map fails to load.  The annotations do load. 

![Screenshot 2024-10-22 at 3 46 20 PM](https://github.com/user-attachments/assets/50308bf9-e5c1-40b1-be12-90d580c2d5a3)

I am setting the .netrc file using my with a `ci_scripts/ci_post_clone` build script

```
#!/bin/bash

if [ -z "$MAPBOX_ACCESS_TOKEN" ]; then
  echo "Please set the MAPBOX_ACCESS_TOKEN environment variable."
  exit 1
fi

# Create the .netrc file with new lines
cat <<EOF > ~/.netrc
machine api.mapbox.com
login mapbox
password $MAPBOX_ACCESS_TOKEN
EOF

chmod 600 ~/.netrc
```

## Expected behavior

Expected behavior is the map loads.

I have tried using custom style and also default, neither seem to load.

## Notes / preliminary analysis

Seems to be an issue with mapbox loading the map in XCode cloud, did not see any additional steps for using mapbox in xcode cloud tests in the documentation.  Any help/work arounds would be great!

**Comment by OdNairy** [comment]
Xcode Cloud doesn't provide access to the GPU resources, that is why Maps SDK could not render the map. 
CircleCI and GitHub Actions started to provide GPU access since migration to M1/M2 machines.
