### ISSUE TITLE
mapView.on(.cameraChanged) callback is called infinitely

### ISSUE THREAD

**Issue by glyuck** [mapbox/mapbox-maps-ios#240]
## Environment

- Xcode version: Version 12.4 (12D4e)
- iOS version: 14.4 (18D46)
- Devices affected: iPhone 11 Pro simulator
- Maps SDK Version: v10.0.0-beta.16

## Observed behavior and steps to reproduce
`mapView.on(.cameraChanged)` callback is called on a loop even without any interaction with the map.
Steps to reproduce: add the following lines to `LineAnnotationExample.swift`:
```
        mapView.on(.cameraChanged) { event in
            print("Camera changed: \(event)")
        }
```

Console output:
```
Camera changed: <MBMEvent: 0x600002659660>
Camera changed: <MBMEvent: 0x6000026aebc0>
Camera changed: <MBMEvent: 0x60000265c6e0>
Camera changed: <MBMEvent: 0x6000026598e0>
Camera changed: <MBMEvent: 0x600002680020>
Camera changed: <MBMEvent: 0x6000027047a0>
Camera changed: <MBMEvent: 0x600002767400>
... and so on
```

https://user-images.githubusercontent.com/352555/113051668-e9eea400-91ae-11eb-8af3-35af1638f8a7.mov

## Expected behavior

I expect that the callback is called only when the camera is actually changed

**Comment by JPritchard9518** [comment]
I am having the same issue with the SwiftUI example. Camera changed is being called constantly causing the map to pan and zoom very slow.
