### ISSUE TITLE
StyleURI should be a struct

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-maps-ios#252]
StyleURI appears to have the same semantics as what’s called an extensible enumeration in Objective-C. In Swift, it would be more elegant to represent it as a struct: the cases would become `static let`s, and the `custom(url:)` case would go away in favor of the existing `StyleURI(rawValue:)` initializer, which would be much simpler. This is the same way an Objective-C extensible enumeration gets bridged to Swift.

A struct would be more maintainable than the existing approach, especially if the set of available named styles changes in the future: there would be only one place to update instead of keeping four different parts of the file in sync. Anyone who needs to specify a custom URL can write `.init(rawValue: …)` instead of having to choose between `.init(rawValue: …)` and `.custom(url: …)`; the choice may not be obvious to a developer who doesn’t have the implementation code on hand.

https://github.com/mapbox/mapbox-maps-ios/blob/14fe6c2cbd25692a6946311b5df40f24eacb307b/Sources/MapboxMaps/Style/StyleURI.swift#L3-L6

For reference, the MapboxDirections library has a [DirectionsProfileIdentifier](https://github.com/mapbox/mapbox-directions-swift/blob/bbe54bc196e71f9603ecdde50fa125d27785bc5c/Sources/MapboxDirections/DirectionsProfileIdentifier.swift) struct with similar semantics.

/cc @mapbox/maps-ios

**Comment by 1ec5** [comment]
Moreover, if there are no plans to add methods specific to StyleURI or use StyleURIs in places that can’t accept arbitrary URLs, then it would be even simpler to move constants like `streets` to an extension on URL itself.

**Comment by macdrevx** [comment]
I like this. cc: @julianrex

**Comment by knov** [comment]
We should also consider applying this to:
- AnimationOwner
- PreferredFPS

**Comment by macdrevx** [comment]
I decided to keep StyleURI instead of adding static methods to URL for 2 reasons:

1. StyleURI has extra requirements (non-nil scheme)
2. A custom type should reduce noise when using code completion

**Comment by neelmistry94** [comment]
https://github.com/mapbox/mapbox-maps-ios/pull/342
