### ISSUE TITLE
Map zoom animation is shaky

### ISSUE THREAD

**Issue by roboqo** [mapbox/mapbox-maps-ios#263]
## Environment

- Xcode version: 12.4
- iOS version: 14.4
- Devices affected: Looks like all
- Maps SDK Version: 10.0.0-beta.16 - 10.0.0-beta.17

## Observed behavior and steps to reproduce

Starting with Maps SDK v10.0.0-beta.16 zooming animation started to work incorrectly. Sometimes it animates perfectly, but sometimes - it shakes like crazy. I did try to get steps how to reproduce it, but actually there is no steps needed. It does that always, just sometimes it works as expected. See attached video:

https://user-images.githubusercontent.com/66432/114659292-0127a880-9cfc-11eb-9f53-8ad3bbfa9623.mp4

The same problem is when zooming using pinch gesture.

## Expected behavior

Camera animation is smooth.

**Comment by patrickkempff** [comment]
We are experiencing the same issue. 
It looks like when you fling the camera and zoom after it stopped the animation it works for a bit.

**Comment by roboqo** [comment]
Yes, sometimes it works as expected after panning. But then, after more zooming in/out it starts flickering again.

**Comment by knov** [comment]
Thanks for reporting this. We will investigate.

**Comment by patrickkempff** [comment]
It seems that 'v10.0.0-beta.18.1' (PR https://github.com/mapbox/mapbox-maps-ios/pull/282) fixes this issue. 

@roboqo can you confirm this?

**Comment by roboqo** [comment]
Yeah, I did a lot of testing with latest (beta 18.1) version and I can confirm, that everything works as expected. Good job 👍🏻❤️

**Comment by patrickkempff** [comment]
awesome!

cc @knov this issue can be closed!

**Comment by knov** [comment]
Thank you for the support and patience in helping us resolve this issue!
