### ISSUE TITLE
Error decoding symbol layer with text-field set to formatted expression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-maps-ios#268]
## Environment

- Xcode version: 12.4
- iOS version: 14.4
- Devices affected: 
- Maps SDK Version: v10.0.0-beta.16

## Observed behavior and steps to reproduce

If a symbol style layer has `text-field` set to a `format` expression, as in the `road-label` layer of mapbox://styles/mapbox/streets-v11, `Style.getLayer(with:type:)` fails on a decoding error:

```
#0	0x000000010d7213e3 in Style.getLayer<A>(with:type:) at /path/to/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:124
```

```
▿ DecodingError
  ▿ dataCorrupted : Context
    ▿ codingPath : 2 elements
      - 0 : CodingKeys(stringValue: "layout", intValue: nil)
      - 1 : CodingKeys(stringValue: "text-field", intValue: nil)
    - debugDescription : "Failed to decode Value<String>"
    - underlyingError : nil
```

## Expected behavior

`Style.getLayer(with:type:)` should successfully return the requested layer.

## Notes / preliminary analysis

`Layout.textField` is of type `Value<String>?` rather than `Value<Formatted>?`. As a result, JSONDecoder expects the `layout` object’s `text-field` key to be set to something that evaluates to a string rather than a `formatted` expression.

Since the property can evaluate to either a string or a formatted expression, there should probably be an enumeration with `string` and `formatted` as cases with associated values, to allow switching by type. In mapbox/mapbox-gl-native#14094, we took the approach of always returning a formatted expression object for `MGLSymbolStyleLayer.text`, but that loses what could be a useful distinction between plain and rich text.

/ref mapbox/mapbox-gl-native#14393
/cc @mapbox/maps-ios @MaximAlien

**Comment by 1ec5** [comment]
This sounds very similar to #62, except that it manifests as an error in a Result rather than an uncaught exception.

/cc @nishant-karajgikar @jmkiley

**Comment by neelmistry94** [comment]
@1ec5 a fix for this exact issue was merged and released in beta 17. Could you update and retry. Let us know if the issue persists.

**Comment by knov** [comment]
@1ec5 have you verified this resolution?
