### ISSUE TITLE
RTL Text is not rendered for SymbolLayers

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-maps-ios#278]
## Environment

- Maps SDK Version: v10 beta 16

## Observed behavior and steps to reproduce

Using a RTL text string for a SymbolLayer text property results in no text being rendered.

## Expected behavior

Text from symbol layer is correctly rendered. Adding a symbol layer via Studio works as expected.

## Notes / preliminary analysis

You can check this behavior out using this branch of the Maps SDK that I created: [`ac-RTL-Render-Error`](https://github.com/mapbox/mapbox-maps-ios/tree/ac-RTL-Render-Error) and try the [`CustomSymbolAnnotationsExample`](https://github.com/mapbox/mapbox-maps-ios/blob/ac-RTL-Render-Error/Apps/Examples/Examples/All%20Examples/CustomSymbolAnnotationsExample.swift) example. You'll notice that one of the symbol "bubbles" is empty. If you look here: https://github.com/mapbox/mapbox-maps-ios/blob/033826894b93e2292a497c5bf7559273fcc1a8b3/Apps/Examples/Examples/All%20Examples/CustomSymbolAnnotationsExample.swift#L182
you'll see where the text of the feature is set.

The text value is specified here:
https://github.com/mapbox/mapbox-maps-ios/blob/033826894b93e2292a497c5bf7559273fcc1a8b3/Apps/Examples/Examples/All%20Examples/CustomSymbolAnnotationsExample.swift#L219

The English strings will render, the Arabic one will not. I also tried Hebrew and had the same result.

**Comment by avi-c** [comment]
![Missing Text Annotation](https://user-images.githubusercontent.com/10037825/115320276-6cc3a880-a136-11eb-8d2e-c53fd6bd69e6.png)

Note the empty purple bubble.

**Comment by 1ec5** [comment]
This fontstack doesn’t include any Arabic or Hebrew glyphs:

https://github.com/mapbox/mapbox-maps-ios/blob/033826894b93e2292a497c5bf7559273fcc1a8b3/Apps/Examples/Examples/All%20Examples/CustomSymbolAnnotationsExample.swift#L243

As in map SDK v6._x_, you’d need to explicitly include a font that includes Arabic or Hebrew glyphs. For example, the Mapbox Streets v11 style specifies `DIN Offc Pro Regular` and `Arial Unicode MS Regular` for its `road-label` layer. Arial Unicode MS is a pan-Unicode font that includes a wide (though not complete) range of Unicode characters, so it’s often used as a fallback. DIN Pro and Open Sans are limited to Western scripts, while Noto Sans CJK JP is limited to Japanese scripts.

**Comment by avi-c** [comment]
OK, I tried your suggestion of "Arial Unicode MS Regular" and it does indeed work. I wrote this up because from what I saw in the Studio UI I believed that it was saying that "Open Sans Regular" was the active font when I was seeing the text rendered in Studio. After @1ec5's suggestion I see that it was actually going to a fallback of "Arial Unicode MS Regular".
