### ISSUE TITLE
CameraView diff should tolerate very small differences to prevent constant re-rendering

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-maps-ios#283]
## Environment

- Xcode version: 12.4
- iOS version: 14.4.2
- Devices affected:
- Maps SDK Version: built from main

## Observed behavior and steps to reproduce

Build the example app and open the "Display a MapViewController" scene. CPU utilization goes up and stays high (~40%) as long as the view is displaying. I don't expect it would make a big difference, but this is with a test app that modifies the default position in BasicMapExample.swift:

```
        let centerCoordinate = CLLocationCoordinate2D(latitude: 40.748, longitude: -74.0079)
        // Create a camera
        let camera = CameraOptions(center: centerCoordinate,
                                     zoom: 15)
        mapView.cameraManager.setCamera(to: camera)
```

## Expected behavior

After the initial render is complete, there should be no further renders until the user interacts with the map.

## Notes / preliminary analysis

The problem appears to be the logic that looks to see if there's a camera difference:

https://github.com/mapbox/mapbox-maps-ios/blob/7c6333e4967333b11c9a80070af9e6cf9dd6d60c/Sources/MapboxMaps/Foundation/Camera/CameraView.swift#L203

In the debugger, you can see that despite there being no changes, the "targetCamera" ends up with very slightly different lat/lon (like `0.000000001` difference)  from the "currentCamera", so an update is continually fired. I think this is basically an issue of the core engine doing tons of camera math that theoretically should give the same answer but small differences show up because of floating point precision limits. On the core side, they tolerate a small "epsilon" on these values when they're testing for camera equivalency.

cc @alexshalamov @julianrex

**Comment by knov** [comment]
This issue was resolved in beta-19 by way of some modifications to the camera system.
