### ISSUE TITLE
SwiftUI infinite loop when inside NavigationView or TabView

### ISSUE THREAD

**Issue by aperfect** [mapbox/mapbox-maps-ios#325]
## Environment

- Xcode version: 12.5
- iOS version: 14.4.2, 14.5
- Devices affected: Simulator, iPhone 12 Pro
- Maps SDK Version: 10.0.0-beta.19.1

## Observed behavior and steps to reproduce

I'm attempting to follow the example code at https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SwiftUIExample.swift to migrate to the v10 maps in my SwiftUI app, but any view that includes the UIViewRepresentable hits an infinite loop of updateUIView()s and pegs the CPU to 100%, without getting as far as displaying the map view.

## Expected behavior

Expect a map to display

## Notes / preliminary analysis

Whether I paste the example code as-is, modify to my own needs or try to simplify to a minimal functionality, it always loops infinitely. I've also tried a much simpler UIViewRepresentable based on the migration 'Display a map' example and that also loops.

**Comment by aperfect** [comment]
As an update, I had time to dig a little more and it seems to be as soon as the map is used within a Swiftui TabView that the problem occurs.

Any higher up in the view hierarchy and it's fine, but as soon as I try to place SwiftUIMapView within a TabView, it won't render and hits the infinite update loop.

So this works:
```
VStack {
    SwiftUIMapView(mapInitOptions: MapInitOptions(), camera: $camera)
}
```

But this doesn't:
```
TabView {
    SwiftUIMapView(mapInitOptions: MapInitOptions(), camera: $camera)
        .tabItem {
            Label("Map", systemName: "map")
        }
    }
}
```

**Comment by aperfect** [comment]
Putting inside a NavigationView and referencing with NavigationLink also seems to trigger the issue

**Comment by macdrevx** [comment]
Hi @aperfect, I'm having a bit of trouble reproducing this issue. Could you provide a minimal sample project that demonstrates it?

**Comment by macdrevx** [comment]
@aperfect I'm not sure if it's related, but there were a couple of other bugs with the SwiftUI example that we're fixing in https://github.com/mapbox/mapbox-maps-ios/pull/467. It may be worth incorporating the patched version to see whether the update loop still occurs.

**Comment by aperfect** [comment]
Hi @macdrevx, thank you for picking this up. I've been able to get the map working with the latest beta so it does seem to be OK now.
