### ISSUE TITLE
Unable to view 3D terrain

### ISSUE THREAD

**Issue by homathko** [mapbox/mapbox-maps-ios#337]
## Environment

- Xcode version: 12.5
- iOS version: 14.5
- Devices affected: iPhone 12, iOS simulator
- Maps SDK Version: 10.0.0-beta.19

## Observed behavior and steps to reproduce

After including the code snippet from [Migrate to v10](https://docs.mapbox.com/ios/beta/maps/guides/migrate-to-v10/) inside my ViewController I can't see any 3D terrain

## Expected behavior

3D terrain appears

### Code

    import UIKit
    import MapboxMaps

    class MapboxUIViewController: UIViewController {
        var mapView: MapView!
        var handler: ((MapboxCoreMaps.Event) -> Void)?

        override func viewDidLoad() {
            super.viewDidLoad()
            CredentialsManager.default.accessToken = "MY_TOKEN"
            mapView = MapView(frame: view.bounds)
            view.addSubview(mapView)

            // Add terrain
            var demSource = RasterDemSource()
            demSource.url = "mapbox://mapbox.mapbox-terrain-dem-v1"
            demSource.tileSize = 512
            demSource.maxzoom = 14.0
            try! mapView.style.addSource(demSource, id: "mapbox-dem")

            var terrain = Terrain(sourceId: "mapbox-dem")
            terrain.exaggeration = .constant(1.5)

            // Add sky layer
            try! mapView.style.setTerrain(terrain)

            var skyLayer = SkyLayer(id: "sky-layer")
            skyLayer.paint?.skyType = .constant(.atmosphere)
            skyLayer.paint?.skyAtmosphereSun = .constant([0.0, 0.0])
            skyLayer.paint?.skyAtmosphereSunIntensity = .constant(15.0)

            try! mapView.style.addLayer(skyLayer)
        }
    }

**Comment by devioustree** [comment]
You might need to defer accessing `mapView.style` until it has been loaded. Something like:

```swift

class MapboxUIViewController: UIViewController {
    var mapView: MapView!
    var handler: ((MapboxCoreMaps.Event) -> Void)?

    override func viewDidLoad() {
        super.viewDidLoad()
        CredentialsManager.default.accessToken = "MY_TOKEN"
        let mapView = MapView(frame: view.bounds)
        view.addSubview(mapView)

        mapView.mapboxMap.onNext(.styleLoaded) { [weak self] _ in
            self?.styleDidLoad()
        }
    }

    func styleDidLoad() {
        // Add terrain
        var demSource = RasterDemSource()
        demSource.url = "mapbox://mapbox.mapbox-terrain-dem-v1"
        demSource.tileSize = 512
        demSource.maxzoom = 14.0
        try! mapView.mapboxMap.style.addSource(demSource, id: "mapbox-dem")

        var terrain = Terrain(sourceId: "mapbox-dem")
        terrain.exaggeration = .constant(1.5)

        // Add sky layer
        try! mapView.mapboxMap.style.setTerrain(terrain)

        var skyLayer = SkyLayer(id: "sky-layer")
        skyLayer.paint?.skyType = .constant(.atmosphere)
        skyLayer.paint?.skyAtmosphereSun = .constant([0.0, 0.0])
        skyLayer.paint?.skyAtmosphereSunIntensity = .constant(15.0)

        try! mapView.mapboxMap.style.addLayer(skyLayer)
    }
}
```

**Comment by homathko** [comment]
Thank you, that did the trick.

Also, I edited my post above in two spots 1) Specified the wrong SDK version, should be 10.0.0-beta.20, and 2) incorrectly created an extraneous mapView variable in the viewDidLoad method using `let` that causes an exception in `styleDidLoad`, - removed

**Comment by knov** [comment]
Thanks @devioustree for the assistance! 

@ homathko, do you have any outstanding issues with viewing 3D terrain or can this issue be closed?

**Comment by marchuguet** [comment]
I'm having this issue again. I'm testing with the first release candidate and I'm getting a tone of this issue that I'm not sure if it's connected. 

nw_endpoint_handler_set_adaptive_write_handler [C13.1 13.32.62.188:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed

**Comment by astojilj** [comment]
@marchuguet It is different reason this time. Please change the code:

        demSource.tileSize = 512

to

       demSource.tileSize = 514

This is padded DEM tile and provides better performance. That should fix the issue. Sorry for the inconvenience.

**Comment by marchuguet** [comment]
Thank you!

**Comment by homathko** [comment]
I just updated to rc.1, and unfortunately, the issue has returned for me. After the above provided by @devioustree had fixed it, today it regressed back to being a flat map, and is spitting out
```
2021-06-17 13:48:02.630355-0700 FlightWave[78854:2142420] <maps> {com.mapbox.mbgl.Worker 4}[General]: 9/80/174=>9 Enable terrain no data
2021-06-17 13:48:02.630750-0700 FlightWave[78854:2142420] <maps> {com.mapbox.mbgl.Worker 1}[General]: 4/2/5=>4 Enable terrain no data
2021-06-17 13:48:02.631336-0700 FlightWave[78854:2142420] <maps> {com.mapbox.mbgl.Worker 2}[General]: 9/81/173=>9 Enable terrain no data
2021-06-17 13:48:02.631686-0700 FlightWave[78854:2142420] <maps> {com.mapbox.mbgl.Worker 3}[General]: 9/80/173=>9 Enable terrain no data
2021-06-17 13:48:02.631973-0700 FlightWave[78854:2142420] <maps> {com.mapbox.mbgl.Worker 1}[General]: 9/81/174=>9 Enable terrain no data
```

**Comment by astojilj** [comment]
@homathko 

This is different issue. This should resolve it:

Inlining comment from https://github.com/mapbox/mapbox-maps-ios/issues/470#issuecomment-862633816:

Please change the code:

    demSource.tileSize = 512
to

   demSource.tileSize = 514
Full code should look something like this:

        var demSource = RasterDemSource()
        demSource.url = "mapbox://mapbox.mapbox-terrain-dem-v1"
        demSource.tileSize = 512
        demSource.maxzoom = 14.0

514 specifies padded DEM tile and provides better performance than 512 tiles. Sorry for the inconvenience.

We need to update our examples to use 514 tiles and resolve issue with 512 tiles. I don't see a reason you'd want to use 512x512 tiles in future so this is not a temporary workaround.
