### ISSUE TITLE
Mapbox v10 SwiftUI Examples

### ISSUE THREAD

**Issue by BrandonRCR** [mapbox/mapbox-maps-ios#364]
My current app uses Mapbox v9 as a UIViewRepresentable. So migrating over to the new version is very temperamental, having a SwiftUI Example of how to implement v10 would be great especially as Apple keeps pushing devs down the SwiftUI route and will eventually make UIKit obsolete.

Any guidance on implementing Mapbox v10 with SwiftUI would be great.

<img width="782" alt="Screenshot 2021-05-19 at 11 06 15" src="https://user-images.githubusercontent.com/69196922/118795247-4f4b4100-b892-11eb-80de-380c7e114023.png">

**Comment by macdrevx** [comment]
Hi @BrandonRCR, check out the v10 SwiftUI example here: https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SwiftUIExample.swift

Let us know if you find it helpful!

**Comment by BrandonRCR** [comment]
That's great. Thank you
