### ISSUE TITLE
How long is this expected to be in Beta?

### ISSUE THREAD

**Issue by jeradhoy** [mapbox/mapbox-maps-ios#373]
Hello mapbox team! I am curious if you guys have any rough (or even very rough) estimate for how long this will be in an unstable beta state for?

I am trying to figure out if it is worth continuing to build my application with the beta, or whether I should revert back to the non-beta version.

**Comment by jeradhoy** [comment]
Any update on this? Would be good to know a timeline for when I can start to integrate the new map box version into map app. It matters if it is 6 months out or a year out.

**Comment by reubn** [comment]
+1

**Comment by patrickkempff** [comment]
The first release candidate has been released. https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.0.0-rc.1

**Comment by knov** [comment]
You can read more about the Release Candidate status [here](https://www.mapbox.com/blog/maps-sdk-v10-release-candidate).
