### ISSUE TITLE
Failed to build - used swift feature not supported by compiler

### ISSUE THREAD

**Issue by alois-lohner** [mapbox/mapbox-maps-ios#385]
## Environment

- Xcode version:  12.2 and 12.4
- iOS version: 14.5
- Devices affected: any device
- Maps SDK Version: V10 beta 20

## Observed behavior and steps to reproduce

Create a Xcode project, copy the SwiftUI example from "all examples" then try to build the the app

Build failed with 8 Swift compiler errors:
<img width="1728" alt="Bildschirmfoto 2021-05-24 um 17 54 32" src="https://user-images.githubusercontent.com/84730363/119373806-1f000a00-bcb9-11eb-9bcf-d95ecf384766.png">

**Comment by macdrevx** [comment]
These errors have been fixed in RC1: https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.0.0-rc.1
