### ISSUE TITLE
Can't compile the latest Mapbox-maps-ios

### ISSUE THREAD

**Issue by zhouhao27** [mapbox/mapbox-maps-ios#397]
## Environment

- Xcode version: 12.5
- iOS version: 14.5
- Devices affected: all
- Maps SDK Version: latest

## Observed behavior and steps to reproduce

Can't compile. Always got the following error:

> checksum of downloaded artifact of binary target 'MapboxCoreMaps' (7961e5afc73a33c564d213fb379495140dd2379ff32586473a02b99be6ec16e7) does not match checksum specified by the manifest (a9120b7f961a4ee0ca40e3d4d380b0775fcd9149d836a868fe913fbd4b8b37d2)

## Expected behavior

Should be able to compile.

**Comment by julianrex** [comment]
Can you please try `Reset Package Caches`? There was an invalid manifest; commit `a9120b7f961a4ee0ca40e3d4d380b0775fcd9149d836a868fe913fbd4b8b37d2` no longer exists.

**Comment by knov** [comment]
closing this as resolved. please reopen if the above solution does not fix your issue.

**Comment by ablohme86** [comment]
I have the same problem now
![Screenshot 2022-12-05 at 17 59 10](https://user-images.githubusercontent.com/17109732/205696800-d929cc65-3dc6-46c1-a0c3-d245bd56e932.png)
