### ISSUE TITLE
3D puck is not displayed on map

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-maps-ios#399]
## Environment

- Xcode version: 12.5
- iOS version:14.5
- Devices affected: iPhone 
- Maps SDK Version:10.0.0-beta2.0

## Observed behavior and steps to reproduce
1. Build the `Examples` schema
2. Choose the `Custom3DPuckExample`

The "race_car_model" for the Custom 3D Puck Example doesn't show up.

## Expected behavior

There should be  a car model in the map center.

**Comment by edenhikri** [comment]
How did you resolve this? I am having the same problem...

**Comment by ShanMa1991** [comment]
Hi @edenhikri , what's the version of maps-ios are you using right now? Because right now the map SDK supports the instant change of map puck type, it would show the 3d puck directly without time delay. Maybe you could adjust the size and location of the 3d puck, it's shown in somewhere on the map.

**Comment by edenhikri** [comment]
Hi @ShanMa1991 feel free to have a look and replicate if you'd like: https://github.com/mapbox/mapbox-maps-ios/issues/736

**Comment by edenhikri** [comment]
We're you able to find a solution @ShanMa1991

**Comment by edenhikri** [comment]
Hi @ShanMa1991 I have tried to do this... please have a look at my open issue
