### ISSUE TITLE
Upgrade to Turf v2.0.0-beta.1

### ISSUE THREAD

**Issue by chezzdev** [mapbox/mapbox-maps-ios#409]
The [new version](https://github.com/mapbox/turf-swift/releases/tag/v2.0.0-beta.1) of Turf-swift is released. We'd like to update MapboxNavigation to it, so we need Maps to upgrade, as right now the version is pinned to 2.0.0-alpha.3.

**Comment by patrickkempff** [comment]
This is resolved by #440
