### ISSUE TITLE
Interpolation expression should accept array of stops

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-maps-ios#418]
An `interpolate` expression currently takes a dictionary representing the stops as its final argument. By contrast, [the style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#interpolate) represents each stop as a distinct pair of arguments. It should be possible to specify the stops as an ordered array rather than a dictionary.

Stop dictionaries were originally introduced in iOS map SDK v4.0 for continuity with the old StyleValue type system. They had the benefit of being slightly more ergonomic to developers who most commonly have the stop data in that form already. However, in the specific case of the `lineGradient` property, the developer may want to assign two values to each stop to achieve a hard break from one color to the next. This isn’t possible with a dictionary representation, which requires each key to be unique.

The navigation SDK uses a hard break between colors to achieve a progress bar–like appearance along a route line color-coded by traffic congestion. As of https://github.com/mapbox/mapbox-navigation-ios/pull/2377#discussion_r432772524, it [specifies keys](https://github.com/mapbox/mapbox-navigation-ios/blob/85170c55d4563e9d13cb168207d6796198060ae1/Sources/MapboxNavigation/VanishingRouteLine.swift#L292) that differ by the smallest amount representable in floating-point precision. This was sufficient as of map SDK v6._x_, but on long enough lines at a high enough zoom level, it’s still possible to see a slight blur between the segments instead of a hard break.

The most literal translation of the style specification to Swift would require `interpolation` expressions to accept an arbitrary number of alternating keys and values as arguments to the expression. However, that can be quite inconvenient if the data is dynamic and not amenable to hard-coding, as in the traffic congestion use case above. Instead, `interpolation` expressions should accept a single array of key-value tuples: `Sequence, S.Element == (Key, Value)`. This representation has the benefit of being ordered and allowing non-unique keys but also dynamically extensible. Crucially, it’s also consistent with the signature of `Dictionary(uniqueKeysWithValues:)`, and it’s easy to convert an ordinary key-value dictionary to the required type using a full-width conversion: `Array(stopDictionary)`. This representation wasn’t possible in map SDK v6._x_, because Objective-C doesn’t have an equivalent to tuples.

The most straightforward way to introduce stop arrays would be to replace stop dictionaries, which would be backwards-incompatible. However, there may be ways to avoid breaking the public API to support stop arrays.

/cc @mapbox/maps-ios @mapbox/navigation-ios

**Comment by 1ec5** [comment]
@julianrex pointed out that `interpolate` expressions already support an arbitrary number of top-level arguments, with the dictionary syntax being only a convenience. Assuming that’s true, then the workaround would be to use `Expression(operator:arguments:)` instead of passing an ExpressionArgumentBuilder into `Expression(_:content:)`. An array convenience would still be more discoverable, especially since there’s already a dictionary convenience, but it wouldn’t be required for achieving the hard break effect described above.

/cc @nishant-karajgikar

**Comment by ShanMa1991** [comment]
@julianrex  According to the [above](https://github.com/mapbox/mapbox-maps-ios/issues/418#issuecomment-852449926), I create a simple example below to use the `Expression(operator:arguments:)` for `lineLayer.lineGradient`. But it failed with the error below:
`interpolate\" expressions must be arranged with input values in strictly ascending order.`
It seems that the `[Expression.Argument]` still doesn't accept the duplicate Double value for gradient stops right now.

the below is the `LineGradientExample` in `Apps/Examples` with the new expression of the `lineGradient`:
```
import Foundation
import MapboxMaps
import Turf

@objc(LineGradientExample)
public class LineGradientExample: UIViewController, ExampleProtocol {

    internal var mapView: MapView!

    override public func viewDidLoad() {
        super.viewDidLoad()

        let options = MapInitOptions(styleURI: .light)
        mapView = MapView(frame: view.bounds, mapInitOptions: options)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(mapView)

        mapView.mapboxMap.onNext(.mapLoaded) { _ in

            self.setupExample()

            let centerCoordinate = CLLocationCoordinate2D(latitude: 38.875, longitude: -77.035)
            let camera = CameraOptions(center: centerCoordinate, zoom: 12.0)
            self.mapView.mapboxMap.setCamera(to: camera)
        }
    }

    internal func decodeGeoJSON(from fileName: String) throws -> FeatureCollection? {
        guard let path = Bundle.main.path(forResource: fileName, ofType: "geojson") else {
            preconditionFailure("File '\(fileName)' not found.")
        }
        let filePath = URL(fileURLWithPath: path)
        var featureCollection: FeatureCollection?
        do {
            let data = try Data(contentsOf: filePath)
            featureCollection = try GeoJSON.parse(FeatureCollection.self, from: data)
        } catch {
            print("Error parsing data: \(error)")
        }
        return featureCollection
    }

    internal func setupExample() {
        DispatchQueue.main.asyncAfter(deadline: .now()+5.0) {
            self.finish()
        }

        guard let featureCollection = try? decodeGeoJSON(from: "GradientLine") else { return }
        let geoJSONDataSourceIdentifier = "geoJSON-data-source"

        var geoJSONSource = GeoJSONSource()
        geoJSONSource.data = .featureCollection(featureCollection)
        geoJSONSource.lineMetrics = true // MUST be `true` in order to use `lineGradient` expression

        var lineLayer = LineLayer(id: "line-layer")
        lineLayer.filter = Exp(.eq) {
            "$type"
            "LineString"
        }

        lineLayer.source = geoJSONDataSourceIdentifier
        lineLayer.lineColor = .constant(ColorRepresentable(color: UIColor.red))

        // Try to creat a line gradient with abrupt color change instead of a blur effect.
        var arguments: [Expression.Argument] = [.expression(Exp(.linear)), .expression(Exp(.lineProgress))]
        
        let gradientStops: [(Double, UIColor)] = [(0, UIColor.red), (0.5, UIColor.red), (0.5, UIColor.blue)]
        let stopsArray:[Expression.Argument] = gradientStops.flatMap{ (stop) -> [Expression.Argument] in
            let douebleExp:Expression.Argument = .number(stop.0)
            let colorExp:Expression.Argument = stop.1.expressionArguments.first!
            return [douebleExp, colorExp]
        }
        arguments += stopsArray
        let expression = Exp(operator: .interpolate, arguments:arguments)

        lineLayer.lineGradient = .expression(expression)
        

        let lowZoomWidth = 10
        let highZoomWidth = 20
        lineLayer.lineWidth = .expression(
            Exp(.interpolate) {
                Exp(.linear)
                Exp(.zoom)
                14
                lowZoomWidth
                18
                highZoomWidth
            }
        )
        lineLayer.lineCap = .constant(.round)
        lineLayer.lineJoin = .constant(.round)

        try! mapView.mapboxMap.style.addSource(geoJSONSource, id: geoJSONDataSourceIdentifier)
        try! mapView.mapboxMap.style.addLayer(lineLayer, layerPosition: nil)
    }
}
```

**Comment by 1ec5** [comment]
> However, in the specific case of the `lineGradient` property, the developer may want to assign two values to each stop to achieve a hard break from one color to the next.

It turns out the core gl-native code doesn’t support specifying identical input values for two adjacent stops. So this issue is at least blocked, and if gl-native doesn’t intend to support identical input values, then we can close out this feature request as moot.

**Comment by nishant-karajgikar** [comment]
Yep, I concur with what @1ec5 says above!
