### ISSUE TITLE
Expose default HttpService to support partial implementations

### ISSUE THREAD

**Issue by datwelk** [mapbox/mapbox-maps-ios#435]
## New Feature
Expose the implementation of `HttpServiceInterface` that is used by default. 

## Why
This allows 3rd party developers to inherit their custom implementations of the protocol from the default class and as such only provide implementations of protocol methods that the developer wants to be different from default behaviour.

**Comment by patrickkempff** [comment]
Would like to see this as well!

**Comment by akirmse** [comment]
In particular, I need to set the user agent of tile requests for a RasterSource to satisfy a server-side security check.  Is there any way to to this with the existing v10 library?

**Comment by macdrevx** [comment]
Hi all, we'll be exposing a way to get the default implementation of HttpServiceInterface in an upcoming release.

@akirmse when that is available, you'll want to try using its `- (void)setInterceptorForInterceptor:(nullable id<MBXHttpServiceInterceptorInterface>)interceptor;` method which will allow you to customize the requests that are being sent.
