### ISSUE TITLE
Expose MBXDownloadStatus custom initializer

### ISSUE THREAD

**Issue by datwelk** [mapbox/mapbox-maps-ios#439]
## Environment

- Xcode version: 12.5 (12E262)
- iOS version: 14.5
- Devices affected: all
- Maps SDK Version: latest master [(15e3071)](https://github.com/mapbox/mapbox-maps-ios/tree/15e30712b8d44db501931c7001dfef6bac0599f7)

## Observed behavior and steps to reproduce
`MBXDownloadStatus`/`DownloadStatus` default initializer is made unavailable, and it does not provide a custom initializer.

## Expected behavior
If the default initializer is made unavailable, a custom initializer is exposed.

## Notes / preliminary analysis
`HttpResponseData` does have a custom initializer exposed:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1571141/121031052-50dd9a00-c7aa-11eb-9998-f8aa2842c9e6.png">

`DownloadStatus` does not:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1571141/121031121-605ce300-c7aa-11eb-96a5-8b4ced83a434.png">

## Additional links and references
N/A

**Comment by julianrex** [comment]
Hi @datwelk - thanks for the ticket. 

What's your use-case for creating a `DownloadStatus`? Are you creating a custom HTTP service conforming to `HttpServiceInterface`?

**Comment by datwelk** [comment]
My pleasure @julianrex, happy to contribute. That's correct, I am implementing a class conforming to `HttpServiceInterface`. All methods part of the protocol are required, and the `DownloadStatusCallback` argument of the `download` function takes a `DownloadStatus` object.

**Comment by jmkiley** [comment]
Landed in https://github.com/mapbox/mapbox-maps-ios/pull/454
