### ISSUE TITLE
Abnormal CPU usage

### ISSUE THREAD

**Issue by nbieniek** [mapbox/mapbox-maps-ios#469]
## Environment

- Xcode version: 12.5
- iOS version: iPadOS 14.6, iOS 14.6
- Devices affected: iPad Air and iPhone X
- Maps SDK Version: v10.0.0-rc.1

## Observed behavior and steps to reproduce

For simplicity, I used the [SwiftUIExample](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SwiftUIExample.swift). 

Firstly, it's expected for a spike in CPU to occur when moving around the map however it should return to normality once you stop. Just like this ?
![image](https://user-images.githubusercontent.com/79703080/121811240-55df9500-cc53-11eb-9b30-8c51438ec960.png)

https://user-images.githubusercontent.com/79703080/121811762-dfdc2d80-cc54-11eb-983e-9e088ac2c197.mp4

The first spike is the map loading and whatnot, the other 4 spikes are the movements I did.

However, an issue arises when you perform somewhat more 'aggresive' movements because it never drops after stopping.

https://user-images.githubusercontent.com/79703080/121812041-e9b26080-cc55-11eb-88d9-8a18dc5f2a99.mp4

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/79703080/121812141-50d01500-cc56-11eb-9e9c-3793a92a51e8.png">

## Expected behavior

So I decided to see if this was present in the prod release i.e Mapbox v6.3.0 (pretty much [this](https://docs.mapbox.com/help/tutorials/ios-swiftui/)) However, those CPU problems did not occur as seen below:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/79703080/121812763-b58c6f00-cc58-11eb-897d-a78b6e8c828f.png">

https://user-images.githubusercontent.com/79703080/121812856-fedcbe80-cc58-11eb-9909-8466ae209400.mp4

**Comment by macdrevx** [comment]
@nbieniek Thank you for the detailed bug report. Following these, steps, I'm able to reproduce this issue.

**Comment by prgorasiya** [comment]
Just to add my test case as I am also facing the same error, even though I didnt do aggressive movements of map I still see CPU usage around 40%. I waited for the map to load first and then just zoomed out a little and CPU usage spiked to 40% and never returned.

**Comment by macdrevx** [comment]
This fix will be included in RC3
