### ISSUE TITLE
3D Terrain no relief extrusion

### ISSUE THREAD

**Issue by 666bsw** [mapbox/mapbox-maps-ios#470]
## Environment

- Xcode version: Version 12.5 (12E262)
- iOS version: Big Sur 11.4
- Devices affected:
- Maps SDK Version: 10.0.0.0 RC1

## Observed behavior and steps to reproduce

3D Terrain no relief extrusion, no extrusion and examples

## Expected behavior

in previous releases, the extrusion of the relief was evident

**Comment by marchuguet** [comment]
I'm having the same issue.

**Comment by 666bsw** [comment]
> I'm having the same issue.

thanks for supporting
extrusion disappeared even in examples

**Comment by astojilj** [comment]
This should resolve the issue:

Please change the code:

        demSource.tileSize = 512

to

       demSource.tileSize = 514

Full code should look something like this:

```
        var demSource = RasterDemSource()
        demSource.url = "mapbox://mapbox.mapbox-terrain-dem-v1"
        demSource.tileSize = 512
        demSource.maxzoom = 14.0

```
514 specifies padded DEM tile and provides better performance than 512 tiles. Sorry for the inconvenience.

We need to update our examples to use 514 tiles and resolve issue with 512 tiles. I don't see a reason you'd want to use 512x512 tiles in future so this is not a temporary workaround.

**Comment by 666bsw** [comment]
>    demSource.tileSize = 514

Thank you
it works
