### ISSUE TITLE
Panning while zooming not working as expected

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#474]
## Environment

- Xcode version: 12.5.0
- iOS version: 14.6
- Devices affected: All
- Maps SDK Version: 10.0.rc1

## Observed behavior and steps to reproduce

I just tried out the new V10 and immediatly noticed that I can move around in the map any more as I am used to. I can't zoom (spread two fingers apart) while panning (move my two fingers across the screen).
The old version of Mapbox could to that. Live every scrollview on iOS does.

I noticed it somehow works when I start with one finger to pan and then add the second to zoom, but it still feels very strange to me... Not like other iOS scrollviews react.
Or am I just missing something?

## Expected behavior

Map pans AND zooms at the same time

**Comment by patrickkempff** [comment]
I noticed this as well

**Comment by cmilack** [comment]
I think this is happening because `maximumNumberOfTouches == 1 ` on the underlying `UIPanGestureRecognizer` in `PanGestureHandler.swift`.  Removing that setting (and using the default of UINT_MAX) seems to resolve the issue, however, I think this will require additional investigation to determine whether there will be any side effects from this change.

**Comment by cmilack** [comment]
> I think this is happening because `maximumNumberOfTouches == 1 ` on the underlying `UIPanGestureRecognizer` in `PanGestureHandler.swift`. Removing that setting (and using the default of UINT_MAX) seems to resolve the issue, however, I think it will require additional investigation to determine whether there will be any side effects from this change.

This turned out to be incorrect and only partially resolved this issue. The real problem was that we were not shifting the map appropriately during zoom/pinch.
