### ISSUE TITLE
Unable to update location of a Point Annotation

### ISSUE THREAD

**Issue by prgorasiya** [mapbox/mapbox-maps-ios#478]
## Environment

- Xcode version: 12.5
- iOS version: 14.0 and above
- Devices affected: All
- Maps SDK Version: V10. RC-1

I am unable to update location of a point annotation.
Here's how I am adding a point annotation
```
guard let lat = locationManager?.location?.coordinate.latitude else {
            return
        }
        guard let long = locationManager?.location?.coordinate.longitude else {
            return
        }
        let centerCoordinate = CLLocationCoordinate2D(latitude: lat, longitude: long)
        let camera = CameraOptions(center: centerCoordinate, zoom: 14)
        mapView.mapboxMap.setCamera(to: camera)
        view.addSubview(mapView)
        
        mapView.mapboxMap.onNext(.mapLoaded) { [self] _ in
            pointAnnotationManager = mapView.annotations.makePointAnnotationManager()
            pointAnnotation = PointAnnotation(coordinate: centerCoordinate)
            pointAnnotation?.image = .custom(image: UIImage(named: "ic_pink_car")!, name: "Car")
            pointAnnotationManager?.syncAnnotations([pointAnnotation!])
        }
```

And this is how I update the location. 
```
pointAnnotationManager = mapView.annotations.makePointAnnotationManager()
let coordinate = CLLocationCoordinate2D(latitude: 1.313833, longitude: 103.862501)
pointAnnotation = PointAnnotation(coordinate: coordinate)
pointAnnotationManager?.syncAnnotations([pointAnnotation!])
```

The code runs and annotation disappears from the map with below message printed in Xcode Console when I try to update the position.

```
Warning: <Annotations> Failed to remove source / layer from map for annotations due to error: StyleError(rawValue: "Source 3782B-layer is in use, cannot remove")
Warning: <Annotations> Failed to remove source / layer from map for annotations due to error: StyleError(rawValue: "Source 7EDAC-layer is in use, cannot remove")
```

It used to be working prior to RC-1 build but I am not sure if I am doing something wrong here. Please share some light on this.
Thanks

**Comment by prgorasiya** [comment]
Hi, just wanted to check if there's any update on this issue? Or any workaround?

**Comment by szewah** [comment]
I am also experiencing the same issue

`        let centerCoordinate = mapView.cameraState.center
        
        let pointAnnotationManager = mapView.annotations.makePointAnnotationManager()

        var customAnnotation = PointAnnotation(coordinate: centerCoordinate)
        customAnnotation.image = .default
        
        mapView.camera.ease(to: CameraOptions(center: centerCoordinate, zoom: 13), duration: 1.3)
        
        pointAnnotationManager.syncAnnotations([customAnnotation])
        
        self.pointAnnotationManager = pointAnnotationManager`


`<Annotations> Failed to remove source / layer from map for annotations due to error: StyleError(rawValue: "Source 1FE16-layer is in use, cannot remove")`

**Comment by szewah** [comment]
Hi @prgorasiya  I also had the same issue (see above). I'm working around it by clearing the annotations 

`pointAnnotationManager.syncAnnotations([]) `

before adding a new one. I do this on activating the search bar.

**Comment by nishant-karajgikar** [comment]
Hey! So I think the key thing to note here is that the `PointAnnotationManager` must be created after the style has loaded so that it can add the initial source/layer.

@prgorasiya , are you sure that the `onNext` closure is being called in your example? Is it possible that the closure is not being invoked at all? If so, that would explain what you're seeing.

**Comment by nishant-karajgikar** [comment]
Going to close this ticket, if you run into it again please reopen!
