### ISSUE TITLE
Supporting Apple Silicon

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-maps-ios#48]
### Apple Silicon

Supporting Apple Silicon is an important goal for the Maps SDK. This means enabling Apple Silicon M1 Macs to be used as both development machines as well as deployment targets, allowing developers to build new and unique experiences for the desktop.

Now that the SDK and our dependencies support XCFrameworks and Swift Package Manager, we can address the following remaining tasks:

- Ensure all dependencies contain arm64 simulator slices
- Migrate SDK development from using Carthage to SPM internally. 
- Remove all existing Xcode 12 / arm64 simulator hacks from makefiles and Xcode configurations.
- Update Cocoapods podspecs similarly

These unblock us from being able to provide Apple Silicon support via XCFrameworks, and to support Xcode 12.3+ without hacks.

**Comment by 1ec5** [comment]
> Ensure all dependencies contain arm64 simulator slices

MapboxMaps contains an arm64 simulator slice:

https://github.com/mapbox/mapbox-maps-ios/blob/82d5012201fa00b24ff13277c56563b5a4622084/scripts/framework/make-xcframework.sh#L18-L21

Presumably MapboxCoreMaps does as well. This script strips it out, but I don’t think the script is used anywhere:

https://github.com/mapbox/mapbox-maps-ios/blob/82d5012201fa00b24ff13277c56563b5a4622084/scripts/framework/make-core-maps-framework.sh#L11-L14

If I’m not mistaken, MapboxCommon already contains an arm64 simulator slice. Now that #118 and #125 have landed, are there any other binary dependencies blocking Apple Silicon support?

**Comment by macdrevx** [comment]
This was resolved with beta 14: https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.0.0-beta.14
