### ISSUE TITLE
Point Annotation

### ISSUE THREAD

**Issue by 666bsw** [mapbox/mapbox-maps-ios#500]
## Environment

- Xcode version: 12.5
- iOS version: latest
- Devices affected: all
- Maps SDK Version:V10. RC-2

## Observed behavior and steps to reproduce

1. Point Annotation halo is below the coordinates of the annotation.
2. Couldn't find a way to make the annotation layer above the line layer. The line closes the annotation.

https://ibb.co/Y3VfjfK

**Comment by ZiZasaurus** [comment]
@666bsw please note that the order of your annotations/markers matters. Can you add your annotations after the line has been added to the map and confirm that it appears as expected? You can use the following methods to do so: 

- Using makePointAnnotationManager()

- Creating PolylineAnnotationManager first and then PointAnnotationManager second. 

I’m not sure what you meant by “Point Annotation halo is below the coordinates of the annotation” or “the line closes the annotation.” Would you be able to clarify these two points?

**Comment by 666bsw** [comment]
Hello!
with one problem solved, thanks.

Second problem
The annotation tip is not at the actual coordinates.
The center of the annotation is located on the actual coordinates.
This can be seen in the attached screenshot, the tip of the annotation is below the line

**Comment by 666bsw** [comment]
Hello!
with one problem solved, thanks.

Second problem
The annotation tip is not at the actual coordinates.
The center of the annotation is located on the actual coordinates.
This can be seen in the attached screenshot, the tip of the annotation is below the line

The attachment
1.how should the annotation be positioned
2. this is how the mapbox annotation is now positioned

**Comment by macdrevx** [comment]
@666bsw thanks for clarifying. I think that the problem is that setting the iconImage to `.default` doesn't automatically adjust the `iconAnchor` or `iconOffset` to make it so that the point of the marker image is over the correct coordinate. I agree that this behavior is surprising, and we will discuss how we can improve this API.

In the meantime, you'll need to tune the position of the image using `iconAnchor` and `iconOffset`.

**Comment by 666bsw** [comment]
Hello!

thanks for the answer

**Comment by ZiZasaurus** [comment]
@666bsw we have removed this feature and will re-evaluate bringing it back in the future. Please feel free to reopen if you have additional questions.

**Comment by 666bsw** [comment]
Hello!
thanks for the answer )
