### ISSUE TITLE
minZoom is unreachable

### ISSUE THREAD

**Issue by ArtemBurmistrov** [mapbox/mapbox-maps-ios#503]
## Environment

- Xcode version: 12.5
- iOS version: all
- Devices affected: all
- Maps SDK Version: 10.0.0-rc.2

## Observed behavior and steps to reproduce

1. Add the map and set `minZoom` to `0`
2. Add `onEvery(.cameraChanged) { ... }` listener
3. Add `print(mapView.cameraState.zoom)` inside the listener
4. Zoom out and try to reach `minZoom`
5. Observe that `minZoom` is unreachable

## Expected behavior

`cameraState.zoom` should equals `minZoom`

**Comment by macdrevx** [comment]
@alexshalamov I believe this is happening because min zoom in camera bounds is limited to about 0.66 even if you set it to 0. Is that intentional?

**Comment by pjleonard37** [comment]
Closing as stale. Please re-open if this still occurs @ArtemBurmistrov.
