### ISSUE TITLE
Add tintColor to the AttributionButtonOptions

### ISSUE THREAD

**Issue by ArtemBurmistrov** [mapbox/mapbox-maps-ios#504]
## New Feature

| Desired looks (achievable using Mapbox 6.3.0) | Current looks |
|:---:|:----:|
| <img width="120" alt="Screenshot 2021-06-29 at 10 47 02" src="https://user-images.githubusercontent.com/81562554/123758481-a3046d80-d8c7-11eb-9fc6-682f62afee91.png"> | <img width="124" alt="Screenshot 2021-06-29 at 10 42 27" src="https://user-images.githubusercontent.com/81562554/123758518-ad266c00-d8c7-11eb-9e13-38433c85b72a.png"> |

## Why
Mapbox 6.3.0 allows customizing `tintColor` of the attribution button. It would be nice to have the same functionality in a new version as well.

**Comment by macdrevx** [comment]
As of 10.4, this is now possible via `mapView.ornaments.attributionButton.tintColor = .red`

Fixed by https://github.com/mapbox/mapbox-maps-ios/pull/1130

**Comment by juliankroener** [comment]
Can this please also be possible for SwiftUI with `AttributionButtonOptions`?
