### ISSUE TITLE
Add layer below puck

### ISSUE THREAD

**Issue by ir-fuel** [mapbox/mapbox-maps-ios#516]
## New Feature

There is as far as I know no example or documentation on how to be sure that layers that are added to the map appear above the map itself but below the puck.

When adding a layer you currently do:

```
try mapView.mapboxMap.style.addLayer(lineLayer)
```
or you can call 
```
try mapView.mapboxMap.style.addLayer(lineLayer, layerPosition: .below("..."))
```

but there is no way of knowing what the id is of the puck layer. Some digging through the code makes me even wonder if it is 1 id, because there seems to be a layer for imprecise location and another for precise location.

I also no longer see an easy way to iterate over the layers in v10.

## Why

This is what happens right now when I overlay a line layer on my map:

![Screenshot 2021-07-02 at 10 20 56](https://user-images.githubusercontent.com/1573715/124260469-0395e380-db30-11eb-9141-3330a843f9cb.jpg)

Here is the code:

```
                var geoJSONSource = GeoJSONSource()
                geoJSONSource.data = .geometry(.lineString(shape))
                geoJSONSource.lineMetrics = true

                try mapView.mapboxMap.style.addSource(geoJSONSource, id: Self.routeSourceIdentifier)
                
                let layerIdentifier = Self.routeLayerIdentifier
                var lineLayer = LineLayer(id: layerIdentifier)
                lineLayer.source = Self.routeSourceIdentifier
                lineLayer.lineColor = .constant(.init(color: UIColor(named: "brand")!))
                lineLayer.lineWidth = .expression(routeLineWidthExpression())
                lineLayer.lineJoin = .constant(.round)
                lineLayer.lineCap = .constant(.round)
                
                try mapView.mapboxMap.style.addLayer(lineLayer)
```

**Comment by ir-fuel** [comment]
Whatever happened to this?

**Comment by ZiZasaurus** [comment]
@ir-fuel the id of the location layer is called "puck". You can reference this id string using the following line: `mapView.mapboxMap.style.addLayer(lineLayer, layerPosition: .below("puck"))`. 

To verify the name of the location puck you can use `print(self.mapView.mapboxMap.style.allLayerIdentifiers)`.
