### ISSUE TITLE
Target Integrity errors: frameworks were built for  iOS + iOS Simulator

### ISSUE THREAD

**Issue by distantnative** [mapbox/mapbox-maps-ios#518]
## Environment

- Xcode version: 13.0 beta (13A5155e)
- iOS version: 15 public beta 2
- Devices affected: iPhone 11 Pro
- Maps SDK Version: 10.0.0-rc.3

## Observed behavior and steps to reproduce

- Follow the "direct download" instructions at https://docs.mapbox.com/ios/maps/guides/install/
- Try to build project in Xcode
- Receiving the following two "Target Integrity" errors

```
Building for iOS Simulator, but the linked and embedded framework 'Mapbox.framework' was built for iOS + iOS Simulator.
Building for iOS Simulator, but the linked and embedded framework 'MapboxMobileEvents.framework' was built for iOS + iOS Simulator.
```

Might be related to running this on an M1 Mac?

## Expected behavior

- Builds without error messages

**Comment by macdrevx** [comment]
@distantnative thanks for reporting this. The error message you shared mentions `'Mapbox.framework'`, but in v10 we distribute XCFrameworks and none of them are named `Mapbox` (one is named `MapboxMaps`). Based on this, I think you may have ended up with the pre-v10 version of the SDK. Here's the link to the instructions for v10. Could you try again with those and see if it resolves this issue? https://docs.mapbox.com/ios/beta/maps/guides/install/

**Comment by macdrevx** [comment]
Hi @distantnative, were you able to diagnose what was happening here?

**Comment by macdrevx** [comment]
Hi @distantnative, since we haven't heard back, I'm optimistically assuming that you've been able to resolve this issue. If that's not the case, please feel free to reopen and update this issue.
