### ISSUE TITLE
No such module 'MapboxCommon_Private'

### ISSUE THREAD

**Issue by szewah** [mapbox/mapbox-maps-ios#523]
## Environment

- Xcode version: 12.5.1
- iOS version: 11.4
- Maps SDK Version: 'Mapbox-iOS-SDK', '~> 6.3.0'

## Observed behavior and steps to reproduce

pod update

## Expected behavior

pods install properly

## Additional links and references

<img width="796" alt="Screen Shot 2021-07-08 at 12 11 05 PM" src="https://user-images.githubusercontent.com/32065713/124956062-9a0d4d80-dfe5-11eb-8ed2-d363e4fb6573.png">

**Comment by Drusy** [comment]
Hi @szewah, how did you fix this ? I have the same issue using SPM in AnnotationOrchestrator.swift

**Comment by parrots** [comment]
Hey @Drusy, I'm seeing the same in SPM when building on my CI server. Did you get anywhere with this?

**Comment by Drusy** [comment]
Hey @parrots, I think I didn't. Then I tried Mapbox v10 beta, which works using SPM but the API entirely changed.
I would use the .framework directly or go with Carthage for this Mapbox dependency < v10.

**Comment by macdrevx** [comment]
`MapboxCommon_Private` is a v10-only module. The OP indicated `Maps SDK Version: 'Mapbox-iOS-SDK', '~> 6.3.0'` so maybe intermediate build artifacts got into an inconsistent state?

@Drusy @parrots which version(s) of the SDK are you using when you're seeing this issue?

**Comment by parrots** [comment]
@parrots I'm using 10.0 (RC8) via SPM.

**Comment by macdrevx** [comment]
@parrots I noticed that you mentioned it's only happening in CI. One thing this error might suggest is that the binary framework for MapboxCommon wasn't downloaded, and one common cause of this is that the environment isn't configured with a secret token in the `.netrc`. If you have logs around when the SPM dependencies are being installed it might shed some more light on this.

**Comment by parrots** [comment]
@macdrevx It's the exact same environment I was using for v6.3 via Carthage + .netrc, which was running fine for a year+, but I'll see if I can't dig some up.

**Comment by macdrevx** [comment]
@parrots we just heard from some folks internally that they've had an issue like this that was resolved by disabling the parallel build setting. We suspect that it may be an issue with SPM + binary dependencies, but don't have anything more concrete than that at the moment. I'll open a feedback with Apple to see if we can find out more about this.

**Comment by parrots** [comment]
@macdrevx any chance on bringing back Carthage support, then? I'd hate to have to purposely slow down my builds just to support Mapbox.

**Comment by macdrevx** [comment]
> I'd hate to have to purposely slow down my builds just to support Mapbox.

I'd hate for you to need to do that too. We'll definitely continue to investigate this issue to see if we can find a solution. While we don't currently have any plans to bring Carthage support to v10, an alternative to consider is the direct download option (switch to the "Direct Download" tap on this page for instructions: https://docs.mapbox.com/ios/beta/maps/guides/install/#add-the-dependency).

**Comment by parrots** [comment]
Did some further playing around looking into one of the suggested workarounds, and Xcode 13 changed the "parallelize build" checkbox to something that is a bit more clear on what exactly it does (the new "Build Order" option). However, Apple is going out of their way to point out setting it to manual (aka turning off the old parallel option) is _strongly discouraged__, in their own words.

<img width="1104" alt="Screen Shot 2021-10-04 at 22 40 06" src="https://user-images.githubusercontent.com/171163/135961138-8d0d5315-c1e2-40b7-a933-a509c73c28e0.png">

Any headway on this?

**Comment by macdrevx** [comment]
Let's hope so! Please let us know if you find that it's fixed. We'll be testing it internally too.

**Comment by dmiluski** [comment]
Upgrading our CI Process to use Xcode 13.2+ seems to have addressed our CI Build Breaks when parallel builds are enabled.
https://github.com/mapbox/straightaway-ios/pull/1427

**Comment by macdrevx** [comment]
Thanks Dane. We've had another internal confirmation of the fix as well. Closing this issue, but please let us know if you see this happen again in Xcode 13.2 or later.
