### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Turf":

### ISSUE THREAD

**Issue by szewah** [mapbox/mapbox-maps-ios#525]
## Environment

Issue is also linked to  #524

- Xcode version: 12.5.1
- iOS version:
- Devices affected:
- Maps SDK Version: iOS V10

## Observed behavior and steps to reproduce

pod 'MapboxMaps', '10.0.0-rc.3'
pod 'MapboxDirections', '~> 1.2'
pod 'MapboxGeocoder.swift', '~> 0.14'
pod 'MapboxSearch', ">= 1.0.0-beta.7", "< 2.0"

pod install

## Expected behavior
Pods installs

## Notes / preliminary analysis

`[!] CocoaPods could not find compatible versions for pod "Turf":
  In snapshot (Podfile.lock):
    Turf (= 1.2.0, ~> 1.0)

  In Podfile:
    MapboxMaps (= 10.0.0-rc.3) was resolved to 10.0.0-rc.3, which depends on
      Turf (= 2.0.0-beta.1)

Specs satisfying the `Turf (= 1.2.0, ~> 1.0), Turf (= 2.0.0-beta.1)` dependency were found, but they required a higher minimum deployment target.

### These three work together:
  pod 'MapboxMaps', '10.0.0-rc.3'
  pod 'MapboxSearch', ">= 1.0.0-beta.7", "< 2.0"
  pod 'MapboxGeocoder.swift', '~> 0.14'

### These two work together:
  pod 'MapboxNavigation', '~> 1.4'
  pod 'MapboxGeocoder.swift', '~> 0.14'

### These don't work together:
  pod 'MapboxNavigation', '~> 1.4'
  pod 'MapboxMaps', '10.0.0-rc.3'

`
[!] CocoaPods could not find compatible versions for pod "Turf":
  In snapshot (Podfile.lock):
    Turf (= 1.2.0, ~> 1.0)

  In Podfile:
    MapboxMaps (= 10.0.0-rc.3) was resolved to 10.0.0-rc.3, which depends on
      Turf (= 2.0.0-beta.1)

Specs satisfying the `Turf (= 1.2.0, ~> 1.0), Turf (= 2.0.0-beta.1)` dependency were found, but they required a higher minimum deployment target.
`

### These don't work together: 
  pod 'MapboxNavigation', '~> 1.4'
  pod 'MapboxSearch', ">= 1.0.0-beta.7", "< 2.0"

`
[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In snapshot (Podfile.lock):
    MapboxMobileEvents (= 0.10.8, ~> 0.10.2, ~> 0.10.4)

  In Podfile:
    MapboxSearch (< 2.0, >= 1.0.0-beta.7) was resolved to 1.0.0-beta.7, which depends on
      MapboxMobileEvents (~> 1.0.2)

Specs satisfying the `MapboxMobileEvents (= 0.10.8, ~> 0.10.2, ~> 0.10.4), MapboxMobileEvents (~> 1.0.2)` dependency were found, but they required a higher minimum deployment target.

`

**Comment by szewah** [comment]
I removed the Podfile.lock and tried reinstalling. This is now the error

`[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In Podfile:
    MapboxMaps (= 10.0.0-rc.3) was resolved to 10.0.0-rc.3, which depends on
      MapboxMobileEvents (= 1.0.2)

    MapboxNavigation (~> 1.4) was resolved to 1.4.1, which depends on
      MapboxMobileEvents (~> 0.10.2)

    MapboxSearch (< 2.0, >= 1.0.0-beta.7) was resolved to 1.0.0-beta.7, which depends on
      MapboxMobileEvents (~> 1.0.2)`

**Comment by macdrevx** [comment]
@szewah, I'm sorry to hear that you've been running into trouble. Have you tried installing with the `--repo-update` flag? `pod install --repo-update`

**Comment by szewah** [comment]
> pod install --repo-update

Thanks. I tried it. However the same error is appearing.


`[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In Podfile:
    MapboxMaps (= 10.0.0-rc.3) was resolved to 10.0.0-rc.3, which depends on
      MapboxMobileEvents (= 1.0.2)

    MapboxNavigation (~> 1.4) was resolved to 1.4.1, which depends on
      MapboxMobileEvents (~> 0.10.2)

    MapboxSearch (< 2.0, >= 1.0.0-beta.7) was resolved to 1.0.0-beta.7, which depends on
      MapboxMobileEvents (~> 1.0.2)`

**Comment by ZiZasaurus** [comment]
@szewah The two SDKs you’re trying to use (Mapbox Navigation 1.4.1 and Mapbox Search 1.0.0.-beta-7) are not compatible, as they require conflicting MapboxMobileEvents libraries. The last version of MapboxNavigation that is compatible with the current version of the Mapbox Search SDK is v2.0.0-beta.14. 

Please note that MapboxSearch v1.0.0-beta.7 requires MapboxCommon v13.x: https://github.com/mapbox/search-ios/blob/v1.0.0-beta.7/Package.swift#L40, while MapboxNavigation v2.0.0-beta.15 and up will require a newer MapboxCommon.

**Comment by ZiZasaurus** [comment]
Closing this ticket, please comment if you still see this issue.
