### ISSUE TITLE
Feature querying methods should return Turf.Feature, not MapboxCommon.Feature

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-maps-ios#526]
MapboxMap’s feature querying methods’ callbacks should accept `Turf.Feature`s as arguments, not `MapboxCommon.Feature`s. Otherwise, there’s no way for the developer to work with the results in other Mapbox products such as MapboxDirections or MapboxNavigation.

https://github.com/mapbox/mapbox-maps-ios/blob/c622444f28cdb486a4ff384d1ddbeeb4f04883a4/Sources/MapboxMaps/Foundation/MapboxMap.swift#L379-L381

At a glance, it seems like the code would simply need to map the results to this convenience initializer:

https://github.com/mapbox/mapbox-maps-ios/blob/c622444f28cdb486a4ff384d1ddbeeb4f04883a4/Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift#L11

/cc @mapbox/maps-ios @ZiZasaurus @mapbox/navigation-ios

**Comment by bmt2018** [comment]
I was confused by this, as well.  My GeoJSON source is a feature collection created from an array of Turf.Feature objects.  But when querying for the rendered feature that was tapped on, I'm getting back an array of QueriedFeature which use instances of MapboxCommon.Feature.  I was trying to cast MapboxCommon.Feature to Turf.Feature or to be able to init Turf.Feature using MapboxCommon.Feature but couldn't get either to work.

**Comment by nbieniek** [comment]
> I was confused by this, as well. My GeoJSON source is a feature collection created from an array of Turf.Feature objects. But when querying for the rendered feature that was tapped on, I'm getting back an array of QueriedFeature which use instances of MapboxCommon.Feature. I was trying to cast MapboxCommon.Feature to Turf.Feature or to be able to init Turf.Feature using MapboxCommon.Feature but couldn't get either to work.

I ran into the same issue so a workaround I used was something Mapbox's 'internal' code does:
https://github.com/mapbox/mapbox-maps-ios/blob/453577dbdfe76725fe55fe3d3422e3c0853d9bda/Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift#L8-L20

So for example, in my application I need access to the feature's geometry type however, mapbox's feature only returns an integer and I'd prefer a more readable format i.e a String which Turf provides. I created a function: 
```swift
// Convert from Mapbox geometry type to Turfs
	static func convertGeometryType(geometry: MapboxMaps.GeometryType) -> Turf.GeometryType? {
		switch geometry {
		case GeometryType_Point:
			return Turf.GeometryType.Point
		// ... You get the gist
	}
```

Hope that helps @bmt2018 

--- 
Anyway, I think there should be more consistency in the querying methods to prevent from having to do workarounds like this. And by consistency what I mean is that some functionality relies on Turf.Feature whereas some on Mapbox's feature.

**Comment by bmt2018** [comment]
@nbieniek Thank you for the suggestion!  I ended up doing something very similar as a workaround for now.  I also hope that they'll make this more consistent in a future build of the SDK.

**Comment by macdrevx** [comment]
We plan to do this by refining FeatureExtensionValue.featureCollection and QueriedFeature.feature so that their types are Turf types instead of the current MBXFeature-based types.

**Comment by macdrevx** [comment]
Resolved by https://github.com/mapbox/mapbox-maps-ios/pull/717 and https://github.com/mapbox/mapbox-maps-ios/pull/628
