### ISSUE TITLE
Improve GeoJSON object support for `distance` and `within` expressions

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-maps-ios#530]
## New Feature

We should improve support for the [`distance`](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#distance) and [`within`](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#within) expressions. These expressions each take a GeoJSON object. Expressions arguments need to conform to `ExpressionArgumentBuilder`. Turf features currently do not. 

One option may be to add a `geoJSONObject` [argument](https://github.com/mapbox/mapbox-maps-ios/blob/cde53c67406bba7cd2d18d0ff5d290b835fb80a0/Sources/MapboxMaps/Style/Types/Expression.swift#L128-L136).

## Why

Because `Turf.GeoJSONObject` and Turf geometries do not conform to `ExpressionArgumentBuilder`, users currently need to add conformity in their own implementations. This means that users need to extend the feature or GeoJSON object class for their use case so that it conforms to the `ExpressionArgumentBuilder` protocol. They then need to create and pass their geometry object into their `distance` or `within` expression.

cc @nishant-karajgikar

**Comment by nishant-karajgikar** [comment]
I wonder if we should add a catchall case to `Expression.Argument` that takes a `Codable`.

```swift
enum Argument {
    ....
    ....
    case json(Codable)
}
```

We'll have to be careful in the encoding decoding logic though.
