### ISSUE TITLE
Can't retrieve source with id

### ISSUE THREAD

**Issue by Jkurbs** [mapbox/mapbox-maps-ios#531]
## Environment

- Xcode version: 12.5
- iOS version: 14.6
- Devices affected: None
- Maps SDK Version: 10.0.0-rc.3

## Observed behavior and steps to reproduce

I get this error when I try to retrieve a source using the id 

> **Type of expression is ambiguous without more context**

```
func clearRoute() {
   if let source =  mapView?.mapboxMap.style.source(withId: "route-source") as? Source {
            
   }
}
```

What I'm I missing?
Thanks!

**Comment by bmt2018** [comment]
It looks like that method is a generic and it throws:

```
    /**
     Retrieves a source from the map
     - Parameter identifier: The id of the source to retrieve
     - Parameter type: The type of the source
     - Returns: The fully formed `source` object of type equal to `type`.
     - Throws: StyleError or type conversion errors
     */
    public func source<T: Source>(withId id: String) throws -> T {
        return try _source(withId: id, type: T.self) as! T
    }

```
So have you tried calling it like this:

```
        do {
            let source: GeoJSONSource = try mapView.mapboxMap.style.source(withId: "route-source")
        } catch {
            // handle error
        }

```
Obviously you need to adjust the specific type if you're not using GeoJSONSource...

**Comment by Jkurbs** [comment]
@bmt2018  thanks for your answer but unfortunately I've already tried that! 
I'm receiving the same error, look at the picture before. 

<img width="1514" alt="Screen Shot 2021-07-13 at 6 43 22 PM" src="https://user-images.githubusercontent.com/10508898/125534549-6bd4d255-1796-4d13-a0eb-81f91d878923.png">

I don't understand what's going on

**Comment by bmt2018** [comment]
@Jkurbs If you declare your mapView variable as implicitly unwrapped so you're not using optional chaining, does that error go away?

`var mapView: MapView!`

`let source: GeoJSONSource = try mapView.mapboxMap.style.source(withId: "route-source")`

instead of 

`let source: GeoJSONSource = try mapView?.mapboxMap.style.source(withId: "route-source")`

**Comment by Jkurbs** [comment]
Yes It's working thank you for the help! I've created a new ticket for another issue.
Please check it out: https://github.com/mapbox/mapbox-maps-ios/issues/535#issue-944665853

**Comment by ZiZasaurus** [comment]
@Jkurbs Thank you for bringing this to the attention of the team. At the moment you need to specify the type of source, however, we'll evaluate changing the method signature to make this less error prone.

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
