### ISSUE TITLE
Delete annotations from PointAnnotationManager

### ISSUE THREAD

**Issue by Jkurbs** [mapbox/mapbox-maps-ios#535]
## Environment

- Xcode version: 12.5 
- iOS version:
- Devices affected:
- Maps SDK Version: 10.0.0-rc.3

## Observed behavior and steps to reproduce
I'm struggling to find a way to delete my annotations using the PointAnnotationManager

Should I use the AnnotationOrchestrator?

```
 /// Controls the addition/removal of annotations to the map.
 public internal(set) var annotations: AnnotationOrchestrator!
```

**I know how to add annotations on the map but can't find a way to remove them**

`self.pointAnnotationManager = self.mapView?.annotations.makePointAnnotationManager()
   self.pointAnnotationManager?.syncAnnotations(annotations)
`

**Here's how it was done in the previous version of Map**

```    
 func clearAnnotations() {
        
     if let annotations = mapView?.annotations {
          mapView?.removeAnnotations(annotations)
      }
 }
```

**Comment by macdrevx** [comment]
Hi @Jkurbs, try passing an empty array: `self.pointAnnotationManager?.syncAnnotations([])`

**Comment by Jkurbs** [comment]
@macdrevx Thank you so much It's working! Hope you wouldn't mind if I ask you another question. 
What's the best way to get the user's current location?

**Comment by bmt2018** [comment]
@Jkurbs I think what you might be looking for is mapView.location.latestLocation.

If you want to monitor updates to the user location, check out this example: https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/TrackingModeExample.swift

That will show you how to implement a class that conforms to LocationConsumer which has a locationUpdate method that gets called whenever the internal location manager gets a location update.

**Comment by Jkurbs** [comment]
Great many thanks!!!

**Comment by ZiZasaurus** [comment]
@akirmse  just wanted to link you to the commend one of my colleagues left recently regarding performance alignment for annotation management between iOS and Android [here](https://github.com/mapbox/mapbox-maps-ios/issues/599#issuecomment-900384467). 

Additionally, thank you for your feedback regarding API parity. The team will evaluate this for potential implementation in the future.

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
