### ISSUE TITLE
Implement feature state API

### ISSUE THREAD

**Issue by RedChops** [mapbox/mapbox-maps-ios#540]
## New Feature

Both the v10 Android and release JS SDKs expose the feature state API, setFeatureState, getFeatureState, etc. It seems as though the iOS v10 library should also expose this API as well to keep in line with the other libraries.

## Why
The iOS library here offers an Expression for  .featureState, but does not expose any way to set or retrieve any given features state which makes it impossible to work with. Additionally, the two other platforms expose this API, so it would be quite handy to unify them.

**Comment by neelmistry94** [comment]
@RedChops This is currently being worked on should be available in the near future. I do not have an official timeline, but please continue to follow our changelog and release notes to see an announcement of this API.

**Comment by tyofemi** [comment]
released in rc.7
