### ISSUE TITLE
Possible to use the new Offline Manager API with self-hosted tiles?

### ISSUE THREAD

**Issue by bmt2018** [mapbox/mapbox-maps-ios#546]
We have an app that we created for a customer which uses v6.3.0 of the Maps SDK for iOS.  This particular customer self-hosts their own vector tiles and the app makes use of the MGLOfflineStorage object to create and manage offline regions.  Since the new v10 SDK is now in a release candidate state, I've started working to migrate this app to the new v10 SDK.

In looking at the Offline Manager API in the v10 SDK, I see that things have changed a bit and offline support now consists of downloading a style pack as well as a tile region.  I can successfully download the style pack but I ran into issues with the tile region.  I've looked through the v10 docs as well as the offline map example code and it looks like the tile store needs to be initialized with, among other things, a Mapbox access token which this particular customer doesn't have since they're just  using the SDK to render self-hosted tiles.  When I've tried to create a new tile region, I get a "Does not exist" TileRegionError.

I have my own Mapbox access token (for testing) and when I modify this code to create the tile region from the Mapbox servers (as the example @ https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/OfflineRegionManagerExample.swift does), it works fine.  Can anyone from the Mapbox SDK team confirm that the Offline Manager API in the v10 SDK should or should not work when used with self-hosted tiles?  Thanks very much.

**Comment by reubn** [comment]
https://docs.mapbox.com/ios/beta/maps/guides/offline/#supported-tiled-sources

Seems to suggest only Mapbox tile sources are supported. This is massive step backwards.

**Comment by PaulC-ManyHats** [comment]
We are also trying to downloading custom tiles with no luck.  Also, anyone else notice that if you clear the cache using "clearData", the entire offline mode breaks?

**Comment by bmt2018** [comment]
@macdrevx can you or anyone on the Mapbox team tell me what your expectation for the offline map capability is with regard to self-hosted tiles?  We've also tried this using the new Android SDK RC and encountered the same behavior which would seem to suggest that this isn't a bug.  I'm just trying to get some kind of "official" confirmation that this isn't planned for the new SDKs so we can tell our customer that migrating isn't going to work for their specific use case.  Thanks.

**Comment by sbma44** [comment]
Apologies for the slow response. Third party tiles aren't currently supported by the new tilepack-based offline system. We know that this is important functionality for some customers, which is why the legacy tile-based offline system remains available in v10. We're continuing to grow the new system to account for more use cases--it'd be great to hear more details of yours.

While I'm at it, I should probably emphasize that vector and raster tile loads of Mapbox-hosted tilesets are free with a maps v10 MAU. I'd be happy to dig into how to make hosting on our infrastructure make sense for your project, in which case the tile pack offline system would be available.

**Comment by bmt2018** [comment]
@sbma44 Hi Tom.  Thanks very much for the reply. That info is much appreciated.  In our specific case, this customer's map tile data cannot be hosted outside of their organization.  I apologize for that (intentionally) vague explanation but I suspect that you can infer the reason.  

We did notice that the legacy tile-based offline system was still available in the latest v10 SDK RC but the fact that it is marked as a deprecated API made us a little hesitant.  However, if the expectation is for the new tile pack system to **eventually** work with self-hosted tiles, then I think that enables us to start the migration to v10 now and update the code later to use the tile pack offline system.

Thanks again for your reply!

**Comment by sharathprabhal** [comment]
@sbma44 Hi Tom, it's been over year since the last comment. Do you have any updates or timeline on this? If not, any recommendations on how to use self-hosted tiles? Thanks!

**Comment by sharathprabhal** [comment]
Curious what approach others in the thread took to support offline mode for non-mapbox hosted tiles? Any feedback/thoughts is much appreciated. Thanks! @bmt2018 @reubn @PaulC-ManyHats
