### ISSUE TITLE
Documentation for code generation architecture

### ISSUE THREAD

**Issue by landyrev** [mapbox/mapbox-maps-ios#550]
Hi! I was going to implement [isDraggable feature](https://github.com/mapbox/mapbox-maps-ios/issues/501) for PointAnnotation, which would require me to modify PointAnnotationManager, which is [code generated](https://github.com/mapbox/mapbox-maps-ios/pull/398) now.

Is there a way for external developers like me to contribute to Annotation Managers and regenerate them? If yes - maybe we should describe it in DEVELOPING.md?

**Comment by landyrev** [comment]
Hi @nishant-karajgikar, sorry for bothering you, but maybe you could help with that?

**Comment by neelmistry94** [comment]
@landyrev Our code generation is not available for external developers. We do not have it on our backlog to change that, however, could you consider using extensions to fulfill your requirements?

**Comment by landyrev** [comment]
Hey @neelmistry94! Thank you for your reply!

I was trying to implement the "isDraggable" feature similar to the Android SDK one. Here you can see the PR: https://github.com/landyrev/mapbox-maps-ios/pull/1/files

To implement this one, I had to change Point Annotation Manager methods and properties to handle drag events. Overriding or changing those is not possible with Swift Extensions

**Comment by landyrev** [comment]
I hope you'll find a way to allow external developers to make PRs to Annotation Managers someday 🙂

**Comment by neelmistry94** [comment]
@landyrev Thank you for your contribution. We know that `isDraggable` is highly requested feature and we do have that work in our backlog. Please continue to follow our release notes to see when it will be released.
