### ISSUE TITLE
choropleth map for world wide over country selection

### ISSUE THREAD

**Issue by Ranga321** [mapbox/mapbox-maps-ios#558]
i'm getting json response as 

 "countrycode": [
                "AR",
                "AU",
                "BR",
                "CA",
                "CL",
                "CO",
                "DE"
]

how to show these counties as selected to fill the colour  ? any demo is there? 

for lat, long response i can able to use . but for alpha 2 country code i'm not able to use.

Thanks in Advance 🙂

**Comment by ZiZasaurus** [comment]
Hi @Ranga321, with v10, you can use the properties in your json file to style your features with expressions. In [this example](https://github.com/mapbox/mapbox-maps-ios/blob/94cebb9bcc8754cb622dd484967a4c9a346da35b/Apps/Examples/Examples/All%20Examples/DataDrivenSymbolsExample.swift#L55), the property used is `POITYPE`.  I used the same expression with a US States json file and was able to color different states. Below is the expression I used to set the color for New York:

```swift
let fillColorExpression = Exp(.switchCase) { // Switching on a value
     Exp(.eq) { 
          Exp(.get) { "STATE_NAME" } // Get the current value for `STATE_NAME property`
          "New York" // returns true for the equal expression if the name is equal to "New York"
     }
     UIColor.green
     UIColor.clear // default case is to return clear so no color will be loaded
  }
layer.fillColor = .expression(fillColorExpression)
``` 
And this is the outcome: 
![Simulator Screen Shot - iPhone 11 - 2021-07-23 at 11 56 03](https://user-images.githubusercontent.com/44972592/126809063-ee0534e2-ac82-4e43-a340-6b4f53026f13.png)

**Comment by ZiZasaurus** [comment]
Closing, please comment if you still see this issue.
