### ISSUE TITLE
[annotations] Custom styling for annotations

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-maps-ios#56]
## New Feature

Add convenience initializers for the following annotations: 
- NOTE: the default style should be that in the style layer itself

**PointAnnotation**

```swift
PointAnnotation(coordinate:color:)
```

**LineAnnotation**

```swift
LineAnnotation(coordinates:color:lineWidth)
```

**PolygonAnnotation**

```swift
PolygonAnnotation(coordinates:color:outlineColor)
```

- After adding the above convenience initializer, we need to expose a way for those properties to be updated via an `update` function that will be on those annotations. 

## Why

Makes it a little easier for developers to add custom styling, otherwise by default `PointAnnotation` just uses a red pin, and `LineAnnotation` and `PolygonAnnotation` colors are black by default.

## Implementation advice

For `PointAnnotation`, we'll need to pass along the specified color to [`defaultAnnotationImage` here](https://github.com/mapbox/mapbox-maps-ios/blob/main/Mapbox/MapboxMapsAnnotations/PointAnnotation.swift#L101-L106). The default image also has a secondary color and tertiary color, so we probably need to alter the incoming specified color to be two and three levels darker than the incoming specified color for this to look ok.

For all annotations, we'll need to add additional expression logic to the methods inside [`updateStyleLayer(for annotation: Annotation)`](https://github.com/mapbox/mapbox-maps-ios/blob/6b75e812e3de58d4cbca9f877c3353080e1f9dda/Mapbox/MapboxMapsAnnotations/AnnotationManager.swift#L415-L426) to support adding multiple annotations of the same type but with different colors, to ensure for example, a developer could add a red `PointAnnotation` and a blue `PointAnnotation` at the same time.

I'd also propose making the styling properties introduced here get-only for now, and to only support these line width and color properties. Any other styling that is more advanced should make use of the `Style` APIs directly.

**Comment by tobrun** [comment]
We refactored the annotations code, they are now fully stylable
