### ISSUE TITLE
Document how to run example app

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-maps-ios#560]
**Why**

Running the example should be easy and quick. One needs to open the workspace file in the `App.xcworkspace` in `Apps` folder but this method not so obvious.

**Comment by macdrevx** [comment]
Debug app is documented here… https://github.com/mapbox/mapbox-maps-ios/blob/main/DEVELOPING.md#running-the-debug-app

but we should update that to include Examples app, and maybe move some of this to the README.
