### ISSUE TITLE
Missing MGLNetworkConfiguration

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#57]
## New Feature

The old version of the Mapbox iOS SDK had `MGLNetworkConfiguration`. There I could set a delegate and therefore intercept API calls. We need something similar again for the new version.

## Why
We used this feature, to implement our own Offline-Map handling. The problem with the default offline-map handling for us was that it wasn't 1. working in the background, 2. very CPU intensive and 3. quite slow.
That's why we went ahead and pre-packed regions for the user. By intercepting the network calls, we were able to provide those tiles ourselves.
We use the same on Android and iOS, and the Android version seems to have even improved support for that:
https://docs.mapbox.com/android/beta/maps/guides/migrate-to-v10/#example-replace-modular-http-stack

For us this is an absolute must as we already build our whole infrastructure on that.

**Comment by julianrex** [comment]
@georgbachmann thanks for posting and for trying out the beta.

It is possible to replace the HTTP stack on iOS, similar to the process on Android. We have updated the migration guide with a similar snippet: https://docs.mapbox.com/ios/beta/maps/guides/migrate-to-v10/#example-replaceable-http-stack

I'm going to close this issue as answered, but please open another feature request if there are features of the *default* network handling that you would like to see added or amended.

**Comment by georgbachmann** [comment]
Wohoooo... that's great news! Thank you @julianrex ! I'll have a look at what's possible with the `HttpServiceInterface` but looks promising from what I can see in the documentation!
