### ISSUE TITLE
Add equivalent of pre-v10 MGLCoordinateQuad

### ISSUE THREAD

**Issue by SunnyShah407** [mapbox/mapbox-maps-ios#570]
## MGLCoordinateQuad

in pre-v10: we have feature of MGLCoordinateQuad to quadrilateral area as measured on a two-dimensional map projection.

is there any way to use this same in v10

Thanks
Sunny

----

Update:

`ImageSource` currently exposes its coordinates as an array of array of Doubles in longitude-latitude order (i.e. the opposite of `CLLocationCoordinate2D`). These coordinates also need to be specified in the correct winding order. For these two reasons we should wrap this functionality in a new type, i.e. the equivalent of `MGLCoordinateQuad`.

**Comment by julianrex** [comment]
Hi @SunnyShah407 - how were you using `MGLCoordinateQuad` pre-v10? Can you explain what you're trying to achieve?

**Comment by julianrex** [comment]
Assuming this is related to setting the coordinates for an `ImageSource`, currently 

> The "coordinates" array contains [longitude, latitude] pairs for the image corners listed in clockwise order: top left, top right, bottom right, bottom left.

Note that the order here is the *opposite* of that in `CLLocationCoordinate2D`. I will mark this issue as a feature request.

**Comment by macdrevx** [comment]
@nishant-karajgikar can we update the generator to make the type `[Turf.Point]`?
