### ISSUE TITLE
`HttpServiceFactory` should retain a strong reference to custom `HttpServiceInterface` implementations

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#571]
## Environment

- Xcode version: 12.5.1
- iOS version: 14.5
- Devices affected: N/A
- Maps SDK Version: 10.0.0-rc.5

## Observed behavior and steps to reproduce

Given the following implementation, none of the methods on `CustomHttpService` will be called because it is immediately deallocated:

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    HttpServiceFactory.setUserDefinedForCustom(CustomHttpService())
    ...
}

class CustomHttpService: HttpServiceInterface {
    ...
}
```

## Expected behavior

I would expect `HttpServiceFactory` (or some implementation-specific type) to retain a strong reference to the `HttpServiceInterface` implementation. This would simplify the implementation of other types, and it matches standard convention.

**Comment by julianrex** [comment]
cc @brunoabinader

**Comment by brunoabinader** [comment]
`setUserDefinedForCustom` only holds a weak reference to this object, which means that it is up to the client to hold a strong reference of it, and thus, to keep ownership of it. @devioustree in the example above, you are not holding any references to `CustomHttpService()` so this is why the object gets immediately destroyed.

We do not hold strong references to this object as it is passed down to our underlying C++ core logic, which has no control of when and how the custom HTTP implementations operate.

**Comment by devioustree** [comment]
Apologies for not being clear, but my ask is to change the implementation so that it _does_ hold a strong reference.

I am unclear why the C++ implementation cannot hold a strong reference to this type? Is the idea so that we can choose to deallocate the service instance if we want to revert to the default implementation?

If that is the goal, I think it would make more sense to allow `nil` to be passed in to `setUserDefinedForCustom`

**Comment by brunoabinader** [comment]
> I am unclear why the C++ implementation cannot hold a strong reference to this type?

Our C++ core logic is unaware of things like Objective-C's, Swift's  [ARC](https://en.wikipedia.org/wiki/Automatic_Reference_Counting), or Java's garbage collection, which directly affects the lifetime scope of objects implemented in domains. Thus, we hold weak references in C++ so that the client has full control of when their custom HTTP implementations are created and destroyed.

> Is the idea so that we can choose to deallocate the service instance if we want to revert to the default implementation?

This private API is meant as a single shot in runtime. For that, we advise calling for `setUserDefinedForCustom` before anything else e.g. before initializing the map object. Once a custom HTTP implementation is set, or after the map object has been initialized, calling that modifier will cause unknown behavior, thus we do not advise doing so.

**Comment by devioustree** [comment]
> > I am unclear why the C++ implementation cannot hold a strong reference to this type?
> 
> 
> 
> Our C++ core logic is unaware of things like Objective-C's, Swift's  [ARC](https://en.wikipedia.org/wiki/Automatic_Reference_Counting), or Java's garbage collection, which directly affects the lifetime scope of objects implemented in domains. Thus, we hold weak references in C++ so that the client has full control of when their custom HTTP implementations are created and destroyed.

The implication here is that no C++ system should ever hold a strong reference to any objects passed in? That seems unwieldy.

> > Is the idea so that we can choose to deallocate the service instance if we want to revert to the default implementation?
> 
> 
> 
> This private API is meant as a single shot in runtime. For that, we advise calling for `setUserDefinedForCustom` before anything else e.g. before initializing the map object. Once a custom HTTP implementation is set, or after the map object has been initialized, calling that modifier will cause unknown behavior, thus we do not advise doing so.

Deallocating the instance is the same thing as calling the modifier with `nil`. If this is undesirable behaviour then the implementation should try its best to reduce that likelihood. It should make sure that its dependencies have the correct lifespan instead of delegating that responsibility externally.

This is also not a private API when it is publicly accessible and has its own section in the v10 documentation.

**Comment by brunoabinader** [comment]
> The implication here is that no C++ system should ever hold a strong reference to any objects passed in?

For this particular case, in which the object passed to C++ comes from another language domain that contains its own memory management, and by which the client owns the implementation and lifetime of the object, yes.

> Deallocating the instance is the same thing as calling the method with nil.

This can cause unknown behavior to existing pending HTTP requests, thus why we advise against doing so.

> This is also not a private API when it is publicly accessible and has its own section in the v10 documentation.

Apologies, yes indeed this is a [(documented) public API](https://docs.mapbox.com/ios/maps/api/10.0.0-rc.5/common/Classes/MBXHttpServiceFactory.html#/c:objc(cs)MBXHttpServiceFactory(cm)setUserDefinedForCustom:).

**Comment by macdrevx** [comment]
This change will be applied in the upcoming release.
