### ISSUE TITLE
Failed to decode Value<ColorRepresentable> when importing layer definition to v10

### ISSUE THREAD

**Issue by will-r** [mapbox/mapbox-maps-ios#577]
## Environment

- Xcode version: 12.5
- iOS version: 14.5
- Devices affected: Simulator
- Maps SDK Version: 10.0.0rc5

## Observed behavior and steps to reproduce

1. Create map view (in this case, wrapped in UIViewRepresentable for SwiftUI integration)
2. Add vector tile source from MTS
3. Create LineLayer like so:

```
    let layer = try JSONDecoder().decode(LineLayer.self, from: jsonData)
```

With this (minimised) JSON file:

```
{
  "id": "stages-line",
  "type": "line",
  "source": "rally",
  "sourceLayer": "stages",
  "minzoom": 4,
  "paint": {
    "line-color": "rgba(255, 255, 0, 1)",
    "line-width": ["interpolate", ["exponential", 2], ["zoom"], 4, 2, 19, 5]
  }
}
```

Decoding fails with this message:

```
Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [PaintCodingKeys(stringValue: "line-color", intValue: nil)], debugDescription: "Failed to decode Value<ColorRepresentable>", underlyingError: nil)), ["NSDebugDescription": "Failed to decode Value<ColorRepresentable>", "NSCodingPath": [PaintCodingKeys(stringValue: "line-color", intValue: nil)]]
```

## Expected behavior

Yellow lines rendered on map :)

## Notes / preliminary analysis

I am sharing resources between a Mapbox GL control UI and a Mapbox IOS client app. The convergence of style definitions is  potentially very helpful to us, but as yet I have not been able to make it work.

It appears that the decoder wants to support rgba color syntax, but apparently not as I have them. Could you let me know please what colour formats are supported so far and what to expect here?

**Comment by will-r** [comment]
I notice that the decoder for ColorRepresentable expects an Expression. As a result this does work:

```
    "line-color": ["rgba", 255, 255, 0, 1]
```

My workaround for now is to translate all our colours into that format in the API.

**Comment by macdrevx** [comment]
Fixed by https://github.com/mapbox/mapbox-maps-ios/pull/650
