### ISSUE TITLE
After setting compass visibility to .visible, the compass still hides when bearing is north.

### ISSUE THREAD

**Issue by sroche27r** [mapbox/mapbox-maps-ios#583]
## Environment

- Xcode version: 12.5.1
- iOS version: 14.7.1
- Devices affected: (all) but tested on iPhone 11 pro
- Maps SDK Version: 10.0.0.rc-5

## Observed behavior and steps to reproduce

1. create a mapView
2. Set mapView.ornaments.options.scaleBar.visibility = .visible
3. Compass is still behaving with adaptive behavior, disappearing when bearing is north

Here is a code snippet from the basic map example
```
public class BasicMapExample: UIViewController, ExampleProtocol {
    internal var mapView: MapView!
    override public func viewDidLoad() {
        super.viewDidLoad()
        mapView = MapView(frame: view.bounds)
        mapView.ornaments.options.compass.visibility = .visible

```

## Expected behavior

Compass should always remain visible.

## Notes / preliminary analysis

The problem is the visibility value never gets set on the compassView, it never makes it past the OrnamentsManager.  And there is no way to set the OrnamantsManager options before the compass is created.
It looks to be a simple fix, in OrnamentsManger.swift

```
public class OrnamentsManager: NSObject {
...
    private func updateOrnaments() {
        ...
        // Update compass visibility
        compassView.visibility = options.compass.visibility
        ...

```

**Comment by macdrevx** [comment]
Related: scale bar has the same issue.

The intended design here was that `OrnamentsManager` would hide views for ornaments with visibility `.hidden`, and that the views themselves would use alpha to manage adaptive visibility. It looks like there are bugs with `.visible`.

I think we could push all of the visibility logic into the individual ornament view classes and make ornaments manager just propagate the settings to them. The implementations within each view can then be independent.

**Comment by sroche27r** [comment]
I don't think I have permission to link an issue with a PR, but I just submitted a PR to cover this issue:
[https://github.com/mapbox/mapbox-maps-ios/pull/589](https://github.com/mapbox/mapbox-maps-ios/pull/589)
