### ISSUE TITLE
Current zoom

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#584]
## New Feature

Hi, I can't find how to get the current zoom of the camera. Previously it was juz mapView.zoomLevel. Is it somewhere hidden right now? How I can get this value

**Comment by macdrevx** [comment]
Hi @MaciejPachciarekSMT, this has been moved to `mapView.cameraState.zoom`.

**Comment by MaciejPachciarekSMT** [comment]
Thanks a lot!
