### ISSUE TITLE
Camera jumps to different locations when panning

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-maps-ios#59]
## Environment

- Xcode version: 12
- iOS version: 14
- Devices affected: All
- Maps SDK Version: v10.0.0-beta.12

## Observed behavior and steps to reproduce

The map camera will sometimes jump around to a new location when attempting to pan on a map. I believe this happens more often (or maybe even exclusively?) when there is a non-zero pitch value on the map camera. 

## Expected behavior

The map camera should remain in a nearby location when panning across the map.

## Additional links and references

Videos:

https://user-images.githubusercontent.com/10850812/106192881-9c7b9980-6161-11eb-98db-ce4e71d70798.MOV

https://user-images.githubusercontent.com/10850812/106192926-aef5d300-6161-11eb-9050-a319f6fe4872.MOV

**Comment by johnkassebaum** [comment]
Ditto, but also have noticed that:
- left right scrolling always works
- forward back scrolling can a) not work, b) go backwards, c) become continuous during halted contact, d) can jump you around the world, e) can jump you into the black.

For instance, in the Examples app, show 3D terrain, the initial view of the rocky hills with neither scroll forward or back. Left and right works. Reducing pitch angle to 0 allows forward/back to work. But the continuous, revolution, and into the black bugs remain.
