### ISSUE TITLE
Can't get coordinates of PointAnnotation

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#595]
It looks like there was formerly a ```coordinate``` property on PointAnnotation:

https://docs.mapbox.com/ios/maps/api/10.0.0-beta.19/Structs/PointAnnotation.html#/s:10MapboxMaps15PointAnnotationV10coordinateSo22CLLocationCoordinate2DVvp

Can this be restored?

It looks like it might be possible to extract coordinates by digging through the associated Turf ```Feature```, but that's an internal implementation detail that clients shouldn't have to know about.

The Mapbox Android SDK has such a property:

https://docs.mapbox.com/android/maps/api/10.0.0-rc.6/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.annotation.generated/-point-annotation/#com.mapbox.maps.plugin.annotation.generated/PointAnnotation/geometry/#/PointingToDeclaration/

**Comment by macdrevx** [comment]
Hi @akirmse, you're right — at the moment, you have to get the coordinate by digging through the Feature:

```
let point = pointAnnotation.feature.geometry.value as! Turf.Point
let coordinate = point.coordinates
```

I agree that it'd be more convenient if we exposed the Point directly.
