### ISSUE TITLE
Only last delegate on an AnnotationManager receives events

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#598]
Given code like this:
```
self.pointAnnotationManager = self.mapView.annotations.makePointAnnotationManager()
self.polylineAnnotationManager = self.mapView.annotations.makePolylineAnnotationManager()
self.polylineAnnotationManager.delegate = self
self.pointAnnotationManager.delegate = self

extension MapboxSDK: AnnotationInteractionDelegate {
    func annotationManager(_ manager: AnnotationManager,
                           didDetectTappedAnnotations annotations: [Annotation]) {
    }
}
```

The delegate function will be invoked only with events from the PointAnnotationManager, never the PolylineAnnotationManager.  The reason is that each AnnotationManager sets its own ```UITapGestureRecognizer``` on the map's view, but that does not work:

https://stackoverflow.com/questions/11379138/adding-multiple-uitapgesturerecognizers-to-single-view-cocos2d

Perhaps the library should install a single ```UITapGestureRecognizer``` and forward it to all of the AnnotationManagers?

This is with 10.0.0-rc.6.

Other possibilities for improvement:

- The delegate function is invoked for all taps on the map, even when the annotations list is empty.  That behavior will not make a lot of sense once this bug is fixed, and multiple AnnotationManagers are invoking the delegate.

- It sure would be nice if the tap position were passed to the delegate.  For example, it is often useful to know where on a PolylineAnnotation a tap occurred, rather than just knowing that the PolylineAnnotation was tapped somewhere.  It is not straightforward for clients to compute this themselves (they have to separately track the click location by another means).

**Comment by macdrevx** [comment]
Fixed by https://github.com/mapbox/mapbox-maps-ios/pull/709
