### ISSUE TITLE
Insert Mapbox access token build phase in the Examples target does not run when token file is updated

### ISSUE THREAD

**Issue by macdrevx** [mapbox/mapbox-maps-ios#606]
As reported in #596, the Insert Mapbox access token build phase in the Examples target does not run when token file is updated. We should fix this so that the build always uses the current token. This will allow developers to have changes to their token file take effect without cleaning.

**Comment by MartinMajewski** [comment]
Interestingly, my client has his public key (purchased license) in the projects plist.info file, and it works on my machine.
On my second and third projects, where I use my own free account to test stuff and get familiar with MapBox, it does not take the plist.info key or the .mapbox key. It only works when I provide the key directly in code to `let resourceOptions = ResourceOptions(accessToken: )` and provide this to the MapInitOptions.

Moreover, my own free account's key is used inside .mapbox, plist.info, and directly in code. My client's public key is only stored inside the project's plist.info file.

**Comment by tobrun** [comment]
Closing as a duplicate

**Comment by macdrevx** [comment]
Reopening — this is distinct from #673.

**Comment by macdrevx** [comment]
I just tried reproducing this with Xcode 13, and couldn't make it fail. Closing this until we can repro.

**Comment by abhishekthapliyalVZ** [comment]
@macdrevx : Can we reopen this? 
still an issue Xcode 15.2

![Screenshot 2024-04-25 at 1 22 46 PM](https://github.com/mapbox/mapbox-maps-ios/assets/168070428/6bbdcbe9-de39-43f0-adda-b839309d1aa9)
