### ISSUE TITLE
Unable to update PointAnnotation's position

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#607]
How does one move an existing point annotation in 10.0.0-rc.6?  PointAnnotation doesn't seem to have any accessible setters to change its position (coordinates).  The only way I see is to make a new annotation, individually copy over each of the properties of the existing one, remove the old one from ```PointAnnotationManager.annotations```, add the new one, then call ```syncAnnotations```.

This works in the Mapbox Android SDK:
```
            annotation.point = newPoint
            pointAnnotationManager.update(annotation)
```

And this works in the Google Maps SDK:
```
            marker.position = newPosition
```

**Comment by macdrevx** [comment]
Hi @akirmse, in rc7, we've added `PointAnnotation.point`, which you can set. We've also removed `syncAnnotations(_:)` in favor of exposing the setter on `PointAnnotationManager.annotations`. This means that you could so something like…

```
pointAnnotationManager.annotations[idx].point = …
```

If you know the index of the annotation you want to update.

Also, in rc8, we'll be shipping an optimization that makes it less expensive to call the `annotations` setter. https://github.com/mapbox/mapbox-maps-ios/pull/621

**Comment by akirmse** [comment]
Thanks, this allowed me to delete quite a bit of ugly code!
