### ISSUE TITLE
Fit the camera to a given shape doesn't fit exactly

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#610]
## Environment
- Xcode version: Version 12.5.1 (12E507)
- iOS version: iOS 14.5
- Devices affected: all iPhones
- Maps SDK Version: '10.0.0-rc.6'

## Observed behavior and steps to reproduce

When we want to show a map contains coordinates using https://docs.mapbox.com/ios/beta/maps/guides/migrate-to-v10/#fit-the-camera-to-a-given-shape map not shows only some part of map

        let coordinates = [
            CLLocationCoordinate2D(latitude: 50.86305,longitude: 6.03254),
            CLLocationCoordinate2D(latitude: 50.86383,longitude: 6.03362)
        ]

        let camera = mapView.mapboxMap.camera(for: coordinates,
                                              padding: .zero,
                                              bearing: nil,
                                              pitch: nil)
        mapView.camera.ease(to: camera, duration: 0.0)

**Map after using code:**
![imageedit_2_3882943743](https://user-images.githubusercontent.com/24453199/130599845-495e57c5-fd2b-4f2d-a6a6-a3ecf90dc6d1.jpg)

**Map after move left (we can see that the building is not fully visible)**
![imageedit_4_3212956561](https://user-images.githubusercontent.com/24453199/130599871-1ba8d880-7065-492c-8eb0-c74604070bc9.jpg)

**Real point on map (corner of the building on OpenStreetMap and on GoogleMap is the same point)**
<img width="1168" alt="Screenshot 2021-08-24 at 12 04 49" src="https://user-images.githubusercontent.com/24453199/130599202-162cac6d-0726-4ba6-be6a-8f525dc87af6.png">

The same situation is on the sw coordinate. 

## Expected behavior

Given coordinates should be visible

**Comment by MaciejPachciarekSMT** [comment]
Anyone can look at this?

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT  I've included a code snippet below to show that the coordinates you specified are included in the returned camera. Additionally you mentioned that the entire building was not visible after the camera moved. If you wish to include the entire building in the camera view, you can either use the center coordinate of the building or the building's corner coordinates.      

```swift
 let coordinates = [
            CLLocationCoordinate2D(latitude: 50.86305,longitude: 6.03254),
            CLLocationCoordinate2D(latitude: 50.86383,longitude: 6.03362)
        ]

        let camera = mapView.mapboxMap.camera(for: coordinates,
                                              padding: .zero,
                                              bearing: nil,
                                              pitch: nil)
        mapView.camera.ease(to: camera, duration: 0.0)

        mapView.mapboxMap.onNext(.mapLoaded) { _ in
            self.annotationManager = self.mapView.annotations.makeCircleAnnotationManager()

            self.annotationManager.annotations = coordinates.map {
                var annotation = CircleAnnotation(centerCoordinate: $0)
                annotation.circleRadius = 2
                annotation.circleColor = StyleColor(.red)
                return annotation
            }
        }
```

We'd also recommend updating to the latest version of v10 (v.10.0.0-rc.8) to take advantage of any changes to our APIs.

**Comment by MaciejPachciarekSMT** [comment]
Hi @ZiZasaurus 
I've checked the new version of Mapbox and now it's working, however not all as expected.
Right now both coordinates are visible, but after we center to coordinates we would like to restricted camera bounds. In  v10.0.0-rc6 we used 
```
        let cameraBoundsOptions = CameraBoundsOptions(bounds: restrictedBounds, minZoom: mapView.cameraState.zoom)
        try! mapView.mapboxMap.setCameraBounds(for: cameraBoundsOptions)
```
Now it works in this way that it excludes all world except the bounds (Now in some cases it's impossible to see both points). Previously it included bounds (the user saw a map with both points and more even with some padding). How we can achieve it now?

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.

**Comment by MaciejPachciarekSMT** [comment]
Hi @ZiZasaurus 
Can you tell me now what is the equivalent of `mapView.camera.options.bounds!.southwest` in mapBox v10.0.1.
As I see there is no `options` property in camera object. I see there is method `mapView.mapboxMap.cameraBounds.bounds.southwest` however it always return wring value 

```
CLLocationCoordinate2D
  - latitude : -90.0
  - longitude : -180.0
```
