### ISSUE TITLE
Custom UI and animation when displaying PointAnnotation

### ISSUE THREAD

**Issue by hingarn** [mapbox/mapbox-maps-ios#63]
## New Feature

I would like to have a custom UI (labels, multiple images) and animations when displaying `PointAnnotation` on the map. The previous version of SDK provides `MGLAnnotationView` to allow that. I was not able to find an equivalent of that in the new SDK.

## Why
The feature is supported in the previous version of SDK.

**Comment by knov** [comment]
Thanks for providing this feedback @hingarn. We are evaluating how to best provide this support with v10 of the SDK.

**Comment by hingarn** [comment]
Here is an example of a custom annotation that I would like to be able to implement
![Active Pin](https://user-images.githubusercontent.com/816542/112902041-68a5ed00-909a-11eb-91e4-4b0da82749e9.png)

**Comment by doozMen** [comment]
I would really like this ticket to git more attention and if possible a timeline as it is very difficult for us at cowboy.com to release our beta version without updating MapBox 10. I also mentioned that in the PR https://github.com/react-native-mapbox-gl/maps/pull/1222#issuecomment-852194637

**Comment by Eke** [comment]
Hello, any updates on this?

**Comment by emtjoshhart** [comment]
Same, we heavily utilize MGLAnnotationViews and see nothing that replaces it.  

StackOverflow post:  https://stackoverflow.com/questions/70025744/what-replaces-mglannotationview-in-version-10-of-mapbox

**Comment by Toucouleur66** [comment]
Any hope for an answer and a date for this ?

**Comment by macdrevx** [comment]
The first iteration of this feature is now in beta: https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.2.0-beta.1

Please give it a try and share your feedback.

There are already some API changes in the works that we plan to ship in the next 10.2 prerelease.

**Comment by Toucouleur66** [comment]
> 

thanks so much!

**Comment by macdrevx** [comment]
View annotations shipped with v10.2.0. Closing this ticket, but please open new ones with feedback about the new feature.
