### ISSUE TITLE
Conflicting definitions of `Feature` type

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#634]
## Environment

- Maps SDK Version: `ccd01605a571e6f39acea4e56fbe00057e28a103`

## Observed behavior and steps to reproduce

A recent change (#622) means that both `Turf` and `MapboxCommon` are exporting a type called `Feature` (at least when imported in Swift).

This means the following code is ambiguous:

```swift
import MapboxMaps

func foo(feature: Feature) {} // `Feature` is ambiguous for type lookup in this context
```

Of course, I can use `Turf.Feature` or `MapboxCommon.Feature` but this could get verbose.

## Expected behavior

Only one `Feature` type should be exported.

**Comment by macdrevx** [comment]
Thanks for calling this out. We'll fix it before the next release.
