### ISSUE TITLE
Question: How to use `MBXHttpServiceInterceptorInterface`?

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#635]
The changelog notes that there is a new API for using an interceptor for HTTP requests made by the SDK. The API appears to be a method definition on the `MBXHttpServiceInterface` protocol:

```objc
@protocol MBXHttpServiceInterface
/**
 * Set an interceptor for the HttpService's function calls.
 *
 * @param interceptor The interceptor to be set.
 */
- (void)setInterceptorForInterceptor:(nullable id<MBXHttpServiceInterceptorInterface>)interceptor;
```

I'm keen to know how we can use this?

Once I've implemented `MBXHttpServiceInterceptorInterface`, how do I get access to the default `HttpServiceInterface` implementation so I can set my custom interceptor?

One other note: can the name of the method be changed to `setInterceptor:`?

**Comment by macdrevx** [comment]
Related to https://github.com/mapbox/mapbox-maps-ios/issues/435

**Comment by macdrevx** [comment]
Hi @devioustree, thanks for reporting this issue. We'll be exposing an API you can use to get the default instance in an upcoming release.

**Comment by akirmse** [comment]
Is this in rc8 on iOS?  It is on Android: https://github.com/mapbox/mapbox-maps-android/issues/610

**Comment by macdrevx** [comment]
No, this hasn't landed yet for iOS. We expect it to be possible in the next release.
