### ISSUE TITLE
AnnotationInteractionDelegate didDetectTappedAnnotations method contains empty annotations array

### ISSUE THREAD

**Issue by arthurschiller** [mapbox/mapbox-maps-ios#638]
## Environment

- Xcode version: 12.5.1
- iOS version: 14.7
- Devices affected: all
- Maps SDK Version: 10.0.0-rc.8

## Observed behavior and steps to reproduce
When assigning a AnnotationInteractionDelegate to a PointAnnotationManager the **annotationManager(_ manager: AnnotationManager, didDetectTappedAnnotations annotations: [Annotation])** method the annotations property always returns an empty array.
This can easily reproduced by running the example _CustomPointAnnotationExample_ and assigning a delegate to the PointAnnotationManager. Even when zooming in really closely and tapping exactly on an annotations the inspected annotations array is always empty.

## Expected behavior
When tapping an associated annotation the above named method should contain all tapped annotations.

**Notes:**
For my usecase I want to change the annotations image on tap to indicate a selection (plus reverting to the old image if another annotation is tapped). Is there a better way to do this?

**Comment by BennoGreg** [comment]
Can confirm this behaviour as I also ran into the same issue.

**Environment**
- Xcode 12.5.1
- iOS version: 14.5 and 15 Dev Beta 7
- Maps SDK Version: 10.0.0-rc.7

**Comment by zhangjt2018** [comment]
> Can confirm this behaviour as I also ran into the same issue.
> 
> **Environment**
> 
> * Xcode 12.5.1
> * iOS version: 14.5 and 15 Dev Beta 7
> * Maps SDK Version: 10.0.0-rc.7

I got this error too.
