### ISSUE TITLE
v10 zoom and rotation do not use correct axis

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#65]
## Environment

- Xcode version: 12.3
- iOS version: 14.3
- Devices affected: all
- Maps SDK Version: v10 beta 12

## Observed behavior and steps to reproduce

- When the user uses a pinch to zoom gesture, the map zooms in on the center of the view, not the center of the pinch gesture
- When the user uses a pinch to rotate gesture, the map rotates about the center of the view, not the center of the pinch gesture

## Expected behavior

- Whenever a pinch gesture is used, the center of the pinch gesture is the axis of the map change.

## Notes / preliminary analysis

NA

## Additional links and references

NA

**Comment by patrickkempff** [comment]
I also noticed this, zooming feels quite off because of this.

**Comment by jmkiley** [comment]
This seems to have been fixed as of v10.0.0-rc.2. Please let us know if you are still seeing this behavior with rotate or pinch zoom gestures.
