### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 666bsw** [mapbox/mapbox-maps-ios#654]
how to make a user location clickable?
how can i use the view for user location?

thanks

**Comment by ZiZasaurus** [comment]
@666bsw at the moment this is not an out of the box supported feature, however, you could implement this yourself using [query rendered features](https://docs.mapbox.com/ios/maps/api/10.0.0-rc.8/Classes/MapboxMap.html#/s:10MapboxMaps19MapFeatureQueryableP21queryRenderedFeatures2at7options10completionySo7CGPointV_So23MBMRenderedQueryOptionsCSgys6ResultOySaySo010MBMQueriedD0CGs5Error_pGctF) directly and your own tap gesture recognizer. Regarding your inquiry about using the view for user location, are you referring to using view backed annotations for the user location annotation?

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
