### ISSUE TITLE
SDK Filesize Doubled vs Previous SDK

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-maps-ios#672]
I've been attempting to port from the old SDK to the new one over the last week, and got to the point where I was able to prep a built for TestFlight. However my automated build analysis tools highlighted something very surprising - the cost of shipping the new SDK, in terms of megs added to our app's download size (even bitcode optimized), has more than _doubled_. It has gone from 6.2megs with the old SDK to 14.6megs. (adding up lines 1, 3, 6, and 7)

![132918426-4466925c-2e3c-4f6b-badc-a33e970fc908](https://user-images.githubusercontent.com/171163/132918871-7c53f295-fc21-4fbe-8342-7a2fb6f9f430.png)

Mapbox was already our largest dependency at 6.2megs with the old SDK, but now Mapbox is an order of magnitude larger than the vast majority of our other dependencies. We have many users in low-bandwidth environments and this 10% increase in our binary size is a concern.

What plans are in place to address this dramatic increase in binary size?

--

Integration method: Swift package manager. Using RC8.

**Comment by macdrevx** [comment]
Hi @parrots, binary size is definitely very important to many folks who use Mapbox. Could you double check something for me? What is the source of line 1? Is there any chance that it's the v6 SDK? For v10, you could expect to see MapboxMaps, MapboxMobileEvents, Turf, MapboxCommon.framework, and MapboxCoreMaps.framework.

**Comment by parrots** [comment]
Good call, Carthage was still embedding the legacy frameworks even though they were unlinked from the project.

Still seeing a 41% increase in the framework size from v6.3 -> v10.0, but at least that's not double.
