### ISSUE TITLE
Inaccurate documentation for setting example app access token

### ISSUE THREAD

**Issue by aleksigron** [mapbox/mapbox-maps-ios#673]
## Environment

- Xcode version: 12.5.1
- iOS version: N/A
- Devices affected: N/A
- Maps SDK Version: 10.0.0-rc8

## Observed behavior and steps to reproduce

The [examples readme file](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/README.md) states

> When you get to the "Configure your public token" step, you can optionally place your public token in the file ~/.mapbox instead of modifying the Example app's Info.plist.

But if I don't place the public token into the ~/.mapbox file, the build gives the following error, making it non-optional:

```
Inserting Mapbox access token...
'error: Missing Mapbox access token'
error: Get an access token from <https://www.mapbox.com/studio/account/tokens/>, then create a new file at /Users/aleksigron/.mapbox that contains the access token.
```

## Expected behavior

If no public token is placed in the ~/.mapbox file, the build step doesn't give an error and leaves the value in Info.plist in place.

## Notes / preliminary analysis

Either the documentation should be changed to indicate the .mapbox file is not optional, or the build step shouldn't produce an error when the file is missing or empty.

**Comment by nishant-karajgikar** [comment]
Thanks for flagging this! We're taking a look!
