### ISSUE TITLE
Feature identifier and QueriedFeature identifier type inconsistency?

### ISSUE THREAD

**Issue by bmt2018** [mapbox/mapbox-maps-ios#675]
## Environment

- Xcode version: 12.5.1
- iOS version: 14.8
- Devices affected: iPhone 12 Pro Max
- Maps SDK Version: v10.0.0-rc.8

## Observed behavior and steps to reproduce

When I create a new Feature object, I assign the identifier as an integer like this:

```
let point = Point(CLLocationCoordinate2D(latitude: latitude, longitude: longitude))
let identifier: Int = 313037
var feature = Feature(geometry: Geometry.point(point))
feature.identifier = .number(.int(identifier))

```

Dumping this object to the console shows the following:

```
  ▿ Turf.Feature
    - type: Turf.FeatureType.feature
    ▿ identifier: Optional(Turf.FeatureIdentifier.number(Turf.Number.int(331037)))
      ▿ some: Turf.FeatureIdentifier.number
        ▿ number: Turf.Number.int
          - int: 331037

```

I have a tap gesture recognizer that I'm using to determine when the user taps on the map and to get the feature (or nearest feature) that they tapped on.  This code calls the queryRenderedFeatures method which, of course, calls a completion handler with an array of QueriedFeature objects.  When I dump the QueriedFeature object(s) to the console, I see that the identifier is a Double instead of an Int:

```
▿ Turf.Feature
  - type: Turf.FeatureType.feature
  ▿ identifier: Optional(Turf.FeatureIdentifier.number(Turf.Number.double(331037.0)))
    ▿ some: Turf.FeatureIdentifier.number
      ▿ number: Turf.Number.double
        - double: 331037.0

```

## Expected behavior

I was expecting that the identifier type would be consistent between the original Feature and the QueriedFeature.

**Comment by ZiZasaurus** [comment]
@bmt2018 this has been addressed [here](https://github.com/mapbox/mapbox-maps-ios/pull/676) and should be resolved in our next release.

**Comment by bmt2018** [comment]
@ZiZasaurus Thank you!  Much appreciated.
