### ISSUE TITLE
Cannot update pod install rc8 for navigate  by podfile 

### ISSUE THREAD

**Issue by williamlongg** [mapbox/mapbox-maps-ios#678]
## New Feature

<- Description of the feature being requested and any outcomes desired, an example use case, and any suggestions for solution ->
As you see  , I cannot use Mapbox Naviagate version which is suitable for mapbox rc8 . 
Please update or support me how to use mapbox Navigate in mapboxMap rc8 
<img width="1030" alt="Screen Shot 2021-09-15 at 10 22 00" src="https://user-images.githubusercontent.com/70317998/133368508-494f91fc-2120-4ba9-9778-82b2717c5da5.png">

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

**Comment by 1ec5** [comment]
The navigation SDK is being upgraded for compatibility with v10.0.0-rc.8 in mapbox/mapbox-navigation-ios#3342. It’s planned to go into navigation SDK v2.0.0-rc.2, but keep an eye on that PR in case the timing works out differently. Once the PR lands, you can depend on the main branch for testing purposes, regardless of which release candidate it is officially included in.

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
