### ISSUE TITLE
Inappropriate scrollings on the map

### ISSUE THREAD

**Issue by lmelnykmylivn** [mapbox/mapbox-maps-ios#681]
## Environment

- Xcode version: 12.5.1 (12E507)
- iOS version: 14.7.1
- Devices affected: iPhone 8, iPhone X (I believe all devices)
- Maps SDK Version: 10.0.0-rc.7 / 10.0.0-rc.8

## Observed behavior and steps to reproduce

I'm trying to adjust the map camera with the same coordinate bounds but with different edge paddings.
Behaviour: sometimes animation it correct but sometimes map scrolling looks like it jumps to some far location and then animates to desired location very fast, please see the video:

https://user-images.githubusercontent.com/90774405/133451257-e35144d0-ea16-4a2b-b469-8d2702fdeea4.mp4

Here is a code snippet:
```swift
    private func adjustMapView() {
        var padding = Constants.MapViewConstants.selectionAreaInsets
        if keyboardHeight > 0 {
            padding.bottom += keyboardHeight + Constants.EditView.height - mapView.safeAreaInsets.bottom
        }
        let animationDuration: TimeInterval = 1
        let bounds = CoordinateBounds(southwest: selectedRegion.southWest, northeast: selectedRegion.northEast)
        let cameraOption = mapView.mapboxMap.camera(for: bounds, padding: padding, bearing: nil, pitch: nil)
        print("Current camera state:")
        print("\(mapView.cameraState)")
        print("Camera will ease to:")
        print("\(cameraOption)")
        mapView.camera.ease(to: cameraOption, duration: animationDuration, curve: .easeInOut) { _ in }
    }
```

Here are outputs for updating camera position:
1) Keyboard appearing

```
    Current camera state:
    CameraState(
        center: __C.CLLocationCoordinate2D(latitude: 48.177827618271984, longitude: 11.537477999998515),
        padding: __C.UIEdgeInsets(top: 32.0, left: 56.0, bottom: 32.0, right: 56.0),
        zoom: 12.48817220389551,
        bearing: -0.0,
        pitch: 0.0
    )
    
    Camera will ease to:
    CameraOptions(
        center: Optional(__C.CLLocationCoordinate2D(latitude: 48.17781965784954, longitude: 11.537477999999794)),
        padding: Optional(__C.UIEdgeInsets(top: 32.0, left: 56.0, bottom: 527.0, right: 56.0)),
        anchor: nil,
        zoom: Optional(12.431388346656073),
        bearing: nil,
        pitch: nil
    )
```

2) Keyboard disappearing

```
    Current camera state:
    CameraState(
        center: __C.CLLocationCoordinate2D(latitude: 48.177819657849554, longitude: 11.537477999999766),
        padding: __C.UIEdgeInsets(top: 32.0, left: 56.0, bottom: 527.0, right: 56.0),
        zoom: 12.431387901306152,
        bearing: -0.0,
        pitch: 0.0
    )
    
    Camera will ease to:
    CameraOptions(
        center: Optional(__C.CLLocationCoordinate2D(latitude: 48.17781965785048, longitude: 11.537477999999027)),
        padding: Optional(__C.UIEdgeInsets(top: 32.0, left: 56.0, bottom: 32.0, right: 56.0)),
        anchor: nil,
        zoom: Optional(12.487615883625027),
        bearing: nil,
        pitch: nil
    )
```

## Expected behavior

Camera should be animated smoothly

Best regards,
Leonid at Mylivn

**Comment by macdrevx** [comment]
@lmelnykmylivn thanks for reporting this issue. Could you provide a few more details?

* What is the value of `bounds` you're passing in to `camera(for:...)`?
* Can you check whether the `MapView`'s frame is changing?

**Comment by lmelnykmylivn** [comment]
@macdrevx thanks for fast reply! Here are details:

> What is the value of bounds you're passing in to camera(for:...)?

```print("bounds => southwest: \(bounds.southwest), northeast: \(bounds.northeast)")```
prints to console:
```
bounds => southwest: CLLocationCoordinate2D(latitude: 48.167651661238466, longitude: 11.521378539064166), northeast: CLLocationCoordinate2D(latitude: 48.18912683662106, longitude: 11.553577460930534)
```

> Can you check whether the MapView's frame is changing?

The frame isn't changing

> Does this also happen on simulator?

Yes, it does

> Does the app run any other animations that might be happening simultaneously?

Yes, as you can see on the video, there are keyboard animation with a panel moving up/down
I've just tried to separate map animation from other animations and the map animation started looking fine:
```
DispatchQueue.main.async { [weak self] in
    self?.adjustMapView()
}
```

**Comment by macdrevx** [comment]
> I've just tried to separate map animation from other animations and the map animation started looking fine.

Very interesting. The SDK uses UIView animations under the hood to do the interpolation of the map camera values. I'm guessing that we're doing something under the assumption that we're not inside of an animation block, but that maybe we actually are in an animation block. Can you share some more about the context of the code where you call `adjustMapView`? Is it called from within an animation block?

**Comment by lmelnykmylivn** [comment]
> Can you share some more about the context of the code where you call adjustMapView? Is it called from within an animation block?

It is called on listening keyboard appearing/disappearing notifications:
- UIResponder.keyboardWillShowNotification
- UIResponder.keyboardDidShowNotification
- UIResponder.keyboardWillChangeFrameNotification
- UIResponder.keyboardDidChangeFrameNotification
- UIResponder.keyboardWillHideNotification
- UIResponder.keyboardDidHideNotification

Here is an example of listeners:
```swift
NotificationCenter.default.publisher(for: UIResponder.keyboardWillShowNotification)
    .sink { [weak self] value in
        // The call stack chain starts from here
    }.store(in: &disposeBag)
```

**Comment by macdrevx** [comment]
@lmelnykmylivn I'm pretty sure I've fixed this issue with https://github.com/mapbox/mapbox-maps-ios/pull/684. If you have a chance, you try using that branch and see if it resolves it for you?

**Comment by lmelnykmylivn** [comment]
@macdrevx it looks like fixed 😎  Thanks you!
