### ISSUE TITLE
Style has no layers property

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#69]
## New Feature

In < Mapbox v10, `style.layers` exists. 
Looks like Android can at least get a list of style layer identifiers: https://docs.mapbox.com/android/maps/api/10.0.0-beta.12/-mapbox%20-maps%20-android/com.mapbox.maps/-style/get-style-layers.html

## Why

Stylelayers can be logically grouped by type or by content association. One way to do this is to access all the identifiers of all stylelayers, and select those whose identifiers satisfy some condition, like has a certain substring. Would need, tho, access to `mapView.style.layers` for that. 

Was there a good reason for not providing `style.layers` in the new world?

**Comment by johnkassebaum** [comment]
I note that I can access `style.styleManager.getStyleLayers()`. There is no documentation for `StyleManager`.

**Comment by neelmistry94** [comment]
@johnkassebaum This is a little buried but we do have docs at https://docs.mapbox.com/ios/maps/api/10.0.0-rc.5/core/Classes/MBMStyleManager.html#/c:objc(cs)MBMStyleManager(im)getStyleLayers. The `StyleManager` actually comes from our CoreMaps

**Comment by macdrevx** [comment]
In v10, you can get all the layers via a combination of [`Style.allLayerIdentifiers`](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/Style.html#/s:10MapboxMaps5StyleC19allLayerIdentifiersSayAA0E4InfoVGvp) and [`Style.layer(withId:)`](https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/Style.html#/s:10MapboxMaps5StyleC5layer6withIdAA5Layer_pSS_tKF)

**Comment by macdrevx** [comment]
Closing this since it's pretty stale, but please feel free to reopen with more info if the solution I mentioned is insufficient for your use case.
