### ISSUE TITLE
The `locationProvider` stops updating location when `puckType` set to `nil`

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-maps-ios#691]
## Environment

- Xcode version: 12.5
- iOS version: 14.5
- Devices affected: all
- Maps SDK Version: 10.0.0-rc.7 to now

## Observed behavior and steps to reproduce

When we try to use our own user location indicator layer and set the `mapView.location.options.puckType = nil`, the `locationProvider` stops updating location. It leads to the `mapView` stops working with camera and other location listeners.

https://github.com/mapbox/mapbox-maps-ios/blob/bedc49744970602ebc10c6de3f8a2b4cc6f084a6/Sources/MapboxMaps/Location/LocationManager.swift#L203-L205

## Expected behavior

When the  `mapView.location.options.puckType = nil`, the `locationProvider` still updates location but just removes the `puck` from the location consumers.

## Additional links and references

There's a ticket related with this issue about hiding the map puck and the camera not working. https://github.com/mapbox/mapbox-navigation-ios/issues/3377

**Comment by ZiZasaurus** [comment]
@ShanMa1991 thanks for writing in. Would you mind sharing your reasoning behind setting `puckType` to nil rather than using .puck2D() or .puck3D()?

**Comment by ShanMa1991** [comment]
Hi @ZiZasaurus , right now if user want to hide the user location layer by setting `puckType` to nil, the `mapView` won't provide location update, thus during the free drive, the camera and other location consumers won't receive any location update. It would lead to the whole `mapView` stops.

**Comment by ZiZasaurus** [comment]
@ShanMa1991 ah, thank you. I was able to reproduce this behavior and will discuss with the team.
