### ISSUE TITLE
Ambiguous methods when importing `Style` SPIs

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#704]
## Environment

- Xcode version: 12.5.1
- iOS version:
- Devices affected:
- Maps SDK Version: 10.0.0-rc.9

## Observed behavior and steps to reproduce

`Style.swift` contains two definitions for `layerProperty(for:property:)`:

```swift
public func layerProperty(for layerId: String, property: String) -> Any
@_spi(Experimental) public func layerProperty(for layerId: String, property: String) -> StylePropertyValue
```

I wish to use the non-SPI method here. But if I need to use an unrelated SPI, both methods are exposed. Since the experimental SPI is more specific, the Swift compiler wants that to take precedence. This means the following code is ambiguous:

```swift
@_spi(Experimental) import MapboxMaps

let style: Style = ...
let type: String = style.layerProperty(for: "foo", property: "type") as! String
```

<img width="353" alt="Screenshot 2021-09-22 at 16 45 52" src="https://user-images.githubusercontent.com/38645/134436644-58d1a1e3-cff6-4fe2-aa6d-b8385deec180.png">

**Comment by macdrevx** [comment]
Thanks for reporting this.

**Comment by neelmistry94** [comment]
@devioustree This issue has been fixed in https://github.com/mapbox/mapbox-maps-ios/pull/708. Please let us know if there are any issues still.

**Comment by devioustree** [comment]
Hah, `moveLayer` was the experimental method I needed and that's been marked stable!

**Comment by neelmistry94** [comment]
@devioustree Hopefully that recent PR fixed a lot of issues and prevents further issues. Thanks for opening an issue and being a user of mapbox.
