### ISSUE TITLE
Modifying a property of the layout property of a stylelayer has no effect 

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#72]
## Environment

- Xcode version: 12.3
- iOS version: 14.3
- Devices affected: All
- Maps SDK Version: v10 beta 12

## Observed behavior and steps to reproduce

```
var result = self.mapView.style.getLayer(with: id, type: LineLayer.self)
if case .success(var lineStyleLayer) = result {
    lineStyleLayer.layout!.visibility = .visible
}
```
Has no effect on the visibility of the stylelayer.

But if one does:

```
self.mapView.style.removeStyleLayer(forLayerId: id)
self.mapView.style.addLayer(layer: lineStyleLayer)
```
...then the stylelayer is visible.  BUT one had to remove the stylelayer from style, and so order is lost -- unless you are expecting developers to have all stylelayer identifiers and layer positions at the ready when they want to change the visibility of a stylelayer.

## Expected behavior

Changing the `visibility` property of the `layout` of a stylelayer should make the stylelayer visible.

**Comment by johnkassebaum** [comment]
One thought is that the `Style` type could include a method like existing `updateSourceProperty(id:property:value:)` but work on stylelayers. As as stylelayer types have value semantics now, changes to the instance returned from `getLayer(with:type:)` clearly will not affect a `style`. But the ability to dynamically control visibility, predicate, and other properties of stylelayers of a `style` is both powerful and essential.

**Comment by julianrex** [comment]
@johnkassebaum thanks for the request and for the valuable feedback.

The Swift `*Layer`s are structs (value types), so the map needs to be updated if they are changed. Currently there is a low-level API to do this (essentially the method you propose above), but we do have a PR (that has just merged 😃) to provide an update mechanism: https://github.com/mapbox/mapbox-maps-ios/pull/85.

Closing as fixed!

**Comment by johnkassebaum** [comment]
@julianrex Good deal. To be in beta-14 perhaps?
