### ISSUE TITLE
[MGL_MMEEventsManager isEnabled] Crash on iOS 15

### ISSUE THREAD

**Issue by DntPullALockett** [mapbox/mapbox-maps-ios#721]
## Environment

- Xcode version: 12.5.1
- iOS version: 15.0
- Devices affected: Any device on iOS 15
- Maps SDK Version: 5.4.0

## Observed behavior and steps to reproduce
Found a crash on my Crashlytics dashboard,

## Notes / preliminary analysis
No additional logs showing

**Comment by ZiZasaurus** [comment]
@DntPullALockett, just want to verify the version of the SDK where you're seeing this behavior -- is it 5.4.0 or the latest version 6.4.0?

**Comment by DntPullALockett** [comment]
> @DntPullALockett, just want to verify the version of the SDK where you're seeing this behavior -- is it 5.4.0 or the latest version 6.4.0?

I am seeing this on 5.4.0 

<img width="1318" alt="Screen Shot 2021-09-30 at 4 36 08 PM" src="https://user-images.githubusercontent.com/51751780/135526625-0346a106-5075-474d-91f1-c8f5d76e8896.png">

**Comment by ZiZasaurus** [comment]
@DntPullALockett support for iOS 15 has been added to v6.4.0.

**Comment by DntPullALockett** [comment]
@ZiZasaurus  Okay thanks, I will update to 6.4.0 and see how that goes!

**Comment by DntPullALockett** [comment]
@ZiZasaurus  I do a manual integration, the site does not have 6.4.0 as the current version, It is still set to 6.3.0. Can you look at that?

**Comment by jmkiley** [comment]
Hi @DntPullALockett - Thank you for flagging. You should see 6.4.0 [available to download](https://docs.mapbox.com/ios/maps/guides/install/#add-the-dependency).

**Comment by ZiZasaurus** [comment]
If this does not answer your question, please feel free to reopen.
