### ISSUE TITLE
Type 'HttpRequestError' does not conform to protocol 'Error'

### ISSUE THREAD

**Issue by voynovia** [mapbox/mapbox-maps-ios#729]
## Environment

- Xcode version: 13.0
- iOS version: 15.0
- Devices affected: iPad11
- Maps SDK Version: 10 rc9

## Observed behavior and steps to reproduce

custom implementations HTTP stack:

<img width="1073" alt="Снимок экрана 2021-10-01 в 19 23 50" src="https://user-images.githubusercontent.com/2351301/135654970-c828dbd0-4eea-4510-81c2-f8ec892cad21.png">

**Comment by voynovia** [comment]
rc 8 also

**Comment by macdrevx** [comment]
I'm unable to reproduce this issue. Conformance is declared here: https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Foundation/Extensions/Core/HttpResponse.swift#L4-L9

Could you share steps to reproduce starting from a new Xcode project or — attach a sample project that reproduces the issue?

**Comment by voynovia** [comment]
"Reset Package Cache" helped
