### ISSUE TITLE
Map does not respond to gestures

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#74]
## Environment

- Xcode version: 12.3
- iOS version: 14.3
- Devices affected: iPhone
- Maps SDK Version: v10 beta12

## Observed behavior and steps to reproduce

Map occasionally does not change in response to any gesture. The `cameraIsChanging` and `cameraDidChange` fire in pairs throughout the interaction.  This seems off, that `didChange` fires during the gesture.

## Expected behavior

The map correctly responds to pan, zoom, rotate and pitch gestures.

**Comment by knov** [comment]
@johnkassebaum we've made significant improvements to this area of the SDK during the beta period. Could you verify that this is resolved for you?

**Comment by knov** [comment]
Closing as stale. Please re-open or create a new ticket if you discover new areas of impact.
