### ISSUE TITLE
Can no longer get a PointAnnotation's image?

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#749]
When a point annotation is clicked, I need to get its image size in order to properly place a popup window next to it.  Previously, I did this:
```
            if let markerImage = (marker as? MapboxMarker)?.mapboxMarker.image {
                switch markerImage {
                case .custom(let uiImage, _):
                    let markerHeight = uiImage.size.height
```

where ```mapboxMarker``` is a ```PointAnnotation```.

But in the released 10.0.0, this no longer seems to work:
```
            if let markerImage = (marker as? MapboxMarker)?.mapboxMarker.image?.image {
                let markerHeight = markerImage.size.height
```

The error is: 'image' is inaccessible due to 'internal' protection level
pointing at this line:
https://github.com/mapbox/mapbox-maps-ios/blob/69e9d106028090929340b717776c3e9f4ccb1750/Sources/MapboxMaps/Annotations/PointAnnotation%2BImageHandling.swift#L6

This is the last breaking change preventing me from compiling with 10.0.0.

**Comment by macdrevx** [comment]
Thanks for reporting this @akirmse. These should have been public. Fixed in #753
