### ISSUE TITLE
LineLayer.lineGradient could not compare with the Value<StyleColor>.expression(expression)

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-maps-ios#759]
## Environment

- Xcode version: 12.5
- iOS version: 14.5
- Devices affected: all
- Maps SDK Version: 10.0.0

## Observed behavior and steps to reproduce

1.  In `Examples/LineGradientExample`, in `func setupExample()`, change the `lineGradient` as following:
```
        let expectedLineGradientExpression = Exp(.step) {
            Exp(.lineProgress)
            UIColor.blue
            [0.49999999999: UIColor.blue,
             0.5: UIColor.red
            ]
        }
        lineLayer.lineGradient = .expression(expectedLineGradientExpression)
```
and then at the end of `func setupExample()`, add the following to compare the retrieval of `LineLayer.lineGradient` with the `Value<StyleColor>.expression(expression)` as following:
```
        do {
            let layer = try mapView.mapboxMap.style.layer(withId: "line-layer") as! LineLayer
            let getLineGradientExpression = layer.lineGradient!
            let expectedValue = Value<StyleColor>.expression(expectedLineGradientExpression)
            print("expectedValue: \(expectedValue)")
            print("getLineGradientExpression: \(getLineGradientExpression)")
            print("equal: \(expectedValue == getLineGradientExpression)")
            
        } catch {
            print(error.localizedDescription)
        }
```
2. The `getLineGradientExpression` of `LineLayer.lineGradient`, is not equal to `expectedValue` as `Value<StyleColor>.expression(expression)`.
```
expectedValue: expression([step, [line-progress], rgba(0.0, 0.0, 255.0, 1.0), 0.49999999999, rgba(0.0, 0.0, 255.0, 1.0), 0.5, rgba(255.0, 0.0, 0.0, 1.0)])
getLineGradientExpression: expression([step, [line-progress], [rgba, 0.0, 0.0, 255.0, 1.0], 0.49999999999, [rgba, 0.0, 0.0, 255.0, 1.0], 0.5, [rgba, 255.0, 0.0, 0.0, 1.0]])
equal: false
```

## Expected behavior

The `expectedValue` should be equal with the `getLineGradientExpression`, `equal: true`

**Comment by pjleonard37** [comment]
Closing out as stale. Please re-open if this issue reproduces on a more recent version. The latest version is v10.10.1.
