### ISSUE TITLE
Convert iconAllowsOverlap Expression to new api

### ISSUE THREAD

**Issue by AlexaderDNT** [mapbox/mapbox-maps-ios#777]
## New Feature
![image](https://user-images.githubusercontent.com/64775721/138277269-75001c3e-9f74-42c8-bdfe-a1837233b479.png)

Can i set this settings in the new api and how?

**Comment by ZiZasaurus** [comment]
@AlexaderDNT you can use the following code to control your icon overlap in v10: 

```
Exp(.step) {
   Exp(.zoom)
      false
      0
      true
      9
      false
}
```
For more information in expressions, please take a look at our documentation [here](https://docs.mapbox.com/ios/maps/guides/styles/use-expressions/). In this particular case, a `case` expression may be simpler.

**Comment by AlexaderDNT** [comment]
And i was wondering if it is possible to set a priority number for a source when you zoom out? So let say i have multiple points on the map, and when i zoom out i wont a single point always to be visible and overlap with the other points.

**Comment by ZiZasaurus** [comment]
@AlexaderDNT, pointAnnotationManagers only take a Bool, whereas SymbolLayers allow you to use expressions for the `iconAllowsOverlap` property. 

Regarding your second question, you can use the [symbolSortKey](https://docs.mapbox.com/ios/maps/api/10.1.0/Structs/PointAnnotation.html#/s:10MapboxMaps15PointAnnotationV13symbolSortKeySdSgvp) to sort features in ascending order based on this value.

**Comment by AlexaderDNT** [comment]
Thank you @ZiZasaurus. When i zoom out and the map loads, the points dissapears and  use long time to show again. See the video

**Comment by AlexaderDNT** [comment]
https://user-images.githubusercontent.com/64775721/141483486-6b73dd9c-7e09-4661-a360-7cf043ed8d84.MOV

**Comment by ZiZasaurus** [comment]
@AlexaderDNT, I was unable to reproduce the behavior above with the points disappearing. I've attached a video below where I set `symbolSortKey` and `iconAllowsOverlap` for both point annotations and symbol layers. 

The first video is for symbolLayer (using our [DataDrivenSymbolsExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/DataDrivenSymbolsExample.swift)):
https://images.zenhubusercontent.com/330733892/88cd90b3-d71c-43a3-8b1f-04e9c86001ab/symbollayerordering.mov

The second video is for point annotation (using our [MultiplePointAnnotationsExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/MultiplePointAnnotationsExample.swift)):
 https://images.zenhubusercontent.com/330733892/7061df62-526c-4588-ac3c-9c255cf5b5b0/pointannotations.mov

**Comment by AlexaderDNT** [comment]
@ZiZasaurus  I see, you have to add 22 000 points to the map to reproduce it

**Comment by ZiZasaurus** [comment]
@AlexaderDNT are you adding these as point annotations or symbolLayers?

**Comment by AlexaderDNT** [comment]
@ZiZasaurus  poin annotations

**Comment by ZiZasaurus** [comment]
@AlexaderDNT for that many data points you would need to use symbol layers, as annotations are inefficient for adding more than 250 points to the map. 

For more information about markers and annotations, please take a look at our documentation [here](https://docs.mapbox.com/ios/maps/guides/annotations/#annotations).

**Comment by AlexaderDNT** [comment]
@ZiZasaurus  Thank you! This helped alot

**Comment by AlexaderDNT** [comment]
Manage to change it to SymbolLayer, but this happend noe when i filter out some points.

**Comment by ZiZasaurus** [comment]
@AlexaderDNT I am still unable to reproduce this behavior even with adding thousands of annotations. How/ when are these annotations being added?

**Comment by AlexaderDNT** [comment]
@ZiZasaurus  These annotations are being added on .mapLoaded and im using SymbolLayer and GeoJSONSource to add them on the map. This only happens when i add the filter, when i filter out properties["id"].

Here is my filter code
![image](https://user-images.githubusercontent.com/64775721/144191733-d68c89f8-68d1-4887-998d-81e277ce8d49.png)

**Comment by AlexaderDNT** [comment]
And if you add 10 filter in the array it´s okey, but if you add 20 000, it becomes slow. Maybe i can write the filter code differently?

**Comment by 1ec5** [comment]
If I understand correctly, your overall filter ends up looking like (id == 1 OR id == 2 OR id ==3 OR … OR id == 20000), which would be very inefficient. Consider using a `match` expression instead. If these values fall within a certain numeric range, use `<` and `>` expressions to make the filter even more efficient.

**Comment by AlexaderDNT** [comment]
@1ec5 Thanks, match worked and was faster
