### ISSUE TITLE
Unable to set image for point annotation

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/mapbox-maps-ios#79]
## Environment

- Xcode version: 12.3
- iOS version: 14.3
- Devices affected: iPhone X
- Maps SDK Version: v10 public beta

## Observed behavior and steps to reproduce
Unable to change image of a point annotation using the following code: 
```swift
            let image = UIImage(named: "star")
            annotation.image = image
            try? mapView.annotationManager.updateAnnotation(annotation)
```

![Simulator Screen Shot - iPhone 11 - 2021-02-03 at 19 43 54](https://user-images.githubusercontent.com/44972592/106828523-61dd9980-6658-11eb-8f5c-31424ac05d33.png)

## Expected behavior
Should be able to set the image for the annotation, update the annotation and have the expected image show. Am I calling something incorrectly?

**Comment by macdrevx** [comment]
It's possible that this will be fixed by the changes in https://github.com/mapbox/mapbox-maps-ios/pull/70. We'll need to test this to verify.

**Comment by johnkassebaum** [comment]
Using beta.13, `updateAnnotation(_:)` works as expected with the `PointAnnotation` to be updated was created either with or without an initial image (ie no matter whether the `image` arg in `PointAnnotation(coordinate:image:)` is `nil` or not).
Did only invoke `annotationManager.updateAnnotation(annotation)` on the `main` thread.

**Comment by macdrevx** [comment]
Thanks for verifying this @johnkassebaum. I just checked as well and can confirm your findings that this is resolved in beta 13.
