### ISSUE TITLE
Can't install via pod, direct or manager.

### ISSUE THREAD

**Issue by doriansgithub** [mapbox/mapbox-maps-ios#797]
## Environment
Mac
- Xcode version: 13.1
- iOS version: 11.4
- Devices affected: all
- Maps SDK Version: pod 'Mapbox-iOS-SDK', '~> 6.4.0'

## Observed behavior and steps to reproduce
Can't install. 

Analyzing dependencies
Downloading dependencies
Installing Mapbox-iOS-SDK (6.4.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/w5/ccr9brh11lq3vywz0w8d45t40000gq/T/d20211101-48264-1t7wzya/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.4.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized

## Expected behavior

I have configured the public token on the plist and I used to be able to install. I removed all previous version. Still can't install.

**Comment by jmkiley** [comment]
Hello @doriansgithub  -

Thank you for reaching out. I am not able to replicate this issue. Could you confirm whether your [credentials are configured](https://docs.mapbox.com/ios/maps/guides/install/) for downloading via CocoaPods? For the direct download, are you appending your access token to the download URL (i.e. https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.4.0/mapbox-ios-sdk-dynamic.zip?access_token=YOUR_ACCESS_TOKEN)?

**Comment by doriansgithub** [comment]
Thanks for getting back. I’ll check the direct link. But for the pods I have the plist configured correctly.

I’ll double check everything and let you know.

Thanks!

**Comment by doriansgithub** [comment]
Hi, what I’m I doing wrong?

Thanks.

**Comment by doriansgithub** [comment]
The package collection at https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.4.0/mapbox-ios-sdk-dynamic.zip?access_token=pk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3V0eml4eXY1dTR6MndxNjNmOHpkb28zIn0.lEGRMwrIneOSd_1x1mf4Aw is unavailable. Please make sure the URL is correct or try again later.

**Comment by doriansgithub** [comment]
The instructions for "direct download", do not mention appending the URL with the token. Also, is it the public token or the secret token?

**Comment by doriansgithub** [comment]
Same message appears with the secret token.

**Comment by doriansgithub** [comment]
Received invalid response at https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.4.0/mapbox-ios-sdk-dynamic.zip?access_token=sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA. Please make sure it is a package collection URL.


My file contains this:
machine api.mapbox.com
login doriansmapbox
password <sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA>

I’ve tried with the <> and without. I’ve tried with login Mapbox. 

My .netrix file is in my user folder. When you say “root”, what are you referring to?

Thanks,

D.

**Comment by doriansgithub** [comment]
I was able to download by searching for the package first. But now it’s giving me this message.

**Comment by doriansgithub** [comment]
It says “Bad response error code 401”.

**Comment by doriansgithub** [comment]
I’ve tried these:

machine api.mapbox.com
login doriansmapbox
password <sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA>

machine api.mapbox.com
login doriansmapbox
password sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA

machine api.mapbox.com
login mapbox
password <sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA>

machine api.mapbox.com
login mapbox
password sk.eyJ1IjoiZG9yaWFuc21hcGJveCIsImEiOiJja3ZnbmxuNG0xaDFsMnVudWZwMnJhMWNjIn0.hilGwgSdtj-PxSo1U2HaJA

**Comment by ZiZasaurus** [comment]
@doriansgithub I deleted your previous comment as it contained sensitive information. Please do not post your secret token in this repository. Yes, your netrc file should be located in your user folder on your computer and should be formatted like below, where mapbox is the name of the login and the password is your secret token without the brackets:

```
machine api.mapbox.com
login mapbox
password <INSERT SECRET API TOKEN>
```

**Comment by doriansgithub** [comment]
Well, I’ve tried that and get the same error.

**Comment by ZiZasaurus** [comment]
Can you please provide a screenshot of where your .netrc file is within your finder?

**Comment by doriansgithub** [comment]
Just noticed that it’s unable to read the Read Me.  Not sure if it’s talking about the .netrc file.

I also created a new one, pasted the info and replaced the one on the directory, but to no avail.

**Comment by doriansgithub** [comment]
I used the terminal to create a new .netrc file, and still doesn’t work.

**Comment by ZiZasaurus** [comment]
@doriansgithub can you please share a screenshot of both your .netrc file contents (please replace your full token with place holder `sk`) and the location of your .netrc file in your Finder?

**Comment by doriansgithub** [comment]
I’m in the middle of switching computers, and I am currently working from a different computer. From this desktop, I’m getting this.




Sincerely,

Dorian Mattar
Realtor
15 Years Experience
Sales, Construction & Permits







Sell or find your home here! 
Find out the value of your home here!

123 S Figueroa Street STE 108
Los Angeles CA 90012

C:	213.254.7355
D:    323.325.8076

I’m here to see you prosper!
CalBRE Lic. # 01291557

**Comment by ZiZasaurus** [comment]
@doriansgithub, I've included a screenshot below that shows my .netrc file saved in my user folder on my computer.  It must be saved as `.netrc` (with the period in front) and not `netrc`.

<img width="320" alt="Screen Shot 2021-11-16 at 11 43 40 AM" src="https://user-images.githubusercontent.com/44972592/142029625-6d853898-8e61-4c1b-b402-ad4d58e1d274.png">

Additionally, please make sure your .netrc file contains the following, where `sk...` is your secret token with the `Downloads:Read` scope and no brackets:
```
machine api.mapbox.com
login mapbox
password sk...
```

**Comment by doriansgithub** [comment]
That’s how I have it.

It’s on my root directory /Users/dorian



machine api.mapbox.com
login mapbox
password token with no quotes.

"Downloads:Read scope and no brackets:”?

What is that? How do I know the: Downloads:Read scope?



Sincerely,

Dorian Mattar
Realtor
15 Years Experience
Sales, Construction & Permits







Sell or find your home here! 
Find out the value of your home here!

123 S Figueroa Street STE 108
Los Angeles CA 90012

C:	213.254.7355
D:    323.325.8076

I’m here to see you prosper!
CalBRE Lic. # 01291557

**Comment by ZiZasaurus** [comment]
When you create your secret token [here](https://account.mapbox.com/access-tokens/create), you need to make sure that the `Downloads:Read` scope is checked like below: 

<img width="1116" alt="Screen Shot 2021-11-16 at 12 42 12 PM" src="https://user-images.githubusercontent.com/44972592/142037519-31b507ad-5de9-4b1a-b186-c63dfa45e559.png">

**Comment by doriansgithub** [comment]
I’ve done that.

All tokens, regardless of the scopes included, are able to view styles, tilesets, and geocode locations for the token's owner. Learn more. <https://docs.mapbox.com/help/how-mapbox-works/access-tokens/#access-token-scopes>
Public scopes
STYLES:TILES
Read style as png tiles and static images.
STYLES:READ
Read styles.
FONTS:READ
Read fonts.
DATASETS:READ
Read datasets.
VISION:READ
Read Vision SDK services.
Secret scopes
SCOPES:LIST
List all available scopes.
MAP:READ
Read tilesets, tilestats, legacy Mapbox Studio Classic styles, and legacy projects.
MAP:WRITE
Create and update Mapbox Studio Classic styles, tilesets, and tilestats.
USER:READ
Read user profile information.
USER:WRITE
Write user profile information.
UPLOADS:READ
READ DATA UPLOADS.
UPLOADS:LIST
List tileset uploads.
UPLOADS:WRITE
CREATE TILESET UPLOADS.
FONTS:LIST
List fonts.
FONTS:WRITE
UPLOAD FONTS.
STYLES:WRITE
CREATE AND UPDATE STYLES.
STYLES:LIST
LIST STYLES.
STYLES:DOWNLOAD
Download bundle of style assets
STYLES:PROTECT
PROTECT WRITE ACCESS TO STYLES AND THEIR ASSETS.
TOKENS:READ
Read tokens.
TOKENS:WRITE
CREATE, UPDATE AND DELETE TOKENS.
DATASETS:LIST
List datasets.
DATASETS:WRITE
CREATE AND UPDATE DATASETS.
TILESETS:LIST
List raster and vector tilesets.
TILESETS:READ
Read raster and vector tilesets.
TILESETS:WRITE
CREATE, UPDATE, AND DELETE TILESETS.
DOWNLOADS:READ
Read and download downloads via the Downloads API
VISION:DOWNLOAD
Download Vision SDK.
NAVIGATION:DOWNLOAD
Download Navigation SDK.
OFFLINE:READ
List and get regions, get status, and download offline packs using the Offline Data API.
OFFLINE:WRITE
CREATE AND EDIT REGION DEFINITIONS USING THE OFFLINE DATA API.


Sincerely,

Dorian Mattar
Realtor
15 Years Experience
Sales, Construction & Permits







Sell or find your home here! 
Find out the value of your home here!

123 S Figueroa Street STE 108
Los Angeles CA 90012

C:	213.254.7355
D:    323.325.8076

I’m here to see you prosper!
CalBRE Lic. # 01291557

**Comment by ZiZasaurus** [comment]
The downloads scope is for your .netrc file, which allows you to download the SDK. 

For more in-depth assistance with your .netrc configuration, please reach out to our support team at help@mapbox.com and they'll be able to get you up and running.

**Comment by doriansgithub** [comment]
Doesn’t the token have all that?

This is so confusing!


Sincerely,

Dorian Mattar
Realtor
15 Years Experience
Sales, Construction & Permits







Sell or find your home here! 
Find out the value of your home here!

123 S Figueroa Street STE 108
Los Angeles CA 90012

C:	213.254.7355
D:    323.325.8076

I’m here to see you prosper!
CalBRE Lic. # 01291557
