### ISSUE TITLE
View-based Annotations

### ISSUE THREAD

**Issue by viyer28** [mapbox/mapbox-maps-ios#80]
## New Feature

Is there a plan to support view-based annotations in v10, as you have for the previous Mapbox versions? If so, when do you plan on releasing it?

## Why

I understand the annotations are now based on style layers, but image-based annotations are very limiting. Our previous code rely on view-based annotations for custom shapes and animations within the annotation. Specifically, our application has video previews on the map, marquee-label animations for showing text at a specific location, and custom text bubble bezier paths for annotations.

**Comment by macdrevx** [comment]
Closing as a duplicate of #63
