### ISSUE TITLE
[MGL_MMEEventsManager isEnabled] Crash on iOS 15

### ISSUE THREAD

**Issue by DntPullALockett** [mapbox/mapbox-maps-ios#804]
## Environment

- Xcode version: 13.0
- iOS version: 15.0 +
- Devices affected: All
- Maps SDK Version: 6.4.0

## Observed behavior and steps to reproduce
Found a crash on my Crashlytics dashboard,

## Notes / preliminary analysis
No additional logs showing

## Additional links and references
<img width="1282" alt="Screen Shot 2021-11-02 at 4 00 05 PM" src="https://user-images.githubusercontent.com/51751780/139943654-90263c13-dabd-4a9a-a9cc-3ad0899787e0.png">
<img width="1245" alt="Screen Shot 2021-10-27 at 10 40 51 AM" src="https://user-images.githubusercontent.com/51751780/139943638-d12ebaf7-bc9e-45f0-9740-9c78e55ccf46.png">

**Comment by DntPullALockett** [comment]
@ZiZasaurus  

This is still happening with 6.4.0

**Comment by DntPullALockett** [comment]
@carlbales-rccl

**Comment by vesh93** [comment]
There is an issue in iOS 15.0, but I'll look into ways to mitigate it in [MME iOS](https://github.com/mapbox/mapbox-events-ios).

**Comment by ZiZasaurus** [comment]
@DntPullALockett the attached call stack is not possible after v0.10.0-alpha, because the `isEnabled` method was removed in v0.10.1. Could it be that crashlogs are coming from some old version of your app?

**Comment by DntPullALockett** [comment]
@ZiZasaurus  No this isn't possible. We released 1.30.0 with the 6.4.0 version and that is the version that is throwing these. Whatever version of MMEE that came with 6.4.0 is the version that we bundled with it.

**Comment by DntPullALockett** [comment]
@vesh93  We do a manual integration, but we do use Mapwize, and I do not think they have an embedded version. I will double check this.

**Comment by ZiZasaurus** [comment]
@DntPullALockett just wanted to follow up, are you still experiencing this crash?

**Comment by DntPullALockett** [comment]
@ZiZasaurus  Yes we are, invert high numbers. But we are still unsure of the origins. We know that you have stated that this function doesn't exist. Also our other Map integrations Mapwize said their product isn't iOS 15 ready. We believe the issue to lay within their framework somewhere. I can close this as I am going to remove Mapwize/Mapwize and do an Apple Maps solution.
