### ISSUE TITLE
Snapshotter should hide invisible features when feature state is used to hide it

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-maps-ios#811]
## Environment

- Xcode version: 12.4
- iOS version: 14
- Devices affected: All devices that use snapshotter + feature state (not known)
- Maps SDK Version: 10.0.1

## Observed behavior and steps to reproduce

**Observed Behavior**

The POI image of "Gnarly Burger" is shown in the bottom section

**Steps to reproduce**

1. Pull down the branch `taku/snapshot-feature-state`
2. Run the example app ([SnapshotterExample.swift][1]) and tap "Create a static map snapshot" button
3. Zoom out slightly (force a re-render)
4. Notice the POI image of "Gnarly Burger" is hidden in the top section
5. The POI image of "Gnarly Burger" is shown in the bottom section

https://user-images.githubusercontent.com/6927131/140330752-c06d3460-b6b7-434c-ad32-e981e44973c4.MP4

<img src="https://user-images.githubusercontent.com/6927131/140330934-8d7a2ff9-84c0-4dd4-b9ab-184c71519d36.png" width="300" />

## Expected behavior

The POI image of "Gnarly Burger" should be invisible in the bottom section (in the snapshot)

## Notes / preliminary analysis

When a feature state is used to hide the Point, specifically 

https://github.com/mapbox/mapbox-maps-ios/blob/ff6b95623b47d2b188a3cdb7d8a26e8d7010df69/Apps/Examples/Examples/All%20Examples/SnapshotterExample.swift#L110-L115

and

https://github.com/mapbox/mapbox-maps-ios/blob/ff6b95623b47d2b188a3cdb7d8a26e8d7010df69/Apps/Examples/Examples/All%20Examples/SnapshotterExample.swift#L73-L96

then `Snapshot` does not take into account the visibility. The diff is [here][2].

[1]: https://github.com/mapbox/mapbox-maps-ios/blob/taku/snapshot-feature-state/Apps/Examples/Examples/All%20Examples/SnapshotterExample.swift
[2]: https://github.com/mapbox/mapbox-maps-ios/compare/v10.0.1...taku/snapshot-feature-state

**Comment by ZiZasaurus** [comment]
@tsuz thank you for bringing this to our attention. I'm able to reproduce this and am investigating.

**Comment by ZiZasaurus** [comment]
@tsuz, it looks as though featureState isn't supported by the snapshotter. Instead, they can use the experimental Snapshot API, which will create a UIImage of the current mapview. To do so, they would need to 

You can test this out by replacing the MapboxMaps import with `@_spi(Experimental) import MapboxMaps` and lines 119-144 with the following: 
```
        mapView.mapboxMap.onEvery(.mapIdle) { [weak self] _ in
            self!.snapshotView.image = try! self?.mapView.snapshot()
        }
```

**Comment by tsuz** [comment]
@ZiZasaurus 

Thanks for the tip!

Initially, it didn't work on my iPhone X, and I kept getting "Metal API Enabled" warning. After disabling this validation in the Scheme (image below), I got this to work! [original SO answer][1].

![Screen Shot 2021-11-08 at 16 17 06](https://user-images.githubusercontent.com/6927131/140699533-5564a436-5431-42f8-b1be-3828b969ad10.png)

I would like to keep this open since the API is experimental and is probably not recommended for production.


[1]: https://stackoverflow.com/a/60645489/1615594

**Comment by ZiZasaurus** [comment]
@tsuz if this works for them, they can use it in production. There's just the possibility that they'll have to update their code when we update the SDK.

**Comment by tsuz** [comment]
@ZiZasaurus 

> if this works for them, they can use it in production. There's just the possibility that they'll have to update their code when we update the SDK.

makes sense - [this function][1] is still within a GA release but it's subjective to change.

Thanks for confirming!

[1]: https://github.com/mapbox/mapbox-maps-ios/blob/v10.1.0/Sources/MapboxMaps/Foundation/MapView+Snapshot.swift#L20
