### ISSUE TITLE
Obtain current camera bounds

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#820]
@MaciejPachciarekSMT I was able to restrict the bounds to the two coordinates (including bounds) using the method below. Can you test this code out and let me know if it works for your use case?     

``` swift

 let padding = UIEdgeInsets(top: 100, left: 100, bottom: 100, right: 100)

 func addCoordinateBounds() {

   let restrictedCamera = mapView.mapboxMap.camera(for: coordinates, padding: padding, bearing: 0, pitch: 0)
   mapView.mapboxMap.setCamera(to: restrictedCamera)
   let newBounds = CoordinateBounds(southwest: mapView.camera.options.bounds!.southwest, northeast: mapView.camera.options.bounds!.northeast)
   let cameraBoundsOptions = CameraBoundsOptions(bounds: newBounds, maxZoom: 18, minZoom: 14, maxPitch: 0, minPitch: 0)
  
   try! mapView.mapboxMap.setCameraBounds(for: cameraBoundsOptions)
 }
```

_Originally posted by @ZiZasaurus in https://github.com/mapbox/mapbox-maps-ios/issues/610#issuecomment-925253251_

Regarding this answer, I would like to what is the equivalent of `mapView.camera.options.bounds!.southwest` in mapBox v 10.0.1. As I see there is no `option` property in camera object. I see there is a method `mapView.mapboxMap.cameraBounds.boudns.southwest` however it always return wrong value (latitude -90, longitude -180)

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT you can use `mapView.mapboxMap.coordinate(for point:)` to get the coordinate for each corner of the mapview, then create a Turf.BoundingBox from those coordinates and use the southwest and northeast coordinates of the bounding box to create a CoordinateBounds. Everything else from the code snippet above should be the same.

**Comment by MaciejPachciarekSMT** [comment]
Hi @ZiZasaurus 

Thanks for the answer. It works, but honestly, it looks like a little workaround.
