### ISSUE TITLE
Globe Map Projection 

### ISSUE THREAD

**Issue by fatih18** [mapbox/mapbox-maps-ios#824]
## Environment

- Xcode version: 12.5
- iOS version: 12
- Devices affected: iphone 12
- Maps SDK Version: v10.1.0

## Observed behavior and steps to reproduce

How to initialize globe view projection on ios? are there any working examples ? or globe view is just an experimental feature ?

**Comment by endanke** [comment]
@fatih18 You can find an usage example here: https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/GlobeViewExample.swift

When you run the Examples app, you can find it at the bottom of the list in the Experimental section.

**Comment by fatih18** [comment]
Thank you for your answer, link in the official docs is broken btw. ( examples section)

**Comment by endanke** [comment]
@fatih18 thanks for reporting it! Could you please share the site where you've seen the broken link?

**Comment by ZiZasaurus** [comment]
Closing this ticket for now, however, if this does not answer your question please feel free to reopen.
