### ISSUE TITLE
Get center of geometry

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#825]
## New Feature

Hi, I can't find the solution to get the center of geometry. I know in Android's old Mapbox there was a solution where we can init TurfMeasurement by Geometry and then easily get center, bbox, etc. 

## Why
Calculating center by own depends on the type.

**Comment by samcrawford** [comment]
MapboxMap has a camera(for geometry) method, and the resulting CameraOptions object has the center populated. Hope this helps!

https://docs.mapbox.com/ios/maps/api/10.1.0/Classes/MapboxMap.html#/s:10MapboxMaps0A3MapC6camera3for7padding7bearing5pitchAA13CameraOptionsV4Turf8GeometryO_So12UIEdgeInsetsV12CoreGraphics7CGFloatVSgAStF

**Comment by MaciejPachciarekSMT** [comment]
Thanks a lot!
