### ISSUE TITLE
Offline maps from existent .sqlite tiles database

### ISSUE THREAD

**Issue by Gelembjuk** [mapbox/mapbox-maps-ios#827]
I have the Android app, it uses osmdroid library for maps. There is offline maps support and maps are stored in .sqlite files.
That are sqlite databases with OSM tiles stored.
Now i want to make my app for iOS too. 
But i think about to reuse my current offline maps sources.
Is it possible to adopt somehow that source to use with mapbox on iOS (and in future maybe on android).
If no direct support of sqlite , maybe there is some option to make a custom plugin for mapbox to read tiles? Like an object for tiles reading?

**Comment by ZiZasaurus** [comment]
@gelembjuk what file format is OSMdroid using? Please note that reusing your current offline map sources (or sideloading databases) is not supported in v10. The only way to get offline regions would be via the OfflineManager API, which downloads them from our server.

**Comment by Gelembjuk** [comment]
OSMdroid uses  sqlite databases as a sources. In settings of OSMdroid library it is needed to set a path to a folder where sqlite files are and it will pick all files from there to look for tiles.
Format of a DB is on the picture
<img width="669" alt="Screenshot 2021-11-17 at 09 16 37" src="https://user-images.githubusercontent.com/1552191/142153491-fd04c24f-61dc-4fee-a9cd-df4a7fc465d7.png">

If Mapbox doesn't support sqlite, it is possible to use custom tile source url with mapdox? i consider the option to run local http server and point  tiles source url to it and that tiny http server would extract tiles from sqlite db. (it is just an idea for now)

**Comment by ZiZasaurus** [comment]
@Gelembjuk, while Mapbox does support the use of sqlite, we do not support the use of non-Mapbox offline regions. The only way to get offline regions would be via the OfflineManager API, which downloads them from our server.
