### ISSUE TITLE
Getting 2 error when trying to run the Examples app

### ISSUE THREAD

**Issue by MarkMolina** [mapbox/mapbox-maps-ios#828]
## Environment

- Xcode version: 13.0
- iOS version: 
- Devices affected:
- Maps SDK Version:

## Observed behavior and steps to reproduce

failed extracting 'https://api.mapbox.com/downloads/v2/mapbox-events-ios/releases/ios/packages/1.0.6/MapboxMobileEvents.zip?access_token=sk.XXXXX' which is required by binary target 'MapboxMobileEvents': /Users/XXXXX/Library/Developer/Xcode/DerivedData/Apps-cmbivftbrvqzxndpfrsfyzhqdjck/SourcePackages/artifacts/extract/MapboxMobileEvents is not a directory

And error

failed extracting 'https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/10.1.0/MapboxCoreMaps.xcframework-dynamic.zip?access_token=sk.XXXXX which is required by binary target 'MapboxCoreMaps': /Users/XXXXX/Library/Developer/Xcode/DerivedData/Apps-cmbivftbrvqzxndpfrsfyzhqdjck/SourcePackages/artifacts/extract/MapboxCoreMaps is not a directory

when trying to run the MapBox Examples for iOS.

## Expected behavior

Run the Examples app in Xcode Simulator

## Notes / preliminary analysis

Added secret and public key (also in ~/.mapbox). Pod install seems to work on other Mapbox projects.

## Additional links and references

<img width="276" alt="Screenshot 2021-11-08 at 23 37 25" src="https://user-images.githubusercontent.com/3329668/140835257-8eddf5eb-a077-4c21-9f3d-5fd1f562c346.png">

**Comment by MarkMolina** [comment]
My slow internet must have caused a network error. After multiple restarts of Xcode (and rebuilding) it suddenly worked.

**Comment by evil159** [comment]
I just had the same error, which I suspect was caused by me trying to build the example project without adding public and secret keys. 


What helped me was to perform in Xcode:
* Reset package cache(`File->Packages->Reset Package Caches`)
* Resolve packages(`File->Packages->Resolve Package Versions`)
