### ISSUE TITLE
MGLOfflinePack has no member 'setContext'

### ISSUE THREAD

**Issue by Amir-OffsureIt** [mapbox/mapbox-maps-ios#835]
## Environment

- Xcode version: 13.0
- iOS version: iOS 15.0
- Devices affected: All iOS devices
- Maps SDK Version: 
- Mapbox-iOS-SDK (5.5.1)
  - MapboxCommon (20.1.0)
  - MapboxCoreMaps (10.1.0):
    - MapboxCommon (~> 20.1)
  - MapboxGeocoder.swift (0.14.0)
  - MapboxMaps (10.1.0):
    - MapboxCommon (= 20.1.0)
    - MapboxCoreMaps (= 10.1.0)
    - MapboxMobileEvents (= 1.0.6)
    - Turf (~> 2.1.0)

I had "Mapbox-iOS-SDK" version 6.4.1 and wanted to update it to 10.1.0. "Mapbox-iOS-SDK" is not updating to the latest version 10.1.0 (https://docs.mapbox.com/ios/maps/guides/), so I removed the "Mapbox-iOS-SDK" pod and installed "MapboxMaps" instead of "Mapbox-iOS-SDK". It downloaded the latest version but I noticed it downgraded the "Mapbox-iOS-SDK"(5.5.1) (previously it was 6.4.1). In that context, I'm getting the following issue -

`Value of type 'MGLOfflinePack' has no member 'setContext'`

Code snippet -

`private func updatePackContext(pack: MGLOfflinePack, userInfo: [String: String], completion: @escaping(_ error: Error?)-> ()) {
        do {
            let context = try NSKeyedArchi
![Screenshot 2021-11-15 at 4 52 19 PM](https://user-images.githubusercontent.com/39256342/141776393-89163ed8-bcb9-41a4-a0e7-ea218b3a57ad.png)
ver.archivedData(withRootObject: userInfo, requiringSecureCoding: false)
            pack.setContext(context) { (error) in
                completion(error)
            }
        } catch {
            completion(nil)
        }
    }`
![Screenshot 2021-11-15 at 4 52 19 PM](https://user-images.githubusercontent.com/39256342/141776545-e2f75a19-d33f-4bb3-9de0-184f894976ee.png)

**Comment by ZiZasaurus** [comment]
@Amir-OffsureIt, thanks for reaching out. Can you share a screenshot of your podfile? Additionally, please note that since the two versions have different codebases, there will be code errors if you use v10 in a project that previously used a version prior to v10.

**Comment by Amir-OffsureIt** [comment]
![Screenshot 2021-11-17 at 9 36 09 AM](https://user-images.githubusercontent.com/39256342/142133102-20038559-c275-4c79-9e41-e5535fc510f0.png
![Screenshot 2021-11-17 at 9 37 07 AM](https://user-images.githubusercontent.com/39256342/142133140-6497f3eb-8e79-4b36-b0b0-a12ad1bb8ba8.png)
)
@ZiZasaurus here are the screenshots of podfile and podlock file

**Comment by ZiZasaurus** [comment]
@Amir-OffsureIt, thank you for your podfile screenshots. Mapbox-iOS-SDK is a different framework from MapboxMaps, therefore it cannot be updated. `setContext` was not made available until v6.0.0 (see https://docs.mapbox.com/archive/ios/maps/api/6.0.0/Classes/MGLOfflinePack.html#/c:objc(cs)MGLOfflinePack(im)setContext:completionHandler:) so your current version of 5.5.1 will not support it.

**Comment by Amir-OffsureIt** [comment]
@ZiZasaurus thank you so much for the clarification. As per my requirement, I need both - offline maps and vector sources for tilesets. So what will be the best approach to keep both in the App?
Should I wait for the next update of MapboxMaps to get `v6.0.0` or is there any other SDK for vector tileset only?

**Comment by ZiZasaurus** [comment]
@Amir-OffsureIt   Vector sources and offline maps are included in both versions of the Mapbox Maps SDK. For more information, please take a look at our API reference here for v10 [offline](https://docs.mapbox.com/ios/maps/api/10.1.0/Extensions/OfflineRegionManager.html) and [vector sources](https://docs.mapbox.com/ios/maps/api/10.1.0/Structs/VectorSource.html).

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you have additional questions.
