### ISSUE TITLE
Add UIView as Layer

### ISSUE THREAD

**Issue by MaxAdamyan** [mapbox/mapbox-maps-ios#842]
## New Feature

I would like to use `UIView` as `Layer` in my MapView. For example in GoogleMaps SDK I can use `iconView` property of `GMSMarker` and get what I want.

## Why

It provides great flexibility and you can achieve beautiful UI with very little overhead. You can have annotations or layers with custom UIView animation. For example we have an App running on Google Maps SDK which renders UIView as annotation with `GMSMarker` and we have nice animations for text changes inside that annotation.

**Comment by endanke** [comment]
@MaxAdamyan great news: we're soon adding support to allow the usage of UIView classes as annotations on the map! You can follow the PR below: https://github.com/mapbox/mapbox-maps-ios/pull/776
If everything goes well it will be merged in the upcoming days.
Also feel free to review it in the meantime! ;)

**Comment by MaxAdamyan** [comment]
@endanke thanks for the response. Nice to hear that. Looking forward to building great stuff with MapBox
