### ISSUE TITLE
Slow incremental builds for MapboxMaps test target

### ISSUE THREAD

**Issue by endanke** [mapbox/mapbox-maps-ios#858]
## Environment

- Xcode version: 13.0
- iOS version: 15.0
- Devices affected: Simulator, iPhone 11 Pro
- Maps SDK Version: v10.2.0-beta.1
- Computer: MacBook Pro (13-inch, M1, 2020)

## Observed behavior and steps to reproduce

Incremental builds of the MapboxMaps test target now takes around 80 seconds.
Previously this felt quicker, but I haven't verified yet, so assigning myself for further investigation.

**Comment by endanke** [comment]
It appears with Xcode 12.5 the test builds are significantly faster.
- On Xcode 12.5: ~3 seconds
- On Xcode 13.0: +80 seconds

|cc: @macdrevx

**Comment by macdrevx** [comment]
Closing since this doesn't seem actionable. If we learn about a way to fix this, we can reopen.
