### ISSUE TITLE
Puck not showing during initial launch with 10.2.0-beta.1

### ISSUE THREAD

**Issue by sosthoff** [mapbox/mapbox-maps-ios#860]
## Environment

- Xcode version: 13.1
- iOS version: 15.0.2
- Devices affected: tested iPad & Simulator
- Maps SDK Version: 10.2.0-beta.1

## Observed behavior and steps to reproduce

When running the sample application https://docs.mapbox.com/ios/maps/examples/tracking-mode/ for the first time, the puck is not displayed.
Steps: 
1. Run application for the first time on a device
2. Grant Location permission while in use
3. Observe camera move to location & puck missing

Future launches of the application display the puck

This issue does not exist in 10.1.0

## Expected behavior

Steps: 
1. Run application for the first time on a device
2. Grant Location permission while in use
3. Observe camera move to location & puck

## Notes / preliminary analysis

It seems to be a regression as I cannot reproduce in 10.1.0 and probably related to the fact that `mapView.location.options.puckType = .puck2D()`is called before the location access permission is granted during the first launch.

**Comment by macdrevx** [comment]
This is happening because the style images are getting cleared in this particular situation.
