### ISSUE TITLE
Panning while zooming still feels a bit strange

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#864]
## Environment

- Xcode version: 13.1
- iOS version: 15.1
- Devices affected: All my devices
- Maps SDK Version: 10.1 but also 10.2-beta

## Observed behavior and steps to reproduce

When you zoom in to your map using a two finger pinch gesture and also while doing so move your two fingers up and down (i do that very often when zooming in on a specific part of the map) the horizontal-movement of the map is off. It seems as if the lat/lng translation of the map (the one from the panning) still has the original-zoom level as a translation-factor. I hope you understand what I mean.
So... when you first zoom IN using two finger pinch... keep your fingers on the display... now pan -> the map will move much faster than your fingers.
On the other hand -> if you first zoom OUT and then pan -> the map will move much slower than your fingers.

I guess (didn't look at code as I don't know if that's even for me to see?!?) it's because the factor for the panning is zoom-releated, right? And maybe that does not update while the zooming is in progress?!? Just a thought...

Hope you understand what I mean... I could try to make a video somehow if not :)

## Expected behavior

The map should feel sticky under the fingers. Like Apple or Google Maps does.

**Comment by macdrevx** [comment]
Verified. Thanks for reporting this.

**Comment by macdrevx** [comment]
This was introduced in 7c2c073838a338504af81246c31e107a95c4e7ba which was first included in 10.2.0-beta.1.

I'm actually not able to repro in 10.1.x unless I zoom out so far that the map isn't allowed to pan north-south enough to follow the touch locations, but that's expected behavior.

**Comment by macdrevx** [comment]
In https://github.com/mapbox/mapbox-maps-ios/pull/890, we're restoring the default behavior to match 10.1. This should resolve this issue. Please reopen if you find that is not the case.
