### ISSUE TITLE
Maps SDK for iOS v10 which CacheManager?

### ISSUE THREAD

**Issue by kostiag** [mapbox/mapbox-maps-ios#869]
[Documentation](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/ ) refers to Cache manager as a replacement to MGLOfflineStorage?
However, I can't find any other reference of what is needed? Building fails with "Cannot find 'CacheManager' in scope" any help would be appreciated. The only thing I found was [https://github.com/boostcode/CacheManager](https://github.com/boostcode/CacheManager) which does not build.

**Comment by kostiag** [comment]
Any update on this?

**Comment by ZiZasaurus** [comment]
@kostiag CacheManager no longer exists. Can you tell me a little more about your use case?

**Comment by kostiag** [comment]
Wouldn't be prudent to update [documentation](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/)? 
we are storing tiles offline using MGLOfflineStorage currently. Our applications need to work offline and pre-downloading of maps is a requirement.

**Comment by ZiZasaurus** [comment]
@kostiag, the [documentation](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/) has been updated. Closing this ticket out, but please feel free to reach back out if you have any additional questions.
