### ISSUE TITLE
Need `verticalAccuracy` and `altitude` attribute

### ISSUE THREAD

**Issue by Args** [mapbox/mapbox-maps-ios#870]
Why does class `Location` only have `horizontalAccuracy` attribute, and there is no `verticalAccuracy` attribute, I need `verticalAccuracy`, `altitude` ,`speed` and many other `CLLocation`'s attributes.

**Comment by macdrevx** [comment]
v10.2.0-beta.1 exposes the underlying `CLLocation` to allow access to all of these fields.

**Comment by Args** [comment]
Thank you. That's what I need.
