### ISSUE TITLE
Style.addCustomGeometrySource - Issue

### ISSUE THREAD

**Issue by Adraesh** [mapbox/mapbox-maps-ios#871]
## Environment

- Xcode version: 13.1
- iOS version: 15.0.2
- Maps SDK Version: 10.1

Hello, It seems there is an issue with the with the addCustomGeometrySource() method.

This simple snippet crashed:

```
let sourceOptions = CustomGeometrySourceOptions.init(fetchTileFunction: { tileId in
    var features: [Feature] = []
    do {
        // do something
        // build features array

        
        try style.setCustomGeometrySourceTileData(forSourceId: MY_SOURCE_ID, tileId: tileId, features: features)
    } catch {
        debugPrint(error)
    }
}, cancelTileFunction: { tileId in
    // silent
}, minZoom: 4, maxZoom: 20, tileOptions: TileOptions.init())

try style.addCustomGeometrySource(withId: MY_SOURCE_ID, options: sourceOptions)
```

The log:
```
MapboxMaps/Style.swift:570: Fatal error: Failed to create SourceType from customvector
```

When I check the Style.swift file and the provided line where it failed we can see:

```
guard let sourceType = SourceType(rawValue: info.type) else {
                  assertionFailure("Failed to create SourceType from \(info.type)")
                  return nil
              }
```

My guess is that the addCustomGeometrySource() method is trying to create a Source with a SourceType = "customvector". The issue is when we check the SourceType.swift file we can see that "customvector" is not something handled and therefore no Source can be created using this string.

Thank you.

**Comment by Adraesh** [comment]
Hello,

Any feedback on this? Is it confirmed to be a bug?

**Comment by Adraesh** [comment]
Hello,

Any sign of life?

**Comment by ZiZasaurus** [comment]
Hi @adradesh, I am unable to reproduce this crash/error when running this snippet on either the simulator or a physical device. If you could please provide a sample project that reproduces this behavior this would assist us in our investigation.

**Comment by Adraesh** [comment]
Hello @ZiZasaurus could you provide me your test sample please?

Thanks.

**Comment by Adraesh** [comment]
Hello @ZiZasaurus

I finally found the issue, it's not directly related to the addCustomGeometrySource method itself but after having using this specific method if somehow you try use another method that calls the Style.allSourceIdentifiers(), basically any method that add/update another Source to the map (iex: updateGeoJSONSource()), it will crash with the same error.

Take the initial provided sample (that I add again bellow), and simply trigger a call to the allSourceIdentifiers() method after:

```
let sourceOptions = CustomGeometrySourceOptions.init(fetchTileFunction: { tileId in
    var features: [Feature] = []
    do {
        // do something
        // build features array

        
        try style.setCustomGeometrySourceTileData(forSourceId: MY_SOURCE_ID, tileId: tileId, features: features)
    } catch {
        debugPrint(error)
    }
}, cancelTileFunction: { tileId in
    // silent
}, minZoom: 4, maxZoom: 20, tileOptions: TileOptions.init())

try style.addCustomGeometrySource(withId: MY_SOURCE_ID, options: sourceOptions)

debugPrint(self.mapView.mapboxMap.style.allSourceIdentifiers)
```

**Comment by ZiZasaurus** [comment]
@adraesh, thank you for following up. I was able to reproduce the error you reported with the code from your latest comment.

**Comment by Adraesh** [comment]
Hi @ZiZasaurus great!

So bottom line when we use `addCustomGeometrySource()` it creates a source with the type "customvector" but then when `allSourceIdentifiers()` is called it's trying to create a `SourceType("customvector")` which is not working because the  enum SourceType does not have the case customvector:

```
public enum SourceType: String, Codable {
    /// A vector tile source.
    case vector = "vector"

    /// A raster tile source.
    case raster = "raster"

    /// A raster DEM source.
    case rasterDem = "raster-dem"

    /// A GeoJSON source.
    case geoJson = "geojson"

    /// An image source.
    case image = "image"

    /// A model source
    case model = "model"
   
    // ....
}
```

It would be most probably either to add this customvector case either to use the "vector" type when creating a new source with `addCustomGeometrySource`

**Comment by Adraesh** [comment]
Hi @ZiZasaurus 

First of all happy new year!

Is there any news regarding this topic? Thank you!

**Comment by Adraesh** [comment]
Hello @ZiZasaurus 

Can we have some update regarding this issue? When a fix will be released?

Thank you.

**Comment by ZiZasaurus** [comment]
@Adradesh, thank you for reporting this. I was able to reproduce and will be looking into it.
