### ISSUE TITLE
Add the ability to highlight group of clusters in which the annotation is highlighted.

### ISSUE THREAD

**Issue by alexeysatsunkevich** [mapbox/mapbox-maps-ios#877]
## New Feature

I know you have an example of highlighting a pin when a user clicks on it. 
But I would like to be able to highlight a group of clusters for all zoom levels in which pin is highlighted.

Below is an example with a light blue highlighting a cluster that has a highlighted pin.
![clustering_hightlighting](https://user-images.githubusercontent.com/89253689/143959704-8b30f4b8-f8b5-4e3f-aea8-70e9b176b235.jpg)

**Comment by alexeysatsunkevich** [comment]
@ZiZasaurus 
Do you have any ideas about this ?

**Comment by ZiZasaurus** [comment]
@alexeysatsunkevich you can use a `distance` expression to change the color of the selected cluster like in the code snippet below: 

```swift
let colorExpression = Exp(.interpolate) {
  Exp(.linear)
  Exp(.distance) {
      GeoJSONObject.feature(convertedPoint)
  }
  1000
  UIColor.systemPink
  2000
  UIColor.black
}

layer.circleStrokeColor = .expression(colorExpression)
```

https://images.zenhubusercontent.com/330733892/7f7f96cc-0968-424e-b938-009192398c13/simulator_screen_recording___iphone_11___2022_01_13_at_18_16_57.mp4
