### ISSUE TITLE
Ability to specify anchor for Zoom gestures

### ISSUE THREAD

**Issue by MaxAdamyan** [mapbox/mapbox-maps-ios#879]
## New Feature

We need to be able to specify anchor, from where the map will Zoom In or Out when using gestures. 
E.g.  Specify map center as the Zoom Gestures anchor, to always keep the center on the same location.

## Why

We are developing a Ride Booking application (read Uber). So we need to keep the location the user specified in center when he/she zooms In or Out.

P.S. The same request applies to the Android SDK, should I open a feature request there as well?

Thanks. 🙏

**Comment by knov** [comment]
Thanks for this request. We will incorporate this request with [this](https://github.com/mapbox/mapbox-maps-android/issues/771) Android request so no need for a second ticket.

**Comment by MaxAdamyan** [comment]
@knov 
Thanks for the reply. As I can see the issue you referenced for Android got closed, as they already have the feature implemented (`FocalPoint` in Gesture's Options). But I cannot find anything like that in iOS SDK. 
Will it be possible to add the feature to iOS SDK as well??

**Comment by MaxAdamyan** [comment]
Hello @knov 
Is there any updates on this Feature Request? 
Thanks.

**Comment by Sonosar** [comment]
We are moving from google maps to mapbox, and this is the only feature that is holding us back, focalPoint is essential for our app
