### ISSUE TITLE
Location indicator is not visible after allowing location usage.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-maps-ios#886]
## Environment

- Xcode version: Xcode `13.1`
- iOS version: iOS `14.1`
- Devices affected: All
- Maps SDK Version: `10.2.0-beta.1`

## Observed behavior and steps to reproduce

Location indicator is not visible after allowing location usage during initial application launch. After all other subsequent application launches location indicator is shown correctly. For example:

https://user-images.githubusercontent.com/1496498/144308992-2f653b97-795d-4e73-b0dc-adb00d3f65e3.mov

## Expected behavior

Location indicator should be visible right after allowing location usage permissions.

## Notes / preliminary analysis

Issue can be reproduced by running such example:
```swift
class ViewController: UIViewController {
    
    var mapView: MapView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let mapInitOptions = MapInitOptions(resourceOptions: ResourceOptions(accessToken: ""))
        mapView = MapView(frame: UIScreen.main.bounds, mapInitOptions: mapInitOptions)
        mapView.autoresizingMask = [.flexibleHeight, .flexibleHeight]
        mapView.location.options.puckType = .puck2D()
        
        view.addSubview(mapView)
    }
}
```

## Additional links and references

Issue is not reproducible when using newly released Mapbox Maps `v10.0.2`.

**Comment by macdrevx** [comment]
Sounds like a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/860 which was fixed by https://github.com/mapbox/mapbox-maps-ios/pull/862

**Comment by MaximAlien** [comment]
Yes, works well in `v10.2.0-rc.1`, thanks. Closing this ticket.
