### ISSUE TITLE
cannot find MapProjection & GlobeMapProjection

### ISSUE THREAD

**Issue by lishuo0710** [mapbox/mapbox-maps-ios#889]
## Environment

- Xcode version:12
- iOS version: 14.5
- Devices affected:
- Maps SDK Version: 10.2.0-beta.1

install SDK by direct download (download url: https://api.mapbox.com/downloads/v2/mobile-maps-ios/releases/ios/10.2.0-beta.1/MapboxMaps.zip?access_token=<access-token>) , the Globe View Example cannot find MapProjection & GlobeMapProjection and etc.

**Comment by macdrevx** [comment]
This is a known issue. It has been fixed on the main branch, and will be shipped in the v10.2.0-rc.1 release.

**Comment by macdrevx** [comment]
Fix is here: https://github.com/mapbox/mapbox-maps-ios/pull/854

**Comment by macdrevx** [comment]
Closing this issue, but feel free to reopen if you find that the issue persists in v10.2.0-rc.1.
