### ISSUE TITLE
Keep content scale of MTKView in sync with pixelRatio

### ISSUE THREAD

**Issue by endanke** [mapbox/mapbox-maps-ios#907]
Related to: https://github.com/mapbox/mapbox-maps-ios/issues/895
The MTKView we use as a surface for rendering currently always uses the native scale of the device, regardless of our configuration:
https://github.com/mapbox/mapbox-maps-ios/blob/cf8d26314ed0f7df7842a80c88fb8579a0cdaeae/Sources/MapboxMaps/Foundation/MapView.swift#L524
We should investigate if the supplied pixel ratio could be set on the MTKView, to allow users to use a different pixel ratio than the default one.

## Environment

- Maps SDK Version: v10.1.0

## Observed behavior and steps to reproduce

In case we use a shader that depends on the pixelRatio, the rendered image is misalinged if the user supplies any value that's not the default native screen scale.
![IMG_8837](https://user-images.githubusercontent.com/2576246/145056801-d01a25d7-38f7-4b27-8708-a4a59ddece87.PNG)

## Expected behavior

When supplying a custom pixelRatio in `MapOptions` the rendered image should match the user's configuration.

## Notes / preliminary analysis

Normally our shaders should operate independently from the device's screen and pixel ratio. The specific problem with the globe's background in the linked issue will be addressed here: https://github.com/mapbox/mapbox-maps-ios/issues/895#:~:text=mapbox/mapbox%2D3d%2Dteam%2371

**Comment by macdrevx** [comment]
Hmm, actually that value is based on what's provided through map init options. So I think we're actually okay on this. Do you agree?

**Comment by endanke** [comment]
Yes, I think we just have to review the rendering of the globe's background. But I thought I'll make sure we use the correct pixelRatio along the way. I'll close this issue and reopen it if we see some problems when we fix that shader.
