### ISSUE TITLE
PointAnnotation Title

### ISSUE THREAD

**Issue by b992** [mapbox/mapbox-maps-ios#911]
I can't find the title property of PointAnnotation. The official iOS SDK documentation mentions it. It says it's a _public var title: String?_  in the SDK, but I can't use it in my Xcode project. Is the current SDK lacks it? How can I add a title to an annotation then? Could someone add it back, or tell me where to find it? Thank you! :) 

## Why
Because documentation mentions it, and I want to add titles to annotations. [Title property in documentation](https://docs.mapbox.com/ios/maps/api/10.0.0-beta.19/Structs/PointAnnotation.html#/s:10MapboxMaps15PointAnnotationV5titleSSSgvp).

**Comment by ZiZasaurus** [comment]
@b992, the documentation that you linked is a bit out of date and the title property no longer exists with the current version ([v10.1.0](https://docs.mapbox.com/ios/maps/api/10.1.0/Structs/PointAnnotation.html#/s:10MapboxMaps15PointAnnotationV2idSSvp)) of the Maps SDK.
