### ISSUE TITLE
Enable pan flicking regardless of the camera's pitch

### ISSUE THREAD

**Issue by tornadojuice** [mapbox/mapbox-maps-ios#912]
## Enable pan flicking regardless of the camera's pitch

Pan flicking is disabled when the camera's pitch is >= `60`. Adjusting `panDecelerationFactor` at a pitch >= `60` has no effect. This produces a very unpleasant user experience for maps with high degrees of pitch.

## Why
Let apps decide if pan flicking should be enabled or disabled by allowing apps to adjust the `panDecelerationFactor` regardless of pitch.

**Comment by macdrevx** [comment]
We've removed the 60 degree cutoff in v10.2.0-rc.1 and made some additional improvements to pan flicking behavior at higher pitches. Please try it out and let us know if you have any feedback.
