### ISSUE TITLE
Convert CGPoint to CLLocation

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#919]
## New Feature

I can't see a function to get CLLocation from the tapping point. 
In old MapBox there was `convert` method
`- (CLLocationCoordinate2D)convertPoint:(CGPoint)point toCoordinateFromView:(nullable UIView *)view;.` 

In Mapbox 10 we also have a method convert:
`open func convert(_ point: CGPoint, to view: UIView?) -> CGPoint`

However, its return just a given point. I don't know if it's a bug that this method doesn't convert anything or I use it in the wrong way. 

What is the equivalent of converting CGPoint to CLLocation in the new version?

**Comment by Tapestes** [comment]
@objc private func onMapClick(_ sender: UITapGestureRecognizer) {
        let touchPoint = sender.location(in: mapView)
        let coordinate = mapView.mapboxMap.coordinate(for: touchPoint)
}

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT, the comment by @Tapestes would be the way to obtain the coordinates at a tapped point. Closing this ticket but please feel free to reopen if you have additional questions.
