### ISSUE TITLE
Offline tile packs

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-ios#930]
I couldn't find information how new offline tile packs are priced? Is the limit of 750 tile packs included in the normal use?

btw. Contact sales web form on your website might be broken. I haven't received any replies from there.

**Comment by ZiZasaurus** [comment]
@ittna right now every [monthly active user](https://docs.mapbox.com/help/glossary/monthly-active-users/) gets 750 tile packs included in the normal use, however, please note that pricing is still being tweaked.

**Comment by ittna** [comment]
Thanks, can I assume that possible tweaks only apply to new SDK versions and current SDK versions won't suddenly change?

**Comment by ZiZasaurus** [comment]
@ittna, that is correct. At the moment the pricing should remain the same for previous versions.

**Comment by akovalov** [comment]
@ZiZasaurus could you please tell if in the next versions it is planned to have pricing for offline tile packs exceeding 750? We have an app used in aviation where network connection could be not available or bad, or with a high cost for traffic. So it would be good to be able to have an offline area for like US territory of zoom levels 2-8 etc. Thank you.

PS We also tried to contact sales via a website form few times over the last few months, but never got a reply.

**Comment by ittna** [comment]
@ZiZasaurus at least now I see that tile pack downloads have counted as Vector Tiles API requests in our Mapbox account and it has also invoiced those from our account. So now it seems it is not included in normal use.

**Comment by ZiZasaurus** [comment]
@akovalov, @ittna, as this is more of a product support Issue, can you please create a support ticket at https://support.mapbox.com/hc/en-us/?

**Comment by pranshuchittora** [comment]
Hey, I am facing the same issue of max allowed tile limit of 750, I tried contacting the mapbox support million times but no reply on any of the ticket. Is there any way to unlock the limit?
