### ISSUE TITLE
Update geometry in sources programmatically

### ISSUE THREAD

**Issue by MaciejPachciarekSMT** [mapbox/mapbox-maps-ios#946]
## New Feature

In our app, we have the option to draw on the map. Users can draw a line and edit it. In pre v10 we used `MGLShapeSource` and then whenever the user change line position we updated geometry by `source.shape = MGLPolylineFeature`.

In v10 I can't see this type of source so I use GeoJSONSource. However when I try to update geometry by `source.data = .geometry(.lineString(LineString))` it not update the geometry. In addition, when I initialize sources by .empty geometry and check the source in debugger i get information with `debugDescription =  "Failed to decode GeoJSONSource `data` property"`

## Why
Update geometry in sources programmatically

**Comment by ZiZasaurus** [comment]
@MaciejPachciarekSMT you can use [updateGeoJSONSource(withId:geoJSON:)]
(https://docs.mapbox.com/ios/maps/api/10.1.2/Classes/Style.html#/s:10MapboxMaps5StyleC19updateGeoJSONSource6withId7geoJSONySS_4Turf0E10JSONObjectOtKF) to programmatically update geometry sources. You can see this demonstrated in our Live Data example [here] (https://github.com/mapbox/mapbox-maps-ios/blob/36dcbfb00866372f5657687e353c396bd57ea7f8/Apps/Examples/Examples/All%20Examples/LiveDataExample.swift). This example also showcases initializing an empty geometry.

**Comment by MaciejPachciarekSMT** [comment]
Thanks for answer!

**Comment by fousa** [comment]
Is this `updateGeoJSONSource` function still working? I can't seem to update my source and make it reflect on the map.

**Comment by MaciejPachciarekSMT** [comment]
HI @fousa 
For me it's still working, look at my usage:

`style.updateGeoJSONSource(withId: Constants.souceId, geoJSON: .geometry(.lineString(line)))`

**Comment by fousa** [comment]
I noticed I had to trigger it explicitly in a `DispatchQueu.main.async` block. Then it worked.
