### ISSUE TITLE
Add example for usage of view annotations with associated point annotations

### ISSUE THREAD

**Issue by endanke** [mapbox/mapbox-maps-ios#951]
Parity for: https://github.com/mapbox/mapbox-maps-android/pull/994

View annotations can be paired with other annotation types. We could add an example to showcase their usage using point annotations, as it is implemented in the Android SDK.

**Comment by endanke** [comment]
I've promised to take this item in January, but now I had a 1-on-1 with Thiago and he asked me to focus on some high prio gl-native items instead. I've unassigned the ticket for the time being and in case I have a bit more bandwidth I'll try to pick it up later.
cc: @macdrevx @kiryldz

**Comment by pjleonard37** [comment]
We now have an [example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/Annotations/ViewAnnotationWithPointAnnotationExample.swift) of using view annotations with associated point annotations. Closing as resolved. 🎉
