### ISSUE TITLE
Expose ornament sizes

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#956]
## New Feature

To be able to perform fine-grained layouts it is useful to know the size of the things to be positioned. Exposing the current size of ornaments like `compass` and `logo` would be a natural complement to the current `margins` attribute.

```swift
public protocol OrnamentOptionsProtocol {
    var position: OrnamentPosition { get set }
    /// The default value for this property is `CGPoint(x: 8.0, y: 8.0)`.
    var margins: CGPoint { get set }

    var size: CGSize { get } // <-- possible approach
}
```

**Comment by macdrevx** [comment]
I think we have another ticket somewhere about enabling ornament-relative layout. It seems like the goal here is the same.

Adding a requirement to a public protocol would be a breaking change, so while this might work in v11, to solve this for v10, we'll need to think of something different.

**Comment by devioustree** [comment]
The protocol may be public, but conforming to it outside of `MapboxMaps` doesn't seem useful? Are there expected reasons for consumers to conform to `OrnamentOptionsProtocol`?

**Comment by devioustree** [comment]
> I think we have another ticket somewhere about enabling ornament-relative layout. It seems like the goal here is the same.

Some of our use is to support positioning ornaments relative to each other, but that's not the entire functionality I desire. I'm also looking to position ornaments relative to other views and have them aligned by their centres.

**Comment by macdrevx** [comment]
> The protocol may be public, but conforming to it outside of MapboxMaps doesn't seem useful? Are there expected reasons for consumers to conform to OrnamentOptionsProtocol?

I don't think so. Regardless, it actually shouldn't limit us since we could just introduce a new protocol that conforms to OrnamentOptionsProtocol that contains the additional field (if that ends up being the solution).

**Comment by macdrevx** [comment]
In v10.4, we exposed the ornament views. @devioustree will that enable the use cases you need?

**Comment by macdrevx** [comment]
I'm going to close this issue for now, but please let us know if you run into any problems with this approach.
