### ISSUE TITLE
View annotations with feature association require SymbolLayer

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-ios#972]
## Environment

- Xcode version: 13.2
- iOS version: 15.2
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce

View annotations with feature association only becomes visible if map style contains SymbolLayer. Not sure if it was intended to only work with SymbolLayer but I didn't see this limitation documented anywhere.

## Expected behavior

View annotations with feature association could be used with other style layers also. For example CircleLayer.

**Comment by ZiZasaurus** [comment]
@ittna can you let me know more about which source the feature id you're trying to reference is defined in? Additionally, what type of source is it (geoJSON source or something else)?

**Comment by ittna** [comment]
I'm using `GeoJSONSource` as source.

```
let featureId = "pin-0"
let feature = Feature(geometry: Point(coordinate))
feature.identifier = .string(featureId)

var source = GeoJSONSource()
source.data = .featureCollection(FeatureCollection(features: [feature]))
try style.addSource(source, id: identifier)

let pinView = PinView()
try mapView.viewAnnotations.add(pinView, options: ViewAnnotationOptions(
    geometry: Point(coordinate),
    width: 40,
    height: 40,
    associatedFeatureId: featureId,
    allowOverlap: true,
    anchor: .center))
```

You have to add `SymbolLayer` to style otherwise pin won't become visible. Also if you don't specify `associatedFeatureId` in `ViewAnnotationOptions` then pin becomes visible.

**Comment by ZiZasaurus** [comment]
@ittna thank you for providing this snippet. I am able to reproduce this behavior in v10.2.0.

**Comment by macdrevx** [comment]
@ittna Can you say about more about the end result you're trying to achieve? You mention `CircleLayer` — do those play a role in your implementation?

**Comment by ittna** [comment]
Previous mapbox version we used MGLAnnotationViews to show map pins and it animated from circle to pin when selected. But on lower zoom levels we were showing pins as smaller dots with circle layer. When we migrated to new Mapbox SDK it was simplest to convert MGLAnnotationViews to view annotations in new SDK and all the animations are working same as before. As a workaround I'm now adding invisible SymbolLayer just to make view annotations visible.

**Comment by macdrevx** [comment]
Thanks @ittna. Another question: `associatedFeatureId` is only needed to enable collision-based hiding of the view annotations (e.g. if the underlying features would overlap in the symbol layer, one of them would be hidden (depending on the symbol layer's settings) and then the corresponding view annotations would also be hidden). Is that the behavior you're trying to achieve by using `associatedFeatureId`?

**Comment by ittna** [comment]
No, my use case is just to associate annotation views with features as the property name suggests. I guess I could maintain the mapping separately myself but this property is poorly documented if it only works for mapbox internal use to implement collision-based hiding. I wasted probably two days finding out this limitation.

**Comment by macdrevx** [comment]
@ittna thanks for the feedback. Based on what you've mentioned, could you try setting `associatedFeatureId` to nil? To control placement of view annotations, set `[ViewAnnotationOptions.geometry](https://docs.mapbox.com/ios/maps/api/10.3.0/Structs/ViewAnnotationOptions.html#/s:10MapboxMaps21ViewAnnotationOptionsV8geometry4Turf8GeometryOSgvp)` to a Turf.Point that corresponds to where you would like it to be placed on the map. Doing this should eliminate the need to use an invisible symbol layer.

**Comment by ittna** [comment]
As stated before it does work if you leave `associatedFeatureId` empty, but then I have maintain my own mapping which annotation view corresponds to which feature.

**Comment by macdrevx** [comment]
Thanks again for the feedback. We'll take this into consideration as we work on future iterations of this feature.

cc: @kiryldz @zmiao

**Comment by gsilvaPF** [comment]
Is this still the issue with 10.4.3? I'm experiencing the same issue. I'm currently coupling an annotation to a UIButton (View Annotation) to be a callout view. I want to toggle visibility of the button on annotation click, but once I update  with "viewAnnoationManager.update(view, options: ViewAnnotationOptions(visible: !visible))" calling "viewAnnoationManager.view(featureId: id)" returns nil.

**Comment by arslankaleem7229** [comment]
@ZiZasaurus  I have not find any solution here... Adding nil to `assosiatedFeatureId` results sshowing of viewAnnotation but if I add `assosiatedFeatureId` it don't show viewAnnotation. How can I show viewAnnotation with assosiatedFeatureId

**Comment by arslankaleem7229** [comment]
> let featureId = "pin-0"
> var feature = Feature(geometry: Point(coordinate))
> feature.identifier = .string(featureId)
> 
> var source = GeoJSONSource()
> source.data = .featureCollection(FeatureCollection(features: [feature]))
> try style.addSource(source, id: identifier)

@ittna I tried this solution which I tried

```
let sampleView = createView()
        do{
            let featureId = "pin-\(id)"
            var feature = Feature(geometry: Point(coordinate))
            feature.identifier = .string(featureId)

            var source = GeoJSONSource()
            source.data = .featureCollection(FeatureCollection(features: [feature]))
            try mapView.mapboxMap.style.addSource(source, id: featureId)
            try mapView?.viewAnnotations?.add(sampleView, options: options)
        }catch{
            print(error)
        }
```

but it is not showing my viewAnnotation. if I add `associatedFeatureId` to nil its working but if I add `associatedFeatureId` to differentiate and perform update on viewAnnotation it is not showing

**Comment by arslankaleem7229** [comment]
@ZiZasaurus thanks for the solution ❤️❤️❤️

**Comment by ZiZasaurus** [comment]
You are most welcome. I will close the ticket but please feel free to reach out if you have any additional questions.

**Comment by arslankaleem7229** [comment]
@ZiZasaurus this didn't resolve my problem. When I out featureId to nil or leave it empty it works perfectly fine. I am converting `SwiftUI View` to `UIView` using `UIHostingController`. Now I want to add the feature to map pins so I can perform required task. I have tried adding layer of symbol which you mentioned but its not working. Whenever I add featureId to viewAnnotation it disappears
```
private func addViewAnnotation(place:Place) {
        let coordinate = CLLocationCoordinate2D(
            latitude: place.latitude.toDouble()!,
            longitude: place.longitude.toDouble()!
        )
        let featureId: String = "pin-\(place.id)"

        let options = ViewAnnotationOptions(
            geometry: Point(coordinate),
            associatedFeatureId: featureId,
            allowOverlap: false,
            visible: true,
            anchor: .center,
            selected: true
        )
        let pinView = createPins()
        do{
            try mapView?.viewAnnotations?.add(pinView, options: options)
        }catch{
            print(error)
        }
    }
```

**Comment by ZiZasaurus** [comment]
@arslankaleem7229 from your code snippet it does not appear as though you have added the required symbol layer as I have in my previous comment. Can you please add the symbol layer and verify the annotation shows as expected?

**Comment by arslankaleem7229** [comment]
@ZiZasaurus  Sorry I just added my annotation code. Here is my function of adding annotations in map

```

    private func addViewAnnotation(place:Place) {
        let coordinate = CLLocationCoordinate2D(
            latitude: place.latitude.toDouble()!,
            longitude: place.longitude.toDouble()!
        )
        let featureId: String = "pin-\(place.id)"
        
        var source = GeoJSONSource()
        source.data = .featureCollection(FeatureCollection(features: []))
        try! mapView.mapboxMap.style.addSource(source, id: featureId)
        
        let options = ViewAnnotationOptions(
            geometry: Point(coordinate),
            associatedFeatureId: featureId,
            allowOverlap: false,
            visible: true,
            anchor: .center,
            selected: true
        )
        
        do{
            let annotationView = createAnnotationPins()
            try mapView?.viewAnnotations?.add(annotationView, options: options)
            var layer = SymbolLayer(id: featureId)
            layer.source = featureId
            layer.iconImage = .constant(ResolvedImage.name("airport-15"))
            layer.iconAnchor = .constant(.bottom)
            layer.iconAllowOverlap = .constant(true)
            try? mapView.mapboxMap.style.addLayer(layer)
        }catch{
            print(error)
        }
    }
```

**Comment by arslankaleem7229** [comment]
@ZiZasaurus did you find any problem in my code ???

**Comment by arslankaleem7229** [comment]
> Previous mapbox version we used MGLAnnotationViews to show map pins and it animated from circle to pin when selected. But on lower zoom levels we were showing pins as smaller dots with circle layer. When we migrated to new Mapbox SDK it was simplest to convert MGLAnnotationViews to view annotations in new SDK and all the animations are working same as before. As a workaround I'm now adding invisible SymbolLayer just to make view annotations visible.
> 
>  clip.mp4

@ZiZasaurus or @ittna  long short story .. Can you provide a block of code to achieve this functionality ? I can simply figure out what I am doing wrong ???
