### ISSUE TITLE
Symbol layer flickering

### ISSUE THREAD

**Issue by PrisakarMaksim** [mapbox/mapbox-maps-ios#977]
## Environment

- Xcode version: 12.5
- iOS version: 14.0.1
- Devices affected: iPad mini 4
- Maps SDK Version: 10.2.0 (Example App)

## Observed behavior and steps to reproduce

1. add raster tiles source
2. add symbol layer or point annotation on the map above raster layer
3. start zoom in/out or scroll map

Icon flicker

## Expected behavior

Icon stay on the map all time while scrolling/zooming

## Additional links and references

[ScreenRecording](https://disk.yandex.ru/i/yIvU-IcmLbp0OA)

**Comment by ZiZasaurus** [comment]
@PrisakarMaksim, thank you for reporting this behavior. I am able to reproduce it on v10.2.0 and am investigating.

**Comment by ZiZasaurus** [comment]
@PrisakarMaksim, we are working on resolving this behavior. In the meantime, if you set the raster layer opacity to 0.99 the flickering stops.

**Comment by PrisakarMaksim** [comment]
@ZiZasaurus, thanks a lot for your response! Approach you suggested works like a charm!
Hope, this bug will be fixed in a future release as our users are allowed to setup different raster map opacity themselves.

**Comment by ZiZasaurus** [comment]
Closing this ticket as the reported bug has been ticketed upstream. Please feel free to reopen this ticket if you have additional questions.
