### ISSUE TITLE
Purple rectangle layer after a background

### ISSUE THREAD

**Issue by latargere** [mapbox/mapbox-maps-ios#978]
## Environment

- Xcode version: 13.2
- iOS version: 15.2
- Devices affected: iPhone 13 pro
- Maps SDK Version: 10.2

## Observed behavior and steps to reproduce

After awhile in the background, when I put back the app in foreground. All layers are represented with purple rectangle.
I got the same behavior in the latest mapbox navigation

## Expected behavior

My annotations should be back

![287A6EC2-600B-4808-911C-91F48D8D090C](https://user-images.githubusercontent.com/7023805/147390279-a83abe55-0c78-4188-99c5-32875ca3c06e.jpeg)

**Comment by ZiZasaurus** [comment]
@latargere, thank you for reporting this behavior. Is this occurring with symbol layers, point annotations or both? Additionally, do you know how much time it took for the purple rectangles to appear and is this happening on physical devices or on the simulator?

**Comment by latargere** [comment]
Thanks for your questions. It was on a real device.
On this screen, the main square is the puck defined with images. The little rectangles are something generated by Mapbox and it should be the little street arrow showing the direction of a street.
I've got this issue on mapbox navigation with the course view

**Comment by latargere** [comment]
Is there a way I can help you?

**Comment by ZiZasaurus** [comment]
@latargere, I am unable to reproduce this behavior with our examples. Would you be able to share a sample project that reproduces this behavior?

**Comment by latargere** [comment]
I'm struggling trying to provide something since I have not identified how to clearly trigger this bug.
Do you have more info how Mapbox core would switch to this state (purple for add layer, grey for street name) ? With a memory warning? Call on background thread? Buffer size exceeded ?

**Comment by ZiZasaurus** [comment]
@latargere happy to get these questions answered for you. In the meantime, would you be able to provide us with any related logs?

**Comment by latargere** [comment]
I tried to get it with the debugger attached but right now, I couldn't. If it can help after having it (after coming from background), I didn't a second background/foreground and layers were fixed

**Comment by ZiZasaurus** [comment]
@latargere do you have a code snippet of how you were originally adding the second background/foreground that caused the purple rectangle?

**Comment by ittna** [comment]
I think usually that purple color means that there was some problem in shader code. Not sure if that is the cause here though.

**Comment by latargere** [comment]
Not sure neither how to trigger this since I cannot get the debugger in the same time. By setting again the same map style after receiving a "willEnterForegroundNotification", I could make the map work again when this bug occurs but I can still this weird behaviour for a fraction of second

**Comment by ZiZasaurus** [comment]
@latargere thank you for reporting. We will look into what may be causing this behavior.
