### ISSUE TITLE
iOS Crash in SourceManager createSource() when loading geojson featurecollection 

### ISSUE THREAD

**Issue by jumbopilot** [mapbox/mapbox-maps-ios#981]
## Environment

- Xcode version: 13.2 Final
- iOS version: 15.3
- Devices affected: iPhone
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce
Add a Fill layer from geojson featurecollection
No self-programmed do-catch error handling is triggered.

Xcode debug output:
---
libc++abi: terminating with uncaught exception of type mapbox::util::bad_variant_access
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type mapbox::util::bad_variant_access
---

Code sample
`          guard let path = Bundle.main.path(forResource: "test", ofType: "geojson") else { return }

            let filePath = URL(fileURLWithPath: path)
            var featureCollection: FeatureCollection?

            do {
                let data = try Data(contentsOf: filePath)
                // Attempt to decode GeoJSON from file bundled with application.
                featureCollection = try JSONDecoder().decode(FeatureCollection.self, from: data)                
            } catch {
               // Error handling
            }

            // Create a GeoJSON data source
            var myGeoJSONSource = GeoJSONSource()
            let sourceJSONIdentifier = "Id1"
            let sourceLayerIdentifier = "Id1-layer"

            let style = self.mapView.mapboxMap.style

            myGeoJSONSource.data = .featureCollection(featureCollection!)
            myGeoJSONSource.cluster = true
            myGeoJSONSource.clusterRadius = 50

            // Create a layer (unclustered features) and access the layer contained
            var layer = FillLayer(id: sourceLayerIdentifier) // polygon

            DispatchQueue.main.async {
                // Add the sources and layers to the map's style
                do {
                    try style.addSource(myGeoJSONSource, id: sourceJSONIdentifier)    // <- crash happens in this instruction
                    try style.addLayer(layer, layerPosition: .default)
                } catch {
                    // Error handling
               }
            }`

## Expected behavior
no runtime exception while creating layer source in `FillLayer`
#9	0x0000000105858750 in ::createSource() at /Users/distiller/project/src/mbgl/sourcemanager/geojson_source_factory.cpp:36

## Notes / preliminary analysis

Adding similarely symbolLayer or circleLayer from geojson works fine

## Additional links and references

[test.geojson.zip](https://github.com/mapbox/mapbox-maps-ios/files/7780185/test.geojson.zip)

**Comment by ZiZasaurus** [comment]
@jumbopilot I experience the same behavior when using the code snippet you've provided above, however, when I remove `myGeoJSONSource.cluster = true` or set it to false the code operates as expected and the fillLayer is rendered. Please note that `cluster` can only be used for point features, as noted [here](https://docs.mapbox.com/ios/maps/api/10.2.0/Structs/GeoJSONSource.html#/s:10MapboxMaps13GeoJSONSourceV7clusterSbSgvp).

**Comment by ZiZasaurus** [comment]
Closing this ticket but please feel free to reopen if you have additional questions.
