### ISSUE TITLE
'Observable' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by LearnWithTung** [mapbox/mapbox-maps-ios#982]
## Environment

- Xcode version: 12.5.1
- iOS version: 15.2
- Devices affected: 
- Maps SDK Version: v10.2.0
- MapboxNavigation: v2.2.0-beta.1
- RxSwift / RxCocoa: ~> 6.0.0
## Observed behavior and steps to reproduce
Compile error with log: 
`'Observable' is ambiguous for type lookup in this context`

## Expected behavior
Compile successful

**Comment by ZiZasaurus** [comment]
@LearnWithTung, can you provide some more context as to how /when you received this error? Were you compiling your own project or one of our example projects?

**Comment by tungvustarglobal** [comment]
@ZiZasaurus I created my own project, install those frameworks via cocoapods. I got the error whenever I use `Observable` for example
```
func connect(backTapped: Observable<Void>) { // compile error `'Observable' is ambiguous for type lookup in this context`
      //...
}
```

**Comment by tungvustarglobal** [comment]
Here's my podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MapboxDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxDemo
  pod 'MapboxMaps', '~> 10.2'
  pod 'MapboxNavigation', '~> 2.2'

  pod 'RxSwift', '~> 6.0.0'
  pod 'RxCocoa', '~> 6.0.0'
  pod 'RxGesture', '~> 4.0.2'
  pod 'RxDataSources', '~> 5.0.0'

end
  ```

**Comment by macdrevx** [comment]
You can resolve the ambiguity by telling the compiler which one you mean when you say `Observable`. For example, if you say

```
typealias Observable = RxSwift.Observable
```

then throughout that module, `Observable` will mean the one from RxSwift. You can still refer to the other one by using it's fully-qualified name `MapboxCoreMaps.Observable`.
