### ISSUE TITLE
Show reduced accuracy location as circle

### ISSUE THREAD

**Issue by ittna** [mapbox/mapbox-maps-ios#983]
## New Feature

When user allows only reduced accuracy location, is it possible to show it as circle? Currently it seems to not show location puck at all with reduced accuracy permissions.

## Why

Implement similar behaviour as on Apple maps. Apple maps shows reduced accuracy location as circle.

**Comment by macdrevx** [comment]
@ZiZasaurus this *should* already be happening. If it's not, please mark it as a bug.

**Comment by ZiZasaurus** [comment]
@ittna thank you for reporting this behavior. It looks like the icon for reduced accuracy is added at 0.0, 0.0 regardless of the user's location and there is indeed no location puck. 

![IMG_C5185D3E0255-1.jpeg](https://images.zenhubusercontent.com/5d9f907d89616e000103e95c/ddfd310f-e639-4a3c-99e0-818e5d95ad51)
