### ISSUE TITLE
Custom style tiles  download fails

### ISSUE THREAD

**Issue by tomascern** [mapbox/mapbox-maps-ios#986]
## Environment

- Xcode version: 13.1
- iOS version: 15.1.1
- Devices affected: iPhone 12
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce

Hello, I have this minimal code: 

```
        let tileStore = TileStore.default
        tileStore.setOptionForKey(TileStoreOptions.mapboxAccessToken, value: MyMapView.accessToken)

        let resourceOptions = ResourceOptions(accessToken: MyMapView.accessToken, tileStore: tileStore, tileStoreUsageMode: .readAndUpdate)
        let offlineManager = OfflineManager(resourceOptions: resourceOptions)

        // let descriptorOptions = TilesetDescriptorOptions(styleURI: .outdoors, zoomRange: 1 ... 11)  //<<<--- This works
        let descriptorOptions = TilesetDescriptorOptions(styleURI: StyleURI(rawValue: "https://maps-api.lufty.app/styles/lufty-style-v2/style.json")!, zoomRange: 1 ... 11) //<<<--- This doesn't work
        let descriptor = offlineManager.createTilesetDescriptor(for: descriptorOptions)

        let circle = Turf.Polygon(center: CLLocationCoordinate2D(latitude: 53, longitude: -1), radius: 10000, vertices: 32)

        let tileRegionLoadOptions = TileRegionLoadOptions(geometry: .polygon(circle), descriptors: [descriptor], metadata: [], acceptExpired: true)!
        tileStore.loadTileRegion(forId: "myTileRegion", loadOptions: tileRegionLoadOptions) { progress in
            log.debug("Tile region progress: \(Float(progress.completedResourceCount) / Float(progress.requiredResourceCount) * 100)%")
        } completion: { result in
            switch result {
            case let .success(tile):
                log.debug("Tile region downloaded successfully: \(tile.id)")
            case let .failure(error):
                log.debug("Tile region download failed: \(error.localizedDescription)")
            }
        }

```
When trying to download tiles with some default Mapbox style, everything works. When I try to download tiles with my custom style, the download immediately stops with the following log:
`Tile region download failed: Does not exist`

## Expected behavior

I can download tiles with any style.

**Comment by bmt2018** [comment]
I asked about this back in July 2021 and they said it's not currently supported and that's why they left the "legacy tile-based offline system" in the v10 SDK.

See https://github.com/mapbox/mapbox-maps-ios/issues/546 for more info.

**Comment by knov** [comment]
Thanks for your request of this feature. We will track this request via #546 and support your continued use of the legacy APIs per [this comment](https://github.com/mapbox/mapbox-maps-ios/issues/546#issuecomment-901160523).

**Comment by tomascern** [comment]
> Thanks for your request of this feature. We will track this request via #546 and support your continued use of the legacy APIs per [this comment](https://github.com/mapbox/mapbox-maps-ios/issues/546#issuecomment-901160523).

In this case, we would also need to add method for setting metadata of the OfflineRegion and method for deleting a region from the storage.
