### ISSUE TITLE
`source.children(of: cluster)` and `source.zoomLevel(forExpanding: cluster)` missing in v10

### ISSUE THREAD

**Issue by ts95** [mapbox/mapbox-maps-ios#988]
We recently updated our MapBox dependency from v6 to v10, and as we were refactoring the code we noticed that it's seemingly no longer possible to implement expanding zoom for annotation clusters when tapping on a cluster. In v6 you could use `source.zoomLevel(forExpanding: cluster)` to get the `zoomLevel` where the cluster would dissolve/expand into multiple new annotations, and call the `setCenter()` method with that zoom level to zoom in.

I can tell that the clustering system has been overhauled in v10 and I'm wondering if I'm missing something, or whether the feature described above has been removed. If it has been removed, are there any plans to bring it back?

**Comment by macdrevx** [comment]
We'll be bringing methods like that back in a future release (PR here: https://github.com/mapbox/mapbox-maps-ios/pull/975). In the meantime, you can use the queryFeatureExtension method of MapboxMap (the PR I linked demonstrates how to use it in each case).
