### ISSUE TITLE
Can viewAnnotations or annotations be moved by animations?

### ISSUE THREAD

**Issue by jokerping** [mapbox/mapbox-maps-ios#997]
In V10 viewAnnotations or annotations can be animated to move according to given coordinates just like Uber's vehicle icons

**Comment by ZiZasaurus** [comment]
@jokerping we don't currently offer any support for animating layers, sources, or annotation positions. To achieve this, you would need to manually update the position of the annotation at every frame using your own CADisplayLink.

What's the source of the location you want to show? the device's current location? If so, can you use a puck? If it's something else could you use a custom location provider or a custom location indicator layer?  [LocationIndicatorLayer](https://docs.mapbox.com/ios/maps/api/10.2.0/Structs/LocationIndicatorLayer.html) has a locationTransition property that you could use to define animations between locations.

**Comment by jokerping** [comment]
The source of the location is not the user's location but a set of defined coordinates and I want the mapxbox to display an icon and have it move according to the coordinates (which I can control and animate). I have tried using the location provider (mapView.location.overrideLocationProvider) but the **custom Provider** does not allow me to set the location coordinates myself. **LocationIndicatorLayer** seems to work,but the link to The documentation doesn't have detailed instructions on how to use it, so I tried using the properties listed
Like this
``` swift
 var location = LocationIndicatorLayer(id: "userLocation")
        location.locationTransition = .init(duration: 2, delay: 0)
        location.location = .constant([coordinate.latitude,coordinate.longitude,0])
        location.topImage = .constant(.name("red_pin"))
        mapView?.mapboxMap.style.addLayer(location)
```

But it doesn't work and it feels a bit tricky

**Comment by ZiZasaurus** [comment]
@jokerping, I've attached sample code below, as well as a screen recording of a working LocationIndicationLayer

```
            var layer = LocationIndicatorLayer(id: "test")
            layer.location = .constant([location.location!.coordinate.latitude, location.location!.coordinate.longitude, location.location!.altitude])
            print(layer.location)
            let image = UIImage(named: "star")!

            layer.topImage = .constant(.name("star"))
            layer.source = "some-source"
            layer.sourceLayer = nil
            layer.locationTransition = StyleTransition(duration: 4, delay: 0)
            try! self.mapView.mapboxMap.style.addImage(image, id: "star", stretchX: [], stretchY: [])
            try! self.mapView.mapboxMap.style.addLayer(layer, layerPosition: .default)


            let timer = Timer.scheduledTimer(withTimeInterval: 1.25, repeats: true) { _ in

                let location = [[38, -76, location.location!.altitude], [39, -76, location.location!.altitude], [40, -76, location.location!.altitude], [38.831017, -76.767062, location.location!.altitude]]
                print(location[self.i])

                try! self.mapView.mapboxMap.style.updateLayer(withId: "test", type: LocationIndicatorLayer.self) { inoutLayer in
                    inoutLayer.location = .constant(location[self.i])
                }
                self.addToI()
            }
```

https://images.zenhubusercontent.com/330733892/b875a96e-36ce-4138-bd5c-cf3913f259dc/simulator_screen_recording___iphone_11___2022_01_10_at_09_38_47.mp4

**Comment by jokerping** [comment]
Thank you very much, the problem is solved
