### ISSUE TITLE
Pulsating halo effect for user location puck

### ISSUE THREAD

**Issue by ts95** [mapbox/mapbox-maps-ios#998]
In MapBox v6 the default user location puck was red, it had a pulsating halo around it, and the red circle in it had a scale animation where it would grow and shrink in an oscillating manner.

The new one is a blue dot with no animations. I see that the `Puck2DConfiguration` object has a field called `showsAccuracyRing`, which I've set to `true`, ~~but it doesn't appear to do anything.~~ (nvm, the ring does appear. It just didn't while I was testing with a mock location.) Also, there doesn't seem to be a way to change the color of the accuracy ring/halo.

<img src="https://user-images.githubusercontent.com/1880556/148527036-364e2faf-556c-4fe0-badb-f3d15b97bc3b.png" width="300px"/>

Here's a video of the old user location puck which we'd like to replicate.

<video src="https://user-images.githubusercontent.com/1880556/148524882-5ad4f40c-16ac-4de1-a71a-f801d65ee660.mp4" width="300px"></video>

By using the properties `topImage` and `bearingImage` on `Puck2DConfiguration` we were able to get pretty close, but there's still no pulsating halo or pulsating red circle and I'm not sure whether it's possible to implement that.

After digging for a bit I found `LocationIndicatorLayer`, which has several interesting properties that seemingly could be used to replicate the old puck, but when I try to customize the layer by setting those properties nothing happens.

**Comment by ts95** [comment]
I tried pitching the map at an angle in MapBox v6 and noticed that the user location puck appears to have a 3D effect, then I found this in v10 of the SDK: `Puck3DConfiguration`. Do you have a 3D model of the old puck?

**Comment by ZiZasaurus** [comment]
@ts95 If you're trying to change the color while using the puck API, it won't work because any changes you make will get overwritten on the next location update.
If you are using LocationIndicatorLayer directly there are a couple options. When you create the layer, you can use Style.addLayer(_:layerPosition:). To update just that property on an existing layer, you can either use updateLayer(withId:type:update:) or setLayerProperty(for:property:value), which is more performant. I've included a code snippet and screen recording below:

```
var layer = LocationIndicatorLayer(id: "test")
layer.location = .constant([location.location!.coordinate.latitude, location.location!.coordinate.longitude, location.location!.altitude])
let image = UIImage(named: "star")!

layer.topImage = .constant(.name("star"))
layer.source = "some-source"
layer.sourceLayer = nil
layer.accuracyRadius = .constant(500)!
layer.accuracyRadiusColor = .constant(StyleColor(red: 255, green: 192, blue: 203, alpha: 0.5)!)
try! self.mapView.mapboxMap.style.addImage(image, id: "star", stretchX: [], stretchY: [])
try! self.mapView.mapboxMap.style.addLayer(layer, layerPosition: .default)
```

To achieve the pulsating halo, you can reference the `accuracyRadiusTransition` property. 

![simulator_screenshot_C4B722AF-E318-4CD2-9783-E9B6D2136327.png](https://images.zenhubusercontent.com/5d9f907d89616e000103e95c/f797b9e6-792d-4e0b-8867-29cfd6a535cf)

**Comment by ts95** [comment]
> @ts95 If you're trying to change the color while using the puck API, it won't work because any changes you make will get overwritten on the next location update.

@ZiZasaurus Ah yeah, that makes sense.

> If you are using LocationIndicatorLayer directly there are a couple options. When you create the layer, you can use Style.addLayer(_:layerPosition:).

Good to know that this is an option, but in my case I'd prefer not to create a new custom puck if it can be avoided because then I'd have to forgo using the native puck altogether which gives me a bunch of things for free out of the box.

> To update just that property on an existing layer, you can either use updateLayer(withId:type:update:) or setLayerProperty(for:property:value), which is more performant.

I tried using this, but it caused the app to crash. I've submitted a bug report here https://github.com/mapbox/mapbox-maps-ios/issues/999.

**Comment by ZiZasaurus** [comment]
@ts95, at the moment there is no halo or pulsating radius out of the box in v10 and you would need to create a custom LocationIndicatorLayer. We will consider your request for adding this feature in a future version of v10.

**Comment by ZiZasaurus** [comment]
@ts95, closing this ticket, but please feel free to reopen if you have additional questions. The team will look into the bug you reported [here](https://github.com/mapbox/mapbox-maps-ios/issues/999).

**Comment by reubn** [comment]
Would like to see this added
